### ISSUE TITLE
Installing py-matplotlib fails

### ISSUE THREAD

**Issue by scottwittenburg** [spack/spack#6634] opened 2017-12-08 17:52 UTC
Spack failed on a vanilla install of py-matplotliib.  The build failed with the following message in the terminal:

```console
==> Installing py-matplotlib
==> '/data/scott/projects/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/python-2.7.14-iforq4u7htoo6tmiir66l3mqpcdr2dfa/bin/python2.7' '-c' 'from distutils.sysconfig import get_config_var; print get_config_var('"'"'prefix'"'"')'
==> '/data/scott/projects/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/python-2.7.14-iforq4u7htoo6tmiir66l3mqpcdr2dfa/bin/python2.7' '-c' 'from distutils.sysconfig import get_config_var; print get_config_var('"'"'prefix'"'"')'
==> link /data/scott/projects/spack/var/spack/stage/py-matplotlib-2.0.2-wqkodrqwhu4bfecgpidikv3los5kurgk -> /tmp/scott/spack-stage/spack-stage-2LxOpQ
==> Using cached archive: /data/scott/projects/spack/var/spack/cache/py-matplotlib/py-matplotlib-2.0.2.tar.gz
==> Staging archive: /data/scott/projects/spack/var/spack/stage/py-matplotlib-2.0.2-wqkodrqwhu4bfecgpidikv3los5kurgk/matplotlib-2.0.2.tar.gz
==> '/bin/tar' '-xf' '/data/scott/projects/spack/var/spack/stage/py-matplotlib-2.0.2-wqkodrqwhu4bfecgpidikv3los5kurgk/matplotlib-2.0.2.tar.gz'
==> Created stage in /data/scott/projects/spack/var/spack/stage/py-matplotlib-2.0.2-wqkodrqwhu4bfecgpidikv3los5kurgk
==> No patches needed for py-matplotlib
==> Building py-matplotlib [PythonPackage]
==> WRITE LOCK: /data/scott/projects/spack/var/spack/stage/.lock[1196596153666456453:1] [Acquiring]
==> WRITE LOCK: /data/scott/projects/spack/var/spack/stage/.lock[1196596153666456453:1] [Acquired]
==> WRITE LOCK: /data/scott/projects/spack/opt/spack/.spack-db/prefix_lock[6488122333627063305:1] [Acquiring]
==> WRITE LOCK: /data/scott/projects/spack/opt/spack/.spack-db/prefix_lock[6488122333627063305:1] [Acquired]
==> Executing phase: 'build'
==> WRITE LOCK: /data/scott/projects/spack/opt/spack/.spack-db/prefix_lock[6488122333627063305:1] [Released]
==> WRITE LOCK: /data/scott/projects/spack/var/spack/stage/.lock[1196596153666456453:1] [Released]
==> Error: ProcessError: Command exited with status 1:
    '/data/scott/projects/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/python-2.7.14-iforq4u7htoo6tmiir66l3mqpcdr2dfa/bin/python2.7' 'setup.py' '--no-user-cfg' 'build'
See build log for details:
  /data/scott/projects/spack/var/spack/stage/py-matplotlib-2.0.2-wqkodrqwhu4bfecgpidikv3los5kurgk/matplotlib-2.0.2/spack-build.out
Traceback (most recent call last):
  File "/data/scott/projects/spack/lib/spack/spack/build_environment.py", line 662, in child_process
    return_value = function()
  File "/data/scott/projects/spack/lib/spack/spack/package.py", line 1444, in build_process
    phase(self.spec, self.prefix)
  File "/data/scott/projects/spack/lib/spack/spack/package.py", line 114, in phase_wrapper
    phase(spec, prefix)
  File "/data/scott/projects/spack/lib/spack/spack/build_systems/python.py", line 167, in build
    self.setup_py('build', *args)
  File "/data/scott/projects/spack/lib/spack/spack/build_systems/python.py", line 135, in setup_py
    self.python(setup, '--no-user-cfg', *args, **kwargs)
  File "/data/scott/projects/spack/lib/spack/spack/build_systems/python.py", line 129, in python
    inspect.getmodule(self).python(*args, **kwargs)
  File "/data/scott/projects/spack/lib/spack/spack/util/executable.py", line 183, in __call__
    proc.returncode, cmd_line)
ProcessError: Command exited with status 1:
    '/data/scott/projects/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/python-2.7.14-iforq4u7htoo6tmiir66l3mqpcdr2dfa/bin/python2.7' 'setup.py' '--no-user-cfg' 'build'
```

Here is the build output file from the failed matplotlib build 

[spack-build.out.txt](https://github.com/spack/spack/files/1543415/spack-build.out.txt)

Looking in there, I notice that at the bottom there is a stack trace which ends with the lines:

```console
...
  File "/data/scott/projects/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/py-numpy-1.13.3-rhfri2h44q37ud7dwavxvaatj2a7cbk5/lib/python2.7/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: /usr/local/lib/libmkl_intel_thread.so: undefined symbol: omp_in_parallel
```

So I have also attached the build log from that numpy build, though I didn't see anything obvious in there that indicated any real kind of failure.

[build.out.txt](https://github.com/spack/spack/files/1543440/build.out.txt)

### Steps to reproduce the issue

```console
$ spack -d install py-matplotlib
```

### Information on your system

This happened on Ubuntu 16.04, with no custom packages or modules yaml files. Please let me know if more system information is needed.

**Comment by adamjstewart** [comment] 2017-12-08 21:38
This is similar to https://github.com/numpy/numpy/issues/8653. Basically, there is a bug in Numpy's build system such that even if you explicitly tell it where BLAS/LAPACK are installed and tell it to RPATH these libraries, it doesn't actually RPATH them. Later, when you try to import specific libraries like `numpy.multiarray`, this crashes because it can't find BLAS/LAPACK. I've complained to them before but they didn't really seem to care.

**Comment by scottwittenburg** [comment] 2017-12-12 17:28
Ping @tgamblin per our discussion this morning.

**Comment by scottwittenburg** [comment] 2019-01-19 00:16
Thanks @scheibelp.  I'll probably have to go back and remind myself what the context around this was, as I've forgotten now.  I suspect it was in the process of trying to get the `VTK` package to behave better.

**Comment by scheibelp** [comment] 2019-01-22 18:20
Feel free to reopen if you can reproduce the issue now that #10383 is merged

**Closed** 2019-01-22 18:19 UTC
Labels: build-error

**Comment by scottwittenburg** [comment] 2019-01-22 18:50
Sounds good, will do.
