### ISSUE TITLE
Spack trying to use `-march` options not recognized by default compiler

### ISSUE THREAD

**Issue by fryeguy52** [spack/spack#13361] opened 2019-10-21 18:43 UTC
snl-atdm-issue

While trying to use `spack install` on a rhel6 machine with haswell processors, spack correctly identifies the `-march` option as `core-avx2` but the default gcc version on rhel6 (gcc-4.4.7) does not recognize that as a valid `-march` option

### Steps to reproduce the issue

```console
$ cat /etc/redhat-release
Red Hat Enterprise Linux Workstation release 6.9 (Santiago)

$ which g++
/usr/bin/g++

$ g++ --version
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ -o hello hello.cpp -march=core-avx2
hello.cpp:1: error: bad value (core-avx2) for -march= switch
hello.cpp:1: error: bad value (core-avx2) for -mtune= switch
```

### Error Message

```console
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... /home/rabartl/Spack.base3/atdm-spack/spack/lib/spack/env/gcc/gcc
checking whether the C compiler works... no
configure: error: in `/tmp/rabartl/spack-stage/spack-stage-libsigsegv-2.12-4wg47p4nrbuzpsovsxhbypwtbcu25k4t/spack-src':
configure: error: C compiler cannot create executables
See `config.log' for more details
...
```
config.log shows:
```
configure:3283: checking whether the C compiler works
configure:3305: /home/rabartl/Spack.base3/atdm-spack/spack/lib/spack/env/gcc/gcc    conftest.c  >&5
conftest.c:1: error: bad value (core-avx2) for -march= switch
conftest.c:1: error: bad value (core-avx2) for -mtune= switch
```

### Information on your system

* Red Hat Enterprise Linux Workstation release 6.9 (Santiago)
* with Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz (Haswell)

**Comment by alalazo** [comment] 2019-10-21 21:02
@fryeguy52 Can you please check if #13362 fixes your issue? I particular can you post the result of:
```console
$ spack arch
$ spack spec zlib %gcc@4.4.7
```
?

**Comment by bartlettroscoe** [comment] 2019-10-29 21:37
Just merged in `v0.13.0` to our local branch.  The updated code gives:

```
$ ./atdm-spack/spack/bin/spack arch
linux-rhel6-broadwell
```

but when installing using:

<details>

<summary><b>spack.yaml</b></summary>

```
???
```

</details>

with:

```
./atdm-spack/spack/bin/spack install
```

it shows:

```
==> Concretized gcc@7.2.0
 -   bq3tfou  gcc@7.2.0%gcc@4.8.3~binutils languages=c,c++,fortran ~nvptx patches=51aebe82afc9a0433ca3503a36592edf5ca769b1433986919cfb9ae2ddf3e343 ~piclibs~strip arch=linux-rhel6-haswell
 -   gbuqqio      ^gmp@6.1.2%gcc@4.8.3 arch=linux-rhel6-haswell
 -   yw3nhqg          ^autoconf@2.69%gcc@4.8.3 arch=linux-rhel6-haswell
 -   vfy645g              ^m4@1.4.18%gcc@4.8.3 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-rhel6-haswell
[+]  5cjvint                  ^libsigsegv@2.12%gcc@4.8.3 arch=linux-rhel6-haswell
 -   svdyfxm              ^perl@5.30.0%gcc@4.8.3+cpanm+shared+threads arch=linux-rhel6-haswell
 -   5oybdwq                  ^gdbm@1.18.1%gcc@4.8.3 arch=linux-rhel6-haswell
 -   qbng4dd                      ^readline@8.0%gcc@4.8.3 arch=linux-rhel6-haswell
 -   y42pycm                          ^ncurses@6.1%gcc@4.8.3~symlinks~termlib arch=linux-rhel6-haswell
 -   jwyexez                              ^pkgconf@1.6.3%gcc@4.8.3 arch=linux-rhel6-haswell
 -   xdsocq2          ^automake@1.16.1%gcc@4.8.3 arch=linux-rhel6-haswell
 -   xglf55w          ^libtool@2.4.6%gcc@4.8.3 arch=linux-rhel6-haswell
 -   afketd2      ^isl@0.18%gcc@4.8.3 arch=linux-rhel6-haswell
 -   5bnd3rv      ^libiconv@1.16%gcc@4.8.3 arch=linux-rhel6-haswell
 -   j7g53wx      ^mpc@1.1.0%gcc@4.8.3 arch=linux-rhel6-haswell
 -   ldddpk3          ^mpfr@3.1.6%gcc@4.8.3 patches=66a5d58364113a21405fc53f4a48f4e8 arch=linux-rhel6-haswell
 -   cjsj4t2      ^zlib@1.2.11%gcc@4.8.3+optimize+pic+shared arch=linux-rhel6-haswell
```

See, the `arch` is different!  The command `spack arch` returns `linux-rhel6-broadwell` but running `spack install` uses the `arch` of `linux-rhel6-haswell`.  Show is that?

That completely breaks the logic in out driver tool that requires that `spack arch` gives the same arch that is used by `spack install`.

Can we get a fix for this on the 0.13 branch?

Re-opening this issue.

**Comment by tgamblin** [comment] 2019-10-29 22:33
@alalazo: just FYI, I added this to 0.13.1

**Comment by tgamblin** [comment] 2019-10-29 22:33
@becker33: FYI

**Comment by alalazo** [comment] 2019-10-30 11:03
@bartlettroscoe I would close this again as this is expected and documented [here](https://spack.readthedocs.io/en/latest/basic_usage.html#support-for-specific-microarchitectures) on the same exact case.

You are using `gcc@4.8.3` which does not support building software that is optimized for `broadwell` (support starts from v 4.9). Therefore Spack chooses the next best fit to your `broadwell` microarchitecture that is also known to `gcc@4.8.3`. This happens to be `haswell`.

**Comment by alalazo** [comment] 2019-10-30 11:04
@bartlettroscoe Wondering if you think this should be a case entering into #13482

**Comment by bartlettroscoe** [comment] 2019-10-30 13:26
> You are using gcc@4.8.3 which does not support building software that is optimized for broadwell (support starts from v 4.9).

@alalazo, sorry that was a mistake on my part.  I forgot to wiping the env before running raw spack.

Here is the error again ...

On a RHEL6 machine with the raw system compiler:

```
$ which gcc
/usr/bin/gcc

$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
```

using the files:

<details>

<summary><b>spack.yaml</b></summary>

```
# Spack env file to build a compiler using Spack
#
# NOTE: Spack will not only read this file but will also write to it so make
# sure you create a copy before spack uses it!
#
spack:
  # Packages to build (ordered mostly by dependencies)
  specs: [
    gcc@7.2.0,
    ]
  modules:
    tcl:
      hash_length: 0
      naming_scheme: spack-${PACKAGE}/${VERSION}
      whitelist:
        - gcc
      blacklist:
        - '%gcc@4.4.7'
      all:
        conflict:
          - '{name}'
        filter:
          environment_blacklist: [CPATH, LIBRARY_PATH]
        environment:
          set:
            ${PACKAGE}_ROOT: ${PREFIX}
      verbose: false
  packages:
    all:
      compiler: [gcc@4.4.7]
  include:
    - packages_tools_for_compiler_build.yaml
    - common_options.yaml
```
</details>

<details>

<summary><b>common_options.yaml</b></summary>

```
mirrors:
  local_filesystem: file:///ascldap/users/rabartl/Spack.base4/atdm-spack/atdm-spack-tarball-mirror
config:
  misc_cache: .spack/cache
```

</details>

<details>

<summary><b>packages_tools_for_compiler_build.yaml</b></summary>

```
???
```

</details>

<details>

<summary><b>atdm-spack/spack/etc/spack/compilers.yaml</b></summary>

```
compilers:
- compiler:
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: rhel6
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.4.7
```

</details>

Running:

```
$ rm spack.lock

$ ./atdm-spack/spack/bin/spack install

==> Concretized gcc@7.2.0
 -   zzfkclh  gcc@7.2.0%gcc@4.4.7~binutils languages=c,c++,fortran ~nvptx patches=51aebe82afc9a0433ca3503a36592edf5ca769b1433986919cfb9ae2ddf3e343 ~piclibs~strip arch=linux-rhel6-core2
 -   pbouq4g      ^gmp@6.1.2%gcc@4.4.7 arch=linux-rhel6-core2
 -   7s5w76y          ^autoconf@2.69%gcc@4.4.7 arch=linux-rhel6-core2
 -   xkdl6g2              ^m4@1.4.18%gcc@4.4.7 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-rhel6-core2
 -   nsk22pg                  ^libsigsegv@2.12%gcc@4.4.7 arch=linux-rhel6-core2
 -   wxdawoa              ^perl@5.30.0%gcc@4.4.7+cpanm+shared+threads arch=linux-rhel6-core2
 -   x5isbjk                  ^gdbm@1.18.1%gcc@4.4.7 arch=linux-rhel6-core2
 -   ea5sbdq                      ^readline@8.0%gcc@4.4.7 arch=linux-rhel6-core2
 -   tj5hsji                          ^ncurses@6.1%gcc@4.4.7~symlinks~termlib arch=linux-rhel6-core2
 -   wrblnyo                              ^pkgconf@1.6.3%gcc@4.4.7 arch=linux-rhel6-core2
 -   eexy7pf          ^automake@1.16.1%gcc@4.4.7 arch=linux-rhel6-core2
 -   cryjtgh          ^libtool@2.4.6%gcc@4.4.7 arch=linux-rhel6-core2
 -   nizawm4      ^isl@0.18%gcc@4.4.7 arch=linux-rhel6-core2
 -   ddtcqci      ^libiconv@1.16%gcc@4.4.7 arch=linux-rhel6-core2
 -   giua3so      ^mpc@1.1.0%gcc@4.4.7 arch=linux-rhel6-core2
 -   laq5nlz          ^mpfr@3.1.6%gcc@4.4.7 patches=66a5d58364113a21405fc53f4a48f4e8 arch=linux-rhel6-core2
 -   6phegih      ^zlib@1.2.11%gcc@4.4.7+optimize+pic+shared arch=linux-rhel6-core2

...
```

But `spack arch` gives:

```
$ ./atdm-spack/spack/bin/spack arch
linux-rhel6-broadwell
```

This shows the miss-match in that `spack arch` returns `linux-rhel6-broadwell` but `spack install` uses `arch=linux-rhel6-core2`.  Again, our scripts require that `spack arch` returns the name arch that `spack install` uses. 

For now, hopefully, we can just manually pass in `--arch <the-arch>` to our driver. Have not gotten a successful build of the Spack package we use since upgrading to Spack `v0.13.0` so I don't know if this will work.  (Trying now.)

**Comment by alalazo** [comment] 2019-10-30 13:40
> This shows the miss-match in that spack arch returns linux-rhel6-broadwell but spack install uses arch=linux-rhel6-core2. Again, our scripts require that spack arch returns the name arch that spack install uses

There's no mismatch, it's the same as before. In the new example you are compiling with `gcc@4.4.7`. Since that old version of gcc knows how to optimize up to the `core2` microarchitecture, that is selected as the best match to `broadwell`. 

If you register a newer compiler (like the `gcc@7.2.0` you are building) then the target will be correctly set to `broadwell` - since the new compiler knows how to generate code for that microarchitecture.

**Comment by bartlettroscoe** [comment] 2019-10-30 13:48
> There's no mismatch

@alalazo, how is that?  The command `spack arch` returns `linux-rhel6-broadwell` but `spack install` selects `arch=linux-rhel6-core2`.  Therefore, after `spack install` is complete, when our `install-trilinos-env.sh` script looks for installed components for `spack arch`, it will not find anything (because it will be looking for `` but what is installed will have `` in the directory name).  That means that we can't use `spack arch` to anything useful.

Here is the bash script that our driver uses which will error out.

```
# Find a package install dir and echo it to STDOUT
#
# This looks for install directories of the form:
#
#   spack/opt/spack/<arch>/<pkg-compiler-name>-<pkg-compiler-ver>/<pkg-name>-<pkg-ver>-<hash>
#
function get_installed_package_path() {

  # Input arguments
  pkg_and_ver=$1             # <pkg-name>@<pkg-ver>
  spack_arch=$2              # <arch>
  pkg_compiler_and_ver=$3    # <pkg-compiler-name>@<pkg-compiler-ver>

  pkg_name=`get_package_name_from_package_and_ver "${pkg_and_ver}"`
  pkg_ver=`get_package_ver_from_package_and_ver "${pkg_and_ver}"`

  pkg_compiler_name=`get_package_name_from_package_and_ver "${pkg_compiler_and_ver}"`
  pkg_compiler_ver=`get_package_ver_from_package_and_ver "${pkg_compiler_and_ver}"`
 
  pkg_install_dir="atdm-spack/spack/opt/spack/${spack_arch}/${pkg_compiler_name}-${pkg_compiler_ver}/${pkg_name}-${pkg_ver}-*"

  pkg_path=`ls -d ${pkg_install_dir} | head -1`

  if [ "${pkg_path}" == "" ] ; then
    echo "ERROR, can't find ${pkg_install_dir}!" >&2
    exit 1
  fi

  echo "${PWD}/${pkg_path}"
}
```

We need that to build up `pacakges.yaml` file for installed tools packages like 'cmake', 'ninja', 'perl', 'python', etc. so that they can be reused and not built over and over again for each compiler.

**Comment by tgamblin** [comment] 2019-10-30 13:55
@bartlettroscoe: not sure what you want us to do. The old compilers will not generate code for the new architecture. We’re labeling the binaries according to *where they can be used*. You can still load a core2 module on a broadwell.  What’s the issue?

**Comment by tgamblin** [comment] 2019-10-30 13:56
@alalazo: we may not have anything that makes it easy for users to do this.  Is there some command we could add for @bartlettroscoe that would allow it?  We already add compatible architectures to the module path.  What does the script need to do?

**Comment by fryeguy52** [comment] 2019-10-30 14:02
what about something like `spack arch %gcc@4.4.7` that would return what `spack install` would use for gcc@4.4.7?

**Comment by alalazo** [comment] 2019-10-30 14:05
@bartlettroscoe Looking at the name of your bash function:
```bash
function get_installed_package_path() {
```
can't that be substituted by `spack location -i` or `spack find -p`?

**Comment by bartlettroscoe** [comment] 2019-10-30 14:14
@alalazo asked:

> can't that be substituted by `spack location -i` or `spack find -p`?

No, I tried that and it was super slow and did not work.  (I don't remember all of the details but I can look back at my notes.)  The current script was arrived at after days and days of experimenting and testing to find what actually works. 

Another option is capture the output from the `spack install` command and then grep it for the `arch` and then look for the install paths for each package.  That is a bit hacked but it would work for our current use case.

@tgamblin asked:

> Is your script online somewhere?

I want to look at making the `atdm-spack` repo public on github so others can see it.  There is nothing sensitive in that repo.  It just deals with spack stuff.  But Sandia is strange about stuff like this.

**Comment by fryeguy52** [comment] 2019-10-30 14:25
@bartlettroscoe or something using `spec` like:
```console
$ spack spec zlib %gcc@4.4.7
Input spec
--------------------------------
zlib%gcc@4.4.7

Concretized
--------------------------------
zlib@1.2.11%gcc@4.4.7+optimize+pic+shared arch=linux-rhel6-core2
```
will give us which arch will be used

**Comment by becker33** [comment] 2019-10-30 14:28
@bartlettroscoe 

1. I would appreciate if you could find the notes you have on the `spack location -i` command failure, that is of definite interest to me.

2. Your script has a failure case if you ever install multiple configurations of the same package/version combination. I don't know how likely it is to come up in your current use-case, but hdf5 with/without mpi would be an easy way for something like that to come up.

**Comment by tgamblin** [comment] 2019-10-30 14:38
@fryeguy52: there is also `spack find —json` and `spack find —format` you might want to look at. 

Note the JSON output of `spack find —json` is “flatter” to be more amenable to things like `jq`.  We could also add `spack spec —format` if you think it’d help.

**Comment by tgamblin** [comment] 2019-10-30 14:49
Note that if your package.py files change, spack spec may need to reindex the to concretize again.

**Comment by bartlettroscoe** [comment] 2019-10-30 14:51
I can sync our atdm-spack repo to the LLNL bitbucket site for now so people can see what we are trying to do.  I am currently working on the branch `cdofa-68-spack-upgrade-concretize-together`.  (I have not actually gotten to test out `conretization=together` yet because the upgrade to version 0.13.0 broke the basic functioning of the install process.)

**Comment by bartlettroscoe** [comment] 2019-10-30 15:04
> Modtime vs modtime of the indexes in ~/.spack

We don't let spack write into ~/.spack/ (which is a disaster if you try to run multiple spack configs in the same user account and destroys reproducability).

What are the "indexes" and how are they computed?


We don't let

**Comment by bartlettroscoe** [comment] 2019-10-30 15:28
@becker33 said:

> Your script has a failure case if you ever install multiple configurations of the same package/version combination. I don't know how likely it is to come up in your current use-case, but hdf5 with/without mpi would be an easy way for something like that to come up.

Right.  But in our use case that will not happen.  And actually, we only look for installed tools packages like 'cmake', 'ninja-fortran', 'python', etc. which we never need more than one of these install per system.  (The only exception is hacks we have been having to put int for missing `-L` paths for libraries.  See #12304).

**Comment by becker33** [comment] 2019-10-30 16:22
Yes.

**Comment by bartlettroscoe** [comment] 2019-11-05 21:07
FYI: Looks like I can get what I need after a `spack install` with:

```
$ time ./atdm-spack/spack/bin/spack find --format "{arch}" | tail -n 1
linux-rhel6-x86_64

real    0m4.622s
user    0m4.475s
sys     0m0.136s
```

Don't know why that is so slow but is that going to be robust?

**Comment by bartlettroscoe** [comment] 2019-11-05 21:29
And this run instantly:

```
$ grep arch= spack.install.out | head -1 | sed 's/.*arch=\([0-9a-z-]*\)/\1/' | cut -d' ' -f 1
linux-rhel6-x86_64
```

**Comment by becker33** [comment] 2019-11-12 01:17
@bartlettroscoe 

The `spack find --format` command and the format string syntax should be a stable part of the API now, yes.

The `spack find` command is slower than your grep script because it had to search every spack package you have installed. If you did `spack find --format "{arch}" /hash-of-a-spack-install` instead it should be substantially faster

**Comment by bartlettroscoe** [comment] 2019-11-12 01:59
@becker33, the install process don't know the install hash anymore than I know the arch.   Spack install determines both of these things internally.  All the install process knows is the compiler@version and the package name and version.

**Comment by tgamblin** [comment] 2019-11-12 09:50
The hash is output at the very least as part of the directory name after the `[+]` in the install output. We could also make `spack install` spit it out in an easier to parse way if you want.

**Comment by tgamblin** [comment] 2019-12-02 22:26
Based on:
> FYI: Looks like I can get what I need after a spack install with:

Closing this as I think it's complete, or the SNL folks have what they need.  Let us know if there are further issues.

**Closed by tgamblin** 2019-12-02 22:26 UTC
Labels: bug, compilers, microarchitectures, platform-support, snl-atdm
