### ISSUE TITLE
spack spec/install not responding

### ISSUE THREAD

**Issue by mShining** [spack/spack#11960] opened 2019-07-09 04:51 UTC
### General
I ran `spack spec [package_name]` and didn't get the specificaions but to wait like forever.

### Steps to reproduce the issue

```console
$ spack spec cmake
```
As far as I've tried, `cmake` can be any package that does exist.

### Error Message

If `package_name` is a package that does exist, it just shows "Concretized" but nothing else, until I manually abort it.
```console
$ spack spec cmake
```
![image](https://user-images.githubusercontent.com/11251757/60859640-1a0d4b00-a246-11e9-84c2-e2b962513688.png)

If `package_name` is a package that doesn't exist, it functions well like expected.
```console
$ spack spec foo_not_exist
```
![image](https://user-images.githubusercontent.com/11251757/60859228-593a9c80-a244-11e9-8060-1215dfcef1a7.png)

Re-run the commands with the additional -d/--stacktrace flags:
```console
$ spack -d --stacktrace spec cmake
```

![image](https://user-images.githubusercontent.com/11251757/60859609-0366f400-a246-11e9-8110-e86c0e8f3623.png)

If needed, here's the right behavior in the case where package does not exist.
```console
$ spack -d --stacktrace spec foo_not_exist
```

![image](https://user-images.githubusercontent.com/11251757/60859897-c94a2200-a246-11e9-9782-0cd2a102a115.png)

### Information on your system

This includes:

 1. which platform you are using
```console
$ uname -a
```
![image](https://user-images.githubusercontent.com/11251757/60859943-f7c7fd00-a246-11e9-9d94-a83351f36013.png)

 2. any relevant configuration detail (custom `packages.yaml` or `modules.yaml`, etc.)

No custom modifications, just installed under convention.

-----

### P.S.

Commands with the similar running process are **NOT** working properly as well, such as `spack install`.
Others are fine, for example, `spack info <packsge>` and `spack mirror <list/add/remove>` are working perfectly.

**Comment by alalazo** [comment] 2019-07-13 11:15
I'm not able to reproduce the bug on 5bc15b2d9a061b37e55434edec6ae3954e95032b:
```
$ time spack spec cmake
Input spec
--------------------------------
cmake

Concretized
--------------------------------
cmake@3.14.5%gcc@9.0.1~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu18.04-x86_64
    ^ncurses@6.1%gcc@9.0.1~symlinks~termlib arch=linux-ubuntu18.04-x86_64
        ^pkgconf@1.6.1%gcc@9.0.1 arch=linux-ubuntu18.04-x86_64
    ^openssl@1.1.1b%gcc@9.0.1+systemcerts arch=linux-ubuntu18.04-x86_64
        ^perl@5.26.2%gcc@9.0.1+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-ubuntu18.04-x86_64
            ^gdbm@1.18.1%gcc@9.0.1 arch=linux-ubuntu18.04-x86_64
                ^readline@7.0%gcc@9.0.1 arch=linux-ubuntu18.04-x86_64
        ^zlib@1.2.11%gcc@9.0.1+optimize+pic+shared arch=linux-ubuntu18.04-x86_64

real    0m0,773s
user    0m0,684s
sys     0m0,087s

$ uname -a
Linux nuvolari 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Could you try:
```console
spack clean -a
```
and check if concretization is stuck again? Beware that the first time you give a command it might take longer (around a minute) as it is rebuilding a few lookup tables for later reuse.

**Comment by alalazo** [comment] 2019-07-18 08:18
@mShining Any news on this issue?

**Comment by alalazo** [comment] 2019-07-20 10:55
Closing the issue. Feel free to reopen if you have a reproducer.

**Closed by alalazo** 2019-07-20 10:55 UTC
Labels: bug, unreproducible
