### ISSUE TITLE
Conflicting conditional dependencies error

### ISSUE THREAD

**Issue by mileschen360** [spack/spack#6231] opened 2017-11-09 04:12 UTC
What does the following error mean? It happened when I run `spack install slepc`.

`Error: Conflicting conditional dependencies onpackage slepc for spec slepc@3.8.0%gcc@5.3.0+arpack arch=linux-rhel6-x86_64 ^blas^bzip2@1.0.6%gcc@5.3.0+shared arch=linux-rhel6-x86_64 ^lapack^ncurses@6.0%gcc@5.3.0~symlinks arch=linux-rhel6-x86_64 ^openssl@1.0.2k%gcc@5.3.0 arch=linux-rhel6-x86_64 ^petsc@3.8:3.8.99^pkg-config@0.29.2%gcc@5.3.0+internal_glib arch=linux-rhel6-x86_64 ^python@2.7.14%gcc@5.3.0+pic+shared~tk~ucs4 arch=linux-rhel6-x86_64 ^readline@7.0%gcc@5.3.0 arch=linux-rhel6-x86_64 ^sqlite@3.20.0%gcc@5.3.0 arch=linux-rhel6-x86_64 ^zlib@1.2.11%gcc@5.3.0+optimize+pic+shared arch=linux-rhel6-x86_64`

**Comment by scheibelp** [comment] 2017-11-09 19:28
I'm looking into this. In the meantime you should be able to proceed with:

`spack spec slepc@3.8.0 ^petsc+mpi`

or

`spack spec slepc@3.8.0 ^petsc~mpi`

(depending on whether you want to build with mpi)

**Comment by citibeth** [comment] 2019-07-03 23:18
All instances of `~` in `depends_on()` should be removed.

**Comment by alalazo** [comment] 2020-11-01 21:22
Duplicate of #1781

**Closed by alalazo** 2020-11-01 21:22 UTC
Labels: concretization
