### ISSUE TITLE
cmake version is chosen prior to package's version

### ISSUE THREAD

**Issue by davydden** [spack/spack#7288] opened 2018-02-19 22:55 UTC
Looks like for `CMakePackage` concretizer fist settles on `cmake` version and only then tries to choose version of the root package. This may lead to failures in concretization if the root package has extra constraints based on its version.

Example is `dealii`. Current stable release is `8.5.1` which needs `cmake@3.9.x`, but if we try `spack spec dealii` it will fail with 

```
dealii requires cmake version :3.9.99, but spec asked for 3.10.1
```

The simplest workaround is to be explicit with versions, i.e. do `spack spec dealii@8.5.1`, but it would be better to have some fix in the order in which dependencies are concretized.
I simply can't explain why Spack would choose `cmake` version prior to chosing the latest stable version of `dealii`.

### Expected Result

Spack should concretize default build of `dealii`.

### Actual Result

```
dealii requires cmake version :3.9.99, but spec asked for 3.10.1
```

### Steps to reproduce the issue

```console
$ spack spec dealii
...
```

### Information on your system

Linux/macOS.

**Comment by christianbaensch** [comment] 2018-02-21 09:46
Good morning,

same here on a brand new Ubuntu 16.04 with offiicial cmake 3.5.1 provided. 
The error

`dealii requires cmake version :3.9.99, but spec asked for 3.10.1`

also occured within the command

`$ spack install dealii`

**Comment by davydden** [comment] 2018-02-21 09:59
@tgamblin @scheibelp I think this issue is a regression with concretizer. I can bisect, but I am quite certain that was not a problem before.

**Comment by davydden** [comment] 2018-03-28 06:11
@tgamblin @scheibelp i bisected this issue and unsatisfactory it lead me to the PR where conditional dependency on `CMake` is introduced https://github.com/spack/spack/pull/7010/ . Good news -- it's not a regression, bad news I don't know any way to fix it and until the next `dealii` major release, the concretizer will fail by default.

Essentially, the issue is that we have
```
depends_on(cmake)
```
in `CMakePackage` and 
```
depends_on('cmake@:3.9.99',    when='@:8.99')
```
in `dealii`. 

Most likely this issue is a duplicate of https://github.com/spack/spack/issues/5753 and probably even these 2016 issues of mine https://github.com/spack/spack/issues/1781 and @adamjstewart https://github.com/spack/spack/issues/2632 .

Are there any updates on the more clever concretizer? Looks like a number of currently opened issues are due to this behaviour. Is it possible to hack the current conretizer to be more careful in these situations?

**Comment by healther** [comment] 2018-03-28 09:02
You should be able to work around this via `spack install dealii ^cmake@3.10.1`, essentially holding the hand of the concretizer.

**Comment by davydden** [comment] 2018-03-28 09:04
> You should be able to work around this via spack install dealii ^cmake@3.10.1, essentially holding the hand of the concretizer.

Sorry, i was not precise enough above. I certainly know of workaround how to conretize things, 
but they are not really _workarounds_ for new users. In the same way I can also get around the problem by being specific about the version, i.e. `spack install dealii@8.5.1` or `spack install dealii@develop`.

**Comment by alalazo** [comment] 2020-11-01 21:45
Duplicate of #1781

**Comment by alalazo** [comment] 2020-11-01 21:45
Different manifestation of the same bug, non-conditional specs are resolved with their default values for variants, etc. If a spec is both unconditional AND conditional the original concretizer may fail

**Closed by alalazo** 2020-11-01 21:45 UTC
Labels: concretization
