### ISSUE TITLE
multiple site-packages/backports/__init__.py files cause activation failure

### ISSUE THREAD

**Issue by lee218llnl** [spack/spack#7001] opened 2018-01-19 16:48 UTC
Multiple py-backports packages include a site-packages/backports/__init__.py file, thus causing a failure when trying to activate multiple py-backports packages.

$ ./bin/spack activate py-backports-functools-lru-cache
==> Error: Extension blocked by file: /nfs/tmp2/lee218/delete/spack-basemap/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/python-2.7.14-7rci3jkmuht2uiwp433afigveuf4ocnu/lib/python2.7/site-packages/backports/__init__.py

$ ls -l opt/spack/linux-rhel7-x86_64/gcc-4.9.3/py-backports*/lib/python2.7/site-packages/backports/__init__.py
-rw------- 1 lee218 lee218  65 May 12  2017 opt/spack/linux-rhel7-x86_64/gcc-4.9.3/py-backports-functools-lru-cache-1.4-znbn6jwuu6xwpbdvk3mclmcntkcjwuhi/lib/python2.7/site-packages/backports/__init__.py
-rw------- 1 lee218 lee218  75 Aug 19  2014 opt/spack/linux-rhel7-x86_64/gcc-4.9.3/py-backports-shutil-get-terminal-size-1.0.0-k2m5kjyz4j3cgpntij77xkiwsnqyc627/lib/python2.7/site-packages/backports/__init__.py
-rw------- 1 lee218 lee218 155 Dec 19  2015 opt/spack/linux-rhel7-x86_64/gcc-4.9.3/py-backports-ssl-match-hostname-3.5.0.1-jsr5wgmh2cfiscwcdptfnov44zna7emk/lib/python2.7/site-packages/backports/__init__.py

Any thoughts on how to best manage this? Currently all of the __init__.py files effectively do the same thing:

$ cat opt/spack/linux-rhel7-x86_64/gcc-4.9.3/py-backports*/lib/python2.7/site-packages/backports/__init__.py__path__ = __import__('pkgutil').extend_path(__path__, __name__)
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
# This is a Python "namespace package" http://www.python.org/dev/peps/pep-0382/
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)

**Comment by scheibelp** [comment] 2018-01-20 02:44
I'm looking to have a solution for this by the end of 1/23 - my aim is to allow packages to customize their activations, e.g. for `PythonPackage` instances to ignore conflicts related to `__init__` files in their namespaces, if they have namespaces.

Side note: there are a few different ways of expressing namespaces and one of them avoids generating `__init__` files. That is decided by the distributors and inconsistencies have created problems. See also: https://github.com/spack/spack/pull/4155

**Comment by healther** [comment] 2018-01-23 10:50
This reads as if #6131 were somewhat related

**Comment by scheibelp** [comment] 2018-01-24 04:52
> I'm looking to have a solution for this by the end of 1/23

New estimate: 1/29 (this is currently my priority so I'm confident I can hit that target)

> This reads as if #6131 were somewhat related

Views can sidestep this issue with `ignore-conflicts`, so the issue is a bit different. However my aim is to resolve both this and #6131 by allowing packages to customize how they are added to views.

**Comment by scheibelp** [comment] 2018-02-01 19:08
I have a WIP PR on this at https://github.com/spack/spack/pull/7152

**Comment by scheibelp** [comment] 2018-11-02 19:35
#7152 has been merged so I consider this resolved

**Closed by scheibelp** 2018-11-02 19:35 UTC

**Comment by lee218llnl** [comment] 2018-11-02 21:04
@scheibelp, just to be clear, is the suggested solution is to do something like: 

`./bin/spack view --verbose symlink -i my_python_view py-backports-ssl-match-hostname  py-backports-functools-lru-cache`

**Comment by scheibelp** [comment] 2018-11-02 21:19
`-i` will resolve the issue by itself, since it will avoid the complaint about the conflicting `__init__.py` files (so doesn't depend on #7152).

If you add a `py_namespace` attribute to a python package that is part of a namespace, then the `__init__.py` files will not be considered in conflict (and you won't have to specify `-i`).

**Comment by scheibelp** [comment] 2018-11-02 21:21
Oh and I did that for `py-backports-ssl-match-hostname` already but not `py-backports-functools-lru-cache`
