### ISSUE TITLE
Installation Issue: slate

### ISSUE THREAD

**Issue by wspear** [spack/spack#11278] opened 2019-04-24 17:26 UTC
Installing slate fails as shown below. I tried setting f_mkl to 1 without checking for mkl in the spec but that resulted in errors like:
test/scalapack_copy.hh:70:32: error: 'cublasGetMatrix' was not declared in this scope
So presumably the intel_mkl package is noit providing the intended cublas functionality that package.py says it is expecting.

---

### Steps to reproduce the issue

```console
$ spack install slate~cuda^mpich
==> Executing phase: 'install'
==> Error: KeyError: 'mkl'

/spack/var/spack/repos/builtin/packages/slate/package.py:50, in install:
         47        f_cuda = "1" if spec.variants['cuda'].value else "0"
         48        f_mpi = "1" if spec.variants['mpi'].value else "0"
         49        f_openmp = "1" if spec.variants['openmp'].value else "0"
  >>     50        f_mkl = "1" if spec.variants['mkl'].value else "0"
         51
         52        compiler = 'mpicxx' if spec.variants['mpi'].value else ''
         53
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux 0b38ba5118cc 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by becker33** [comment] 2019-07-22 22:03
@wspear the line throwing the error is not in any code accepted to Spack, and fails because it references a non-existent variant. Does the error occur when using the `slate` package as provided?

**Comment by wspear** [comment] 2019-08-01 18:01
@becker33 This works with the latest spack. Whatever was amiss seems to have been corrected, but no idea what it may have been.

**Comment by becker33** [comment] 2019-08-02 20:09
Closing as not reproducible

**Closed by becker33** 2019-08-02 20:09 UTC
Labels: build-error, impact-low
