### ISSUE TITLE
Infinite recursion getattr

### ISSUE THREAD

**Issue by ibaned** [spack/spack#9392] opened 2018-10-01 16:51 UTC
While trying to run any `spack` command, I get an error about maximum recursion. It looks like `getattr` is calling itself in one of the Python classes.

### Steps to reproduce the issue

```console
$ source $SPACK_ROOT/share/spack/setup-env.sh
```

### Error Message

```console
...
  File "/home/daibane/src/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
  File "/home/daibane/src/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
  File "/home/daibane/src/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
  File "/home/daibane/src/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
  File "/home/daibane/src/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
  File "/home/daibane/src/spack/lib/spack/llnl/util/lang.py", line 552, in instance
    self._instance = self.factory()
  File "/home/daibane/src/spack/lib/spack/spack/config.py", line 547, in _config
    defaults = InternalConfigScope('_builtin', config_defaults)
  File "/home/daibane/src/spack/lib/spack/spack/config.py", line 238, in __init__
    _validate_section({section: dsec}, section_schemas[section])
  File "/home/daibane/src/spack/lib/spack/spack/config.py", line 611, in _validate_section
    _validate_section.validator(schema).validate(data)
  File "/home/daibane/src/spack/lib/spack/external/jsonschema/validators.py", line 67, in __init__
    resolver = RefResolver.from_schema(schema)
  File "/home/daibane/src/spack/lib/spack/external/jsonschema/validators.py", line 260, in from_schema
    return cls(schema.get(u"id", u""), schema, *args, **kwargs)
  File "/home/daibane/src/spack/lib/spack/external/jsonschema/validators.py", line 245, in __init__
    for id, validator in iteritems(meta_schemas)
  File "/home/daibane/src/spack/lib/spack/external/jsonschema/_utils.py", line 20, in __init__
    self.store.update(*args, **kwargs)
  File "/home/daibane/src/spack/lib/spack/external/jsonschema/validators.py", line 244, in <genexpr>
    (id, validator.META_SCHEMA)
  File "/usr/lib/python2.7/_abcoll.py", line 406, in iteritems
    yield (key, self[key])
  File "/home/daibane/src/spack/lib/spack/external/jsonschema/_utils.py", line 23, in __getitem__
    return self.store[self.normalize(uri)]
  File "/home/daibane/src/spack/lib/spack/external/jsonschema/_utils.py", line 16, in normalize
    return urlsplit(uri).geturl()
  File "/home/daibane/src/spack/lib/spack/external/jsonschema/compat.py", line 37, in urlsplit
    scheme, netloc, path, query, fragment = _urlsplit(url)
  File "/usr/lib/python2.7/urlparse.py", line 174, in urlsplit
    allow_fragments = bool(allow_fragments)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

### Information on your system

This is an Ubuntu 17.10 system

**Comment by ibaned** [comment] 2018-10-01 16:59
Note that this is using the `develop` version of `spack`, commit 57236fa2ce136ded8f9fdaaa36fbd8f46ab98666

**Comment by ibaned** [comment] 2018-10-01 17:07
commit 8ad40babd624b4ca512639848ef72235fff34bf3 is known to work fine

**Comment by scheibelp** [comment] 2018-10-01 18:13
This appears to be a duplicate of https://github.com/spack/spack/issues/9206

Feel free to reopen if that appears incorrect.

**Closed by scheibelp** 2018-10-01 18:13 UTC
