### ISSUE TITLE
Testing hysteresis with different selection methods

### ISSUE THREAD

**Issue by greenc-FNAL** [spack/spack#14433] opened 2020-01-08 22:17 UTC
Since https://github.com/spack/spack/commit/4beb9fc5d36ab85cb5d2e43e451b26204f36cdcd, `develop` has exhibited the following worrying behavior:
```console
spack test -vv cmd_extensions.py
```
executes two tests, `cmd_extensions.py::test_simple_command_extension` and `cmd_extensions.py::test_command_with_import`, the former passing and the latter failing with a strange YAML validation schema error:
```console
<snip>
self = <jsonschema.validators.Validator object at 0x7f4b72b7a0d0>
schema = {'$schema': 'http://json-schema.org/schema#', 'additionalProperties': False, 'properties': {'config': {'default': {}, ...{...}]}, 'ccache': {'type': 'boolean'}, ...}, 'type': 'object'}}, 'title': 'Spack core configuration file schema', ...}
types = (), resolver = None, format_checker = None

    def __init__(
        self, schema, types=(), resolver=None, format_checker=None,
    ):
        self._types = dict(self.DEFAULT_TYPES)
        self._types.update(types)

        if resolver is None:
>           resolver = RefResolver.from_schema(schema)
E           AttributeError: 'NoneType' object has no attribute 'from_schema'

../../external/jsonschema/validators.py:64: AttributeError

```

In contrast:
```console
spack test -vvk cmd_extensions
```
while executing the same two tests—_in apparently the same order_—shows that both tests pass. This is in fact what happens to these tests in CI.

Any insight into locating the source of the hysteresis would be appreciated.

**Comment by chissg** [comment] 2020-01-08 22:17
@tgamblin

**Comment by tgamblin** [comment] 2020-01-09 01:20
@chissg: see #14319 for details on the change.  You can add a `-k` option to get the old behavior you want.

I agree that `pytest`'s error message is unhelpful here... I'd normally say we should upgrade the external package, but we're tied to a relatively old version of `pytest` to continue supporting Python 2.6.  Would it help if we added something to catch the attribute error and say "did you mean..."?

**Comment by chissg** [comment] 2020-01-09 03:47
@tgamblin I'm still not sure of the correlation between the first form of the invocation and the error. What is `pytest` not doing that is causing the second test to fail, or is there a weakness in the test I should be fixing?

**Comment by tldahlgren** [comment] 2020-01-09 21:18
FWIW.  I ran the tests both ways -- from `develop` at `6b3e173` -- and it passes.

**Comment by chissg** [comment] 2020-01-13 14:39
Still trying to ascertain what makes this reproducible for me but not for anyone else. Platform is SLF7.7.

**Comment by chissg** [comment] 2020-01-13 22:26
@tgamblin I have been able to reproduce this on a (different) SLF7.7 machine. The error does not occur if `/usr/bin/python3` is available, which is used for preference. It _does_ occur if `/usr/bin/python` (corresponding to version 2.7.5) is invoked. On the machine where `python3` is not present the invocation of `spack test -vv cmd_extensions.py` fails reliably; on the other machine it passes unless I change the order of preference of Python executables at https://github.com/spack/spack/blob/673a725576d2c6b9caa8b0e60d7161befbf98b95/bin/spack#L14 to invoke Python2 for preference. Quite _what_ is sensitive to Python2 versus Python3 I have no idea, but at least I know I'm not hallucinating.

**Comment by alalazo** [comment] 2023-05-04 12:32
@greenc-FNAL Can we close this one, since Spack doesn't support running with Python 2 anymore?

**Closed** 2024-07-03 06:09 UTC
Labels: tests, python2, robustness
