### ISSUE TITLE
strange concretization error with multi-line depends_on

### ISSUE THREAD

**Issue by mwkrentel** [spack/spack#15478] opened 2020-03-13 04:01 UTC
I'm seeing a strange concretization error.  So strange that I don't
even know how to write a good subject line.

I want to write a dependency with multiple `depends_on` lines (for
clarity and separation of concerns).

Artificially add `depends_on('zlib')` to package xz.

```
depends_on('zlib~pic')
depends_on('zlib@:1.2.8', when='@:5.2.4')
```

This says that xz always depends on zlib with pic off, and you must
use zlib <= 1.2.8 when xz <= 5.2.4.  Note that 5.2.4 is the latest
version of xz.

AFAIK, this is supposed to work and I have used this before.  All the
constraints go into the giant SAT solver.

```
$ spack spec xz @5.2.3
--------------------------------
xz@5.2.3%gcc@7.3.1 arch=linux-fedora26-westmere
    ^zlib@1.2.8%gcc@7.3.1+optimize~pic+shared arch=linux-fedora26-westmere


$ spack spec xz @5.2.4
--------------------------------
xz@5.2.4%gcc@7.3.1 arch=linux-fedora26-westmere
    ^zlib@1.2.8%gcc@7.3.1+optimize~pic+shared arch=linux-fedora26-westmere
```

This works and it picks up both constraints: ~pic and 1.2.8.

But then:
```
$ spack spec xz  
--------------------------------
==> Error: An unsatisfiable version constraint has been detected for spec:

    zlib@1.2.11%gcc@7.3.1+optimize~pic+shared arch=linux-fedora26-westmere

while trying to concretize the partial spec:

    xz@5.2.4%gcc@7.3.1 arch=linux-fedora26-westmere

xz requires zlib version :1.2.8, but spec asked for 1.2.11
```

Something somewhere has prematurely fixed on zlib 1.2.11 and that
conflicts with :1.2.8.  Even though it's the same 5.2.4 version that
works when you explicitly say 5.2.4.

WTF !?

Even stranger, if I change the depends to 5.2.3, not the latest
version:

```
depends_on('zlib~pic')
depends_on('zlib@:1.2.8', when='@:5.2.3')
```

then everything works as expected.  It works for xz@5.2.4, 5.2.3,
5.2.0, default (unspecified).  All works and picks up the correct zlib
version.

Btw, here's the use case that I actually care about.  For hpctoolkit,
the new binutils 2.34 breaks the build.  So I want:

```
depends_on('binutils+libiberty~nls', type='link')
depends_on('binutils@:2.33.1', when='@:2020.03.01')
```

Again, `spack spec hpctookit` fails with 2.34 conflicting with
:2.33.1, but `spack spec hpctookit @2020.03.01` works.  Again,
2020.03.01 is the latest numbered rev (not counting master).

@becker33 @scheibelp  Any idea what's going on?

Whatever it is, it's been around for a while.  I tried going back over
a year and I didn't find a rev where this worked as I'd expect.

**Comment by adamjstewart** [comment] 2020-03-13 16:55
This is a known long-term issue. It's caused by the same issue as https://spack.readthedocs.io/en/latest/known_issues.html#variants-are-not-properly-forwarded-to-dependencies. Basically, Spack's concretizer is trying to solve an NP-hard problem (SAT), so it takes a lot of shortcuts to solve things quickly. One of those shortcuts is that it doesn't backtrack far enough. So logic like:
```python
depends_on('zlib~pic')
depends_on('zlib@:1.2.8', when='@:5.2.4')
```
will cause the concretizer to decide on the version of `zlib` to use before it decides on the version of `xz` to use. You can get around this on the command-line by explicitly specifying which version of `xz` you want to build (or which version of `zlib` to build with). Alternatively, you can use:
```python
depends_on('zlib~pic', when='@5.2.5:')
depends_on('zlib@:1.2.8~pic', when='@:5.2.4')
```

**Comment by mwkrentel** [comment] 2020-03-13 22:48
I see, that's unfortunate.  I'll need to be more careful about how I
write dependencies.

Do you happen to know if this problem of choosing a version early
applies just to versions or also variants?  I know I've written
variants with multiple lines before.  I didn't notice a problem, but
maybe there was and I didn't notice.

Maybe we'll start a Crowd Fund for the new concretizer, or just prove
P = NP, whichever is easier.  :-)

**Comment by adamjstewart** [comment] 2020-03-13 23:14
The same problem occurs with variants, versions, providers, and just about every aspect of the spec. The new concretizer is expected sometime this spring.

**Comment by mwkrentel** [comment] 2020-03-14 03:16
In that case, I have seriously mislead someone somewhere about this.
But I don't remember which package.  Sorry ....

**Comment by alalazo** [comment] 2020-11-02 22:44
Duplicate of #1781

**Comment by alalazo** [comment] 2020-11-02 22:44
#19501 should solve this

**Closed by alalazo** 2020-11-02 22:44 UTC
Labels: bug, concretization, duplicate
