### ISSUE TITLE
Spack install no-checksum not working correctly with spack environments

### ISSUE THREAD

**Issue by prckent** [spack/spack#11636] opened 2019-06-05 18:06 UTC
I am having trouble using the --no-checksum setting with install and spack environments.
Use case involves setting up multiple compilers and libraries using the spack environments capability to simplify development and testing of another program and avoid the maintenance headache of a brittle version specific script. The --no-checksum setting does not appear to work with e.g. libxml2 on the install line when it is invoked in the second created environment. A workaround would be very helpful.

### Steps to reproduce the issue

Simplified script:

```
rm -r -f $HOME/apps/spack
rm -f $HOME/.spack/linux/compilers.yaml
cd $HOME/apps
git clone https://github.com/spack/spack.git
cd spack/bin
./spack bootstrap

module() { eval `/usr/bin/modulecmd bash $*`; }

export SPACK_ROOT=$HOME/apps/spack
. $SPACK_ROOT/share/spack/setup-env.sh

echo --- Spack list
spack find
echo --- Modules list
module list
echo --- End listings

gcc_vnew=8.3.0
gcc_vold=5.5.0
libxml2_vnew=2.9.9
libxml2_vold=2.9.1

echo --- START env `date`
spack env create gccnewbuild
spack env activate gccnewbuild
spack install gcc@${gcc_vnew}
spack load gcc@${gcc_vnew}
spack compiler add
spack add libxml2@${libxml2_vnew}%gcc@${gcc_vnew}
# Intended usage would have many more adds here

spack install --no-checksum #because some packages such as libxml2 don't have checksums
spack env deactivate
echo --- FINISH env `date`

echo --- START env `date`
spack env create gccoldbuild
spack env activate gccoldbuild
spack install gcc@${gcc_vold}
spack load gcc@${gcc_vold}
spack compiler add
spack add libxml2@${libxml2_vold}%gcc@${gcc_vold}
# Intended usage would have many more adds here

spack install --no-checksum
spack env deactivate
echo --- FINISH env `date`
```

### Error Message

The error occurs on the second install of libxml2. The first installation of libxml2 appears to be successful.

```
==> Successfully installed zlib
  Fetch: 0.00s.  Build: 1.43s.  Total: 1.44s.
[+] /home/pk7/apps/spack/opt/spack/linux-rhel7-x86_64/gcc-5.5.0/zlib-1.2.11-56rgaosb4ij2unhwfsnbiv7z3qjximce
==> Warning: No Spack mirrors are currently configured
==> Installing libxml2
==> Searching for binary cache of libxml2
==> No binary for libxml2 found: installing from source
==> Warning: There is no checksum on file to fetch libxml2@2.9.1 safely.
==> Error: FetchError: Will not fetch libxml2@2.9.1
    Add a checksum or use --no-checksum to skip this check.

/home/pk7/apps/spack/lib/spack/spack/package.py:996, in do_fetch:
        993                    tty.msg("Fetching with no checksum.", ck_msg)
        994
        995            if not ignore_checksum:
  >>    996                raise FetchError("Will not fetch %s" %
        997                                 self.spec.format('{name}{@version}'), ck_msg)
        998
        999        self.stage.create()

```

### Information on your system

System is a RHEL 7.6 box. spack is today's head version.

**Comment by vsoch** [comment] 2021-05-13 17:40
I just reproduced this in development (spack develop branch on ubuntu 20.04) trying to create an environment with a few scientific libraries, and (even with --no-checksum) it comes down to:

```
==> Warning: There is no checksum on file to fetch python@3.8 safely.
==> Error: FetchError: Will not fetch python@3.8
    Add a checksum or use --no-checksum to skip this check.
```
This issue is almost 2 years old - has anyone taken a look?

**Comment by vsoch** [comment] 2021-05-13 17:50
I tried moving up the config command to not use a checksum to earlier in install(), because the environment interaction was previously before it (and thus not influencing it), this part:

```python
if args.no_checksum:
    spack.config.set('config:checksum', False, scope='command_line')
```

and the result is that it moves forward without doing the check, but then fails because it doesn't have a url for the version:

```
==> Cannot find version 3.8 in url_list
==> Error: FetchError: All fetchers failed

/home/vanessa/Desktop/Code/spack/lib/spack/spack/package.py:1360, in do_fetch:
       1357
       1358        self.stage.create()
       1359        err_msg = None if not self.manual_download else self.download_instr
  >>   1360        start_time = time.time()
       1361        self.stage.fetch(mirror_only, err_msg=err_msg)
       1362        self._fetch_time = time.time() - start_time
       1363

```

**Comment by scheibelp** [comment] 2021-05-13 20:59
> This issue is almost 2 years old - has anyone taken a look?

I assigned myself but never got to looking at it. Are you able to look into it? I will reassign this to you for now (but feel free to bounce it back)

**Comment by vsoch** [comment] 2021-05-13 21:00
I tried a few things but I don't have a solution to offer. I'm not sure where the 3.8 is coming from (and why it can't resolve to 3.8.8). Do you have ideas of where to look?

**Comment by scheibelp** [comment] 2021-05-13 21:18
Can you mention the Spack command you were running and your configuration (particularly `packages.yaml`, if it deviates from the defaults). 

I grepped for explicit dependencies on `python@3.8` (which can result in this problem whereas `python@3.8:` should work) in our packages repository and didn't see any examples.

Also to make sure, this issue as originally presented concerns an attempt to download a `libxml2` version that is not listed in the `libxml2` package. Are you requesting something similar in this case? It looks like the attempt to download `python@3.8` is unexpected, so I suspect your issue may not be the same.

**Comment by vsoch** [comment] 2021-05-13 21:33
I'm running this via a pipe from another piece of software I'm developing but I'll do my best! So I'm trying to create and then eventually activate / use a spack environment to go alongside a scientific workflow.

So I start with the spack.yaml, which has what I need for a particular step:

```yaml
spack:
  specs:
  - bcftools
  - samtools
  concretization: together
  view: true
```

And then I create the environment (this works okay)
```bash
spack env create --dir '/home/vanessa/Desktop/Code/snakemake/tutorial/.snakemake/spack/c542467204e7deaea9d01f93905a074a' /home/vanessa/Desktop/Code/snakemake/tutorial/.snakemake/spack/c542467204e7deaea9d01f93905a074a/spack.yaml
```
So then to concretize and install I was running:

```bash
eval `spack env activate --sh /home/vanessa/Desktop/Code/snakemake/tutorial/.snakemake/spack/c542467204e7deaea9d01f93905a074a`; spack install --no-checksum
```
And the --no-checksum doesn't do any kind of difference - and this is because the config to setting it happens _after_ the environment block. But if we move it before, the checksum is skipped and it fails with the second message I posted, that there is no url and the fetchers failed. So I suspect there is some issue with being able to see this version and say "okay, I have a digest for 3.8.8 I'll use that instead." I grepped around the package files and I don't see where it specifies needing exactly this version. I was trying to fix it by updating that. Anyway, it would be helpful if we can talk about where to look, and what to try - I can definitely offer to debub and test and follow up with a PR if we have a solution!

**Comment by scheibelp** [comment] 2021-05-13 21:52
I'd like to see the concretized specs (to make sure that the concretizer didn't decide on this) but since the specs aren't installed, that will take a bit of work: can you try the following commands (in part using `spack-python`):
```
$ spack env create testenv1 /path/to/spack.yaml
$ spack env activate testenv1
$ spack concretize
$ spack-python
Spack version 0.16.1
Python 2.7.16, Darwin x86_64
>>> e1 = spack.environment.read('testenv1')
>>> print(list(e1.concretized_specs())[0][1].tree())
```

**Comment by vsoch** [comment] 2021-05-13 22:39
ah this is embarrassing! So I went back trying to figure out why I didn't see python@3.8 anywhere, and turns out I was looking at the wrong spack.yaml. The 3.8 was hardcoded by yours truly:
```yaml
spack:
    specs:
      - py-pysam
      - py-matplotlib
      - python@3.8
    concretization: together
```
and the reason is because I was copying a conda environment for snakemake verbatim, not thinking that spack doesn't have that version. When I updated it:
```yaml
spack:
    specs:
      - py-pysam
      - py-matplotlib
      - python@3.8.8
    concretization: together
```
the error of course went away! Was the issue that I needed to do `python@3.8:` to imply I'm okay with versions later than that?

**Comment by scheibelp** [comment] 2021-05-13 22:51
Thanks for the extra info!

> Was the issue that I needed to do python@3.8: to imply I'm okay with versions later than that?

Yes. We could definitely make this clearer. There is some complexity though in that some packages have mixed `x.y` and `x.y.z` versions, so there are cases where the user would ask for `3.8` and mean it (but not this one).

That being said, I think the issue as originally reported (unable to skip checksums in an environment) still exists, so I'm going to collapse these comments (feel free to undo that if you disagree).

**Comment by ndalton12** [comment] 2022-01-06 18:52
Hi there, any updates on this issue? Still seeing it as of spack version 0.16.1 (maybe it's since been worked on?)

**Comment by climbfuji** [comment] 2022-07-06 02:32
> Hi there, any updates on this issue? Still seeing it as of spack version 0.16.1 (maybe it's since been worked on?)

I am still seeing this issue with 0.18.0.

**Comment by alalazo** [comment] 2024-01-17 10:42
Seems to work as of:

* **Spack:** 0.22.0.dev0 (28675478ce7c8b3dc1d896829585493ce57cd420)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

Minimal reproducer:
```console
spack env activate --temp
spack add libxml2@=2.9.1
spack concretize --fresh
spack install --no-checksum
```
this gives:
![Screenshot from 2024-01-17 11-40-08](https://github.com/spack/spack/assets/4199709/b1d63905-bea5-4c10-91f3-51b919844f0d)

**Closed by alalazo** 2024-01-17 10:42 UTC
Labels: bug
