### ISSUE TITLE
test_lock_checks_user fails on macOS

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#8430] opened 2018-06-08 16:38 UTC
Just noticed that `spack test` fails on macOS on the latest develop:
```
$ spack test test_lock_checks_user
==================================================================== test session starts =====================================================================
platform darwin -- Python 3.6.4, pytest-unknown, py-1.4.34, pluggy-0.4.0
rootdir: /Users/Adam/spack, inifile: pytest.ini
plugins: hypothesis-3.38.5
collected 1121 items                                                                                                                                          

lib/spack/spack/test/llnl/util/lock.py F
================================================================== short test summary info ===================================================================
FAIL lib/spack/spack/test/llnl/util/lock.py::test_lock_checks_user

================================================================= slowest 20 test durations ==================================================================
0.01s setup    lib/spack/spack/test/llnl/util/lock.py::test_lock_checks_user
0.00s teardown lib/spack/spack/test/llnl/util/lock.py::test_lock_checks_user
0.00s call     lib/spack/spack/test/llnl/util/lock.py::test_lock_checks_user
========================================================================== FAILURES ==========================================================================
___________________________________________________________________ test_lock_checks_user ____________________________________________________________________

self = <py._error.ErrorMaker object at 0x10f6cff60>, func = <built-in function chown>
args = ('/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-57/test_lock_checks_user0', 501, 501), kwargs = {}
__tracebackhide__ = False, cls = <class 'py.error.EPERM'>, value = PermissionError(1, 'Operation not permitted'), tb = <traceback object at 0x111824048>
errno = 1

    def checked_call(self, func, *args, **kwargs):
        """ call a function and raise an errno-exception if applicable. """
        __tracebackhide__ = True
        try:
>           return func(*args, **kwargs)
E           PermissionError: [Errno 1] Operation not permitted: '/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-57/test_lock_checks_user0'

lib/spack/external/py/_error.py:65: PermissionError

During handling of the above exception, another exception occurred:

tmpdir = local('/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-57/test_lock_checks_user0')

    def test_lock_checks_user(tmpdir):
        """Ensure lock checks work."""
        path = str(tmpdir)
        uid = os.getuid()
    
        # self-owned, own group
>       tmpdir.chown(uid, uid)

lib/spack/spack/test/llnl/util/lock.py:944: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
lib/spack/external/py/_path/local.py:69: in chown
    py.error.checked_call(os.chown, str(self), uid, gid)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <py._error.ErrorMaker object at 0x10f6cff60>, func = <built-in function chown>
args = ('/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-57/test_lock_checks_user0', 501, 501), kwargs = {}
__tracebackhide__ = False, cls = <class 'py.error.EPERM'>, value = PermissionError(1, 'Operation not permitted'), tb = <traceback object at 0x111824048>
errno = 1

    def checked_call(self, func, *args, **kwargs):
        """ call a function and raise an errno-exception if applicable. """
        __tracebackhide__ = True
        try:
            return func(*args, **kwargs)
        except self.Error:
            raise
        except (OSError, EnvironmentError):
            cls, value, tb = sys.exc_info()
            if not hasattr(value, 'errno'):
                raise
            __tracebackhide__ = False
            errno = value.errno
            try:
                if not isinstance(value, WindowsError):
                    raise NameError
            except NameError:
                # we are not on Windows, or we got a proper OSError
                cls = self._geterrnoclass(errno)
            else:
                try:
                    cls = self._geterrnoclass(_winerrnomap[errno])
                except KeyError:
                    raise value
>           raise cls("%s%r" % (func.__name__, args))
E           py.error.EPERM: [Operation not permitted]: chown('/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-57/test_lock_checks_user0', 501, 501)

lib/spack/external/py/_error.py:85: EPERM
=================================================================== 1120 tests deselected ====================================================================
========================================================= 1 failed, 1120 deselected in 1.67 seconds ==========================================================
```
Let me know if you need any other info to reproduce this. I was able to reproduce this with both Python 2 and 3 on macOS 10.13.4.

**Comment by alalazo** [comment] 2018-06-11 13:48
Duplicate of #8225

**Closed** 2018-06-11 15:34 UTC
Labels: locking, macOS, tests
