### ISSUE TITLE
glib fails to build on OS X

### ISSUE THREAD

**Issue by IanLee1521** [spack/spack#1755] opened 2016-09-12 22:19 UTC
This might be related to: https://github.com/LLNL/spack/issues/1517#issuecomment-239710073, https://github.com/LLNL/spack/pull/1455#issuecomment-239507716, https://github.com/LLNL/spack/pull/1041#issuecomment-238363551

But, I get a failure when attempting to build glib on Mac OS X 10.11.6:

```
==> Building glib
==> Error: Command exited with status 2:
'make' '-j8'

See build log for details:
  /private/var/folders/vr/7lfgcgzd0wb4brywdhg86ygw00157w/T/lee1001/spack-stage/spack-stage-QAjlc9/glib-2.49.4/spack-build.out

/Users/lee1001/projs/llnl/spack/var/spack/repos/builtin/packages/glib/package.py:57, in install:
     55       def install(self, spec, prefix):
     56           configure("--prefix=%s" % prefix)
  >> 57           make()
     58           make("install", parallel=False)
==> Error: Installation process had nonzero exit code : 256
```

And the last bit of that log is:

```
2 warnings generated.
  CC       libglib_2_0_la-gerror.lo
  CC       libglib_2_0_la-gfileutils.lo
  CC       libglib_2_0_la-ggettext.lo
  CC       libglib_2_0_la-ghash.lo
1 warning generated.
  CC       libglib_2_0_la-ghmac.lo
  CC       libglib_2_0_la-ghook.lo
  CC       libglib_2_0_la-ghostutils.lo
  CC       libglib_2_0_la-giochannel.lo
  CC       libglib_2_0_la-gkeyfile.lo
  CC       libglib_2_0_la-glib-init.lo
  CC       libglib_2_0_la-glib-private.lo
  CC       libglib_2_0_la-glist.lo
  CC       libglib_2_0_la-gmain.lo
  CC       libglib_2_0_la-gmappedfile.lo
  CC       libglib_2_0_la-gmarkup.lo
  CC       libglib_2_0_la-gmem.lo
  CC       libglib_2_0_la-gmessages.lo
  CC       libglib_2_0_la-gnode.lo
  CC       libglib_2_0_la-goption.lo
  CC       libglib_2_0_la-gpattern.lo
  CC       libglib_2_0_la-gpoll.lo
gmessages.c:1446:53: error: format string is not a string literal [-Werror,-Wformat-nonliteral]
      size = _g_vsnprintf (buffer, sizeof (buffer), format, args);
                                                    ^~~~~~
/usr/include/secure/_stdio.h:75:63: note: expanded from macro 'vsnprintf'
  __builtin___vsnprintf_chk (str, len, 0, __darwin_obsz(str), format, ap)
                                                              ^
gmessages.c:1451:55: error: format string is not a string literal [-Werror,-Wformat-nonliteral]
      message = message_allocated = g_strdup_vprintf (format, args);
                                                      ^~~~~~
2 errors generated.
make[4]: *** [libglib_2_0_la-gmessages.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by healther** [comment] 2018-04-14 11:48
Closing as I cannot reproduce it on a current OSX and a reasonably current `spack`

**Comment by citibeth** [comment] 2018-07-11 14:53
@KineticTheory @michaelkuhn @adamjstewart @mathstuf @alalazo 
I'm having a different problem building `glib` on OS X.  I'm getting the error (see attached build log).  Maybe something wrong with various PTYHON env vars?

```
==> Installing glib
==> Using cached archive: /Users/rpfische/spack/giss/var/spack/cache/glib/glib-2.56.0.tar.xz
==> Staging archive: /Users/rpfische/spack/giss/var/spack/stage/glib-2.56.0-peylgw2ibbvhmw7pivonfbd2lw6u4mot/glib-2.56.0.tar.xz
==> Created stage in /Users/rpfische/spack/giss/var/spack/stage/glib-2.56.0-peylgw2ibbvhmw7pivonfbd2lw6u4mot
==> Applied patch no-Werror=format-security.patch
==> Building glib [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j4'

5 errors found in build log:
     1143    make[3]: Nothing to be done for `all-am'.
     1144    Making all in tests
     1145    /Library/Developer/CommandLineTools/usr/bin/make  all-recursive
     1146    Making all in gobject
     1147      GEN      stamp-testmarshal.h
     1148    ImportError: No module named site
  >> 1149    make[4]: *** [stamp-testmarshal.h] Error 1
  >> 1150    make[3]: *** [all-recursive] Error 1
  >> 1151    make[2]: *** [all] Error 2
  >> 1152    make[1]: *** [all-recursive] Error 1
  >> 1153    make: *** [all] Error 2

[spack-build.txt](https://github.com/spack/spack/files/2184980/spack-build.txt)
```

**Comment by sethrj** [comment] 2020-02-22 15:51
I just built glib with spack-provided python3.7. Is this still an issue?
```
-- darwin-mojave-x86_64 / clang@11.0.0-apple --------------------
shdhdbh glib@2.56.3~libmount patches=c325997b72a205ad1638bb3e3ba0e5b73e3d32ce63b2d0d3282f3e3a2ff4663c tracing=none
msyeqht     gettext@0.20.1+bzip2+curses+git~libunistring+libxml2+tar+xz
ysmjykg         bzip2@1.0.8+shared
w354vrb         libxml2@2.9.9~python
jg6ekuh             libiconv@1.16
b7n722h             xz@5.2.4
xj36ejk             zlib@1.2.11+optimize+pic+shared
zbgxvxi         ncurses@6.1~symlinks~termlib
2e6sifw         tar@1.32
7yg7qah     libffi@3.2.1
zg55iyu     pcre@8.43~jit+multibyte+utf
zqrlxlz     perl@5.30.0+cpanm+shared+threads
un7wzvl     python@3.7.4+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations patches=210df3f28cde02a8135b58cc4168e70ab91dbf9097359d05938f1e2843875e57 +pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib
l4gxq46         expat@2.2.9~libbsd
3t4dwsv         gdbm@1.18.1
h2bjtz2             readline@8.0
ugvknwc         openssl@1.1.1d+systemcerts
hsmq6ou         sqlite@3.30.1~column_metadata+fts~functions~rtree
```

**Closed** 2020-02-22 15:56 UTC
Labels: build-error
