### ISSUE TITLE
MPI wrapper compiler 

### ISSUE THREAD

**Issue by SheraLee** [spack/spack#12722] opened 2019-09-05 21:01 UTC
I am trying to create a spack package for p3dfft.3 [https://github.com/sdsc/p3dfft.3]. 
I start with trying on SDSC Comet with default Intel Compilers. 

The package depends on FFTW and MPI, in this particular platform, we use mvapich2. 

**My  python script:** 
`class P3dfft3(Package):
    homepage = "https://www.p3dfft.net"
    url      = "https://github.com/sdsc/p3dfft.3/archive/master.tar.gz"

    version('0.0.0', '458b788512fe1bc7009282201f476d7c')

       git = "https://github.com/sdsc/p3dfft.3"

    version('develop', branch = 'master')
    version('0.0.0', '734afcef3f2baf1a25b24963c66e13e9')

    variant('fftw', default = False ,
            description='Builds with FFTW library')
    variant('essl', default=False,
            description='Builds with ESSL library')
    variant('openmp', default=False,
            description="Enable OpenMP support.")

    depends_on('mpi')
    depends_on('fftw',when = '+fftw')
    depends_on('essl',when = '+essl')

    def setup_environment(self, spack_env, run_env):
        spec = self.spec

        spack_env.set('CC', spec['mpi'].mpicc)
        spack_env.set('FC', spec['mpi'].mpifc)
        spack_env.set('CXX', spec['mpi'].mpicxx)

    def install(self, spec, prefix):
        config_args = ['--prefix={0}'.format(prefix)]

        if '+fftw' in spec:
            config_args.append('--enable-fftw')
            config_args.append ('--with-fftw-lib= %s' % spec['fftw'].prefix.lib)
            config_args.append ('--with-fftw-inc= %s' % spec['fftw'].prefix.include)

        if '+essl' in spec:
            config_args.append('--enable-essl')
            config_args.append ('--with-fftw-lib= %s' % spec['essl'].prefix.lib)
            config_args.append ('--with-fftw-inc= %s' % spec['essl'].prefix.include)

        configure( *config_args)

        make()
        make('install')

**My compiler.yaml:** : I did not modify it. It is auto created

```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos6
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.4.7
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos6
    paths:
      cc: /opt/intel/composer_xe_2013_sp1.2.144/bin/intel64/icc
      cxx: /opt/intel/composer_xe_2013_sp1.2.144/bin/intel64/icpc
      f77: /opt/intel/composer_xe_2013_sp1.2.144/bin/intel64/ifort
      fc: /opt/intel/composer_xe_2013_sp1.2.144/bin/intel64/ifort
    spec: intel@14.0.2
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos6
    paths:
      cc: /opt/gnu/gcc/bin/gcc
      cxx: /opt/gnu/gcc/bin/g++
      f77: /opt/gnu/gcc/bin/gfortran
      fc: /opt/gnu/gcc/bin/gfortran
    spec: gcc@4.9.2
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos6
    paths:
      cc: /opt/pgi/linux86-64/17.5/bin/pgcc
      cxx: /opt/pgi/linux86-64/17.5/bin/pgc++
      f77: /opt/pgi/linux86-64/17.5/bin/pgfortran
      fc: /opt/pgi/linux86-64/17.5/bin/pgf95
    spec: pgi@17.5
    target: x86_64

```
**My package.yaml:**
```
 packages:
    fftw:
        modules:
             fftw@3.3.4: fftw/3.3.4
        buildable: False

    mvapich2: 
        modules:
              mvapich2@2.1: mvapich2_ib/2.1
        buildable: False

```
**spack-build-env.txt**
```
ANT_HOME=/opt/rocks; export ANT_HOME
function module() {  eval `/usr/bin/modulecmd bash $*`
}; export -f module
function spack() {  if [ -n "${ZSH_VERSION:-}" ]; then
 emulate -L sh;
 fi;
 _sp_flags="";
 while [ ! -z ${1+x} ] && [ "${1#-}" != "${1}" ]; do
 _sp_flags="$_sp_flags $1";
 shift;
 done;
 if [ -n "$_sp_flags" ] && [ "${_sp_flags#*h}" != "${_sp_flags}" ] || [ "${_sp_flags#*V}" != "${_sp_flags}" ]; then
 command spack $_sp_flags "$@";
 return;
 fi;
 _sp_subcommand="";
 if [ ! -z ${1+x} ]; then
 _sp_subcommand="$1";
 shift;
 fi;
 case $_sp_subcommand in 
 "cd")
 _sp_arg="";
 if [ -n "$1" ]; then
 _sp_arg="$1";
 shift;
 fi;
 if [ "$_sp_arg" = "-h" ] || [ "$_sp_arg" = "--help" ]; then
 command spack cd -h;
 else
 LOC="$(spack location $_sp_arg "$@")";
 if [ -d "$LOC" ]; then
 cd "$LOC";
 else
 return 1;
 fi;
 fi;
 return
 ;;
 "env")
 _sp_arg="";
 if [ -n "$1" ]; then
 _sp_arg="$1";
 shift;
 fi;
 if [ "$_sp_arg" = "-h" ] || [ "$_sp_arg" = "--help" ]; then
 command spack env -h;
 else
 case $_sp_arg in 
 activate)
 _a="$@";
 if [ -z ${1+x} ] || [ "${_a#*--sh}" != "$_a" ] || [ "${_a#*--csh}" != "$_a" ] || [ "${_a#*-h}" != "$_a" ]; then
 command spack env activate "$@";
 else
 eval $(command spack $_sp_flags env activate --sh "$@");
 fi
 ;;
 deactivate)
 _a="$@";
 if [ "${_a#*--sh}" != "$_a" ] || [ "${_a#*--csh}" != "$_a" ]; then
 command spack env deactivate "$@";
 else
 if [ -n "$*" ]; then
 command spack env deactivate -h;
 else
 eval $(command spack $_sp_flags env deactivate --sh);
 fi;
 fi
 ;;
 *)
 command spack env $_sp_arg "$@"
 ;;
 esac;
 fi;
 return
 ;;
 "use" | "unuse" | "load" | "unload")
 _sp_subcommand_args="";
 _sp_module_args="";
 while [ "${1#-}" != "${1}" ]; do
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
 command spack $_sp_flags $_sp_subcommand $_sp_subcommand_args "$@";
 return;
 else
 if [ "$1" = "-r" ] || [ "$1" = "--dependencies" ]; then
 _sp_subcommand_args="$_sp_subcommand_args $1";
 else
 _sp_module_args="$_sp_module_args $1";
 fi;
 fi;
 shift;
 done;
 case $_sp_subcommand in 
 "use")
 if _sp_full_spec=$(command spack $_sp_flags module dotkit find $_sp_subcommand_args "$@"); then
 use $_sp_module_args $_sp_full_spec;
 else
 $(exit 1);
 fi
 ;;
 "unuse")
 if _sp_full_spec=$(command spack $_sp_flags module dotkit find $_sp_subcommand_args "$@"); then
 unuse $_sp_module_args $_sp_full_spec;
 else
 $(exit 1);
 fi
 ;;
 "load")
 if _sp_full_spec=$(command spack $_sp_flags module tcl find $_sp_subcommand_args "$@"); then
 module load $_sp_module_args $_sp_full_spec;
 else
 $(exit 1);
 fi
 ;;
 "unload")
 if _sp_full_spec=$(command spack $_sp_flags module tcl find $_sp_subcommand_args "$@"); then
 module unload $_sp_module_args $_sp_full_spec;
 else
 $(exit 1);
 fi
 ;;
 esac
 ;;
 *)
 command spack $_sp_flags $_sp_subcommand "$@"
 ;;
 esac
}; export -f spack
CC=/opt/mvapich2/intel/ib/bin/mpicc; export CC
CMAKE_PREFIX_PATH=/opt/fftw/3.3.4/intel/mvapich2_ib:/opt/mvapich2/intel/ib; export CMAKE_PREFIX_PATH
CVS_RSH=ssh; export CVS_RSH
CXX=/opt/mvapich2/intel/ib/bin/mpicxx; export CXX
DK_NODE=/home/shera/spack/spack/share/spack/dotkit/linux-centos6-x86_64; export DK_NODE
F77=/home/shera/spack/spack/lib/spack/env/intel/ifort; export F77
FC=/opt/mvapich2/intel/ib/bin/mpif90; export FC
FFTWHOME=/opt/fftw/3.3.4/intel/mvapich2_ib; export FFTWHOME
FPATH=/opt/intel/composer_xe_2013_sp1.2.144/mkl/include; export FPATH
GDBSERVER_MIC=/opt/intel/composer_xe_2013_sp1.2.144/debugger/gdb/target/mic/bin/gdbserver; export GDBSERVER_MIC
GDB_CROSS=/opt/intel/composer_xe_2013_sp1.2.144/debugger/gdb/intel64_mic/bin/gdb-mic; export GDB_CROSS
GNUTOOLSHOME=/opt/gnu; export GNUTOOLSHOME
G_BROKEN_FILENAMES=1; export G_BROKEN_FILENAMES
HISTCONTROL=ignoredups; export HISTCONTROL
HISTSIZE=1000; export HISTSIZE
HOME=/home/shera; export HOME
HOSTNAME=comet-ln2.sdsc.edu; export HOSTNAME
INCLUDE=/opt/intel/composer_xe_2013_sp1.2.144/mkl/include; export INCLUDE
INFOPATH=/opt/intel/composer_xe_2013_sp1.2.144/debugger/gdb/intel64/share/info/:/opt/intel/composer_xe_2013_sp1.2.144/debugger/gdb/intel64_mic/share/info/; export INFOPATH
INTELHOME=/opt/intel/composer_xe_2013_sp1.2.144; export INTELHOME
INTEL_LICENSE_FILE=/opt/intel/composer_xe_2013_sp1.2.144/licenses:/opt/intel/licenses:/root/intel/licenses; export INTEL_LICENSE_FILE
INTEL_PYTHONHOME=/opt/intel/composer_xe_2013_sp1.2.144/debugger/python/intel64/; export INTEL_PYTHONHOME
IPPROOT=/opt/intel/composer_xe_2013_sp1.2.144/ipp; export IPPROOT
JAVA_HOME=/usr/java/latest; export JAVA_HOME
KRB5CCNAME=FILE:/tmp/krb5cc_524149_Rai27h; export KRB5CCNAME
LANG=en_US.UTF-8; export LANG
LC_ALL=C; export LC_ALL
LD_LIBRARY_PATH=/opt/mvapich2/intel/ib/lib:/opt/fftw/3.3.4/intel/mvapich2_ib/lib; export LD_LIBRARY_PATH
LESSOPEN='||/usr/bin/lesspipe.sh %s'; export LESSOPEN
LIBPATH=/opt/fftw/3.3.4/intel/mvapich2_ib/lib; export LIBPATH
LM_LICENSE_FILE=/opt/flexlm/license/license.dat; export LM_LICENSE_FILE
LOADEDMODULES=intel/2013_sp1.2.144:mvapich2_ib/2.1:gnutools/2.69:fftw/3.3.4; export LOADEDMODULES
LOGNAME=shera; export LOGNAME
LS_COLORS='rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lz=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.bz=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.rar=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:'; export LS_COLORS
MAIL=/var/spool/mail/shera; export MAIL
MANPATH=/opt/intel/composer_xe_2013_sp1.2.144/man/en_US:/opt/intel/composer_xe_2013_sp1.2.144/man/en_US:/opt/intel/composer_xe_2013_sp1.2.144/debugger/gdb/intel64/share/man/:/opt/intel/composer_xe_2013_sp1.2.144/debugger/gdb/intel64_mic/share/man/:/usr/share/man; export MANPATH
MIC_LD_LIBRARY_PATH=/opt/intel/composer_xe_2013_sp1.2.144/compiler/lib/mic:/opt/intel/composer_xe_2013_sp1.2.144/mpirt/lib/mic:/opt/intel/composer_xe_2013_sp1.2.144/compiler/lib/mic:/opt/intel/composer_xe_2013_sp1.2.144/mkl/lib/mic:/opt/intel/composer_xe_2013_sp1.2.144/tbb/lib/mic; export MIC_LD_LIBRARY_PATH
MIC_LIBRARY_PATH=/opt/intel/composer_xe_2013_sp1.2.144/compiler/lib/mic:/opt/intel/composer_xe_2013_sp1.2.144/mpirt/lib/mic:/opt/intel/composer_xe_2013_sp1.2.144/tbb/lib/mic; export MIC_LIBRARY_PATH
MKLROOT=/opt/intel/composer_xe_2013_sp1.2.144/mkl; export MKLROOT
MKL_ROOT=/opt/intel/composer_xe_2013_sp1.2.144/mkl; export MKL_ROOT
MODULEPATH=/home/shera/spack/spack/share/spack/modules/linux-centos6-x86_64:/opt/modulefiles/mpi/.intel:/opt/modulefiles/applications/.intel:/opt/modulefiles/mpi:/opt/modulefiles/compilers:/opt/modulefiles/applications:/usr/share/Modules/modulefiles:/etc/modulefiles; export MODULEPATH
MODULESHOME=/usr/share/Modules; export MODULESHOME
MPICC=/opt/mvapich2/intel/ib/bin/mpicc; export MPICC
MPICH_CC=/home/shera/spack/spack/lib/spack/env/intel/icc; export MPICH_CC
MPICH_CXX=/home/shera/spack/spack/lib/spack/env/intel/icpc; export MPICH_CXX
MPICH_F77=/home/shera/spack/spack/lib/spack/env/intel/ifort; export MPICH_F77
MPICH_F90=/home/shera/spack/spack/lib/spack/env/intel/ifort; export MPICH_F90
MPICH_FC=/home/shera/spack/spack/lib/spack/env/intel/ifort; export MPICH_FC
MPICXX=/opt/mvapich2/intel/ib/bin/mpicxx; export MPICXX
MPIF77=/opt/mvapich2/intel/ib/bin/mpif77; export MPIF77
MPIF90=/opt/mvapich2/intel/ib/bin/mpif90; export MPIF90
MPIHOME=/opt/mvapich2/intel/ib; export MPIHOME
MPM_LAUNCHER=/opt/intel/composer_xe_2013_sp1.2.144/debugger/mpm/bin/start_mpm.sh; export MPM_LAUNCHER
MV2_ALLTOALL_TUNING=2; export MV2_ALLTOALL_TUNING
NLSPATH=/opt/intel/composer_xe_2013_sp1.2.144/compiler/lib/intel64/locale/%l_%t/%N:/opt/intel/composer_xe_2013_sp1.2.144/ipp/lib/intel64/locale/%l_%t/%N:/opt/intel/composer_xe_2013_sp1.2.144/mkl/lib/intel64/locale/%l_%t/%N:/opt/intel/composer_xe_2013_sp1.2.144/debugger/gdb/intel64_mic/share/locale/%l_%t/%N:/opt/intel/composer_xe_2013_sp1.2.144/debugger/gdb/intel64/share/locale/%l_%t/%N; export NLSPATH
PATH=/home/shera/spack/spack/lib/spack/env/intel:/home/shera/spack/spack/lib/spack/env/case-insensitive:/home/shera/spack/spack/lib/spack/env:/opt/mvapich2/intel/ib/bin:/opt/fftw/3.3.4/intel/mvapich2_ib/bin:/opt/mvapich2/intel/ib/bin:/opt/fftw/3.3.4/intel/mvapich2_ib/bin:/opt/fftw/3.3.4/intel/mvapich2_ib/bin:/home/shera/spack/spack/bin:/opt/gnu/gcc/bin:/opt/gnu/bin:/opt/mvapich2/intel/ib/bin:/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64:/opt/intel/composer_xe_2013_sp1.2.144/mpirt/bin/intel64:/opt/intel/composer_xe_2013_sp1.2.144/debugger/gdb/intel64_mic/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/usr/java/latest/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/shera/bin; export PATH
PDSHROOT=/opt/pdsh; export PDSHROOT
PKG_CONFIG_PATH=/opt/mvapich2/intel/ib/lib/pkgconfig:/opt/fftw/3.3.4/intel/mvapich2_ib/lib/pkgconfig; export PKG_CONFIG_PATH
#PWD=/home/shera; export PWD
PYTHONPATH=/opt/sdsc/lib; export PYTHONPATH
QTDIR=/usr/lib64/qt-3.3; export QTDIR
QTINC=/usr/lib64/qt-3.3/include; export QTINC
QTLIB=/usr/lib64/qt-3.3/lib; export QTLIB
ROCKSROOT=/opt/rocks/share/devel; export ROCKSROOT
ROCKS_ROOT=/opt/rocks; export ROCKS_ROOT
ROLLSROOT=/opt/rocks/share/devel/src/roll; export ROLLSROOT
SDSCDEVEL=/opt/sdsc/devel; export SDSCDEVEL
SDSCHOME=/opt/sdsc; export SDSCHOME
SHELL=/bin/bash; export SHELL
SHLVL=3; export SHLVL
SPACK_CC=/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64/icc; export SPACK_CC
SPACK_CC_RPATH_ARG=-Wl,-rpath,; export SPACK_CC_RPATH_ARG
SPACK_COMPILER_SPEC=intel@14.0.2; export SPACK_COMPILER_SPEC
SPACK_CXX=/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64/icpc; export SPACK_CXX
SPACK_CXX_RPATH_ARG=-Wl,-rpath,; export SPACK_CXX_RPATH_ARG
SPACK_DEBUG_LOG_DIR=/home/shera; export SPACK_DEBUG_LOG_DIR
SPACK_DEBUG_LOG_ID=p3dfft-3-v6h2bqu; export SPACK_DEBUG_LOG_ID
SPACK_ENV_PATH=/home/shera/spack/spack/lib/spack/env:/home/shera/spack/spack/lib/spack/env/case-insensitive:/home/shera/spack/spack/lib/spack/env/intel; export SPACK_ENV_PATH
SPACK_F77=/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64/ifort; export SPACK_F77
SPACK_F77_RPATH_ARG=-Wl,-rpath,; export SPACK_F77_RPATH_ARG
SPACK_FC=/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64/ifort; export SPACK_FC
SPACK_FC_RPATH_ARG=-Wl,-rpath,; export SPACK_FC_RPATH_ARG
SPACK_INCLUDE_DIRS=/opt/fftw/3.3.4/intel/mvapich2_ib/include:/opt/mvapich2/intel/ib/include; export SPACK_INCLUDE_DIRS
SPACK_LINK_DIRS=/opt/fftw/3.3.4/intel/mvapich2_ib/lib:/opt/mvapich2/intel/ib/lib; export SPACK_LINK_DIRS
SPACK_ROOT=/home/shera/spack/spack; export SPACK_ROOT
SPACK_RPATH_DIRS=/home/shera/spack/spack/opt/spack/linux-centos6-x86_64/intel-14.0.2/p3dfft-3-0.0.0-v6h2bqutm7rmpcjnp272grcmhrtms3hr/lib:/home/shera/spack/spack/opt/spack/linux-centos6-x86_64/intel-14.0.2/p3dfft-3-0.0.0-v6h2bqutm7rmpcjnp272grcmhrtms3hr/lib64:/opt/fftw/3.3.4/intel/mvapich2_ib/lib:/opt/mvapich2/intel/ib/lib; export SPACK_RPATH_DIRS
SPACK_SHORT_SPEC='p3dfft-3@0.0.0%intel@14.0.2~essl+fftw~openmp arch=linux-centos6-x86_64/v6h2bqu'; export SPACK_SHORT_SPEC
SPACK_SYSTEM_DIRS=/bin:/usr/bin:/usr/local/bin:/bin64:/usr/bin64:/usr/local/bin64:/include:/usr/include:/usr/local/include:/lib:/usr/lib:/usr/local/lib:/lib64:/usr/lib64:/usr/local/lib64:/:/usr:/usr/local; export SPACK_SYSTEM_DIRS
SSH_CLIENT='37.120.132.126 58108 22'; export SSH_CLIENT
SSH_CONNECTION='37.120.132.126 58108 198.202.113.253 22'; export SSH_CONNECTION
SSH_TTY=/dev/pts/120; export SSH_TTY
TBBROOT=/opt/intel/composer_xe_2013_sp1.2.144/tbb; export TBBROOT
TERM=xterm-256color; export TERM
USER=shera; export USER
_=/usr/bin/python; export _
_LMFILES_=/opt/modulefiles/compilers/intel/2013_sp1.2.144:/opt/modulefiles/mpi/.intel/mvapich2_ib/2.1:/opt/modulefiles/applications/gnutools/2.69:/opt/modulefiles/applications/.intel/fftw/3.3.4; export _LMFILES_
```

**Steps to reproduce the issue**
When call spack install, I encounter this error: 
```
[shera@comet-ln2 ~]$ spack  install p3dfft-3%intel +fftw
==> fftw@3.3.4 : has external module in fftw/3.3.4
==> fftw@3.3.4 : is actually installed in /opt/fftw/3.3.4/intel/mvapich2_ib
==> fftw@3.3.4 : already registered in DB
==> mvapich2@2.1 : has external module in mvapich2_ib/2.1
==> mvapich2@2.1 : is actually installed in /opt/mvapich2/intel/ib
==> mvapich2@2.1 : already registered in DB
==> Installing p3dfft-3
==> Searching for binary cache of p3dfft-3
==> Warning: No Spack mirrors are currently configured
==> No binary for p3dfft-3 found: installing from source
==> Warning: Suspicious requests to set or unset 'CC' found
==> Warning: 	    	env.set('CC', os.path.join(link_dir, compiler.link_paths['cc'])) at /home/shera/spack/spack/lib/spack/spack/build_environment.py:185
==> Warning: 	--->	spack_env.set('FC', spec['mpi'].mpifc) at /home/shera/spack/spack/var/spack/repos/tutorial/packages/p3dfft-3/package.py:54
==> Warning: Suspicious requests to set or unset 'CXX' found
==> Warning: 	    	env.set('CXX', os.path.join(link_dir, compiler.link_paths['cxx'])) at /home/shera/spack/spack/lib/spack/spack/build_environment.py:188
==> Warning: 	--->	 at /home/shera/spack/spack/var/spack/repos/tutorial/packages/p3dfft-3/package.py:56
==> Warning: Suspicious requests to set or unset 'FC' found
==> Warning: 	    	env.set('FC', os.path.join(link_dir, compiler.link_paths['fc'])) at /home/shera/spack/spack/lib/spack/spack/build_environment.py:194
==> Warning: 	--->	spack_env.set('CXX', spec['mpi'].mpicxx) at /home/shera/spack/spack/var/spack/repos/tutorial/packages/p3dfft-3/package.py:55
==> Using cached archive: /home/shera/spack/spack/var/spack/cache/p3dfft-3/p3dfft-3-0.0.0.tar.gz
==> Staging archive: /home/shera/spack/spack/var/spack/stage/p3dfft-3-0.0.0-v6h2bqutm7rmpcjnp272grcmhrtms3hr/master.tar.gz
==> Created stage in /home/shera/spack/spack/var/spack/stage/p3dfft-3-0.0.0-v6h2bqutm7rmpcjnp272grcmhrtms3hr
==> No patches needed for p3dfft-3
==> Building p3dfft-3 [Package]
==> Executing phase: 'install'
==> Error: ProcessError: Command exited with status 77:
    './configure' '--prefix=/home/shera/spack/spack/opt/spack/linux-centos6-x86_64/intel-14.0.2/p3dfft-3-0.0.0-v6h2bqutm7rmpcjnp272grcmhrtms3hr' '--enable-fftw' '--with-fftw-lib= /opt/fftw/3.3.4/intel/mvapich2_ib/lib' '--with-fftw-inc= /opt/fftw/3.3.4/intel/mvapich2_ib/include'

2 errors found in build log:
     18    checking whether to use ESSL library... no
     19    checking whether to use MKL library... no
     20    checking fftw lib location...  /opt/fftw/3.3.4/intel/mvapich2_ib/lib
     21    checking fftw inc location...  /opt/fftw/3.3.4/intel/mvapich2_ib/inc
           lude
     22    checking for gcc... /opt/mvapich2/intel/ib/bin/mpicc
     23    checking whether the C compiler works... no
  >> 24    configure: error: in `/tmp/shera/spack-stage/spack-stage-HmWLVU/spac
           k-src':
  >> 25    configure: error: C compiler cannot create executables
     26    See `config.log' for more details

See build log for details:
  /home/shera/spack/spack/var/spack/stage/p3dfft-3-0.0.0-v6h2bqutm7rmpcjnp272grcmhrtms3hr/spack-build-out.txt
```

However, I can build the package successfuly in the spack debug environment, after call
`'./configure --prefix=/home/shera/installed --enable-intel --enable-fftw CC=mpicc CXX=mpicxx FC=mpif90'.
`
My best guess is that the error is caused by CC=mpicc CXX=mpicxx FC=mpif90, because if I removed these 3 arguments, I will not get the C compiler cannot create executables error, but spack will not find mpicc(./configure --prefix=/home/shera/installed --enable-intel --enable-fftw  works when not using spack, CC and CXX has been automatically set correctly).

I am pretty new to HPC and spack, so there is could be some silly mistakes. Hope I can get some helps. Thank you!

**Comment by alalazo** [comment] 2019-10-08 20:20
Duplicate of #12864

**Comment by alalazo** [comment] 2019-10-08 20:21
Closing as it seems a duplicate of another issue. Feel free to reopen if I am wrong on that.

**Closed by alalazo** 2019-10-08 20:21 UTC
