### ISSUE TITLE
Intel compilers are broken

### ISSUE THREAD

**Issue by ssergien** [spack/spack#5542] opened 2017-09-29 02:36 UTC
I pulled the develop branch today and noticed that my intel compilers got broken.
```
$ icc -v
icc version 17.0.4 (gcc version 4.4.7 compatibility)
ld    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.4.7/crtbegin.o --eh-frame-hdr --build-id -dynamic-linker /lib64/ld-linux-x86-64.so.2 -m elf_x86_64 -o a.out -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/lib/intel64 -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/tbb/lib/intel64/gcc4.4 -L/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.13-uwrwojsic25qib2jggkjdp4mekuf6nc4/lib -L/soft/lcrc/lib -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/ -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/ -L/lib/../lib64 -L/lib/../lib64/ -L/usr/lib/../lib64 -L/usr/lib/../lib64/ -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/lib/intel64/ -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/tbb/lib/intel64/gcc4.4/ -L/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.13-uwrwojsic25qib2jggkjdp4mekuf6nc4/lib/ -L/soft/lcrc/lib/ -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../ -L/lib64 -L/lib/ -L/usr/lib64 -L/usr/lib -rpath /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin -Bdynamic -Bstatic -limf -lsvml -lirng -Bdynamic -lm -Bstatic -lipgo -ldecimal --as-needed -Bdynamic -lcilkrts -lstdc++ --no-as-needed -lgcc -lgcc_s -Bstatic -lirc -lsvml -Bdynamic -lc -lgcc -lgcc_s -Bstatic -lirc_s -Bdynamic -ldl -lc /usr/lib/gcc/x86_64-redhat-linux/4.4.7/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crtn.o
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
```
The fix was to rename `icc.cfg`, `icpc.cfg`, `ifort.cfg`. 

After that it seems like it behaves correctly:
```
$ icc -v
icc version 17.0.4 (gcc version 4.8.5 compatibility)
```
Here is what I did
```
[ssergien@blogin1 intel64]$ mv icc.cfg icc.bak
[ssergien@blogin1 intel64]$ mv icpc.cfg icpc.bak
[ssergien@blogin1 intel64]$ mv ifort.cfg ifort.bak
[ssergien@blogin1 intel64]$ icc -v
icc version 17.0.4 (gcc version 4.4.7 compatibility)
[ssergien@blogin1 intel64]$ icpc -v
icpc version 17.0.4 (gcc version 4.4.7 compatibility)
[ssergien@blogin1 intel64]$ ifort -v
ifort version 17.0.4
[ssergien@blogin1 intel64]$ mv icc.bak icc.cfg
[ssergien@blogin1 intel64]$ mv icpc.bak icpc.cfg
[ssergien@blogin1 intel64]$ mv ifort.bak ifort.cfg
[ssergien@blogin1 intel64]$ icc -v
icc version 17.0.4 (gcc version 4.4.7 compatibility)
ld    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.4.7/crtbegin.o --eh-frame-hdr --build-id -dynamic-linker /lib64/ld-linux-x86-64.so.2 -m elf_x86_64 -o a.out -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/lib/intel64 -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/tbb/lib/intel64/gcc4.4 -L/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.13-uwrwojsic25qib2jggkjdp4mekuf6nc4/lib -L/soft/lcrc/lib -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/ -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/ -L/lib/../lib64 -L/lib/../lib64/ -L/usr/lib/../lib64 -L/usr/lib/../lib64/ -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/lib/intel64/ -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/tbb/lib/intel64/gcc4.4/ -L/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.13-uwrwojsic25qib2jggkjdp4mekuf6nc4/lib/ -L/soft/lcrc/lib/ -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../ -L/lib64 -L/lib/ -L/usr/lib64 -L/usr/lib -rpath /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin -Bdynamic -Bstatic -limf -lsvml -lirng -Bdynamic -lm -Bstatic -lipgo -ldecimal --as-needed -Bdynamic -lcilkrts -lstdc++ --no-as-needed -lgcc -lgcc_s -Bstatic -lirc -lsvml -Bdynamic -lc -lgcc -lgcc_s -Bstatic -lirc_s -Bdynamic -ldl -lc /usr/lib/gcc/x86_64-redhat-linux/4.4.7/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crtn.o
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
[ssergien@blogin1 intel64]$ icpc -v
icpc version 17.0.4 (gcc version 4.4.7 compatibility)
ld    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.4.7/crtbegin.o --eh-frame-hdr --build-id -dynamic-linker /lib64/ld-linux-x86-64.so.2 -m elf_x86_64 -o a.out -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/lib/intel64 -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/tbb/lib/intel64/gcc4.4 -L/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.13-uwrwojsic25qib2jggkjdp4mekuf6nc4/lib -L/soft/lcrc/lib -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/ -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/ -L/lib/../lib64 -L/lib/../lib64/ -L/usr/lib/../lib64 -L/usr/lib/../lib64/ -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/lib/intel64/ -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/tbb/lib/intel64/gcc4.4/ -L/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.13-uwrwojsic25qib2jggkjdp4mekuf6nc4/lib/ -L/soft/lcrc/lib/ -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../ -L/lib64 -L/lib/ -L/usr/lib64 -L/usr/lib -rpath /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin -Bdynamic -Bstatic -limf -lsvml -lirng -Bdynamic -lstdc++ -lm -Bstatic -lipgo -ldecimal --as-needed -Bdynamic -lcilkrts --no-as-needed -lstdc++ -lgcc -lgcc_s -Bstatic -lirc -lsvml -Bdynamic -lc -lgcc -lgcc_s -Bstatic -lirc_s -Bdynamic -ldl -lc /usr/lib/gcc/x86_64-redhat-linux/4.4.7/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crtn.o
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
[ssergien@blogin1 intel64]$ ifort -v
ifort version 17.0.4
ld    /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.4.7/crtbegin.o --eh-frame-hdr --build-id -dynamic-linker /lib64/ld-linux-x86-64.so.2 -m elf_x86_64 -o a.out /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin/for_main.o -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/lib/intel64 -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/tbb/lib/intel64/gcc4.4 -L/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.13-uwrwojsic25qib2jggkjdp4mekuf6nc4/lib -L/soft/lcrc/lib -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/ -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/ -L/lib/../lib64 -L/lib/../lib64/ -L/usr/lib/../lib64 -L/usr/lib/../lib64/ -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/lib/intel64/ -L/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/tbb/lib/intel64/gcc4.4/ -L/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.13-uwrwojsic25qib2jggkjdp4mekuf6nc4/lib/ -L/soft/lcrc/lib/ -L/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../ -L/lib64 -L/lib/ -L/usr/lib64 -L/usr/lib -rpath /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin -Bdynamic -Bstatic -lifport -lifcoremt -limf -lsvml -Bdynamic -lm -Bstatic -lipgo -lirc -Bdynamic -lpthread -Bstatic -lsvml -Bdynamic -lc -lgcc -lgcc_s -Bstatic -lirc_s -Bdynamic -ldl -lc /usr/lib/gcc/x86_64-redhat-linux/4.4.7/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crtn.o
/blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-17.0.4-5llkj4fktdqhrjvnu263hm3hq32m5daw/compilers_and_libraries_2017.4.193/linux/compiler/lib/intel64_lin/for_main.o: In function `main':
for_main.c:(.text+0x2a): undefined reference to `MAIN__'
```
Any one else had this issue?

Thanks

**Comment by alalazo** [comment] 2017-09-29 16:53
We have the same problem at my site. Imho it's a bug - not the most relevant, but still a bug - with the Intel compiler. The configuration files like `icc.cfg` are setting flags and options that are prepended by default to the compiler. If there are options that are passed to the linker, then the linker is executed regardless of the fact that `-v` is the last option and no file name has been given.

You can actually reproduce the behavior starting from the version working "correctly":
```console
$ icc -v
icc version 17.0.2 (gcc version 4.8.5 compatibility)

$ icc -Xlinker -rpath=/ssoft/spack/external/intel/2017/compilers_and_libraries_2017.2.174/linux/ipp/lib/intel64  -v
icc version 17.0.2 (gcc version 4.8.5 compatibility)
ld    /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbegin.o --eh-frame-hdr --build-id -dynamic-linker /lib64/ld-linux-x86-64.so.2 -m elf_x86_64 -o a.out -L/ssoft/spack/external/intel/2017/compilers_and_libraries_2017/linux/tbb/lib/intel64/gcc4.4 -L/ssoft/spack/external/intel/2017/compilers_and_libraries_2017/linux/lib/intel64 -L/ssoft/spack/external/intel/2017/compilers_and_libraries_2017.2.174/linux/bin/lib_lin -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/ -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/ -L/lib/../lib64 -L/lib/../lib64/ -L/usr/lib/../lib64 -L/usr/lib/../lib64/ -L/ssoft/spack/external/intel/2017/compilers_and_libraries_2017/linux/tbb/lib/intel64/gcc4.4/ -L/ssoft/spack/external/intel/2017/compilers_and_libraries_2017/linux/lib/intel64/ -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../ -L/lib64 -L/lib/ -L/usr/lib64 -L/usr/lib -rpath=/ssoft/spack/external/intel/2017/compilers_and_libraries_2017.2.174/linux/ipp/lib/intel64 -Bdynamic -Bstatic -limf -lsvml -lirng -Bdynamic -lm -Bstatic -lipgo -ldecimal --as-needed -Bdynamic -lcilkrts -lstdc++ --no-as-needed -lgcc -lgcc_s -Bstatic -lirc -lsvml -Bdynamic -lc -lgcc -lgcc_s -Bstatic -lirc_s -Bdynamic -ldl -lc /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
```

**Comment by alalazo** [comment] 2017-09-29 16:54
Note that the compilers are not broken, and they still work correctly.

**Comment by lee218llnl** [comment] 2017-09-29 17:06
I will submit a bug report to Intel. We have the same issue at LLNL.

**Comment by alalazo** [comment] 2017-11-23 20:00
Closing this, as it is an Intel bug. I am curious though if @lee218llnl got any reply from the Intel support.

**Closed by alalazo** 2017-11-23 20:00 UTC
Labels: question

**Comment by lee218llnl** [comment] 2017-11-27 16:47
I haven't heard from Intel other than that they were considering it. A "fix" is not in the 18.0.1 compiler, though. I pinged Intel for an update.

**Comment by lee218llnl** [comment] 2017-12-11 19:50
The latest update from Intel is that they have a gcc compatible option "-print-prog-name=nul", which will avoid calling the linker and thus not print the "undefined reference to 'main'" error and will return 0. I pushed back on them, however, as this still prints "nul" or whatever name you provide to that option.

**Comment by alalazo** [comment] 2017-12-12 07:17
@lee218llnl  

> I pushed back on them, however, as this still prints "nul" or whatever name you provide to that option.

I completely agree. It doesn't seem at all sensible to add that option in a config file that is always used, given that:

> -print-file-name=library
           Print the full absolute name of the library file library that would be used when linking---**and don't do anything else.  With this option, GCC does not compile or link anything; it just prints
           the file name.**
> ...
> -print-prog-name=program
           Like -print-file-name, but searches for a program such as cpp.

**Comment by tstilwel** [comment] 2019-07-16 20:47
@lee218llnl @alalazo 

Just curious if you received more feedback or have any updates.  I'm experiencing the same problem with version 19.

Thanks,
Terry

**Comment by lee218llnl** [comment] 2019-07-16 21:26
I just pinged Intel. I still have an open request with them.

**Comment by robert-mijakovic** [comment] 2020-05-06 10:52
Hi @lee218llnl,

did you get any response from Intel as we experience the same issue?

I have contacted Intel and got the following response:

=======================================================================
Dear Robert,

I have additional discussion with the development team and the issue you reported is not a bug.

Use of -Xlinker tells the compiler driver that the linker has to be invoked - even if no files are provided on the command line. Reason being is that -Xlinker (or -Wl,*) are options that pass along options to the linker and are basically not 'seen' by the driver. This means the driver does not know the contents and there is always the possibility that the user can pass along objects that require linking.

This behavior is expected as use of ifort.cfg is just like using the command line.

Use of -L<dir> is fine as it is an option that is parsed and known by the driver.

Please let me know if you have any additional questions.

=======================================================================

In your opinion, is that something we should fix in Spack or push Intel further to fix it.

Best regards,
Robert

**Comment by robert-mijakovic** [comment] 2020-05-10 14:53
@alalazo Any comment from your side?

**Comment by alalazo** [comment] 2020-05-11 08:22
@robert-mijakovic This is a very old issue, so I need to check if there are further workarounds or ways to solve it. My inclination would be to say that this is still something Intel needs to address either in docs (saying that having linker options in `cfg` files may interfere with other options of `icc` - thus limiting the usefulness of `cfg` files) or in their compilers. 

Also, I find  `icc -help` confusing in this respect. Consider:
```
[ ... ]
-dryrun   show driver tool commands but do not execute tools
-v        show driver tool commands and execute tools
[ ... ]
```
and this output with no configuration files:
```console
$ icc -v
icc version 18.0.5 (gcc version 4.8.5 compatibility)

$ icc -dryrun
icc: command line error: no files specified; for help type "icc -help"
rm /tmp/iccdummy297WOi.c
rm /tmp/iccdashvh7yKlw
```
As you see it's really not the same behavior as it seems to be advertized in the help. With a configuration file that forwards linker options to set RPATHs you get:
```console
$ cat $ICCCFG 
-gcc-name=/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.8.5/gcc-6.5.0-zh4rtcgdquhyaobmlogojyf7incbzjkf/bin/gcc #
-isystem/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/compiler/include/intel64 #
-isystem/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/compiler/include #
-Xlinker -L/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/ipp/lib/intel64 #
-Xlinker -rpath=/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/ipp/lib/intel64 #
-Xlinker -L/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/tbb/lib/intel64/gcc4.7 #
-Xlinker -rpath=/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/tbb/lib/intel64/gcc4.7 #
-Xlinker -L/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64 #
-Xlinker -rpath=/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64 #
-Xlinker -L/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/compiler/lib/intel64 #
-Xlinker -rpath=/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/compiler/lib/intel64 #
-Xlinker -rpath=/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.8.5/gcc-6.5.0-zh4rtcgdquhyaobmlogojyf7incbzjkf/lib64
$ icc -v
icc version 18.0.5 (gcc version 6.5.0 compatibility)
ld    /lib/../lib64/crt1.o /lib/../lib64/crti.o /ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.8.5/gcc-6.5.0-zh4rtcgdquhyaobmlogojyf7incbzjkf/lib/gcc/x86_64-pc-linux-gnu/6.5.0/crtbegin.o --eh-frame-hdr --build-id -dynamic-linker /lib64/ld-linux-x86-64.so.2 -m elf_x86_64 -o a.out -L/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/compiler/lib/intel64_lin -L/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.8.5/gcc-6.5.0-zh4rtcgdquhyaobmlogojyf7incbzjkf/lib/gcc/x86_64-pc-linux-gnu/6.5.0/ -L/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.8.5/gcc-6.5.0-zh4rtcgdquhyaobmlogojyf7incbzjkf/lib/gcc/x86_64-pc-linux-gnu/6.5.0/../../../../lib64 -L/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.8.5/gcc-6.5.0-zh4rtcgdquhyaobmlogojyf7incbzjkf/lib/gcc/x86_64-pc-linux-gnu/6.5.0/../../../../lib64/ -L/lib/../lib64 -L/lib/../lib64/ -L/usr/lib/../lib64 -L/usr/lib/../lib64/ -L/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.8.5/gcc-6.5.0-zh4rtcgdquhyaobmlogojyf7incbzjkf/lib/gcc/x86_64-pc-linux-gnu/6.5.0/../../../ -L/lib64 -L/lib/ -L/usr/lib64 -L/usr/lib -L/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/ipp/lib/intel64 -rpath=/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/ipp/lib/intel64 -L/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/tbb/lib/intel64/gcc4.7 -rpath=/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/tbb/lib/intel64/gcc4.7 -L/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64 -rpath=/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64 -L/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/compiler/lib/intel64 -rpath=/ssoft/spack/external/intel/2018.4/compilers_and_libraries_2018.5.274/linux/compiler/lib/intel64 -rpath=/ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.8.5/gcc-6.5.0-zh4rtcgdquhyaobmlogojyf7incbzjkf/lib64 -Bdynamic -Bstatic -limf -lsvml -lirng -Bdynamic -lm -Bstatic -lipgo -ldecimal --as-needed -Bdynamic -lcilkrts -lstdc++ --no-as-needed -lgcc -lgcc_s -Bstatic -lirc -lsvml -Bdynamic -lc -lgcc -lgcc_s -Bstatic -lirc_s -Bdynamic -ldl -lc /ssoft/spack/humagne/v1/opt/spack/linux-rhel7-x86_E5v4_Mellanox/gcc-4.8.5/gcc-6.5.0-zh4rtcgdquhyaobmlogojyf7incbzjkf/lib/gcc/x86_64-pc-linux-gnu/6.5.0/crtend.o /lib/../lib64/crtn.o
/lib/../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
```

**Comment by lee218llnl** [comment] 2020-05-11 20:29
FWIW, I got a similar explanation from Intel regarding -Xlinker in the .cfg file. No word yet on a potential new option that will print the version regardless.
