### ISSUE TITLE
openmpi fails to compile

### ISSUE THREAD

**Issue by f-sim** [spack/spack#7401] opened 2018-03-06 14:33 UTC
Installing openmpi fails

### Expected Result

openmpi is installed with gcc

### Actual Result

Build fails with error

```
  mpool_memkind.h:57:40: error: ‘MEMKIND_NUM_BASE_KIND’ undeclared here (not in a function)
```

See the log files.

[spack-build.env.txt](https://github.com/spack/spack/files/1785368/spack-build.env.txt)
[spack-build.out.txt](https://github.com/spack/spack/files/1785369/spack-build.out.txt)

### Steps to reproduce the issue

```console
$ spack install openmpi
```

### Information on your system

I am using the system default gcc 4.8.5 on CentOS 7.

**Comment by alalazo** [comment] 2018-03-06 16:06
Using #7204 and giving the following command:
```console
$ spack docker build --image=centos:7 openmpi
==> Building image for "centos:7"
==> Fetching source files
==> Installing specs [--net=none]
==> Creating binary caches
```
works for me. Closing for now, as it seems related to your environment. Feel free to reopen if you have a reproducer.

p.s. for your information, the packages installed on top of the bare `centos:7` are:
```
yum -y install git gcc gcc-c++ gcc-gfortran make bzip2 patch file
```

**Closed by alalazo** 2018-03-06 16:06 UTC
Labels: build-error
