### ISSUE TITLE
Binary Relocation in Py3: string + byte concatenation error

### ISSUE THREAD

**Issue by eugeneswalker** [spack/spack#12648] opened 2019-08-29 17:29 UTC
There are multiple places inside /lib/spack/spack/relocate.py where strings and bytes are concatenated, which is not allowed in Python 3. For instance, if you try to install a package from binary cache (`spack buildcache install <spec-available-at-buildcache>`), using Spack+Py3, the process fails with an error from line 323 of lib/spack/spack/relocate.py complaining about this. There are at least a few other places in that file which cause problems during installation from binary cache with python3.

**Comment by gartung** [comment] 2019-10-09 21:11
As code has been added since you made this report is this the command that fails
https://github.com/spack/spack/blob/469bef880a402ce8d7b4b3b804c18f32884c6fb4/lib/spack/spack/relocate.py#L379

**Comment by gartung** [comment] 2019-10-09 21:22
That would imply that this routine in Conda has the same  bug
https://github.com/conda/conda/blob/95e80f1487f3cc72bd57137af09377290fa2db64/conda/core/portability.py#L91

**Comment by gartung** [comment] 2019-10-09 21:25
I need more info to try and reproduce this bug. Can you tell me the package you built and were trying to relocate when this error occurred? Does this error occur for any 'spack buildcache install' command when run with python3?

**Comment by gartung** [comment] 2019-10-09 21:30
It looks like I missed the part where the text is encoded as utf-8
https://github.com/conda/conda/blob/95e80f1487f3cc72bd57137af09377290fa2db64/conda/core/portability.py#L66

**Comment by gartung** [comment] 2019-10-09 21:39
@adamjstewart or @eugeneswalker can you confirm that this PR fixes the issue:
https://github.com/spack/spack/pull/13114

**Comment by gartung** [comment] 2019-10-10 15:39
My test on a Centos8 system with python3 shows that the error occurs in other places. Back to debugging.

**Comment by eugeneswalker** [comment] 2019-10-10 19:36
Thanks for taking a look at this! I would love to be able to use Spack/Python3 with buildcaches! I have not tried Python3/Spack with buildcaches in a while but I recall it being not specific to a package, but rather a general result of internal `spack buildcache install` logic.

**Comment by gartung** [comment] 2019-10-11 03:12
Resolved with https://github.com/spack/spack/pull/13141 hopefully.

**Comment by gartung** [comment] 2019-10-14 16:09
This is now resolved in the head of develop and should go into the next tagged version of spack.

**Closed** 2019-10-14 16:09 UTC
Labels: bug, buildcache, python3
