### ISSUE TITLE
boost does not build with clang 9.0

### ISSUE THREAD

**Issue by jarrah42** [spack/spack#7170] opened 2018-02-02 18:34 UTC
I'm not able to build boost with clang 9.0. This is on Mac OS X High Sierra.

```console
$ spack install boost
==> bzip2 is already installed in .../Work/git/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/bzip2-1.0.6-vfmdedxrupkurelhiarhiuiccvkluoks
==> zlib is already installed in .../Work/git/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/zlib-1.2.11-t74siw3tvuz3vfb3rje5mkbiwneuzfb5
==> Installing boost
==> Using cached archive: .../.spack/cached_archives/boost/boost-1.60.0.tar.bz2
==> Staging archive: .../gw6/Work/git/spack/var/spack/stage/boost-1.60.0-ppxlrzjpwqjmvb2whu7sddxjt3auiyg5/boost_1_60_0.tar.bz2
==> Created stage in .../Work/git/spack/var/spack/stage/boost-1.60.0-ppxlrzjpwqjmvb2whu7sddxjt3auiyg5
==> Applied patch python_jam.patch
==> Building boost [Package]
==> Executing phase: 'install'
==> Error: TypeError: a bytes-like object is required, not 'str'
TypeError: TypeError: a bytes-like object is required, not 'str'

.../Work/git/spack/var/spack/repos/builtin/packages/boost/package.py:385, in install:
     73            # The shared libraries are not installed correctly
     74            # on Darwin; correct this
     75            if (sys.platform == 'darwin') and ('+shared' in spec):
  >> 76                fix_darwin_install_name(prefix.lib)

See build log for details:
 .../Work/git/spack/var/spack/stage/boost-1.60.0-ppxlrzjpwqjmvb2whu7sddxjt3auiyg5/boost_1_60_0/spack-build.out
```

**Comment by jrood-nrel** [comment] 2018-02-12 21:53
Ah, I have not tried High Sierra, but for reference I use boost 1.60.0 consistently on multiple Sierra machines with Apple Clang 9.0.0:

```
machine:~ user$ spack find boost %clang
==> 1 installed packages.
-- darwin-sierra-x86_64 / clang@9.0.0-apple ---------------------
boost@1.60.0
```

**Comment by ziolai** [comment] 2018-02-19 17:54
@jarrah42 and @jrood-nrel: have same problem installing boost 1.60.0 on Mac OS X Sierra (as part of installing OpenFoam). Tried both gcc and Apple Clang 9.0.0. 

@jarrah42: did you resolve the issue? If so, how? 

@jrood-nrel: could you share your .spack/darwin/compilers.yaml ? 

Thank you so much! Domenico

**Comment by ziolai** [comment] 2018-02-19 18:57
Update: 

I managed to edit my ./spack/darwin/compilers.yaml to include path to 
      cc: /Applications/Xcode.app/.../usr/bin/clang
      cxx: /Applications/Xcode.app/.../usr/bin/clang++
I found that difficulties persist, that is, I get the same error as reported by jarrah42. I also verified that spack install boost@1.60.0 -shared does fine, see below. 

Difficulties seems to reside with shared libraries. I see that an extra_rpath entry for the compiler.yaml does exist. I am not sure how to use it. Any thoughts? 

Thanks, Domenico. 

Domenicos-MBP:clang-9.0.0-apple ziolai$ spack install boost@1.60.0 %clang -shared 
==> bzip2 is already installed in /Users/ziolai/spack/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/bzip2-1.0.6-dspzezlf3hhea4busq6pqyqkpba67vzg
==> zlib is already installed in /Users/ziolai/spack/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/zlib-1.2.11-cpdvq4e7otjepbwdtxmgk5bzszze27fj
==> Installing boost
==> Using cached archive: /Users/ziolai/spack/var/spack/cache/boost/boost-1.60.0.tar.bz2
==> Staging archive: /Users/ziolai/spack/var/spack/stage/boost-1.60.0-v4xjv5myzboeknp36cladatcvbooq3wa/boost_1_60_0.tar.bz2
==> Created stage in /Users/ziolai/spack/var/spack/stage/boost-1.60.0-v4xjv5myzboeknp36cladatcvbooq3wa
==> Applied patch python_jam.patch
==> Building boost [Package]
==> Executing phase: 'install'
==> Successfully installed boost
  Fetch: 0.20s.  Build: 7m 42.38s.  Total: 7m 42.58s.
[+] /Users/ziolai/spack/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/boost-1.60.0-v4xjv5myzboeknp36cladatcvbooq3wa

**Comment by jarrah42** [comment] 2018-02-19 19:13
I haven't been able to get it to work.

**Comment by ziolai** [comment] 2018-02-19 19:19
Thx. Good to know.

**Comment by jrood-nrel** [comment] 2018-02-20 14:52
I'm worried about how old the Spack clone is for @jarrah42 since a version of boost isn't specified and it's using 1.60.0 when I would expect 1.66.0 unless a version was specified.

@ziolai I'm not sure `compilers.yaml` is going to help with the error @jarrah42 is seeing because it looks like a Python error.

```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
      cxx: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: clang@9.0.0-apple
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/local/bin/gcc-7
      cxx: /usr/local/bin/g++-7
      f77: /usr/local/bin/gfortran-7
      fc: /usr/local/bin/gfortran-7
    spec: gcc@7.2.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/local/bin/gcc-5
      cxx: /usr/local/bin/g++-5
      f77: /usr/local/bin/gfortran-5
      fc: /usr/local/bin/gfortran-5
    spec: gcc@5.4.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/local/bin/gcc-6
      cxx: /usr/local/bin/g++-6
      f77: /usr/local/bin/gfortran-6
      fc: /usr/local/bin/gfortran-6
    spec: gcc@6.4.0
    target: x86_64
```

```
machine:~ user$ spack find -vd boost
==> 2 installed packages.
-- darwin-sierra-x86_64 / clang@9.0.0-apple ---------------------
    boost@1.60.0+atomic+chrono~clanglibcpp+date_time~debug+exception+filesystem~graph~icu+iostreams+locale+log+math~mpi+multithreaded patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199 +program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave
        ^bzip2@1.0.6+shared
        ^zlib@1.2.11+optimize+pic+shared


-- darwin-sierra-x86_64 / gcc@7.2.0 -----------------------------
    boost@1.60.0+atomic+chrono~clanglibcpp+date_time~debug+exception+filesystem~graph~icu+iostreams+locale+log+math~mpi+multithreaded patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199 +program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave
        ^bzip2@1.0.6+shared
        ^zlib@1.2.11+optimize+pic+shared
```

**Comment by jarrah42** [comment] 2018-02-20 15:37
My repo was up to date with Github. I tried blowing it away and recloning and now I'm getting boost 1.66.0.

$ ./spack compilers
==> Available compilers
-- clang highsierra-x86_64 --------------------------------------
clang@9.0.0-apple

-- gcc highsierra-x86_64 ----------------------------------------
gcc@7.3.0  gcc@6.3.0
$ ./spack install boost
==> Installing bzip2
==> Fetching http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
######################################################################## 100.0%
==> Staging archive: /Users/user/Work/git/spack/var/spack/stage/bzip2-1.0.6-vfmdedxrupkurelhiarhiuiccvkluoks/bzip2-1.0.6.tar.gz
==> Created stage in /Users/user/Work/git/spack/var/spack/stage/bzip2-1.0.6-vfmdedxrupkurelhiarhiuiccvkluoks
==> Ran patch() for bzip2
==> Building bzip2 [Package]
==> Executing phase: 'install'
==> Successfully installed bzip2
  Fetch: 2.79s.  Build: 5.45s.  Total: 8.24s.
[+] /Users/user/Work/git/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/bzip2-1.0.6-vfmdedxrupkurelhiarhiuiccvkluoks
==> Installing zlib
==> Fetching http://zlib.net/fossils/zlib-1.2.11.tar.gz
######################################################################## 100.0%
==> Staging archive: /Users/user/Work/git/spack/var/spack/stage/zlib-1.2.11-t74siw3tvuz3vfb3rje5mkbiwneuzfb5/zlib-1.2.11.tar.gz
==> Created stage in /Users/user/Work/git/spack/var/spack/stage/zlib-1.2.11-t74siw3tvuz3vfb3rje5mkbiwneuzfb5
==> No patches needed for zlib
==> Building zlib [Package]
==> Executing phase: 'install'
==> Successfully installed zlib
  Fetch: 0.74s.  Build: 3.84s.  Total: 4.58s.
[+] /Users/user/Work/git/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/zlib-1.2.11-t74siw3tvuz3vfb3rje5mkbiwneuzfb5
==> Installing boost
==> Fetching https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2
######################################################################## 100.0%
==> Staging archive: /Users/user/Work/git/spack/var/spack/stage/boost-1.66.0-ndkla2rjg62ro3uhudevi2loxpsadylv/boost_1_66_0.tar.bz2
==> Created stage in /Users/user/Work/git/spack/var/spack/stage/boost-1.66.0-ndkla2rjg62ro3uhudevi2loxpsadylv
==> Applied patch python_jam.patch
==> Building boost [Package]
==> Executing phase: 'install'
==> Error: TypeError: a bytes-like object is required, not 'str'
TypeError: TypeError: a bytes-like object is required, not 'str'

/Users/user/Work/git/spack/var/spack/repos/builtin/packages/boost/package.py:385, in install:
     73            # The shared libraries are not installed correctly
     74            # on Darwin; correct this
     75            if (sys.platform == 'darwin') and ('+shared' in spec):
  >> 76                fix_darwin_install_name(prefix.lib)

See build log for details:
  /Users/user/Work/git/spack/var/spack/stage/boost-1.66.0-ndkla2rjg62ro3uhudevi2loxpsadylv/boost_1_66_0/spack-build.out

**Comment by jrood-nrel** [comment] 2018-02-20 15:43
Ok great. The next thing I would be curious about is the python in use. This might be a python 3 issue. Spack is supposed to work with python 3, but I have never tried it. I am just using the system python:
```
machine:~ user$ which python
/usr/bin/python
machine:~ user$ python --version
Python 2.7.10
```

**Comment by jarrah42** [comment] 2018-02-20 15:49
$ python --version
Python 3.6.1 :: Anaconda custom (x86_64)

**Comment by jrood-nrel** [comment] 2018-02-20 16:02
Ah, I can't believe I didn't catch this earlier. There is actually a single issue about this in a repo I have at https://github.com/NaluCFD/NaluSpack/issues/1 . I'm trying to figure out what the solution is here and if it's either an Anaconda problem, or Python 3, or the Boost package file itself.

**Comment by ziolai** [comment] 2018-02-20 17:35
As I get the same problem installing the cgal package (as part of openfoam), I doubt that the problems lies with the Boost package itself.

**Comment by jrood-nrel** [comment] 2018-02-20 17:41
@ziolai Spack has a package file `package.py` for Boost that is most likely the problem here. That's where the Python 3 errors are happening.

**Comment by ziolai** [comment] 2018-02-20 18:24
Thanks! Any suggestions for work arounds?

**Comment by jrood-nrel** [comment] 2018-02-21 16:20
@ziolai Unfortunately the only workaround I can suggest is not using Python 3 for Spack. Someone will have to update the Boost package file to work with Python 3. I don't use Python 3, but I can try to take a look and see if it's an easy fix.

**Comment by ziolai** [comment] 2018-02-22 06:33
Thanks! Is there a way to instruct spack install to use python 2 and to override the python 3 default?

**Comment by jrood-nrel** [comment] 2018-02-22 16:58
I think you are likely setting Python 3 to be the default if you do `which python; python --version`, most likely in your `.bashrc`, `.bash_profile`, or `.profile`. This is the Python that is used to execute Spack itself even before any packages are installed. It is possible if packages have Python dependencies to use `spack install boost ^python@2.7.14` to constrain the version of a dependency, but I don't think that applies here.

**Comment by scheibelp** [comment] 2018-02-22 22:36
@jarrah42 could you rerun the install command with `-d`: `spack -d install boost`

The boost package references an OSX-specific Spack library function which may not be python3 compatible but that is hard for me to test as I don't have access to a Mac (seeing the detailed error is likely to provide enough information for me to fix it though).

**Comment by jrood-nrel** [comment] 2018-02-23 00:30
I was able to reproduce this with Python 3.6.3. Here is the `-d` output:

**Comment by jarrah42** [comment] 2018-02-23 00:54
Mine looks the same.

**Comment by scheibelp** [comment] 2018-02-23 02:40
OK looks like this is an issue with the output of Popen for python2 vs. python3; I have a potential fix at https://github.com/spack/spack/pull/7329 - could you try that out? This might be somewhat back-and-forth since I can't replicate the exact issue.

**Comment by ziolai** [comment] 2018-02-23 11:18
Will be happy to try fixes proposed. From #7329 it is however not clear to me what I should do. Could you please elaborate a bit? Thank you so much.

**Comment by jrood-nrel** [comment] 2018-02-23 15:52
@scheibelp I tried your fix and it worked 👍

**Comment by ziolai** [comment] 2018-02-23 17:49
What exactly did you do? Thanks!

**Comment by scheibelp** [comment] 2018-02-23 18:31
@jrood-nrel thanks! I have merged #7329 so I'll close this.

@ziolai to test out a PR you can do the following:

```
git fetch origin pull/<pr number>/head:<an identifier chosen by you, e.g. X>
git checkout X
```

**Closed by scheibelp** 2018-02-23 18:31 UTC
Labels: build-error

**Comment by jarrah42** [comment] 2018-02-23 19:01
This fix worked for me also.

**Comment by ziolai** [comment] 2018-02-23 19:19
Apologies for still being confused. What should pr number new here? How do I proceed after the git checkout? Thank you so much.

**Comment by jrood-nrel** [comment] 2018-02-23 22:28
@ziolai The fix has been committed. You can just pull the latest `develop` branch now.

Thanks for fixing this @scheibelp .
