### ISSUE TITLE
 spack install vtk

### ISSUE THREAD

**Issue by lcebaman** [spack/spack#11987] opened 2019-07-11 17:05 UTC
### Steps to reproduce the issue

```console
spack install vtk ^hdf5+hl+mpi
Input spec
--------------------------------
vtk
    ^hdf5+hl+mpi

Concretized
--------------------------------
==> Error: Multiple providers found for 'gl': ['mesa@18.1.2%gcc@8.2.0~hwrender~llvm+swrender arch=linux-centos7-x86_64  ^binutils ^bison@2.4.1: ^damageproto@1.1: ^diffutils@3.7%gcc@8.2.0 arch=linux-centos7-x86_64  ^expat@2.2.5%gcc@8.2.0+libbsd arch=linux-centos7-x86_64  ^fixesproto@5.0: ^flex@2.5.35: ^gdbm ^gettext@0.19: ^glproto@1.4.14: ^help2man ^icu4c ^inputproto ^kbproto ^libbsd ^libpthread-stubs ^libsigsegv ^libx11@1.6: ^libxau@0.99.2: ^libxcb@1.9.3: ^libxdamage ^libxdmcp ^libxext ^libxfixes ^libxshmfence@1.1: ^libxv ^libxvmc ^m4@1.4.18%gcc@8.2.0+sigsegv arch=linux-centos7-x86_64  ^ncurses ^openssl ^perl@5.14.0: ^pkgconf@1.6.0%gcc@8.2.0 arch=linux-centos7-x86_64  ^presentproto@1.0: ^py-argparse ^py-mako@0.3.4: ^py-markupsafe@0.9.2: ^py-setuptools ^python@2.7:2.8,3.4: ^readline ^util-macros ^videoproto ^xcb-proto ^xextproto@7.1.99: ^xproto@7.0.17: ^xtrans ^zlib@1.2.11%gcc@8.2.0+optimize+pic+shared arch=linux-centos7-x86_64', 'opengl']

```

### Platform and user environment

```commandline
$ uname -a 
Linux indy2-login0 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	CentOS Linux release 7.3.1611 (Core)
```

**Comment by lcebaman** [comment] 2019-07-11 17:07
Any idea how to fix this?

**Comment by adamjstewart** [comment] 2019-07-13 01:43
Possible duplicate of #7901 #7986 #8133 #9408. Hopefully one of those issues mentions a workaround that helps!

**Comment by lcebaman** [comment] 2019-07-14 15:22
Possible, but the solutions provided do not satisfy our system. We cannot even locate `packages.yaml`. Is there a cleaner solution?

**Comment by adamjstewart** [comment] 2019-07-14 19:32
> We cannot even locate `packages.yaml`.

You can figure out where your `packages.yaml` contributions come from via:
```console
$ spack config blame packages
```
Also see https://spack.readthedocs.io/en/latest/configuration.html for additional locations where `packages.yaml` files can be placed if you don't already have any.

> Is there a cleaner solution?

I don't currently know of one, but @scheibelp or @tgamblin might.

@scheibelp @tgamblin if we figure out a reliable way to workaround this, we should add it to https://spack.readthedocs.io/en/latest/known_issues.html until a more permanent solution can be found. This seems to be a common issue.

**Comment by scheibelp** [comment] 2019-07-15 21:00
What commit of Spack are you on?

> the solutions provided do not satisfy our system.

So for example you cannot build mesa? If so, you could do `spack spec vtk+osmesa ^hdf5+hl+mpi ^mesa`, which should avoid the concretization issue.

**Comment by alalazo** [comment] 2020-11-02 20:28
I can't reproduce this issue anymore, both with the original and the new concretizer. Closing for now, but feel free to reopen if I missed something.

**Closed by alalazo** 2020-11-02 20:28 UTC
Labels: build-error, concretization, impact-low, virtual-dependencies
