### ISSUE TITLE
Spack Environment Concretization Duplicating Dependencies

### ISSUE THREAD

**Issue by rspavel** [spack/spack#11095] opened 2019-04-02 22:46 UTC
We are investigating spack environments as a way to replicate build environments and noticed top level dependencies being built as separate variants.

Is this expected behavior or should the concretization process be spread across all specs in the spack.yaml?

### Steps to reproduce the issue
Reproduced on multiple platforms and verified in the spack/ubuntu:18.04 container with commit 7a28a61a59b1233a82ea21c1b09dd40e4628183f 

```
[ubuntu] tmp2: cat spack.yaml
spack:
  specs:
  - boost@1.68.0
  - trilinos@12.12.1
```

### Error Message

```
[ubuntu] tmp2: spack concretize -f
==> Concretizing boost@1.68.0
 -   7znc464  boost@1.68.0%gcc@7.3.0+atomic+chrono~clanglibcpp cxxstd=default +date_time~debug+exception+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199 ~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave arch=linux-ubuntu18.04-x86_64
...
==> Concretizing trilinos@12.12.1
 -   kmmhk7k  trilinos@12.12.1%gcc@7.3.0~alloptpkgs+amesos+amesos2+anasazi+aztec+belos+boost build_type=RelWithDebInfo ~cgns~complex~debug~dtk+epetra+epetraext+exodus+explicit_template_instantiation~float+fortran~fortrilinos+gtest+hdf5+hypre+ifpack+ifpack2~intrepid~intrepid2~isorropia+kokkos+metis~minitensor+ml+muelu+mumps~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado~shards+shared~stk+suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~x11~xsdkflags~zlib+zoltan+zoltan2 arch=linux-ubuntu18.04-x86_64
 -   tumf2uc      ^boost@1.69.0%gcc@7.3.0+atomic+chrono~clanglibcpp cxxstd=default +date_time~debug+exception+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199 ~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave arch=linux-ubuntu18.04-x86_64
```

**Comment by davydden** [comment] 2019-04-05 09:58
i think this is a duplicate of https://github.com/spack/spack/issues/9902

**Comment by alalazo** [comment] 2019-04-05 14:08
@rspavel Having all the abstract requirements concretized together is definitely in the road-map and as far as I know it will become an option in `spack.yaml`.

**Comment by rspavel** [comment] 2019-04-05 14:15
Thanks. I guess I just got really lucky with the first few spackage combinations I tested.

**Comment by bartlettroscoe** [comment] 2019-08-01 22:36
We have seen this too.

FYI: We fixed that by creating a dummy package that depends on all of the packages that we want spack to build and then spack seems to build just one version of each package.  There was another hack that was needed to avoid spack building multiple MPI versions too.

**Comment by alalazo** [comment] 2019-08-02 05:38
@bartlettroscoe Did you have a look at #11372 ?

**Comment by bartlettroscoe** [comment] 2019-08-02 10:56
>  Did you have a look at #11372 ?

Yes I saw that but it is not merged yet so we can't use it (and we are stuck on an older version of spack anyway).

 Again, I ask why this was not the default behavior to begin with?  Customers want to be able to link everything that Spack builds into downstream software so why in the heck would Spack, by default, build diferent versions of MPI for different packages, multiple selections of BLAS/LAPACK? This one issue makes Spack unusable for most people.  (I have talked with many people who tried spack, saw stuff like this and gave up.) 

We would have been stuck too if I had not figured out how to create a dummy downstream package that just include all of the other packages and tricks spack into building a consistent set of versions of intermediate packages.  And even that was not enough for MPI.  There was another hack you and to do to trick spack into not building multiple MPI versions.

This is crazy.

**Comment by alalazo** [comment] 2019-08-02 11:11
> There was another hack you and to do to trick spack into not building multiple MPI versions.

Which other hack? :thinking:

**Comment by bartlettroscoe** [comment] 2019-08-02 11:24
> > There was another hack you and to do to trick spack into not building multiple MPI versions.
>
> Which other hack?

You have to explicitly give the MPI version in the spec, even though the dummy package does not directly depend on MPI.

```
spack:
  specs: [snl-atdm-deps ^openmpi@1.10.1%gcc@7.2.0 cppflags="-fPIC"]
```
The dummy package 'snl-atdm-deps' `package.py` file just lists the outer most leaf packages:

```
    depends_on('cgns')
    depends_on('netcdf')
    depends_on('hdf5')
    depends_on('superlu-dist')
    depends_on('parmetis')
    depends_on('superlu')
    depends_on('netlib-lapack')
    depends_on('boost')
    depends_on('zlib')
    depends_on('binutils')
```

But with just that, spack was still using different versions of MPI for different packages :-(

I can't imagine what other users are going through trying to get a consistent set of packages to build.

**Comment by bartlettroscoe** [comment] 2019-08-02 11:31
Without scripting, hacked dummy package, etc., this is what we  had to do to get spack to build consistent versions of everything:

```
spack:
  # add package specs to the `specs` list
  specs: [netcdf@4.4.1%gcc@7.2.0 maxdims=65536 maxvars=52428 +parallel-netcdf ^hdf5@1.8.20%gcc@7.2.0+cxx~debug+fortran+hl+mpi+pic+shared~szip~threadsafe
      ^openmpi@1.10.1%gcc@7.2.0 ^parallel-netcdf ^zlib~shared, openmpi@1.10.1%gcc@7.2.0
      ^zlib~shared, hdf5@1.8.20%gcc@7.2.0+cxx~debug+fortran+hl+mpi+pic+shared~szip~threadsafe
      ^openmpi@1.10.1%gcc@7.2.0 ^zlib~shared, superlu@4.3%gcc@7.2.0 ^netlib-lapack%gcc@7.2.0
      ^zlib~shared, zlib~shared, netlib-lapack%gcc@7.2.0 ^zlib~shared, gcc@7.2.0 ^zlib~shared,
    cmake ^zlib~shared, git ^zlib~shared, boost@1.59.0%gcc@7.2.0 ^zlib~shared, ninja-fortran%gcc@7.2.0 ^zlib~shared,
    cgns@snl-atdm%gcc@7.2.0 +fortran~tools ^hdf5@1.8.20%gcc@7.2.0+cxx~debug+fortran+hl+mpi+pic+shared~szip~threadsafe ^openmpi@1.10.1%gcc@7.2.0 ^zlib~shared,
    parmetis%gcc@7.2.0 ^openmpi@1.10.1 ^zlib~shared,
    superlu-dist%gcc@7.2.0 ^parmetis%gcc@7.2.0 ^openmpi@1.10.1 ^zlib~shared ^netlib-lapack%gcc@7.2.0,
    binutils%gcc@7.2.0+libiberty+headers ^zlib~shared]
```

How about that for a nice maintainable set of specifications for building packages!

How many users are having to writing spack.yaml files like this?

**Comment by alalazo** [comment] 2019-08-02 12:39
I can get a consistent set of specs with #11372 and this `spack.yaml`:
```yaml
spack:
  specs:
  - cgns
  - netcdf
  - hdf5+hl
  - superlu-dist
  - parmetis
  - superlu
  - netlib-lapack
  - boost
  - zlib
  - binutils
  concretize_together: true
  view: false
```
which replicates your dummy package above.

**Closed** 2019-10-07 16:53 UTC
Labels: concretization, duplicate, environments, feature
