### ISSUE TITLE
Unable to use cray compilers on ANL/theta(XC40)

### ISSUE THREAD

**Issue by balay** [spack/spack#6107] opened 2017-11-02 16:44 UTC
I'm attempting spack/xsdk build on ANL/theta(XC40) - and having trouble with the 'module syntax in ~/.spack/packages.yaml

The softenv I'm using is:

```
balay@thetalogin6:~/spack> module list |& egrep \(PrgEnv\|mpich\|intel\)
  3) intel/18.0.0.128
 19) PrgEnv-intel/6.0.4
 21) cray-mpich/7.6.3
```

Using Instructions from http://spack.readthedocs.io/en/latest/getting_started.html?highlight=intel-mpi#spack-on-cray  - I have the following in my package.py

```
packages:
  mpich:
    modules:
      mpich@7.6.3%intel@18.0.0.128 arch=cray-CNL-mic_knl: cray-mpich
    buildable: False
  all:
    providers:
      mpi: [mpich]
    compiler: [intel@18.0.0.128]
```

With this - I get:

```
balay@thetalogin6:~/spack> spack spec parmetis
Input spec
--------------------------------
parmetis

Normalized
--------------------------------
parmetis
    ^cmake@2.8:
    ^metis@5:
    ^mpi

Concretized
--------------------------------
==> Error: invalid syntax (<string>, line 525)
```

And here is the bizzare part.
```
Could you help me with correctly configuring and using cray? And How do I debug this error?

**Comment by KineticTheory** [comment] 2017-11-02 17:59
@balay FWIW - my `packages.yaml` entry for cray-mpich looks like this:

```
  mpich:
    version: [7.6.2]
    modules:
      mpich@7.6.2: cray-mpich/7.6.2
      mpich@7.5.2: cray-mpich/7.5.2
      mpich@7.4.2: cray-mpich/7.4.2
    buildable: False
```

I haven't tried to target KNL yet, so I'm not sure if you need the `arch` portion of the identifier.

**Comment by balay** [comment] 2017-11-02 20:02
It doesn' work. I tried bunch of other stuff with weird behaviour - which I can't reproduce now..

```packages:
  mpich:
    modules:
      mpich@7.6.3%intel@18.0.0.128 : cray-mpich/7.6.3
    buildable: False
  all:
    providers:
      mpi: [mpich]
    compiler: [intel@18.0.0.128]
```

```balay@thetalogin6:~/spack> spack spec parmetis
Input spec
--------------------------------
parmetis

Normalized
--------------------------------
parmetis
    ^cmake@2.8:
    ^metis@5:
    ^mpi

Concretized
--------------------------------
==> Error: invalid syntax (<string>, line 525)
balay@thetalogin6:~/spack> 
```

BTW: The `arch` matches what `spack` prints below..

```
balay@thetalogin6:~/spack> spack spec pkg-config
Input spec
--------------------------------
pkg-config

Normalized
--------------------------------
pkg-config

Concretized
--------------------------------
pkg-config@0.29.2%intel@18.0.0.128+internal_glib arch=cray-CNL-mic_knl 

balay@thetalogin6:~/spack> 

````

**Comment by mamelara** [comment] 2017-11-02 20:33
```spack -d spec parmetis
Input spec
--------------------------------
parmetis

Normalized
--------------------------------
parmetis
    ^cmake@2.8:
    ^metis@5:
    ^mpi

Concretized
--------------------------------
==> Reading config file /global/u2/m/mamelara/spack/etc/spack/defaults/packages.yaml
==> Reading config file /global/u2/m/mamelara/spack/etc/spack/defaults/cray/packages.yaml
==> READ LOCK: /global/homes/m/mamelara/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /global/homes/m/mamelara/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /global/homes/m/mamelara/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> Reading config file /global/homes/m/mamelara/.spack/cray/compilers.yaml
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'PrgEnv-gnu'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-x1'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-x2'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-cray'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-intel'
Traceback (most recent call last):
  File "/global/homes/m/mamelara/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/global/u2/m/mamelara/spack/lib/spack/spack/main.py", line 547, in main
    return _main(command, parser, args, unknown)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/main.py", line 439, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/main.py", line 355, in _invoke_spack_command
    return_val = command(parser, args)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/cmd/spec.py", line 90, in spec
    spec.concretize()
  File "/global/u2/m/mamelara/spack/lib/spack/spack/spec.py", line 1855, in concretize
    load_module(mod)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/util/module_cmd.py", line 141, in load_module
    unload_module(text[i + 1])
  File "/global/u2/m/mamelara/spack/lib/spack/spack/util/module_cmd.py", line 123, in unload_module
    'exec'))
  File "<string>", line 505
    craype-mic-knl requires cce/8.4 or later, intel/14.0 or later, or gcc/5.1 or later
                          ^
SyntaxError: invalid syntax```

Hmm we ran into this issue before and our solution was to load cce when installing with mic-knl (And I really don't know why cray makes this complaint).

**Comment by balay** [comment] 2017-11-02 20:47
On Thu, 2 Nov 2017, Mario Melara wrote:

> spack -d spec parmetis

> solution was to load cce when installing with mic-knl

Thanks! Will give it a try!

**Comment by becker33** [comment] 2024-12-05 19:12
Closing as the issue is specific to ANL/Theta which is a retired machine

**Closed by becker33** 2024-12-05 19:12 UTC
Labels: cray
