### ISSUE TITLE
spack compiler find: update "None" entries with found

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2599] opened 2016-12-15 12:37 UTC
Re-running `spack compiler find` does not find compilers that have been installed since the last time it was run.  See:

https://groups.google.com/forum/#!topic/spack/9r4CR9jmNjY

**Comment by davydden** [comment] 2016-12-15 12:45
so the suggestion is to always update `compilers.yaml` with the new paths, in case Spack find the same compiler/version but in a new location now?

**Comment by adamjstewart** [comment] 2016-12-16 18:39
Just to be more clear, the issue isn't that `spack compiler find` doesn't find new compilers. It's that it doesn't update _existing_ Spack compilers with _newly added_ Fortran compilers. If you run `spack compiler remove gcc` and re-run `spack compiler find`, I suspect it will work as expected.

This is definitely a troublesome bug, and probably happens for a lot of macOS users.

**Comment by tgamblin** [comment] 2016-12-16 22:10
The idea with the current behavior is that it will not update an existing user configuration with a "better" compiler if the user doesn't want one.  I suspect people actually want their Fortran compilers updated when they run `spack compiler find`.

Is it sufficient to notice that some compilers are set to `None` and to update *those* if they are found?

**Comment by adamjstewart** [comment] 2016-12-16 22:12
> Is it sufficient to notice that some compilers are set to None and to update those if they are found?

I think that would be enough. The only thing I want to make sure is that it won't overwrite my `cflags` and friends.

**Comment by citibeth** [comment] 2016-12-16 22:12
`spack compiler find` could root around, find stuff, show it to the user,
and then ask for direction on what to do.

**Comment by davydden** [comment] 2016-12-17 09:00
> Is it sufficient to notice that some compilers are set to None and to update those if they are found?

sounds good to me. Additionally in this case it would be good to print out something like `fc f77 compilers are updated in XYZ@1234`

> `spack compiler find` could root around, find stuff, show it to the user,
and then ask for direction on what to do.

that would also do, but I don't think it's necessary for the current problem and is also more complicated to implement. I would not bother asking a user when updating `None` to `something`, jus t confirm to him/her that this happened.

**Comment by citibeth** [comment] 2016-12-17 17:10
> spack compiler find could root around, find stuff, show it to the user,
> and then ask for direction on what to do.
>
> that would also do, but I don't think it's necessary for the current
> problem and is also more complicated to implement. I would not bother
> asking a user when updating None to something, jus t confirm to him/her
> that this happened.
>
I agree, sounds good to me.

**Comment by aprokop** [comment] 2016-12-21 03:07
Got hit by that in #2342 when using a container with only gcc/g++ installed. Updated HEAD which included a newer variant of openmpi (which needs Fortran), installed gfortran, even blew away spack but the problem was only solved by removing `~/.spack/linux/complers.py`

**Comment by alalazo** [comment] 2019-12-09 12:46
Closing as it appears to be solved:
```
$ spack compilers
==> Available compilers
-- clang ubuntu18.04-x86_64 -------------------------------------
clang@9.0.1  clang@8.0.0  clang@7.0.0  clang@6.0.1  clang@5.0.1  clang@4.0.1  clang@3.9.1

-- gcc ubuntu18.04-x86_64 ---------------------------------------
gcc@9.0.1  gcc@8.3.0  gcc@7.4.0  gcc@6.5.0  gcc@5.5.0  gcc@4.8

$ spack compiler remove gcc@5.5.0
==> Removed compiler gcc@5.5.0

$ spack compiler find
==> Added 1 new compiler to /home/culpo/.spack/linux/compilers.yaml
gcc@5.5.0
==> Compilers are defined in the following files:
    /home/culpo/.spack/linux/compilers.yaml
```

**Closed by alalazo** 2019-12-09 12:46 UTC
Labels: bug, commands, compilers, configuration
