### ISSUE TITLE
libxml2.so link failure against libz.so looking for gzopen64@ZLIB_1.2.3.3

### ISSUE THREAD

**Issue by bartlettroscoe** [spack/spack#12143] opened 2019-07-25 23:36 UTC
CC: @becker33, @fryeguy52

When trying to link Trilinos with against packages built with Spack with shared libs on an SNL COE RHEL6 machine we get the link errors in Trilinos like:

`FAILED: packages/seacas/libraries/ioss/src/main/cth_pressure_map`
...
`/home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/libxml2-2.9.8-qckwa5f4brssbbwbbtxe7tvdy4dnhwlw/lib/libxml2.so.2: undefined reference to 'gzopen64@ZLIB_1.2.3.3'`

The full link line in Trilinos for this was:

<details>
<summary><b>FULL LINK LINE</b> (click to expand)</summary>

`/home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/openmpi-1.10.1-x2ipjvmrhhgydtcpz5i6s2ln6zjuzvqj/bin/mpicxx  --std=c++11 -g -fopenmp     -O3 -DNDEBUG   packages/seacas/libraries/ioss/src/main/CMakeFiles/cth_pressure_map.dir/cth_pressure_map.C.o packages/seacas/libraries/ioss/src/main/CMakeFiles/cth_pressure_map.dir/vector3d.C.o  -o packages/seacas/libraries/ioss/src/main/cth_pressure_map  -Wl,-rpath,/home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/netcdf-4.4.1-zyizihnvwgg6u7yt5pldcj4vfpmqt7ki/lib:/home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/hdf5-1.8.21-tmyizpmttnq3d3lpjq3usvuhksngh3zw/lib:/home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/zlib-1.2.11-aqhxxoj2tgtjgdkqpxtdyzo6sfwsi6vg/lib:/home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/metis-5.1.0-ui6om2qpphok7c5uqdiwqle6om7funue/lib:/home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/parmetis-4.0.3-rpa6ngvxiacewkq3twiic2pxh5ea64r6/lib::::::::::::::: packages/seacas/libraries/ioss/src/main/libio_info_lib.a packages/seacas/libraries/ioss/src/init/libIonit.a packages/seacas/libraries/ioss/src/transform/libIotr.a packages/seacas/libraries/ioss/src/heartbeat/libIohb.a packages/seacas/libraries/ioss/src/gen_struc/libIogs.a packages/seacas/libraries/ioss/src/generated/libIogn.a packages/seacas/libraries/ioss/src/visualization/libIovs.a packages/seacas/libraries/ioss/src/cgns/libIocgns.a packages/seacas/libraries/ioss/src/pamgen/libIopg.a packages/seacas/libraries/ioss/src/exo_fac/libIoexo_fac.a packages/seacas/libraries/ioss/src/exo_par/libIopx.a packages/seacas/libraries/ioss/src/exo_fpp/libIofx.a packages/seacas/libraries/ioss/src/exodus/libIoex.a packages/seacas/libraries/ioss/src/libIoss.a packages/seacas/libraries/exodus/libexodus.a /home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/netcdf-4.4.1-zyizihnvwgg6u7yt5pldcj4vfpmqt7ki/lib/libnetcdf.so /home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/hdf5-1.8.21-tmyizpmttnq3d3lpjq3usvuhksngh3zw/lib/libhdf5_hl.so /home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/hdf5-1.8.21-tmyizpmttnq3d3lpjq3usvuhksngh3zw/lib/libhdf5.so /usr/lib64/libdl.so /usr/lib64/libm.so /home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/parallel-netcdf-1.11.0-yo2opthsskufdzqep2tgb56ztn2kdya5/lib/libpnetcdf.a packages/pamgen/src/libpamgen_extras.a packages/pamgen/src/libpamgen.a packages/zoltan/src/libzoltan.a -lm packages/kokkos/algorithms/src/libkokkosalgorithms.a packages/kokkos/containers/src/libkokkoscontainers.a packages/kokkos/core/src/libkokkoscore.a /home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/cgns-snl-atdm-ep36qaokeela4hyhnwypxehgx5dax4fq/lib/libcgns.a -L/home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/hdf5-1.8.21-tmyizpmttnq3d3lpjq3usvuhksngh3zw/lib -lz /home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/hdf5-1.8.21-tmyizpmttnq3d3lpjq3usvuhksngh3zw/lib/libhdf5_hl.a /home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/hdf5-1.8.21-tmyizpmttnq3d3lpjq3usvuhksngh3zw/lib/libhdf5.a /home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/zlib-1.2.11-aqhxxoj2tgtjgdkqpxtdyzo6sfwsi6vg/lib/libz.so -ldl /home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/metis-5.1.0-ui6om2qpphok7c5uqdiwqle6om7funue/lib/libmetis.so /home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/parmetis-4.0.3-rpa6ngvxiacewkq3twiic2pxh5ea64r6/lib/libparmetis.so`

</details>

The spack build specs for these packages was:

```
[+]  qckwa5f              ^libxml2@2.9.8%gcc@7.2.0~python arch=linux-rhel6-x86_64 
[+]  pnczpyw                  ^libiconv@1.15%gcc@7.2.0 arch=linux-rhel6-x86_64 
[+]  cptljw3                  ^pkgconf@1.5.4%gcc@7.2.0 cppflags="-fPIC"  arch=linux-rhel6-x86_64 
[+]  4mfrw3e                  ^xz@5.2.4%gcc@7.2.0 arch=linux-rhel6-x86_64 
[+]  aqhxxoj                  ^zlib@1.2.11%gcc@7.2.0+optimize+pic+shared arch=linux-rhel6-x86_64 
```

The generated 'libxml2.so' library showed:

```
$ nm /home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/libxml2-2.9.8-qckwa5f4brssbbwbbtxe7tvdy4dnhwlw/lib/libxml2.so.2 | grep gzopen
                 U gzopen64@@ZLIB_1.2.3.3
```

The generated 'libz.so' library showed:

```
$ nm  /home/rabartl/Spack.base7/atdm-spack/spack/opt/spack/linux-rhel6-x86_64/gcc-7.2.0/zlib-1.2.11-aqhxxoj2tgtjgdkqpxtdyzo6sfwsi6vg/lib/libz.so | grep gzopen
000000000000d5a0 T gzopen
000000000000d590 T gzopen64
000000000000d590 t gzopen64.localalias.1
```

So 'libz.so' defines the symbol `gzopen64` and 'libxml2.so' is looking for the symbol `gzopen64@@ZLIB_1.2.3.3`.   What is that?  I have never seen a linker symbol like that.

**Comment by bartlettroscoe** [comment] 2019-07-26 15:22
Darn, looks like this was also reported in #5758 almost 2 years ago and the issue got closed without it being resolved :-(

I am going to try to force Spack to build as static 'libxml2' with`-fPIC` and see if that hack will fix our use case.

**Comment by bartlettroscoe** [comment] 2019-07-28 21:40
Still fighting with this issue.  The version of zlib that spack is installing is zlib-1.2.11.  But I just noticed on my RHEL6 system:

```
/lib/libz.so.1
/lib/libz.so.1.2.3
/lib64/libz.so.1
/lib64/libz.so.1.2.3
```

I bet that the spack 'libxml2' package is building against the system-installed zlib-1.2.3(.3) instead of the zlib-1.2.11 that spack installs but downstream packages are pulling in the correct zlib-1.2.11.   Now to figure out how to debug the 'libxml2' package install ...

**Comment by bartlettroscoe** [comment] 2019-07-30 17:29
CC: @becker33, @fryeguy52

Through some detailed analysis about the 'libxml2' and 'zlib' link errors we have been seeing here and there, I have been able to determine:

* The spack build of 'libxml2' is correctly building and linking the 'libxml2.so' library against the 'libz.so' library in 'zlib-1.2.11' that Spack builds.

* The symbol 'ZLIB_1.2.2.3' (and several other version strings) actually exists in the binary 'libz.so' built by Spack!  (Not clear how the linker uses this to create the linker symbol 'gzopen64@@ZLIB_1.2.3.3' in 'libxml2.so' but that is what it must be doing.)

* Trying to link with some libs that include 'libxml2.so' somewhere in the chain and putting in `-lz` by itself will actually result in the linker finding the system /lib64/libz.so.1 (on RHEL6) which appears **not** to be link compatible with the 'libz.so' produced by Spack with 'zlib-1.2.11'.

* The key then to fixing links with 'libxml2' and 'zlib' is to pass in `-L${ZLIB_ROOT}/lib` when linking with `-lz`.  (That fixed the SPARC build against the TPLs installed by Spack.)

See details in [CDOFA-52](https://sems-atlassian-srn.sandia.gov/secure/attachment/19179/cdofa-52-20190730.txt) (protected SNL site).

Does this indicate there might be a missing RPATH embedded in some share lib built by spack or does it mean that if you pass in `-lz` without the right `-L<dir>` that the RPATH location for 'libz.so' gets ignored?  If so, why are we not seeing something similar with other libraries that may also have default system library versions installed?

In any case, being careful to pass in `-L${ZLIB_ROOT}/lib` with `-lz` seems to make our use cases work so I am okay with closing this issue.

**Comment by scheibelp** [comment] 2019-08-03 00:51
To make sure: are you building Trilinos outside of Spack? If so, is there a chance you may be able to use the Spack `trilinos` package?

> does it mean that if you pass in -lz without the right -L<dir> that the RPATH location for 'libz.so' gets ignored

RPATH doesn't replace (or remove the need for) `-L` when linking, it only influences what libraries are loaded when you are running a program. When building packages with Spack, it makes an effort to set RPATH and also add `-L` entries for Spack-built dependencies.

> Darn, looks like this was also reported in #5758 almost 2 years ago and the issue got closed without it being resolved :-(

Feel free to reopen issues if you disagree (although for now I still think that closing the issue makes sense e.g. given the above).

As for how to make it easier for you to build with non-Spack packages using Spack-built packages. There are a few options and we could discuss them (although probably in a new thread).

**Comment by bartlettroscoe** [comment] 2019-08-03 01:16
> To make sure: are you building Trilinos outside of Spack? If so, is there a chance you may be able to use the Spack trilinos package?

That does not really work because our Trilinos build supports development too.  You would not want to use Spack to drive development builds.

> RPATH doesn't replace (or remove the need for) -L when linking, it only influences what libraries are loaded when you are running a program. 

Right.  The ironic part is that because we are linking with libxml2.so, you don't actually need `-lz`.  Turns out that Spack breaks a lot of build scripts that assume that libz will always be pulled in from the system.  I don't know anyone's build scripts that builds libz (spack is the only one).

**Comment by scheibelp** [comment] 2019-08-05 17:42
> Right. The ironic part is that because we are linking with libxml2.so, you don't actually need -lz

I think you're saying that because of

> Trying to link with some libs that include 'libxml2.so' somewhere in the chain and putting in -lz by itself will actually result in the linker finding the system /lib64/libz.so.1

That's the type of roundabout behavior Spack tries to avoid. This is harder to coordinate between Spack and non-Spack builds, but Spack provides some means to facilitate this, which gets to

> That does not really work because our Trilinos build supports development too. You would not want to use Spack to drive development builds.

I think depending on what you mean Spack either is useful for this or could be modified to be useful to this case:

* Spack could generate module files for all your Trilinos dependencies that update `LIBRARY_PATH` for your Trilinos build
* Though I'm not sure of its current state, `spack setup` was a command intended to set up and mark packages as under develop in a DAG

and at least one other comes to mind. This is for a separate thread IMO. The original issue (why is this not working?) appears to be resolved so I will close this.

**Closed by scheibelp** 2019-08-05 17:42 UTC
Labels: build-error, impact-low

**Comment by bartlettroscoe** [comment] 2019-08-05 17:55
@scheibelp 

Fine to close now that I know what the issue is.

> Though I'm not sure of its current state, `spack setup` was a command intended to set up and mark packages as under develop in a DAG

There is no mention of `spack setup` at all at:

* https://spack.readthedocs.io/en/latest/tutorial_packaging.html#debugging-package-builds

Also, we do multi-repo co-development so it would be great if you could tell spack not to blow away build dirs for a given set of packages on down and then just rebuild on re-installs.  I know that is dangerous with some build systems but if you can't do rebuilds then you are in a whole of hurt doing development.

I think a bigger priority is to get spack to be able to cleanly install dependencies for a set of compilers, MPI, and TPLs upstream from Trilinos.  We have been working on that (at various levels) for 6+ months now (and every time I think we are close, another issue comes up).

**Comment by sethrj** [comment] 2021-02-23 00:00
Thanks @bartlettroscoe for the debugging history -- it saved me some work, so I'll add my own debugging here in case it helps with yours or anyone else who has the misfortune of building on RHEL6. (And the root issue may extend beyond RHEL6, we might just be getting "lucky.")

I've been struggling with a similar issue today that only manifests in unusual situations. I was only seeing the error in our app when building with `mpif90`, not when linking against `-lmpi`.
```
/projects/spack/opt/spack/gcc-4.4.7/binutils/4i6ifl5/bin/ld: /projects/spack/opt/spack/gcc-8.3.0/libxml2/vcxejll/lib/libxml2.so.2: undefined reference to `gzopen64@ZLIB_1.2.3.3'
collect2: error: ld returned 1 exit status
```

My minimal test case was using `gcc -lgfortran -lhwloc test.c`, for gcc@8.3+binutils and any of the following changes fixed it:
- Drop `-lgfortran` or `-lhwloc`
- Use `-lxml2` or `-lz` instead of `hwloc`
- Use `openmpi@4` instead of `openmpi@2` (both use different versions of hwloc, but both hwloc individually fail)

It turns out that `libgfortran.so` is missing rpaths:
```
$ readelf -d $(spack location -i gcc@8.3)/lib64/libgfortran.so | grep RPATH
 0x000000000000000f (RPATH)              Library rpath: [/projects/spack/opt/spack/gcc-4.4.7/gcc/punpbku/lib/../lib64]
```

Looking through the `spack-build-out.txt` for `gcc@8 ^gcc@4`: even though GCC links against spack's `libz` while building, **the call to `libtool` that links libgfortran only includes the rpath to `gcc`, *not* to the other dependencies that Spack specifies.** I don't know if this is a GCC problem or something the spack compiler toolchain is supposed to address.

I checked on the working prior builds I had of gcc@8 on RHEL6 from a year ago, and they show the same issue -- but it seems some fortuitous change in the share library load order must've allowed them to work.

Also notably: `gcc@8.3~binutils` on `rhel7` *does* have the correct rpath for zlib, even though the call to `libtool` in the `build-out`  is essentially identical (no explicit `-Wl,-rpath` for the zlib). That makes me think this could somehow be an unforeseen situation in how spack's libtool wrapper interacts with the `+binutils`?

**Comment by bartlettroscoe** [comment] 2021-02-23 00:16
>  anyone else who has the misfortune of building on RHEL6

@sethrj, FYI: RHEL6 is now officially dead at SNL (since Nov 2020) :-)

**Comment by sethrj** [comment] 2021-02-23 01:01
> > anyone else who has the misfortune of building on RHEL6
> 
> @sethrj, FYI: RHEL6 is now officially dead at SNL (since Nov 2020) :-)

Nice! As it should be. 😒 Ours is in life extension mode I think.

But in good/bad news, I reproduced the rpath error on rhel8, it just required `+binutils` for gcc. I'm going to open a new spack issue for it, since the rpath failure could conceivably cause other issues.
