### ISSUE TITLE
octave mkoctfile status

### ISSUE THREAD

**Issue by ImanolGB** [spack/spack#14702] opened 2020-01-31 11:16 UTC
I am trying to build [oct-files](https://octave.org/doc/v4.2.1/Getting-Started-with-Oct_002dFiles.html#Getting-Started-with-Oct_002dFiles) using octave's mkoctfile executable. 

I am aware of octave and compiler [issue](https://github.com/spack/spack/issues/4874), but I am not sure if it has been worked around using `env` or not. Could someone @alalazo update me if mkoctfile is somehow available or not? I am limited in programming and I read Gibberish.

Thanks!

**Comment by adamjstewart** [comment] 2020-01-31 17:47
As far as I know, nothing has changed with respect to `octave`. It's easy to replace Spack's compiler wrapper with the actual compiler if it's stored in a text file, but we currently don't have a way to change it if it's stored in a binary file.

Do you know if there's any way to tell Octave which compiler to store or to use at run-time? If not, we may just have to resort to building Octave without our compiler wrappers and hope for the best. It seems like we explicitly pass the installation prefix for most dependencies, so maybe this will be fine.

**Comment by mtmiller** [comment] 2020-02-01 00:29
:wave: Octave developer here.

The `mkoctfile` program is a simple wrapper around calling the compiler and linker that Octave was originally built with, the natural assumption is that the same toolchain was used to build Octave and is used to compile extensions later. All of its default assumptions can be influenced with environment variables, if you look at `mkoctfile --help` it should list all of the variables that can be overridden. We try to use standard names like `CC`, `CXX`, and so on.

**Comment by adamjstewart** [comment] 2020-02-01 20:00
@mtmiller would you like to be added as a maintainer of the `octave` package in Spack? You don't have to be a Spack expert, just someone willing to take a look at Octave-related issues and PRs. For example, #6647 and #4874 (a duplicate of this issue).

**Comment by mtmiller** [comment] 2020-02-02 00:23
@adamjstewart Sure, I'd be happy to be a resource to help out with any Octave issues that come up, or help determine if there are things we can do better in Octave.

**Comment by adamjstewart** [comment] 2020-02-02 01:07
@ImanolGB are you satisfied with this resolution? We could have the `octave` module file set `CC` and friends for you, but that could cause other problems.

**Comment by alalazo** [comment] 2020-02-02 08:03
@adamjstewart @mtmiller I had a brief look at the issue and staged files from the octave distribution. Am I correct assuming that:
1. `mkoctfile` is generated from `mkoctfile.in.cc` at configure time
2. `mkoctfile` is not used during the compilation of `octave` itself

? If so we can patch `mkoctfile.cc` after it has been generated i.e. filter out Spack's compiler wrappers in favor of the real underlying compilers. Would that be a viable solution?

**Comment by ImanolGB** [comment] 2020-02-02 12:59
> @ImanolGB are you satisfied with this resolution? We could have the `octave` module file set `CC` and friends for you, but that could cause other problems.

@adamjstewart I appreciate your concern. I am certainly out from the decision tree. I just wanted to find out if a solution was available, but I can't be of any help to you. I am very happy you three can study if there is a solution, and I will be satisfied with whatever you come out with.

**Comment by siko1056** [comment] 2020-02-03 05:07
@alalazo something like you suggested https://github.com/spack/spack/issues/14702#issuecomment-581109236 must happen.

Does Spack offer an mechanism to expose the true compiler that is used by Spack's compiler wrapper?  Using these values, `mkoctfile.cc` can be patched with them.

When invoked, `mkoctfile` first polls some environment variables (see below) to set the values.  If an environment variable is unset, the respective value Octave used at compile time gets used.

The Octave compile time values for `mkoctfile.cc` are
```
CC     = /opt/spack/lib/spack/env/gcc/gcc
CXX    = /opt/spack/lib/spack/env/gcc/g++
CXXCPP = /opt/spack/lib/spack/env/gcc/g++ -E
DL_LD  = /opt/spack/lib/spack/env/gcc/g++
F77    = /opt/spack/lib/spack/env/gcc/gfortran
LD_CXX = /opt/spack/lib/spack/env/gcc/g++
SH_LD  = /opt/spack/lib/spack/env/gcc/g++
```

At MY runtime, Octave 5.1.0 sees the following environment:
```octave
>> getenv ("CC")
ans = /opt/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/llvm-9.0.0-7a2pbn33kuookldaf36syhgtsqdayucv/bin/clang
>> getenv ("CXX")
ans = /opt/spack/opt/spack/linux-opensuse_leap15-skylake/gcc-7.5.0/llvm-9.0.0-7a2pbn33kuookldaf36syhgtsqdayucv/bin/clang++
>> getenv ("CXXCPP") = '' 
>> getenv ("DL_LD")  = '' 
>> getenv ("F77")    = '' 
>> getenv ("LD_CXX") = '' 
>> getenv ("SH_LD")  = '' 
```

Two workarounds, that do not guarantee to select a "nice" compiler, are

1. Starting Octave with proper environment:
```
spack load octave
CC=gcc CXX=g++ CXXCPP=g++ DL_LD=g++ F77=gfortran LD_CXX=g++ SH_LD=g++ octave
```

2. Run the following commands, if Octave starts up, or inside `.octaverc`:

```octave
setenv ("CC", "gcc");
setenv ("CXX", "g++");
setenv ("CXXCPP", "g++");
setenv ("DL_LD", "g++");
setenv ("F77", "gfortran");
setenv ("LD_CXX", "g++"); 
setenv ("SH_LD", "g++"); 
```

**Comment by mtmiller** [comment] 2020-02-03 08:06
> Am I correct assuming that:
> 
> 1. `mkoctfile` is generated from `mkoctfile.in.cc` at configure time
> 2. `mkoctfile` is not used during the compilation of `octave` itself

Yes, true on both.

> If so we can patch `mkoctfile.cc` after it has been generated i.e. filter out Spack's compiler wrappers in favor of the real underlying compilers. Would that be a viable solution?

Yeah, we could patch the original source `mkoctfile.in.cc`, the generated `mkoctfile.cc` source, or `build-aux/subs-config-vals.sh`, the script that makes `.cc` from `.in.cc`.

**Closed** 2020-02-03 21:08 UTC
Labels: compilers
