### ISSUE TITLE
Concretization failure when using system-installed CUDA

### ISSUE THREAD

**Issue by SteVwonder** [spack/spack#8745] opened 2018-07-18 20:28 UTC
When I add a system-installed version of CUDA to my `packages.yaml` along with `buildable: False`, anything that depends on cuda fails to concretize.  The main problem here being that the system-installed version of CUDA is not one of the versions explicitly listed in the cuda package.py.  If I add that version of CUDA to the package.py, then everything works as expected.  So ultimately, I think this comes down to spack being unable to automatically generate a url to download the CUDA version from.  This is potentially a symptom of #5814. 

### Expected Result

```
# herbein1 at sierra4362 in /usr/workspace/wsb/herbein1/spack_blueos_ppc/var/spack/repos on git:fix-lmod-separator ✖︎ [13:19:06]
→ spack spec hwloc +cuda
Input spec
--------------------------------
hwloc+cuda

Concretized
--------------------------------
hwloc@2.0.1%gcc@4.9.3~cairo+cuda+libxml2+pci+shared arch=linux-rhel7-ppc64le 
    ^cuda@9.2.64%gcc@4.9.3 arch=linux-rhel7-ppc64le 
    ^libpciaccess@0.13.5%gcc@4.9.3 arch=linux-rhel7-ppc64le 
        ^libtool@2.4.6%gcc@4.9.3 arch=linux-rhel7-ppc64le 
            ^m4@1.4.18%gcc@4.9.3 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e +sigsegv arch=linux-rhel7-ppc64le 
                ^libsigsegv@2.11%gcc@4.9.3 arch=linux-rhel7-ppc64le 
        ^pkgconf@1.4.2%gcc@4.9.3 arch=linux-rhel7-ppc64le 
        ^util-macros@1.19.1%gcc@4.9.3 arch=linux-rhel7-ppc64le 
    ^libxml2@2.9.8%gcc@4.9.3~python arch=linux-rhel7-ppc64le 
        ^xz@5.2.4%gcc@4.9.3 arch=linux-rhel7-ppc64le 
        ^zlib@1.2.11%gcc@4.9.3+optimize+pic+shared arch=linux-rhel7-ppc64le 
```

### Actual Result

```
# herbein1 at sierra4362 in /usr/workspace/wsb/herbein1/spack_blueos_ppc/var/spack/repos on git:fix-lmod-separator ✖︎ [13:18:44]
→ spack spec hwloc +cuda
Input spec
--------------------------------
hwloc+cuda

Concretized
--------------------------------
==> Error: Class constructor failed for package 'cuda'.

Caused by:
TypeError: expected string or buffer
  File "/usr/workspace/wsb/herbein1/spack_blueos_ppc/lib/spack/spack/repo.py", line 833, in get
    return package_class(spec)
  File "/usr/workspace/wsb/herbein1/spack_blueos_ppc/lib/spack/spack/package.py", line 672, in __init__
    f = fs.for_package_version(self, self.version)
  File "/usr/workspace/wsb/herbein1/spack_blueos_ppc/lib/spack/spack/fetch_strategy.py", line 977, in for_package_version
    url = pkg.url_for_version(version)
  File "/usr/workspace/wsb/herbein1/spack_blueos_ppc/lib/spack/spack/package.py", line 794, in url_for_version
    default_url, self.url_version(version))
  File "/usr/workspace/wsb/herbein1/spack_blueos_ppc/lib/spack/spack/url.py", line 845, in substitute_version
    ver,  vs, vl, voffs) = substitution_offsets(path)
  File "/usr/workspace/wsb/herbein1/spack_blueos_ppc/lib/spack/spack/url.py", line 789, in substitution_offsets
    ver,  vs, vl, vi, vregex = parse_version_offset(path)
  File "/usr/workspace/wsb/herbein1/spack_blueos_ppc/lib/spack/spack/url.py", line 408, in parse_version_offset
    path, ext, suffix = split_url_extension(path)
  File "/usr/workspace/wsb/herbein1/spack_blueos_ppc/lib/spack/spack/url.py", line 346, in split_url_extension
    match = re.search(r'(.*(?:sourceforge\.net|sf\.net)/.*)(/download)$', path)
  File "/usr/tce/packages/python/python-2.7.14/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
```

### Steps to reproduce the issue

```console
# Add the config stuff pasted below into your packages.yaml
$ spack spec hwloc +cuda
...
```

### Information on your system

This includes:

 1. Sierra @ LLNL: RHEL7, ppc64le.  This is why I cannot use the spack provided CUDA, which only installs the x86 version.
 2. `packages.yaml`:
```
packages:
  all:
    compiler: [gcc@6.4.0]
  cuda:
    buildable: False
    paths:
      cuda @9.2.64 target=ppc64le : /usr/tce/packages/cuda/cuda-9.2.64
```

**Comment by adamjstewart** [comment] 2018-07-18 20:57
Duplicate of #8733.

**Closed by adamjstewart** 2018-07-18 20:57 UTC
