### ISSUE TITLE
Concretizer Bug

### ISSUE THREAD

**Issue by citibeth** [spack/spack#16031] opened 2020-04-13 22:44 UTC
Packages that `depedns_on` both `hdf5` and `netcdf-c` won't concretize.

### Steps to reproduce the issue

1. Clone the latest Spack.

2. Create the `mypackage/package.py`:

```
from spack import *


class Mypackage(CMakePackage):
    """Sample Package"""

    homepage = "https://qgis.org"
    url      = "https://qgis.org/downloads/qgis-3.8.1.tar.bz2"

    maintainers = ['adamjstewart', 'Sinan81']

    version('3.12.1', sha256='a7dc7af768b8960c08ce72a06c1f4ca4664f4197ce29c7fe238429e48b2881a8')

    # the below dependencies are shown in cmake config
    depends_on('hdf5')
    depends_on('netcdf-c')
```

Do: `spack spec mypackage`.

### Error Message

```
$ spack spec mypackage
Input spec
--------------------------------
mypackage

Concretized
--------------------------------
==> Warning: clang@11.0.3-apple cannot build optimized binaries for "broadwell". Using best target possible: "x86_64"
==> Error: An unsatisfiable variant constraint has been detected for spec:

    hdf5@1.10.6%clang@11.0.3-apple~cxx~debug~fortran~hl+mpi+pic+shared~szip~threadsafe arch=darwin-catalina-x86_64
        ^mpi
        ^zlib@1.2.11%clang@11.0.3-apple+optimize+pic+shared arch=darwin-catalina-x86_64


while trying to concretize the partial spec:

    netcdf-c@4.7.3%clang@11.0.3-apple~dap~hdf4+mpi~parallel-netcdf+pic+shared arch=darwin-catalina-x86_64
        ^m4@1.4.18%clang@11.0.3-apple+sigsegv arch=darwin-catalina-x86_64
            ^libsigsegv
        ^mpi
        ^zlib@1.2.11%clang@11.0.3-apple+optimize+pic+shared arch=darwin-catalina-x86_64


netcdf-c requires hdf5 variant +hl, but spec asked for ~hl
```

**Comment by adamjstewart** [comment] 2020-04-13 23:31
@skosukhin will #15950 fix this or make it worse?

**Comment by alalazo** [comment] 2020-04-14 09:09
I think this is another manifestation of the issues in #267 and #303 - so I added the duplicate label. The root issue is that the current concretizer is greedy and:
1. `hdf5` default to `~hl`
2. `netcdf-c` requires `+hl`

The new concretizer should solve all issues like this one, but for the time being a workaround is either to depend only on `netcdf-c` or to specify explicitly the dependency on `hdf5+hl`.

**Comment by skosukhin** [comment] 2020-04-15 10:20
@adamjstewart actually, #15950 fixes this

**Comment by citibeth** [comment] 2020-04-15 10:22
Sorry, it does not.

**Comment by skosukhin** [comment] 2020-04-15 10:30
```python
from spack import *


class Banana(AutotoolsPackage):
    """Just a banana."""

    homepage = "http://banana.net"
    url = "http://banana.net/banana-1.0.0.tar.gz"

    version('1.0.0', sha256='c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1')

    depends_on('hdf5')
    depends_on('netcdf-c')
```

```console
$ git checkout develop
$ spack spec banana
Input spec
--------------------------------
banana

Concretized
--------------------------------
==> Error: An unsatisfiable variant constraint has been detected for spec:

    hdf5@1.10.6%gcc@6.3.0~cxx~debug~fortran~hl+mpi+pic+shared+szip+threadsafe arch=linux-debian9-haswell


while trying to concretize the partial spec:

    netcdf-c@4.7.3%gcc@6.3.0~dap~hdf4+mpi~parallel-netcdf+pic+shared arch=linux-debian9-haswell
        ^mpi


netcdf-c requires hdf5 variant +hl, but spec asked for ~hl
$ git checkout netcdf_fix
$ spack spec banana
Input spec
--------------------------------
banana

Concretized
--------------------------------
banana@1.0.0%gcc@6.3.0 arch=linux-debian9-haswell
    ^hdf5@1.10.6%gcc@6.3.0~cxx~debug~fortran+hl+mpi+pic+shared+szip+threadsafe arch=linux-debian9-haswell
        ^libaec@1.0.2%gcc@6.3.0 build_type=RelWithDebInfo arch=linux-debian9-haswell
            ^cmake@3.17.0%gcc@6.3.0~doc~ncurses~openssl+ownlibs~qt arch=linux-debian9-haswell
        ^openmpi@3.1.5%gcc@6.3.0~cuda+cxx_exceptions fabrics=none ~java~legacylaunchers~memchecker~pmi schedulers=none ~sqlite3~thread_multiple+vt arch=linux-debian9-haswell
            ^hwloc@1.11.11%gcc@6.3.0~cairo~cuda~gl+libxml2~nvml+pci+shared arch=linux-debian9-haswell
                ^libpciaccess@0.13.5%gcc@6.3.0 arch=linux-debian9-haswell
                    ^libtool@2.4.6%gcc@6.3.0 arch=linux-debian9-haswell
                        ^m4@1.4.18%gcc@6.3.0 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 ~sigsegv arch=linux-debian9-haswell
                    ^pkgconf@1.6.3%gcc@6.3.0 arch=linux-debian9-haswell
                    ^util-macros@1.19.1%gcc@6.3.0 arch=linux-debian9-haswell
                ^libxml2@2.9.9%gcc@6.3.0~python arch=linux-debian9-haswell
                    ^libiconv@1.16%gcc@6.3.0 arch=linux-debian9-haswell
                    ^xz@5.2.5%gcc@6.3.0 arch=linux-debian9-haswell
                    ^zlib@1.2.11%gcc@6.3.0+optimize+pic+shared arch=linux-debian9-haswell
                ^numactl@2.0.12%gcc@6.3.0 arch=linux-debian9-haswell
                    ^autoconf@2.69%gcc@6.3.0 arch=linux-debian9-haswell
                        ^perl@5.30.1%gcc@6.3.0+cpanm+shared+threads arch=linux-debian9-haswell
                            ^gdbm@1.18.1%gcc@6.3.0 arch=linux-debian9-haswell
                                ^readline@8.0%gcc@6.3.0 arch=linux-debian9-haswell
                                    ^ncurses@6.2%gcc@6.3.0~symlinks+termlib arch=linux-debian9-haswell
                    ^automake@1.16.2%gcc@6.3.0 arch=linux-debian9-haswell
    ^netcdf-c@4.7.3%gcc@6.3.0~dap~hdf4+mpi~parallel-netcdf+pic+shared arch=linux-debian9-haswell
```

**Comment by alalazo** [comment] 2020-11-02 22:46
Duplicate of #1781

**Closed by alalazo** 2020-11-02 22:46 UTC
Labels: bug, concretization, duplicate
