### ISSUE TITLE
Spack installs x86 jdk on non-x86 systems

### ISSUE THREAD

**Issue by mcneish1** [spack/spack#7336] opened 2018-02-23 19:06 UTC
Summary

### Expected Result

A working jdk

### Actual Result

`/[...]/blueos_3_ppc64le_ib/[...]/bin/javac: cannot execute binary file`

```
$ file /[...]/blueos_3_ppc64le_ib/[...]/bin/javac
/[...]/bin/javac: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (use
s shared libs), for GNU/Linux 2.6.9, BuildID[sha1]=fa472824c41b020e4e35331a17ee214b1fdb3b51, not stripped
```

### Steps to reproduce the issue

`spack install jdk`

### Information on your system

ppc64le

---

I'm going to try to add an openjdk package to spack some time next week.

Is there some way to make versions depend on the system architecture? It seems like there could be other binaries spack manages, this could affect them too.

**Comment by alalazo** [comment] 2018-02-26 08:18
> I'm going to try to add an openjdk package to spack some time next week.

Don't know if it could help, but there's a [tentative `openjdk` package](https://github.com/spack/spack/pull/2622) that is up for grabs.

**Comment by mcneish1** [comment] 2018-02-26 22:37
Thanks, that got me 90% of the way there.

This recipe worked with gcc@4.9.3 on ppc64le, haven't tried any other compilers or platforms:
```
from spack import *

class Openjdk(Package):
    """Open-source JDK"""

    homepage = "http://openjdk.java.net"

    version('9.0', hg='http://hg.openjdk.java.net/jdk9/jdk9')

    depends_on('libxt')
    depends_on('libxtst')
    depends_on('libxrender')
    depends_on('libxi')
    depends_on('cups')
    depends_on('alsa-lib')

    provides('java@9', when='@9.0')

    parallel=False

    def install(self, spec, prefix):
        Executable('chmod')('u+x', 'get_source.sh')
        Executable('./get_source.sh')()
        Executable('chmod')('u+x', 'configure')
        configure('--prefix=%s' % prefix)
        make('all')
        make('install')
```

OpenJDK 8 fails with "configure: error: cannot guess build type; you must specify one" (would probably be fine if this was x86/x64), and OpenJDK 7 fails with "chmod: cannot access 'configure': No such file or directory" (the installation directions probably changed in the meantime), so I didn't include them as versions.

`parallel=False` because the Makefile requires `make JOBS=N` instead of `make -jN`. Make appears to parallelize the build by itself.

I required `ulimit -u` >2048 to complete the build, otherwise I got a lot of
```
     790     [0.172s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 4096k, guardsize: 0k, detached.
  >> 791     Error occurred during initialization of VM
```
however `ulimit -u` == 36864 was enough

**Comment by mcneish1** [comment] 2018-02-26 22:59
Also:
```
    def setup_environment(self, spack_env, run_env):
        run_env.set('JAVA_HOME', self.spec.prefix)

    def setup_dependent_environment(self, spack_env, run_env, dependent_spec):
        spack_env.set('JAVA_HOME', self.spec.prefix)
```

**Comment by luigi-calori** [comment] 2018-02-27 14:26
I has similar issue trying spack install java on a MacOSX
The point is that the binary install URL is hardcoded for Linux, while OSX install requre another url
and likely a sligtly different install script.
I would  be interested in having current jdk package support also OSX

**Comment by adamjstewart** [comment] 2018-02-27 20:59
See #2009 for more discussion on how to handle downloads that are specific to a certain operating system/architecture. Ideally we would add an `arch` argument to the `version()` directive.

**Comment by mcneish1** [comment] 2018-02-28 01:01
Problems so far:
* Bootstrapping - no progress since #2622, I didn't look into it
* Arch selection - to be added to the current jdk package
* OSX install directory patching
* Ant has [all these dependencies](http://ant.apache.org/manual/install.html#librarydependencies), which are provided by Oracle's JDK but not by OpenJDK. This means that ant can't build without a custom JAVA_HOME or manual user intervention in downloading all those jars. I imagine other packages have similar required files OpenJDK doesn't provide, this would break them too

---

That's about as far as I want to take this for now

**Comment by alalazo** [comment] 2020-08-17 13:17
Duplicate of #11206

**Comment by alalazo** [comment] 2020-08-17 13:20
Closing since this is a specific case for #11206. It will be solved as soon as we permit different urls for the same version of a package. Feel free to reopen if you think this specific java issue needs to be discussed further.

**Closed by alalazo** 2020-08-17 13:20 UTC
Labels: build-error
