### ISSUE TITLE
Installation issue: casacore

### ISSUE THREAD

**Issue by cnwangfeng** [spack/spack#15143] opened 2020-02-21 04:32 UTC
### Steps to reproduce the issue

```console
 spack install casacore%gcc@5.5.0 fftw=True hdf5=True openmp=True python=True sofa=True

... # and the relevant part of the error message
==> Installing casacore
==> Searching for binary cache of casacore
==> Warning: No Spack mirrors are currently configured
==> No binary for casacore found: installing from source
==> Using cached archive: /mnt/storage-ssd/spack/var/spack/cache/_source-cache/archive/58/58eccc875053b2c6fe44fe53b6463030ef169597ec29926936f18d27b5087d63.tar.gz
==> Staging archive: /tmp/cnlab/spack-stage/spack-stage-casacore-2.4.1-r6ehn2codnmamuv5v5xigecgcypzcu2x/v2.4.1.tar.gz
==> Created stage in /tmp/cnlab/spack-stage/spack-stage-casacore-2.4.1-r6ehn2codnmamuv5v5xigecgcypzcu2x
==> No patches needed for casacore
==> Building casacore [CMakePackage]
==> Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    'cmake' '/tmp/cnlab/spack-stage/spack-stage-casacore-2.4.1-r6ehn2codnmamuv5v5xigecgcypzcu2x/spack-src' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:PATH=/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/casacore-2.4.1-r6ehn2codnmamuv5v5xigecgcypzcu2x' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=FALSE' '-DCMAKE_INSTALL_RPATH:STRING=/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/casacore-2.4.1-r6ehn2codnmamuv5v5xigecgcypzcu2x/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/casacore-2.4.1-r6ehn2codnmamuv5v5xigecgcypzcu2x/lib64;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/boost-1.70.0-imzdvsfohn2mafvythjzywvtnrr53xeo/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/bzip2-1.0.8-pflbd3h5qwkvntpmpyoriw74aio7wqnz/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/python-3.7.4-67nm4d22xxsbkmbhejq4d7nsxvqg2joq/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/expat-2.2.9-fjt6xq4t3fs65ufu6hrp3vdurilguuli/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/libbsd-0.9.1-iigy4ueoywicsbjnannpbblfuwchjpdw/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/gdbm-1.18.1-g7s2nhwoohyvxkvltanf72dad4szn4wu/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/readline-8.0-cwa6eefd5xwarsjz4cprltwj7w3gr4h5/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/ncurses-6.1-rqukpnudnmakm6oan2ie7g635je3nj6s/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/gettext-0.20.1-7tmcjejysx3fsfd3i5do6obi43bblnyb/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/libxml2-2.9.9-ojizfxcxeqdbkevrtw6hz2fw33746acg/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/libiconv-1.16-4ilhzg5r4wn2b3nu6n27bleulwttuwh5/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/xz-5.2.4-owbvohaxnjqeybftlvntgr4fnxxn63wl/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/zlib-1.2.11-cg3ibqmpmiyf57vjuxw55heayz372tnc/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/libffi-3.2.1-rlyjjf7jim6qwmrf5otzri5vqxtsji7h/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/openssl-1.1.1d-3bsjg64jhkspgoifpnyjumdhn7a4grjh/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/sqlite-3.30.1-23e5o2w4xor4r5fdhhf6ezwfgqodz53d/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/cfitsio-3.450-25dwwh6h76bovjujimtmojjfoyf6y2ej/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/curl-7.63.0-ovcvacfdcwlr27cq2kpz6vwrcc2mpgs5/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/fftw-3.3.8-ukkhstpfe6bpg7wqx2n22ubroyx62u6k/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/hdf5-1.10.5-h66xlvc4zqfvntim4umusdae7knoj42s/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/openmpi-3.1.4-5ykaajekv4qd6ke5oo4a2t64a2yj3d73/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/hwloc-1.11.11-xvthrn3gba5upcr6yurlrencrmxqwfoy/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/libpciaccess-0.13.5-6oxvvekphj6wl7itzlowv7bxspmun3ad/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/numactl-2.0.12-lycndcyjdz5yh7el3ixsgjfipyuftsnf/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/openblas-0.3.7-ajrahnszw3cur3ulcsnwcdlfbkjt4325/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/py-numpy-1.17.3-txvddcmykxcb6c57f55g4cosylhxygrf/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/sofa-c-20180130-7hfvzztk7b2nn4vnmp65tlq6mbhr7nkl/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/wcslib-6.4-7zyaymox2mb6orhdaji4ph6jz7iyevdv/lib;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/libffi-3.2.1-rlyjjf7jim6qwmrf5otzri5vqxtsji7h/lib64' '-DCMAKE_PREFIX_PATH:STRING=/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/cfitsio-3.450-25dwwh6h76bovjujimtmojjfoyf6y2ej;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/flex-2.6.4-u4xdgz5zpqlp3h265fsbi5rc5cfmzfdj;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/cmake-3.15.4-uxb7qpvmixf675rl3jndnaslfbjwofxt;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/hdf5-1.10.5-h66xlvc4zqfvntim4umusdae7knoj42s;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/python-3.7.4-67nm4d22xxsbkmbhejq4d7nsxvqg2joq;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/fftw-3.3.8-ukkhstpfe6bpg7wqx2n22ubroyx62u6k;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/py-numpy-1.17.3-txvddcmykxcb6c57f55g4cosylhxygrf;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/wcslib-6.4-7zyaymox2mb6orhdaji4ph6jz7iyevdv;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/bison-3.4.2-cxzrh6vv7cvl5qwz2v3cm56tfqa7hfrr;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/sofa-c-20180130-7hfvzztk7b2nn4vnmp65tlq6mbhr7nkl;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/boost-1.70.0-imzdvsfohn2mafvythjzywvtnrr53xeo;/mnt/storage-ssd/spack/opt/spack/linux-centos7-haswell/gcc-5.5.0/openblas-0.3.7-ajrahnszw3cur3ulcsnwcdlfbkjt4325' '-DENABLE_SHARED=YES' '-DUSE_OPENMP=YES' '-DUSE_HDF5=YES' '-DUSE_FFTW3=YES' '-DBUILD_PYTHON=NO' '-DBUILD_PYTHON3=YES'
1 error found in build log:
     82    -- Looking for python3 specific environment...
     83    -- Found PythonInterp: /mnt/storage-ssd/spack/opt/spack/linux-centos
           7-haswell/gcc-5.5.0/python-3.7.4-67nm4d22xxsbkmbhejq4d7nsxvqg2joq/bi
           n/python (found version "3.7.4")
     84    -- Found PythonLibs: /mnt/storage-ssd/spack/opt/spack/linux-centos7-
           haswell/gcc-5.5.0/python-3.7.4-67nm4d22xxsbkmbhejq4d7nsxvqg2joq/lib/
           libpython3.7m.so (found version "3.7.4")
     85    -- Found Boost 1.70.0 at /mnt/storage-ssd/spack/opt/spack/linux-cent
           os7-haswell/gcc-5.5.0/boost-1.70.0-imzdvsfohn2mafvythjzywvtnrr53xeo/
           lib/cmake/Boost-1.70.0
     86    --   Requested configuration: QUIET REQUIRED COMPONENTS python-py37
     87    -- Found boost_headers 1.70.0 at /mnt/storage-ssd/spack/opt/spack/li
           nux-centos7-haswell/gcc-5.5.0/boost-1.70.0-imzdvsfohn2mafvythjzywvtn
           rr53xeo/lib/cmake/boost_headers-1.70.0
  >> 88    CMake Error at /mnt/storage-ssd/spack/opt/spack/linux-centos7-haswel
           l/gcc-5.5.0/boost-1.70.0-imzdvsfohn2mafvythjzywvtnrr53xeo/lib/cmake/
           Boost-1.70.0/BoostConfig.cmake:95 (find_package):
     89      Could not find a package configuration file provided by "boost_pyt
           hon-py37"
     90      (requested version 1.70.0) with any of the following names:
     91
     92        boost_python-py37Config.cmake
     93        boost_python-py37-config.cmake
     94
See build log for details:
  /tmp/cnlab/spack-stage/spack-stage-casacore-2.4.1-r6ehn2codnmamuv5v5xigecgcypzcu2x/spack-build-out.txt

```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux login-1 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by adamjstewart** [comment] 2020-02-21 18:38
@mpokorny can you take a look at this? Also pinging the developer @casacore

**Comment by mpokorny** [comment] 2020-02-21 20:25
This looks like an attempt to build casacore with an older version of spack, which I can tell because the `+sofa` option has been removed in the latest casacore package. The latest package also supports builds of newer casacore versions (up to 3.2.0). @cnwangfeng, if you are able to use newer versions of casacore, you might try updating spack, and re-try another casacore installation. Aside from that, I can say that just a few moments ago I built casacore v3.2.0 with the variants you've selected under a relatively recent spack, and it completed successfully. If you need the older version of casacore, please let me know and I'll dig further.

**Comment by mpokorny** [comment] 2020-02-21 22:25
I suspect that the problem is in a CMake file in casacore v2.4.1 located in the `python3` source sub-directory. I'm not going to fix that (it is fixed in some later casacore version). If you must use casacore v2.4.1 the build will work for Python 2.7, as follows `spack install casacore@2.4.1+fftw+hdf5+openmp+python ^python@2.7.16 ^py-numpy@1.16.6`

**Comment by mpokorny** [comment] 2020-02-21 22:45
@adamjstewart , perhaps it's best to prohibit building casacore 2.4.1 (and perhaps other versions) with Python 3 in spack. Would that be OK as far as spack is concerned?

**Comment by adamjstewart** [comment] 2020-02-21 23:39
Yeah, we could add a conflict like we do for compilers.

**Comment by cnwangfeng** [comment] 2020-02-24 06:48
Thanks a lot for your help. I will try to compile with casacore 3.x. 
BTW, I am using the latest version of spack and python3.

**Comment by cnwangfeng** [comment] 2020-02-24 07:02
Hi @mpokorny , 

I still met the error.  The command is: 
spack install casacore@3.2.0%gcc@8.3.0 fftw=True hdf5=True openmp=True python=True

The error messages are listed as follows. 
1 error found in build log:
     86    -- Found Boost 1.70.0 at /mnt/storage-ssd/spack/opt/spack/linux-cent
           os7-haswell/gcc-8.3.0/boost-1.70.0-5jnojlp5or6h5wjbvwbvt2axxmlsegik/
           lib/cmake/Boost-1.70.0
     87    --   Requested configuration: QUIET REQUIRED
     88    -- Found boost_headers 1.70.0 at /mnt/storage-ssd/spack/opt/spack/li
           nux-centos7-haswell/gcc-8.3.0/boost-1.70.0-5jnojlp5or6h5wjbvwbvt2axx
           mlsegik/lib/cmake/boost_headers-1.70.0
     89    -- Found Boost: /mnt/storage-ssd/spack/opt/spack/linux-centos7-haswe
           ll/gcc-8.3.0/boost-1.70.0-5jnojlp5or6h5wjbvwbvt2axxmlsegik/lib/cmake
           /Boost-1.70.0/BoostConfig.cmake (found version "1.70.0")
     90    -- Found Boost 1.70.0 at /mnt/storage-ssd/spack/opt/spack/linux-cent
           os7-haswell/gcc-8.3.0/boost-1.70.0-5jnojlp5or6h5wjbvwbvt2axxmlsegik/
           lib/cmake/Boost-1.70.0
     91    --   Requested configuration: QUIET REQUIRED COMPONENTS python37
  >> 92    CMake Error at /mnt/storage-ssd/spack/opt/spack/linux-centos7-haswel
           l/gcc-8.3.0/boost-1.70.0-5jnojlp5or6h5wjbvwbvt2axxmlsegik/lib/cmake/
           Boost-1.70.0/BoostConfig.cmake:95 (find_package):
     93      Could not find a package configuration file provided by "boost_pyt
           hon37"
     94      (requested version 1.70.0) with any of the following names:
     95
     96        boost_python37Config.cmake
     97        boost_python37-config.cmake
     98
See build log for details:
  /tmp/cnlab/spack-stage/spack-stage-casacore-3.2.0-3ouxcl7ghacd2zkhstk3ccxzroofrfhv/spack-build-out.txt

My point is the reason was caused by the Python3 and boost_python.

**Comment by mpokorny** [comment] 2020-02-24 17:45
@cnwangfeng , I'm unable to reproduce your error. Starting from a new, empty spack environment, using the install command that you quoted, my build completed successfully (on an RHEL7 system). This is the first time that I'm attempting to help with someone else's build issues of casacore in spack, and I'm not certain of the best and/or standard way to proceed, but I'll take a stab at it. Are you able to attach your complete build log, and also maybe a copy of all the output from the build command?

**Comment by cnwangfeng** [comment] 2020-02-26 08:11
[cnlab@login-1 spack]$ git pull
remote: Enumerating objects: 242, done.
remote: Counting objects: 100% (242/242), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 455 (delta 237), reused 242 (delta 237), pack-reused 213
Receiving objects: 100% (455/455), 250.90 KiB | 230.00 KiB/s, done.
Resolving deltas: 100% (248/248), completed with 125 local objects.
From https://github.com/spack/spack
   629c69d..ae87828  develop    -> origin/develop
   d8efd55..9f816a7  features/spack-test-libxml2 -> origin/features/spack-test-libxml2
   f9658e8..58d3b57  master     -> origin/master
   b6fe919..62f1d72  packages/gsl-external-cblas -> origin/packages/gsl-external-cblas
   629c69d..97d46dc  releases/v0.14 -> origin/releases/v0.14
 * [new tag]         v0.14.0    -> v0.14.0
Already up-to-date.
[cnlab@login-1 spack]$ date
Wed Feb 26 16:09:40 CST 2020
[cnlab@login-1 spack]$

**Comment by cnwangfeng** [comment] 2020-02-26 08:47
I have created a package.yaml file because I have installed sulrm manually. 

[cnlab@login-1 spack]$ pwd
/mnt/storage-ssd/spack/etc/spack
[cnlab@login-1 spack]$ more packages.yaml
packages:
  all:
    compiler:
    - gcc
    providers:
      blas:
      - openblas
      lapack:
      - openblas
      mpi:
      - openmpi
      scalapack:
      - netlib-scalapack
  scons:
    buildable: false
    paths:
      scons@3.1.2: /usr
  slurm:
      - intel-mkl
    buildable: false
    paths:
      slurm@19.05.5: /usr
  subversion:
    buildable: false
    paths:
      subversion@1.7.14: /usr

**Comment by cnwangfeng** [comment] 2020-02-26 10:20
It's NICE. It seemed compiling is success via such command:
spack install casacore@3.2.0+fftw+hdf5+openmp+python ^python@3.7.4 > buildlog

**Comment by cnwangfeng** [comment] 2020-02-26 15:47
Hi @mpokorny ,

I am sure that the casacore can be compiled without any problem while using pure spack + gcc4.8.5 (default compilers of Centos7). I will install gcc@7.3.0 and further test the casacore compiling.  I will report yo as soon as possible. 

I have another minor question.  In this time, I used lmod instead of environment-modules. I have added a modules.yaml and enabled lmod. I also refreshed and recreated the lmod packages tree. 

[wangfeng@login-1 ~]$ module purge
[wangfeng@login-1 ~]$
[wangfeng@login-1 ~]$ module av

-------------------------------------------------- /mnt/storage-ssd/spack/share/spack/modules/linux-centos7-haswell ---------------------------------------------------
   autoconf-2.69-gcc-4.8.5-zfhncua      gmp-6.1.2-gcc-4.8.5-zn55wh7              lmod-8.3-gcc-4.8.5-fhwe3tt                     pcre2-10.31-gcc-4.8.5-cuz5d7z
   automake-1.16.1-gcc-4.8.5-4iqekwd    isl-0.18-gcc-4.8.5-igs522o               lua-5.3.5-gcc-4.8.5-iis6obm                    perl-5.30.1-gcc-4.8.5-37r7jd2
   bzip2-1.0.8-gcc-4.8.5-ersrl36        libbsd-0.10.0-gcc-4.8.5-zdpj4mi          lua-luafilesystem-1_7_0_2-gcc-4.8.5-s4jjhpe    pkgconf-1.6.3-gcc-4.8.5-2qrpgpd
   curl-7.68.0-gcc-4.8.5-xrxn4ke        libiconv-1.16-gcc-4.8.5-qazxaa4          lua-luaposix-33.4.0-gcc-4.8.5-ii5n3vc          readline-8.0-gcc-4.8.5-3sg7t2w
   diffutils-3.7-gcc-4.8.5-jknorwe      libidn2-2.1.1a-gcc-4.8.5-tb437xf         m4-1.4.18-gcc-4.8.5-7x2wh2t                    tar-1.32-gcc-4.8.5-v3iynan
   expat-2.2.9-gcc-4.8.5-kbptkkm        libsigsegv-2.12-gcc-4.8.5-ymriiur        mpc-1.1.0-gcc-4.8.5-eogmmao                    tcl-8.6.8-gcc-4.8.5-nirnlnq
   gdbm-1.18.1-gcc-4.8.5-ts26f2l        libtool-2.4.6-gcc-4.8.5-fzl2npj          mpfr-3.1.6-gcc-4.8.5-nsgsjfy                   unzip-6.0-gcc-4.8.5-bp5mi5x
   gettext-0.20.1-gcc-4.8.5-5trbflx     libunistring-0.9.10-gcc-4.8.5-o2r2guv    ncurses-6.1-gcc-4.8.5-quxyulr                  xz-5.2.4-gcc-4.8.5-lwgmb5t
   git-2.25.0-gcc-4.8.5-wkaj7ii         libxml2-2.9.9-gcc-4.8.5-52ybz3p          openssl-1.1.1d-gcc-4.8.5-dhfrfou               zlib-1.2.11-gcc-4.8.5-pkmj6e7

---------------------------------------------------------------- /usr/share/lmod/lmod/modulefiles/Core ----------------------------------------------------------------
   lmod    settarg

Use "module spider" to find all possible modules and extensions.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".


[wangfeng@login-1 ~]$ spack load autoconf@2.69
[wangfeng@login-1 ~]$ module list
No modules loaded
[wangfeng@login-1 ~]$ module load autoconf-2.69-gcc-4.8.5-zfhncua
[wangfeng@login-1 ~]$ module list

Currently Loaded Modules:
  1) autoconf-2.69-gcc-4.8.5-zfhncua

[wangfeng@login-1 ~]$

**Comment by cnwangfeng** [comment] 2020-02-27 00:25
[cnlab@login-1 spack]$ module load gcc-7.3.0-gcc-4.8.5-7ovecya
[cnlab@login-1 spack]$ gcc
gcc: fatal error: no input files
compilation terminated.
[cnlab@login-1 spack]$ gcc --version
gcc (Spack GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
[cnlab@login-1 spack]$ spack install casacore@3.2.0+fftw+hdf5+openmp+python ^python@3.7.4 > buildlog
==> Warning: Missing a source id for slurm@19.05.5
curl: (28) Resolving timed out after 10519 milliseconds
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> Error: FetchError: All fetchers failed for spack-stage-python-3.7.4-7axba7ismaurzcle6c5ku2ugc2w7jbiy
/mnt/storage-ssd/spack/lib/spack/spack/package.py:1127, in do_fetch:
       1124                raise FetchError("Will not fetch %s" %
       1125                                 self.spec.format('{name}{@version}'), ck_msg)
       1126
  >>   1127        self.stage.create()
       1128        self.stage.fetch(mirror_only)
       1129        self._fetch_time = time.time() - start_time
       1130
==> Error: Failed to install python due to ChildError: FetchError: All fetchers failed for spack-stage-python-3.7.4-7axba7ismaurzcle6c5ku2ugc2w7jbiy
/mnt/storage-ssd/spack/lib/spack/spack/package.py:1127, in do_fetch:
       1124                raise FetchError("Will not fetch %s" %
       1125                                 self.spec.format('{name}{@version}'), ck_msg)
       1126
  >>   1127        self.stage.create()
       1128        self.stage.fetch(mirror_only)
       1129        self._fetch_time = time.time() - start_time
       1130
Traceback (most recent call last):
  File "/mnt/storage-ssd/spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/mnt/storage-ssd/spack/lib/spack/spack/installer.py", line 984, in build_process
    pkg.do_patch()
  File "/mnt/storage-ssd/spack/lib/spack/spack/package.py", line 1167, in do_patch
    self.do_stage()
  File "/mnt/storage-ssd/spack/lib/spack/spack/package.py", line 1152, in do_stage
    self.do_fetch(mirror_only)
  File "/mnt/storage-ssd/spack/lib/spack/spack/package.py", line 1128, in do_fetch
    self.stage.fetch(mirror_only)
  File "/mnt/storage-ssd/spack/lib/spack/spack/util/pattern.py", line 68, in getter
    getattr(item, self.name)(*args, **kwargs)
  File "/mnt/storage-ssd/spack/lib/spack/spack/stage.py", line 476, in fetch
    raise fs.FetchError(err_msg, None)
FetchError: All fetchers failed for spack-stage-python-3.7.4-7axba7ismaurzcle6c5ku2ugc2w7jbiy
==> Warning: Skipping build of py-cython since python failed
==> Warning: Skipping build of py-numpy since py-cython failed
==> Warning: Skipping build of casacore since py-numpy failed
==> Warning: Skipping build of boost since python failed
==> Warning: Skipping build of py-setuptools since python failed
==> Error: Installation of casacore failed.  Review log for details
[cnlab@login-1 spack]$

**Comment by cnwangfeng** [comment] 2020-02-27 01:28
Hi @mpokorny ,

After the installation of gcc@7.3.0, I have tried to install casacaore again. 

spack install casacore@3.2.0%gcc@8.3.0 fftw=True hdf5=True openmp=True python=True

It's OK. Thanks again.

**Comment by mpokorny** [comment] 2020-02-28 20:56
Hi @cnwangfeng ,
Sorry about the silence on my part. I'm glad that you've gotten the casacore package installed. As for the spack and lmod related questions, I'm not your best resource for answering those, you ought to consider asking those questions elsewhere -- perhaps the slack group?
I think this issue can be closed. What do you think @cnwangfeng ?

**Comment by alalazo** [comment] 2020-02-29 13:27
@cnwangfeng Closing after reading the last few comments. Feel free to reopen if you think there's something still to be addressed.

**Closed by alalazo** 2020-02-29 13:27 UTC
Labels: build-error
