### ISSUE TITLE
compiler version in spec

### ISSUE THREAD

**Issue by mileschen360** [spack/spack#8735] opened 2018-07-17 21:48 UTC
This is a general question that confuse me:

I have only one compiler, gcc 4.4.6 installed,  I would like to install a package, let's call it P

Why `spack install P%gcc@4.4` and `spack install P%gcc@4.4.6` install the same package twice at two different locations, using the same compiler?

What is the purpose of this behavior? I expect spack automatically complete the compiler version if it is unique or report if it is ambiguous.

**Comment by healther** [comment] 2018-07-18 04:32
I'm surprised that it even works at all. In my experience (albeit only with versions of the package, not the once on the compiler) `spack` happily tries to install a `python@3` and then fails with the error that it doesn't know any `python@3`.

But I'm running rather old versions of `spack` atm, so this might already be fixed in the current HEAD

**Comment by alalazo** [comment] 2018-10-08 07:33
Confirmed the existence of this bug in the fairly recent commit 75fe3a5436eb46498d0adb4791ce9284ee680162. Added it to the list of the most wanted because I think it needs to be fixed rather sooner than later. @tgamblin @scheibelp

**Closed** 2020-02-20 20:20 UTC
Labels: bug, compilers, specs
