### ISSUE TITLE
Spack finds wrong arch on Cori at NERSC

### ISSUE THREAD

**Issue by jhux2** [spack/spack#11641] opened 2019-06-05 23:42 UTC
I am attempting to use spack VOTD (SHA f4e77867) to install various TPLs required by the low Mach CFD code Nalu-Wind on the Cori supercomputer @ NERSC.

### Steps to reproduce the issue
```
> git clone https://github.com/LLNL/spack.git
> source ./spack/share/spack/setup-env.sh
> spack arch
cray-cnl6-haswell
> spack install cmake
```
### Error Message
```
==> Error: No compilers found for operating system cnl6 and target haswell.
If previous installations have succeeded, the operating system may have been updated.
Compilers are defined for the following operating systems and targets:
	sles12-x86_64
	cnl9-any
Run 'spack compiler find' to add compilers.
```

If I checkout out a release version of spack, the command works as expected:
```
> cd spack
> git checkout --track origin/releases/v0.12
Branch releases/v0.12 set up to track remote branch releases/v0.12 from origin.
Switched to a new branch 'releases/v0.12'
> source ./spack/share/spack/setup-env.sh
> spack -v arch
cray-cnl9-haswell
> spack install cmake
==> ncurses@6.0 : externally installed in /usr
==> ncurses@6.0 : generating module file
==> ncurses@6.0 : registering into DB
==> openssl@1.1.0 : has external module in openssl/1.1.0a
==> openssl@1.1.0 : is actually installed in /global/common/cori/software/openssl/1.1.0a/hsw
==> openssl@1.1.0 : generating module file
==> openssl@1.1.0 : registering into DB
==> Installing cmake
==> Searching for binary cache of cmake
==> Warning: No Spack mirrors are currently configured
==> No binary for cmake found: installing from source
==> Fetching https://cmake.org/files/v3.12/cmake-3.12.3.tar.gz
######################################################################## 100.0%
[snip]
```
### Information on your system

Cray XC40 (Cori @ NERSC)
default modules loaded:
```
  1) modules/3.2.10.6                                  9) pmi/5.0.14                                       17) atp/2.1.3
  2) nsg/1.2.0                                        10) dmapp/7.1.1-6.0.7.1_5.45__g5a674e0.ari           18) PrgEnv-intel/6.0.4
  3) intel/18.0.1.163                                 11) gni-headers/5.0.12.0-6.0.7.1_3.11__g3b1768f.ari  19) craype-haswell
  4) craype-network-aries                             12) xpmem/2.2.15-6.0.7.1_5.11__g7549d06.ari          20) cray-mpich/7.7.3
  5) craype/2.5.15                                    13) job/2.2.3-6.0.7.1_5.43__g6c4e934.ari             21) gcc/7.3.0
  6) cray-libsci/18.07.1                              14) dvs/2.7_2.2.118-6.0.7.1_10.2__g58b37a2           22) altd/2.0
  7) udreg/2.3.2-6.0.7.1_5.13__g5196236.ari           15) alps/6.6.43-6.0.7.1_5.45__ga796da32.ari          23) darshan/3.1.4
  8) ugni/6.0.14.0-6.0.7.1_3.13__gea11d3d.ari         16) rca/2.2.18-6.0.7.1_5.47__g2aa4f39.ari
```

@sayerhs

**Comment by mamelara** [comment] 2019-06-12 19:22
Did you previously have a `compilers.yaml` file? Can I see the contents of your `~/.spack/cray/compilers.yaml` file?

**Comment by jhux2** [comment] 2019-06-13 23:52
@mamelara I did, attached with suffix changed for upload.
[compilers-yaml.txt](https://github.com/spack/spack/files/3288469/compilers-yaml.txt)

**Comment by mamelara** [comment] 2019-06-13 23:54
Could you either delete your `compilers.yaml` or move it away and then run spack again? There was a previous bug that grepped all of the PrgEnvs but didn't account for site specific PrgEnvs - like PrgEnv-llvm.

**Comment by scheibelp** [comment] 2019-07-03 01:43
@jhux2 are you able to reproduce the bug after trying @mamelara's suggestion at https://github.com/spack/spack/issues/11641#issuecomment-501919261?

**Comment by hainest** [comment] 2020-01-02 04:17
I can confirm this is still an issue.

    $ git branch -v
      * develop 7a97dc377 py-numpy: add 1.17.5 (#14341)

    $ lsb_release -d
      Description:	SUSE Linux Enterprise Server 15

    $ spack compiler list
      ==> Available compilers
      -- cce cnl7-any -------------------------------------------------
      cce@9.1.0  cce@9.1.0  cce@9.0.0  cce@9.0.0  cce@9.0.0  cce@9.0.0  cce@8.7.9  cce@8.7.9

      -- gcc cnl7-any -------------------------------------------------
      gcc@8.3.0  gcc@8.2.0  gcc@8.1.1  gcc@8.1.0  gcc@7.3.0  gcc@6.3.0  gcc@6.1.0

      -- gcc sles15-x86_64 --------------------------------------------
      gcc@7.4.1

      -- intel cnl7-any -----------------------------------------------
      intel@19.0.3.199  intel@18.0.3.222  intel@17.0.2.174  intel@16.0.3.210
      intel@19.0.0.117  intel@18.0.1.163  intel@17.0.1.132

      -- pgi cnl7-any -------------------------------------------------
      pgi@19.10  pgi@19.9  pgi@19.7  pgi@19.5  pgi@19.4  pgi@19.3  pgi@19.1  pgi@18.10
    
    $ spack install gcc@9.2.0 %gcc@7.4.1
      ==> Error: No compilers with spec gcc@7.4.1 found for operating system cnl7 and target haswell.
      Run 'spack compiler find' to add compilers.


    $ module list
      Currently Loaded Modulefiles:
        1) modules/3.2.11.1                                 15) job/2.2.4-7.0.1.1_3.25__g36b56f4.ari
        2) nsg/1.2.0                                        16) dvs/2.12_2.2.151-7.0.1.1_5.20__g7eb5e703
        3) cray-mpich/7.7.6                                 17) alps/6.6.56-7.0.1.1_4.30__g2e60a7e4.ari
        4) craype-haswell                                   18) rca/2.2.20-7.0.1.1_4.25__g8e3fb5b.ari
        5) craype-hugepages2M                               19) atp/2.1.3
        6) craype-network-aries                             20) PrgEnv-gnu/6.0.5
        7) craype/2.5.18                                    21) boost/1.70.0
        8) cray-libsci/19.02.1                              22) gcc/8.3.0
        9) udreg/2.3.2-7.0.1.1_3.16__g8175d3d.ari           23) git/2.21.0
       10) ugni/6.0.14.0-7.0.1.1_7.19__ge78e5b0.ari         24) cmake/3.14.4
       11) pmi/5.0.14                                       25) tbb/19.0.3.199
       12) dmapp/7.1.1-7.0.1.1_4.26__g38cf134.ari           26) cray-python/3.7.3.2
       13) gni-headers/5.0.12.0-7.0.1.1_6.17__g3b1768f.ari  27) altd/2.0
       14) xpmem/2.2.19-7.0.1.1_3.13__gdcf436c.ari          28) darshan/3.1.7

**Comment by hainest** [comment] 2020-01-02 08:23
Spack appears to be uncertain about which OS is on the target (note from my previous comment that gcc@8.3.0 is for the cnl7-any target).

    $ spack install gcc@9.2.0 %gcc@8.3.0
    $ module load module load cray-cnl7-haswell/gcc-9.2.0-gcc-8.3.0-yub63gu
    $ spack compiler add gcc@9.2.0
      ==> Added 1 new compiler to /global/homes/t/thaines/.spack/cray/compilers.yaml
          gcc@9.2.0
      ==> Compilers are defined in the following files:
          /global/homes/t/thaines/.spack/cray/compilers.yaml
    $ spack compiler list
      ==> Available compilers
      <SNIP>
      -- gcc sles15-x86_64 --------------------------------------------
      gcc@9.2.0  gcc@7.4.1

The generated module file for gcc@9.2.0 says it's for the cnl7 target, but it gets added to the sles15 target. The NERSC folks appear to be trying to support both cnl7 and sles15 due to the recent OS upgrades there. I wouldn't imagine this would be a typical use case for Spack, but it highlights some possible ambiguities in the target/arch. I have a feeling this is made more complicated by having to parse the Cray modules to figure all this out.

**Comment by alalazo** [comment] 2023-06-01 20:12
Closing since Cori has been decommissioned.

**Closed by alalazo** 2023-06-01 20:12 UTC
Labels: bug, triage
