### ISSUE TITLE
Spack behavior with macOS upgrade

### ISSUE THREAD

**Issue by BarrySmith** [spack/spack#1851] opened 2016-09-26 02:45 UTC
$ ./spack install petsc
==> Error: No available compiler version matches 'None' on operating_system sierra
Run 'spack compilers' to see available compiler Options.
~/Src/spack/bin (develop=) 
$ spack compilers
==> Available compilers
-- gcc ----------------------------------------------------------
gcc@6.2.0

-- clang --------------------------------------------------------
clang@8.0.0-apple
~/Src/spack/bin (develop=) 
$ spack find
==> 1 installed packages.
-- darwin-None-x86_64 / clang@8.0.0-apple -----------------------
mpich@3.2
~/Src/spack/bin (develop=) 
$ spack compiler find
==> Added 1 new compiler to /Users/barrysmith/.spack/compilers.yaml
    gcc@4.2.1
~/Src/spack/bin (develop=) 

Kind of an annoying error message. No indication of what I should do to resolve the "problem". Note I upgraded the compilers (xcode and gcc) a few days before upgrading the OS so the compilers are correct for the OS.

**Comment by davydden** [comment] 2016-09-26 06:05
> darwin-None-x86_64

this is strange.

Did you do a clean install of Spack on Sierra, i.e. wiped out completely your `opt` directory? 

This issues appears to be a duplicate of https://github.com/LLNL/spack/issues/1815

**Comment by adamjstewart** [comment] 2016-09-26 13:46
Actually, this is a completely different problem. It's a duplicate of #1476, although the error message has changed. I just updated to macOS Sierra to confirm:
```
$ spack arch
darwin-sierra-x86_64
$ spack install libsigsegv
==> Error: No available compiler version matches 'None' on operating_system sierra
Run 'spack compilers' to see available compiler Options.
```
The problem is that your `~/compilers.yaml` still contains the elcapitan entries:
```yaml
compilers:
- compiler:
    modules: []
    operating_system: elcapitan
    paths:
      cc: /usr/local/bin/gcc
      cxx: /usr/local/bin/g++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: gcc@5.3.0
...
```
The most reliable solution is to delete your `~/compilers.yaml` and re-run `spack compiler find`. Simply running `spack compiler find` won't do the trick, as reported in #1492.

**Comment by BarrySmith** [comment] 2016-09-26 18:01
It would be nice if Spack could give some useful diagonostics when this happens. Maybe spack could keep the current os name cached somewhere and ever time spack is run compare against the cached version and tell the user the os has changed and they need to do something? Otherwise you will get these "bug reports" forever since most people will not remember they need to change something in spack when they upgrade the os.

**Comment by adamjstewart** [comment] 2016-09-26 18:08
I think Spack should notice that there are no compilers available for your current OS, automatically run `spack compiler find` for you, and carry on its merry way. No user intervention should be necessary.

**Comment by adamjstewart** [comment] 2016-12-12 17:12
Just updated to Fedora 25 and it looks like there are no changes with respect to this PR. The error message is the same:
```
==> Error: No available compiler version matches 'None' on operating_system fedora25 for target x86_64
```
It would be nice if the error message was more clear, or if Spack automatically updated the OS version.

**Closed** 2022-05-13 07:54 UTC
Labels: bug, duplicate, configuration, compilers
