### ISSUE TITLE
Concretization failure with some when clause conditions

### ISSUE THREAD

**Issue by krafczyk** [spack/spack#7211] opened 2018-02-09 21:56 UTC
### Summary

In some cases, dependencies specified with a when clause can be removed when a spec is fully concretized resulting in a mysterious error.

This can be resolved by specifying a more complete spec initially, however the concretizer should be smart enough to avoid this problem.

When the new concretizer is complete, it should handle this situation correctly.

### Steps to reproduce the issue

Try the command

```console
spack spec py-pytest-mock^python@3:
```

Specifying that you want py-pytest-mock depending on the latest version of python 3.

### Expected Result

One would expect this to resolve neatly with python 3.6.3 (at the time of this writing)

### Actual Result

However, instead you get this nasty error message:

```console
==> Error: py-pytest-mock does not depend on py-enum34
```

### Cause

This happens because `py-pytest-mock` depends on `py-mock` which depends on `py-pbr` which depends on `py-enum34` with a when clause: `when='python@:3.3'`. When the dependencies are initially added during concretization, the when clause is satisfied by `python@3:` and so `py-enum34` is added as a dependency. Later in concretization however, `python@3:` becomes `python@3.6.3` at which point, the when clause is no longer satisfied thus triggering the error.

### Mitigation

You can be more specific with the initial spec.

```console
spack spec py-pytest-mock^python@3.5:
```

Works fine.

### Information on your system

Os is Arch,
This issue should occur regardless of custom configuration settings.

**Comment by alalazo** [comment] 2020-11-01 21:40
Duplicate of #1781

**Closed** 2020-11-01 21:40 UTC
Labels: concretization, duplicate
