### ISSUE TITLE
Can't install tensorflow because of bazel

### ISSUE THREAD

**Issue by coreyjadams** [spack/spack#14234] opened 2019-12-19 21:14 UTC
I am trying to install tensor flow for cpu via spack.  It falls over at bazel:
```
==> Installing bazel
==> Searching for binary cache of bazel
==> No binary for bazel found: installing from source
==> Using cached archive: /lus/theta-fs0/projects/datascience/cadams/spack/cooley/spack/var/spack/cache/_source-cache/archive/c0/c0e94f8f818759f3f67af798c38683520c540f469cb41aea8f5e5a0e43f11600.zip
==> Staging archive: /tmp/cadams/spack-stage/spack-stage-bazel-0.26.1-4mmpkcidyja4i6smxm2ahqifvh322xsz/bazel-0.26.1-dist.zip
==> Created stage in /tmp/cadams/spack-stage/spack-stage-bazel-0.26.1-4mmpkcidyja4i6smxm2ahqifvh322xsz
==> Applied patch /lus/theta-fs0/projects/datascience/cadams/spack/cooley/spack/var/spack/repos/builtin/packages/bazel/bazelruleclassprovider-0.25.patch
==> Applied patch /lus/theta-fs0/projects/datascience/cadams/spack/cooley/spack/var/spack/repos/builtin/packages/bazel/unix_cc_configure-0.15.patch
==> Applied patch /lus/theta-fs0/projects/datascience/cadams/spack/cooley/spack/var/spack/repos/builtin/packages/bazel/compile-0.21.patch
==> Building bazel [Package]
==> Executing phase: 'bootstrap'
==> Executing phase: 'install'
==> Error: FileNotFoundError: [Errno 2] No such file or directory: 'output/bazel'

/lus/theta-fs0/projects/datascience/cadams/spack/cooley/spack/var/spack/repos/builtin/packages/bazel/package.py:136, in install:
        134    def install(self, spec, prefix):
        135        mkdir(prefix.bin)
  >>    136        install('output/bazel', prefix.bin)

See build log for details:
  /tmp/cadams/spack-stage/spack-stage-bazel-0.26.1-4mmpkcidyja4i6smxm2ahqifvh322xsz/spack-build-out.txt
```
Here was the command I have used:
```console
$ spack install py-tensorflow@1.15 cuda_arch=35 ^cuda@10.1 %gcc@6.3.0
```

And, I am on this system:
```
$ uname -a
Linux cc047 3.10.0-957.27.2.el7.x86_64 #1 SMP Tue Jul 9 16:53:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release
LSB Version:	:core-4.1-amd64:core-4.1-noarch
```

Any ideas for how to fix this?  I have the latest version of spack as of this morning.  Is there an older version of bazel that will work?

**Comment by adamjstewart** [comment] 2019-12-19 23:19
Can you share the build log? That will help me diagnose the problem.

**Comment by Sinan81** [comment] 2019-12-20 01:31
I think that error shows up when openjdk is used. I would suggest switching to jdk instead.

**Comment by adamjstewart** [comment] 2019-12-20 01:38
The following error:
```
==> Error: FileNotFoundError: [Errno 2] No such file or directory: 'output/bazel'
```
just means that something went wrong during bootstrapping. Unfortunately, the bootstrap script doesn't exit with the proper exit code if it fails, so things fail during the install phase.

**Comment by s-sajid-ali** [comment] 2019-12-20 16:36
This looks like the error I got when I built bazel with openJDK. 

@adamjstewart : Since we know that `bazel` fails with `openJDK` as per https://github.com/spack/spack/issues/14058, should we switch the default provider for `java` to `jdk` instead ?

**Comment by coreyjadams** [comment] 2019-12-20 17:15
Here is the build log:

https://gist.github.com/coreyjadams/a43b1a165c29acbfb542cca98f9ad4b0.js

It does in fact look related to java, I'll try with java instead of openJDK.

**Comment by coreyjadams** [comment] 2019-12-20 17:33
For what it's worth, java moved the build past bazel as @s-sajid-ali suggested via a private email:
`spack install py-tensorflow@1.15 cuda_arch=35 ^cuda@10.1 ^jdk@1.8.0_231-b11 %gcc@6.3.0`

The java specification had to be exactly the one listed or it still failed.

I'll follow up if there are other crashes in tensorflow.

**Comment by adamjstewart** [comment] 2019-12-20 17:45
> This looks like the error I got when I built bazel with openJDK.
> 
> @adamjstewart : Since we know that `bazel` fails with `openJDK` as per #14058, should we switch the default provider for `java` to `jdk` instead ?

I would keep the default provider at `openjdk` for legal issues (don't want to pick a fight with Oracle about automatically accepting their licenses). I've also had problems downloading `jdk` recently. It might be better to switch the `bazel` dependency to `jdk`.

**Comment by coreyjadams** [comment] 2020-01-15 20:36
I have been trying again to install tensorflow.  Limited success, really.  I have tried with tensorflow versions 1.14.0 and 1.15.0, neither builds.

1.14.0 error:
```
==> Error: ProcessError: Command exited with status 1:
    'bazel' '--nohome_rc' '--nosystem_rc' '--output_user_root=/tmp/spack/tf' 'build' '--color=no' '--jobs=12' '--config=opt' '--verbose_failures' '--subcommands=pretty_print' '--explain=explainlogfile.txt' '--verbose_explanations' '--config=cuda' '--config=noaws' '--config=nogcp' '--config=nohdfs' '--config=noignite' '--config=nokafka' '--cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0' '//tensorflow/tools/pip_package:build_pip_package'

5 errors found in build log:
     2195        -w \
     2196        '-std=c99' \
     2197        -c \
     2198        external/nasm/asm/rdstrnum.c \
     2199        -o \
     2200        bazel-out/k8-opt/bin/external/nasm/_objs/nasm/rdstrnum.o)
  >> 2201    ERROR: /tmp/spack/tf/966c9fe0240f93060470a6ff832dbefd/external/nasm/BUILD.bazel:8:1: C++ compilation of ru
             le '@@nasm//:nasm' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
     2202      (cd /tmp/spack/tf/966c9fe0240f93060470a6ff832dbefd/execroot/org_tensorflow && \
     2203      exec env - \
     2204        CUDA_TOOLKIT_PATH=/gpfs/mira-fs0/software/x86_64/datascience/spack/opt/spack/linux-rhel7-haswell/gcc-8
             .2.0/cuda-10.1.243-d6wxkrjmwfuciuaqaaqesckso6cgjy2i \
     2205        CUDNN_INSTALL_PATH=/gpfs/mira-fs0/software/x86_64/datascience/spack/opt/spack/linux-rhel7-haswell/gcc-
             8.2.0/cudnn-7.6.5.32-10.1-linux-x64-uxogwqksn2qauwxcnnxjafzcktmt6h6h \
     2206        GCC_HOST_COMPILER_PATH=/soft/datascience/spack/lib/spack/env/gcc/gcc \
     2207        LD_LIBRARY_PATH=/gpfs/mira-fs0/software/x86_64/datascience/spack/opt/spack/linux-rhel7-haswell/gcc-8.2
             .0/cuda-10.1.243-d6wxkrjmwfuciuaqaaqesckso6cgjy2i/targets/x86_64-linux/lib/stubs:/gpfs/mira-fs0/software/x
             86_64/datascience/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/cudnn-7.6.5.32-10.1-linux-x64-uxogwqksn2qa
             uwxcnnxjafzcktmt6h6h/lib64:/gpfs/mira-fs0/software/x86_64/datascience/spack/opt/spack/linux-rhel7-haswell/
             gcc-8.2.0/nccl-2.4.8-1-6o2d6dlye3qadynng6vetzcr4tm6seyx/lib \

     ...

     2248        TF_NEED_OPENCL_SYCL=0 \
     2249        TF_NEED_ROCM=0 \
     2250        TF_NEED_TENSORRT=0 \
     2251      external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-
             opt/bin/external/nasm/_objs/nasm/outelf.d '-frandom-seed=bazel-out/k8-opt/bin/external/nasm/_objs/nasm/out
             elf.o' -DHAVE_SNPRINTF -DHAVE_SYS_TYPES_H -iquote external/nasm -iquote bazel-out/k8-opt/bin/external/nasm
              -iquote external/bazel_tools -iquote bazel-out/k8-opt/bin/external/bazel_tools -isystem external/nasm/asm
              -isystem bazel-out/k8-opt/bin/external/nasm/asm -isystem external/nasm/include -isystem bazel-out/k8-opt/
             bin/external/nasm/include -isystem external/nasm/output -isystem bazel-out/k8-opt/bin/external/nasm/output
              -isystem external/nasm/x86 -isystem bazel-out/k8-opt/bin/external/nasm/x86 -Wno-builtin-macro-redefined '
             -D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIE -U_FORTIFY_SOURCE '-D_FO
             RTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-syst
             em-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections '-march=haswell' '-mtune=haswell' -w '-std
             =c99' -c external/nasm/output/outelf.c -o bazel-out/k8-opt/bin/external/nasm/_objs/nasm/outelf.o)
     2252    Execution platform: @bazel_tools//platforms:host_platform
     2253    In file included from external/nasm/output/outelf.c:49:
  >> 2254    /gpfs/mira-fs0/software/x86_64/datascience/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/python-3.7.4-j4sb
             fz26j6k2mt2vzmvxhtklskffam33/include/python3.7m/eval.h:10:12: error: unknown type name 'PyObject'
     2255     PyAPI_FUNC(PyObject *) PyEval_EvalCode(PyObject *, PyObject *, PyObject *);
     2256                ^~~~~~~~
  >> 2257    /gpfs/mira-fs0/software/x86_64/datascience/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/python-3.7.4-j4sb
             fz26j6k2mt2vzmvxhtklskffam33/include/python3.7m/eval.h:12:12: error: unknown type name 'PyObject'
     2258     PyAPI_FUNC(PyObject *) PyEval_EvalCodeEx(PyObject *co,
     2259                ^~~~~~~~
  >> 2260    /gpfs/mira-fs0/software/x86_64/datascience/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/python-3.7.4-j4sb
             fz26j6k2mt2vzmvxhtklskffam33/include/python3.7m/eval.h:21:12: error: unknown type name 'PyObject'
     2261     PyAPI_FUNC(PyObject *) _PyEval_EvalCodeWithName(
     2262                ^~~~~~~~
  >> 2263    /gpfs/mira-fs0/software/x86_64/datascience/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/python-3.7.4-j4sb
             fz26j6k2mt2vzmvxhtklskffam33/include/python3.7m/eval.h:31:12: error: unknown type name 'PyObject'
     2264     PyAPI_FUNC(PyObject *) _PyEval_CallTracing(PyObject *func, PyObject *args);
     2265                ^~~~~~~~
     2266    Target //tensorflow/tools/pip_package:build_pip_package failed to build
     2267    INFO: Elapsed time: 57.328s, Critical Path: 1.32s
     2268    INFO: 8 processes: 8 local.
     2269    FAILED: Build did NOT complete successfully

See build log for details:
  /tmp/cadams/spack-stage/spack-stage-py-tensorflow-1.14.0-a3lc7hqjvpzmnv6zdhklnyvrczvldfty/spack-build-out.txt
```

1.15.0 error:
```
ERROR: /tmp/spack/tf/84085fcd4911be325444e10a40e1c6ce/external/com_google_protobuf/BUILD:106:1: undeclared inclusion(s) in rule '@com_google_protobuf//:protobuf_lite':
this rule is missing dependency declarations for the following files included by 'external/com_google_protobuf/src/google/protobuf/stubs/int128.cc':
  '/gpfs/mira-fs0/software/x86_64/datascience/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/gettext-0.20.1-7ipvgryanyyat522m5ran5vsagy6bog2/include/libintl.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 73.809s, Critical Path: 8.00s
INFO: 12 processes: 12 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```


This is on a standard GPU cluster, nothing complicated like cross compiling.  Bazel builds, at least, though as you mention it is not very reliable with the jdk download.

**Comment by adamjstewart** [comment] 2020-01-15 21:01
@coreyjadams have you tried TF 2.0 or 2.1?

**Comment by s-sajid-ali** [comment] 2020-01-15 21:16
Ugh, this is most definitely another instance of https://github.com/bazelbuild/bazel/issues/10437 as I see the error is caused by the same include error for nasm where bazel tries to include the wrong header. I'm still waiting for a reply on that issue but I hope if enough people try to tell the bazel team that this is a serious impediment to building tf on rhel/centos/sles/cle (just any os apart from ubuntu) they would fix it.

**Comment by adamjstewart** [comment] 2020-01-15 21:21
Maybe we should add a note/warning that says the `bazel` and `py-tensorflow` packages are only tested on macOS/Ubuntu and may not build on RHEL and friends? I also had trouble building it on Amazon Linux (https://github.com/bazelbuild/bazel/issues/10418) which is RHEL-based.

**Comment by coreyjadams** [comment] 2020-01-15 21:28
I sent them a ping.  We'll see.  We'll need a good way to install DL frameworks on Aurora so I hope we can get this working.

I have not tried tf 2+, though I can.  Do you expect it to be any better?

**Comment by s-sajid-ali** [comment] 2020-01-15 21:42
It could be that this issue was fixed in a later release of `bazel` but that's just a guess at best.

With each new release of tf, the required bazel version also goes up but I find their .bazelversion and CI bazel-version to be inconsistent. For example, the [.bazelversion for `tf-2.1.0`](https://github.com/tensorflow/tensorflow/blob/r2.1/.bazelversion) says that one should use `bazel@0.29.1` but the [CI page](https://www.tensorflow.org/install/source#linux) says that they test `tf-2.1.0` with `bazel@0.26.1`.

**Comment by adamjstewart** [comment] 2020-01-16 00:17
> I have not tried tf 2+, though I can. Do you expect it to be any better?

Nah, but you never know...

> the CI page says that they test tf-2.1.0 with bazel@0.26.1

That's probably a mistake, since `configure.py` will crash if you don't use `bazel@0.27.1:0.29.1`. The only thing TF is good at is explicitly listing which versions of Bazel work.

**Comment by Sinan81** [comment] 2020-01-16 01:03
I managed to build tf@1.14 (with python2 and python3 and tf@2.1 (with python 3) on Centos however the catch is that I am using an old version of TF package file. Something has changed in the final (and more polished) version, and v1.14 doesn't build anymore. If I remember correctly, I am not able to build tf@1.15 or tf@2.0. with the version that I have.

**Closed** 2020-04-21 20:56 UTC
Labels: build-error
