### ISSUE TITLE
whats going on with cray systems and head of develop

### ISSUE THREAD

**Issue by hppritcha** [spack/spack#8354] opened 2018-06-02 02:53 UTC
Okay, so I blew away all of my ~/.spack files and anything else ( I think ) that knew about my old
work using spack on cray.  I do a fresh clone from github of spack and now when I try to build a package on my cray XC CLE 6.0up04 system I get this:

/scratch1/users/hpp/spack@ga-fe1:/scratch1/users/hpp/spack> (develop)spack install libhio
==> Error: Compiler configuration contains entries with duplicate specification (gcc@7.3.0, cray-cnl6-haswell) in the following files:
	/users/hpp/.spack/cray/compilers.yaml: 7 times
	/users/hpp/.spack/compilers.yaml: 7 times

I use not to see this.  Anyone know what's going on?

@junghans

**Comment by junghans** [comment] 2018-06-02 14:01
I am not 100%, but doesn't the error just meant you have `gcc@7.3.0` defined twice and hence spack doesn't know, which one to use? @adamjstewart might know more.

**Comment by hppritcha** [comment] 2018-06-02 16:00
It may be that Cray has changed something with the Programming environment modules that now doesn't sit well with spack.

**Comment by mamelara** [comment] 2018-06-02 17:52
I wasn't able to reproduce that error. I have seen this error before in the past though and it was due to the fact that we had two modules with the same name and compiler version.

**Comment by mamelara** [comment] 2018-06-02 17:54
Mind posting your compilers.yaml?

**Comment by adamjstewart** [comment] 2018-06-02 19:29
It looks like you have 2 `compilers.yaml`. Is this intentional? You'll have to delete whichever one is a duplicate of the other.

**Comment by hppritcha** [comment] 2018-06-04 16:41
Here's the compilers.yaml file
https://gist.github.com/hppritcha/859b94be40d6899a4d2ea93380ee7a8f

**Comment by hppritcha** [comment] 2018-06-04 16:45
I manually edited the compiler.yaml and cray/compiler.yaml and moved beyond this issue.  Its not obvious to me from the Cray PrgEnv's though why spack gets tripped up on gnu 7.3.0.

**Comment by adamjstewart** [comment] 2018-06-04 16:49
It looks like you had 3 compilers named `gcc@7.3.0` and 4 compilers named `intel@18.0.2` in this `compilers.yaml` alone.

The first time you run Spack on a Cray machine, it will search for modules that sound like compilers and add all of them to your `compilers.yaml` for you. Spack will only do this the first time you run, if you don't already have any compilers available. After that, running `spack compiler find` with no arguments will have the same affect. Spack _shouldn't_ add duplicates of these compilers. If it is, then that's a bug.

**Comment by mamelara** [comment] 2018-06-20 05:46
@hppritcha is it the case that Spack is adding duplicates?

**Comment by alalazo** [comment] 2019-12-17 13:13
Closing as stale, and probably solved by @becker33 in #11910. Feel free to reopen if still an issue.

**Closed by alalazo** 2019-12-17 13:13 UTC
Labels: compilers, cray
