### ISSUE TITLE
Module files for external packages are not properly created in anonymous environments

### ISSUE THREAD

**Issue by bvanessen** [spack/spack#13486] opened 2019-10-29 16:39 UTC
Building a set of spack packages inside of an anonymous environment produced module files without proper paths to the external packages.  Specifically, I was building the LBANN environment as detailed at https://lbann.readthedocs.io/en/latest/building_lbann.html.  The environment uses external packages for cmake, cuda, and mvapich2.  Previous versions of spack correctly created the modules for each of these.  With the head of develop from Thursday 10/24 just prior to the release of 0.13, spack was no longer able to properly create the module files.

### Steps to reproduce the issue

Using the lbann build instructions:

```console
$ export LBANN_HOME=/path/to/lbann/git/repo
$ export LBANN_BUILD_DIR=/path/to/a/build/directory
$ export LBANN_INSTALL_DIR=/path/to/an/install/directory
$ cd ${LBANN_BUILD_DIR}
$ spack env create -d . ${LBANN_HOME}/spack_environments/developer_release_<arch>_cuda_spack.yaml # where <arch> = x86_64 | ppc64le
$ cp ${LBANN_HOME}/spack_environments/std_versions_and_variants_llnl_lc_cz.yaml .
$ cp ${LBANN_HOME}/spack_environments/externals_<arch>_llnl_lc_cz.yaml . # where <arch> = x86_64 | ppc64le
$ spack install
$ spack env loads # Spack creates a file named loads that has all of the correct modules
$ source ${SPACK_ROOT}/share/spack/setup-env.sh # Rerun setup since spack doesn't modify MODULEPATH unless there are module files defined
$ source loads
```

### Error Message

If you try to follow the rest of the build instructions at this point you will find that the module files for cuda, cmake, and mvapich2 are not properly generated.  These are the three external packages used.

### Information on your system

This is done on an x86 + GPU system on LC using the directions for developers at:
https://lbann.readthedocs.io/en/latest/building_lbann.html for the https://github.com/LLNL/lbann/ project.

-----

**Comment by bvanessen** [comment] 2019-10-29 16:39
@becker33 Here is the issue for the environment build problem.

**Comment by bvanessen** [comment] 2019-10-29 16:40
@alalazo I believe that @becker33 wanted you to look at this issue.

**Comment by bvanessen** [comment] 2019-10-31 17:39
Any thoughts on this?  It pretty much breaks the usefulness of the current head of develop.

**Comment by alalazo** [comment] 2019-11-01 10:24
@bvanessen I am starting to have a look at this right now.

**Comment by alalazo** [comment] 2019-11-01 14:37
Got sidetracked by another issue for a couple of hours. Anyhow trying to build locally I get empty module files for e.g. `cmake` which is installed externally:
```tcl
#%Module1.0
## Module file created by spack (https://github.com/spack/spack) on 2019-11-01 15:32:00.332217
##
## cmake@3.12.1%gcc@7.3.0~doc~ncurses~openssl+ownlibs patches=93488edf3f89cef6f3c77e821007c022e88e9f1f566ae9bf824a87ecbac97ebb,dd3a40d4d92f6b2158b87d6fb354c277947c776424aa03f6dc8096cf3135f5d0 ~qt arch=linux-ubuntu18.04-broadwell/zs5e3hn
##
## Configure options: unknown, software installed outside of Spack
##


module-whatis "A cross-platform, open-source build system. CMake is a family of tools designed to build, test and package software."

proc ModulesHelp { } {
puts stderr "A cross-platform, open-source build system. CMake is a family of tools"
puts stderr "designed to build, test and package software."
}
```
Is that the issue you are experiencing?

**Comment by alalazo** [comment] 2019-11-01 14:59
So, investigating what is happening I have a guess which seem to be a problem with the configuration file on your side and not a bug with Spack. Can you try to remove the double colon in:
```yaml
# std_versions_and_variants_llnl_lc_cz.yaml
modules::  #<- Remove the double colon as it overrides prefix inspection
  enable::
```
? If the issue persist please double check the paths are correct, since inspecting a non-existing path will also result in an empty module file like the one above.

Taking care of both these issues I have a module file that looks like:
```tcl
#%Module1.0
## Module file created by spack (https://github.com/spack/spack) on 2019-11-01 15:57:58.453929
##
## cmake@3.12.1%gcc@7.3.0~doc~ncurses~openssl+ownlibs patches=93488edf3f89cef6f3c77e821007c022e88e9f1f566ae9bf824a87ecbac97ebb,dd3a40d4d92f6b2158b87d6fb354c277947c776424aa03f6dc8096cf3135f5d0 ~qt arch=linux-ubuntu18.04-broadwell/4ku7hzo
##
## Configure options: unknown, software installed outside of Spack
##


module-whatis "A cross-platform, open-source build system. CMake is a family of tools designed to build, test and package software."

proc ModulesHelp { } {
puts stderr "A cross-platform, open-source build system. CMake is a family of tools"
puts stderr "designed to build, test and package software."
}


prepend-path MANPATH "/usr/share/man"
prepend-path ACLOCAL_PATH "/usr/share/aclocal"
prepend-path PKG_CONFIG_PATH "/usr/lib/pkgconfig"
prepend-path PKG_CONFIG_PATH "/usr/share/pkgconfig"
```
where I set the prefix of my external `cmake` to `/usr`. Can you confirm that this works also for you?

**Comment by bvanessen** [comment] 2019-11-01 16:24
Yeah, that looks like the error that I am seeing.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by alalazo** [comment] 2019-11-01 16:45
@bvanessen Can you confirm that also the solution works for you?

**Comment by bvanessen** [comment] 2019-11-01 16:50
I am testing now.

**Comment by alalazo** [comment] 2019-11-04 10:02
@bvanessen Any news? Can we close this issue?

**Comment by alalazo** [comment] 2019-11-05 13:01
@bvanessen I'll default to "no news good news" and close this. Feel free to reopen if there are still issues

**Closed by alalazo** 2019-11-05 13:01 UTC
Labels: bug, environments, external-packages, modules
