### ISSUE TITLE
spack load return code

### ISSUE THREAD

**Issue by ax3l** [spack/spack#7281] opened 2018-02-18 23:12 UTC
```bash
spack load nonExistingPackage
```
does not return a non-zero return code to bash.

### Expected Result

A non-zero return code and a message that the package does not exist

### Actual Result

Zero return code and no message.

### Steps to reproduce the issue

```console
$ spack bootstrap
# default tcl modules
$ spack load nonExistingPackage
```

### Information on your system

Debian 9.2
Spack 8ae50ae8b

ccing @alalazo

**Comment by davydden** [comment] 2018-02-18 23:14
see https://github.com/spack/spack/issues/2570

**Comment by healther** [comment] 2018-02-19 10:36
I took a stab at this (feels like ages ago) and didn't come too far, but maybe it helps as a starting point #3827

**Comment by alalazo** [comment] 2018-07-09 11:57
Duplicate of #2570

**Closed** 2018-07-09 16:03 UTC
Labels: commands, duplicate, modules
