### ISSUE TITLE
Compiler version in install path matches neither compilers.yaml nor package versions

### ISSUE THREAD

**Issue by matz-e** [spack/spack#14730] opened 2020-02-03 16:17 UTC
We would like to make it simple for users to specify which compilers certain packages should use. As such, we make good use of the `%gcc`, `%intel` spec parts. But we noticed a few unexpected installation directories when, e.g., `%intel@19` is used in an attempt to match the installed version of the intel compiler from 2019 (without being overly specific). This results in a new installation tree:
```
❯ spack install nano%intel@19
==> ncurses@6.1 : externally installed in /some/path/linux-rhel7-x86_64/gcc-8.3.0/ncurses-6.1-esk7yfugjx
==> ncurses@6.1 : generating module file
==> ncurses@6.1 : registering into DB
==> Installing nano
<snip>
==> Successfully installed nano
  Fetch: 0.71s.  Build: 1m 28.70s.  Total: 1m 29.41s.
[+] /gpfs/bbp.cscs.ch/home/matwolf/.cache/spack/install/linux-rhel7-x86_64/intel-19/nano-4.4-qqaacp
```
Notice the `/intel-19/`, where we would have expected `/intel-19.0.4.243/`, in line with the version given in `compilers.yaml`:
```
❯ spack compiler list
==> Available compilers
-- intel rhel7-x86_64 -------------------------------------------
intel@19.0.4.243
```
Is this expected? Could the behavior changed to either produce an error if the version is not matched exactly, or to actually match the highest version found in the full spec? Our configuration for the install path scheme:
```
❯ spack config get config|rg install_path
  install_path_scheme: ${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:6}
```

@pramodk, FYI.

**Comment by alalazo** [comment] 2020-02-05 12:50
Duplicate of #8735

**Comment by matz-e** [comment] 2020-02-05 13:15
Ah, I didn't see that one when I searched for this.

**Comment by alalazo** [comment] 2020-02-05 13:34
@matz-e No worries, I'm just following our [triage guide](https://github.com/spack/spack/wiki/Issue-Prioritization-and-Triage) as I investigate this. It just means that if I'll find a fix I'll close 2 issues :wink:

**Closed** 2020-02-20 20:20 UTC
Labels: bug, compilers, impact-medium, versions
