### ISSUE TITLE
Installation issue: cmake

### ISSUE THREAD

**Issue by pibion** [spack/spack#13227] opened 2019-10-16 00:03 UTC
### Steps to reproduce the issue

```console
$ spack install cmake@3.15.4 %gcc@4.8.5
... 
==> Executing phase: 'bootstrap'                                                                                        
==> [2019-10-15-23:13:35.418868] './bootstrap' '--prefix=/home/daq/packages/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/cmake-3.15.4-n32j6iddoejl2qjmtqxo4npaelqsgaf5' '--parallel=8' '--no-system-libs' '--no-qt-gui' '--' '-DCMAKE_USE_OPENSSL=True'  
--------------------------------------------                                                                           
CMake 3.15.4, Copyright 2000-2019 Kitware, Inc. and Contributors
C compiler on this system is: /home/daq/packages/spack/lib/spack/env/gcc/gcc
---------------------------------------------                                                                           
Error when bootstrapping CMake:
Cannot find a C++ compiler that supports both C++11 and the specified C++ flags.
Please specify one using environment variable CXX.  
The C++ flags are "".  
They can be changed using the environment variable CXXFLAGS. 
See cmake_bootstrap.log for compilers attempted.  
```

### Platform and user environment

I am running a centos7 docker container, with gcc@4.8.5 installed on the system:
```commandline
$ uname -a 
(base) [daq@e0dcbfa7d647 ~]$ uname -a                                                                                   
Linux e0dcbfa7d647 4.19.72-microsoft-standard #1 SMP Sun Sep 15 10:03:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
$ spack compilers
==> Available compilers                                                                                                 
-- gcc centos7-x86_64 -------------------------------------------  
gcc@4.8.5     
``` 

I'm confused by this error; I thought that a gcc version greater than 4.8.1 should implement the full C++11 standard.

### Additional information

It seems that my spack installation is able to build some packages correctly:
```console
$ spack spec --install-status cmake
Input spec                                                                                                              
--------------------------------                                                                                         
-   cmake      
Concretized                                                                                                             
--------------------------------     
-   cmake@3.15.4%gcc@4.8.5~doc+ncurses+openssl+ownlibs~qt arch=linux-centos7-haswell
[+]      ^ncurses@6.1%gcc@4.8.5~symlinks~termlib arch=linux-centos7-haswell      
[+]          ^pkgconf@1.6.3%gcc@4.8.5 arch=linux-centos7-haswell      
[+]      ^openssl@1.1.1d%gcc@4.8.5+systemcerts arch=linux-centos7-haswell   
[+]          ^perl@5.30.0%gcc@4.8.5+cpanm+shared+threads arch=linux-centos7-haswell     
[+]              ^gdbm@1.18.1%gcc@4.8.5 arch=linux-centos7-haswell    
[+]                  ^readline@8.0%gcc@4.8.5 arch=linux-centos7-haswell    
[+]          ^zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-haswell
```

Rebuilding the package with the following options also fails and produces spack-cc-cmake-n32j6id.in.log  and spack-cc-cmake-n32j6id.out.log, both of which are attached below.
```console
$ spack -d install -j 1 cmake
...
Traceback (most recent call last):                                                                                        
File "/home/daq/packages/spack/lib/spack/spack/build_environment.py", line 775, in child_process
return_value = function()                                                                                             
File "/home/daq/packages/spack/lib/spack/spack/package.py", line 1667, in build_process
phase(self.spec, self.prefix)                                                                                         
File "/home/daq/packages/spack/lib/spack/spack/package.py", line 109, in phase_wrapper
phase(spec, prefix)                                                                                                   
File "/home/daq/packages/spack/var/spack/repos/builtin/packages/cmake/package.py", line 170, in
bootstrap               
File "/home/daq/packages/spack/lib/spack/spack/util/executable.py", line 189, in __call__
proc.returncode, long_msg)                                                                                          spack.util.executable.ProcessError: Command exited with status 7:                                                           './bootstrap' '--prefix=/home/daq/packages/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/cmake-3.15.4-n32j6iddoejl2qjmtqxo4npaelqsgaf5' '--parallel=1' '--no-system-libs' '--no-qt-gui' '--' '-DCMAKE_USE_OPENSSL=True'
```

[spack-cc-cmake-n32j6id.in.log](https://github.com/spack/spack/files/3731867/spack-cc-cmake-n32j6id.in.log)
[spack-cc-cmake-n32j6id.out.log](https://github.com/spack/spack/files/3731868/spack-cc-cmake-n32j6id.out.log)

**Comment by chuckatkins** [comment] 2019-10-18 13:33
>  I thought that a gcc version greater than 4.8.1 should implement the full C++11 standard.

It doesn't and is still lacking quite a bit, esp. w.r.t to standard libraries (the regex implementation, for instance, is a no-op until 4.9+).  All that being said though, 4.8.5 should be sufficient to build and install `cmake`.  Unfortunately I'm not able to reproduce the error (i.e. builds and works for me on CentOS 7 w/ gcc 4.8.5).

Can you post the `spack-src/Bootstrap.cmk/cmake_bootstrap.log` from the failed build stage?

**Comment by pibion** [comment] 2019-10-19 05:09
Okay, good to know about gcc 4.8.5.  I've attached the `spack-src/Bootstrap.cmk/cmake_bootstrap.log` below.

[cmake_bootstrap.log](https://github.com/spack/spack/files/3746218/cmake_bootstrap.log)

I'm running spack in a centos7 docker container, in case that helps:

```
FROM centos:centos7       
USER root   
RUN yum -y install sudo wget git gcc curl make gnupg2   
RUN mkdir /packages  
RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh -O /packages/anaconda.sh && \    
/bin/bash /packages/anaconda.sh -b -p /packages/anaconda3 && \  
rm /packages/anaconda.sh  

## Configure user and entrypoint        
RUN groupadd --gid 101 sudo   
RUN useradd -ms /bin/bash -g root -G sudo,wheel -u 1000 jotunn  
RUN echo ". /packages/anaconda3/etc/profile.d/conda.sh && conda activate base" >> /home/user1/.bashrc         
RUN echo 'jotunn:password1' | chpasswd 

#ENTRYPOINT ["/bin/bash"]    
RUN chown -R user1/home/user1/   
USER user1
WORKDIR /home/user1
```

**Comment by pat-s** [comment] 2019-10-25 13:05
I am getting the same error when using gcc@9.2.0 on CentOS7 (build from systems gcc@4.8.5).

Works when using gcc@4.8.5.

**Comment by chuckatkins** [comment] 2019-10-29 20:31
> I am getting the same error when using gcc@9.2.0 on CentOS7 (build from systems gcc@4.8.5).
> 
> Works when using gcc@4.8.5.

Is it possible the gcc@9.2.0 you built is only the C compiler and doesnt include the C++ compiler?

**Comment by pat-s** [comment] 2019-10-29 20:57
No everything was fine in that case. However, this issue was also solved by #13460 for me.

**Comment by alalazo** [comment] 2019-11-06 07:42
Closing as I also can't reproduce:
```console
$ spack install cmake@3.15.4 %gcc@4.8
[ ... ]
==> Successfully installed cmake
  Fetch: 0.04s.  Build: 7m 3.87s.  Total: 7m 3.92s.
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-4.8/cmake-3.15.4-zr6zbvfmxlhorqpevj6r5esk235a7jbx

$ gcc-4.8 --version
gcc-4.8 (Ubuntu 4.8.5-4ubuntu8) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Feel free to reopen if the issue persists and you find a way to make it reproducible (use a container image perhaps?).

**Closed by alalazo** 2019-11-06 07:42 UTC
Labels: build-error, cmake

**Comment by pibion** [comment] 2019-11-09 14:54
> @pibion I just realized you're missing the c++ and fortran compilers from your docker image. I believe that may be the cause here. Try changing:
> 
> ```
> RUN yum -y install sudo wget git gcc curl make gnupg2
> ```
> 
> to
> 
> ```
> RUN yum -y install sudo wget git gcc gcc-c++ gcc-gfortran curl make gnupg2
> ```
> 
> Fun fact though, while tracking this down with @bradking we found an unrelated bug in the bootstrap script :-D

Adding `gcc-c++` and `gcc-gfortran` has fixed the issue, spack now successfully compiles cmake!
