### ISSUE TITLE
Unable to build mpileaks, getting a StageError

### ISSUE THREAD

**Issue by pelegs** [spack/spack#5507] opened 2017-09-27 14:59 UTC
Hello,

following [this tutorial](http://spack.readthedocs.io/en/latest/tutorial_packaging.html) I'm getting the following error when running `$ spack install mpileaks`:

[...]
==> Installing gettext
==> Using cached archive: /home/tapir/spack/var/spack/cache/gettext/gettext-0.19.8.1.tar.xz
==> Staging archive: /home/tapir/spack/var/spack/stage/gettext-0.19.8.1-gzmvyrknpp3ihuiijvxhgiaxeexdy3oo/gettext-0.19.8.1.tar.xz
==> '/home/tapir/spack/opt/spack/linux-scientific6-x86_64/gcc-4.4.7/tar-1.29-2ikg7zktul4pztwxaumtrb7kae4hkwb5/bin/tar' '-xf' '/home/tapir/spack/var/spack/stage/gettext-0.19.8.1-gzmvyrknpp3ihuiijvxhgiaxeexdy3oo/gettext-0.19.8.1.tar.xz'
==> Created stage in /home/tapir/spack/var/spack/stage/gettext-0.19.8.1-gzmvyrknpp3ihuiijvxhgiaxeexdy3oo
==> Error: StageError: Attempt to chdir before expanding archive.
StageError: StageError: Attempt to chdir before expanding archive.

/home/tapir/spack/lib/spack/spack/package.py:982, in do_stage:
     5     
     6             self.do_fetch(mirror_only)
     7             self.stage.expand_archive()
     8             self.stage.chdir_to_source()
(error on line 8)

I found [this thread](https://github.com/LLNL/spack/issues/3018), suggesting I should try `$ spack clean mpileaks` (in my case). I get the same error. When I try `$ spack purge --downloads` I get `==> Error: Unknown command: purge` (using version 0.10.0).

Can anyone perhaps point me to a possible solution to the problem?

Thanks

**Comment by pelegs** [comment] 2017-09-27 15:18
Yes, they do (installing from the already existing scripts that came with my 0.10.0 clone).

**Comment by naromero77** [comment] 2017-09-27 20:44
I am not a Spack developer, just another contributor. There are a number of packages that don't install and creating a GitHub issue does not seem to lead to getting the package fixed on a short time scale. My advice would be to track the person who contributed that package down and reach out to them directly.

Sometimes posting on the Google Group can help.

**Comment by scheibelp** [comment] 2017-09-27 20:58
> using version 0.10.0
> `==> Error: Unknown command: purge`

The suggestion likely applies to the develop version of spack. We respond to issues that people have with develop so it's ok to use that too (in fact at this point `0.10.0` is old enough that I'd recommend it). If you have the time to try with develop, does the same issue occur?

> There are a number of packages that don't install and creating a GitHub issue does not seem to lead to getting the package fixed on a short time scale.

@naromero77 are there any issues that are high priority to you that aren't getting looked at? Sometimes the issue is specific to the package itself and your suggestion to track down the original author is the most efficient one.

**Comment by pramodskumbhar** [comment] 2017-09-27 21:26
@pelegs : I would also suggest to try develop (which most of us use regularly). With this, you could do `spack clean -a` to remove builds as well downloaded tarballs.

I quickly tried `mpileaks` and `gettext` is building fine:

```
$spack install mpileaks
....
==> Installing gettext
==> Fetching http://ftpmirror.gnu.org/gettext/gettext-0.19.8.1.tar.xz
######################################################################## 100.0%

▽
==> Staging archive: /gpfs/homeb/pcp0/pcp0043/spack/var/spack/stage/gettext-0.19.8.1-liniztuxa2etuecgrtwswqc2r7mygpq5/gettext-0.19.8.1.tar.xz
==> Created stage in /gpfs/homeb/pcp0/pcp0043/spack/var/spack/stage/gettext-0.19.8.1-liniztuxa2etuecgrtwswqc2r7mygpq5
==> Applied patch test-verify-parallel-make-check.patch
==> Building gettext [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed gettext
  Fetch: 1.49s.  Build: 2m 52.27s.  Total: 2m 53.76s.
```

@naromero77 : you could also ask questions on Slack channel which could be more quick/interactive.

**Comment by naromero77** [comment] 2017-09-28 03:39
@scheibelp I have had a few issues with specific packages. I usually post question on the Google Group. I have been mostly working around the issues since its resource intensive to support all these different combinations, but I may be more proactive about tracking down authors moving forward.

@pelegs I use slack for three other projects. If the channel is open to contributors (i.e. not core developers), you can send an invite to naromero@anl.gov.

**Comment by tgamblin** [comment] 2017-09-28 04:49
@naromero77: just click on the slack button in the GitHub README -- we have it set up to automatically send you an invite.

**Comment by alalazo** [comment] 2021-03-10 15:05
See https://github.com/spack/spack/issues/5507#issuecomment-332660520

**Closed by alalazo** 2021-03-10 15:05 UTC
Labels: build-error
