### ISSUE TITLE
Hard links are not handled correctlt in llnl.util.filesystem.copy_tree

### ISSUE THREAD

**Issue by alecthomas** [spack/spack#14905] opened 2020-02-12 10:21 UTC
Using `buildcache create` results in a tarball without any hard links. This is often not an issue, but for some packages (most notably git), this results in a cache many times the size it should be.

```console
$ du -sh ./opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/git-2.25.0-uiijfvku32ioewkuqk4ti3vya25ifwh5/
 46M	./opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/git-2.25.0-uiijfvku32ioewkuqk4ti3vya25ifwh5/
$ du -sh ./build_cache/darwin-catalina-x86_64/clang-11.0.0-apple/git-2.25.0/darwin-catalina-x86_64-clang-11.0.0-apple-git-2.25.0-uiijfvku32ioewkuqk4ti3vya25ifwh5.spack
219M	./build_cache/darwin-catalina-x86_64/clang-11.0.0-apple/git-2.25.0/darwin-catalina-x86_64-clang-11.0.0-apple-git-2.25.0-uiijfvku32ioewkuqk4ti3vya25ifwh5.spack
```

Note that the 219MB is the compressed size. After extraction to disk it takes 556MB.

i'm guessing this occurs because Spack doesn't track hard links during relocation.

### Steps to reproduce the issue

```console
$ spack install git
$ spack buildcache create git
$ du -sh ./build_cache
```

**Comment by chissg** [comment] 2020-02-13 14:57
@gartung

**Comment by gartung** [comment] 2020-02-13 16:40
The tarfile creation and extraction needs to be checked for how it handles hardlinked files.
@scheibelp Does have any ideas.

**Comment by gartung** [comment] 2020-02-13 20:04
Depending on how old your system python is, it might suffer from this reported bug

https://bugs.python.org/issue29612****

**Comment by gartung** [comment] 2020-02-13 20:07
@alecthomas Can you tell me what version of python you are using. Spack will default to python3 if it is in the path.

**Comment by gartung** [comment] 2020-02-13 20:07
@adamjstewart Can you reproduce this bug?

**Comment by alecthomas** [comment] 2020-02-13 23:46
I'm on 3.7. As I mentioned, I'm 90% sure it's occurring during shared library relocation, not tarring itself.

**Comment by gartung** [comment] 2020-02-14 05:40
The install prefix is copied to a workdir with install_tree here:

https://github.com/spack/spack/blob/8c05221bc6b7dad8829b83d26402fcddf103719a/lib/spack/spack/binary_distribution.py#L346

and the tarfile is created here

https://github.com/spack/spack/blob/8c05221bc6b7dad8829b83d26402fcddf103719a/lib/spack/spack/binary_distribution.py#L371

one or the other is handling hardlinks incorrectly. 

I don't have Catalina on my mac laptop so I have now way to test this. 

@adamjstewart Can you try to reproduce this.

**Comment by gartung** [comment] 2020-02-14 05:52
So it looks like install_tree calls copy_tree which as far as I can tell does noting with hard linked files
https://github.com/spack/spack/blob/8c05221bc6b7dad8829b83d26402fcddf103719a/lib/spack/llnl/util/filesystem.py#L459

**Comment by gartung** [comment] 2020-02-14 22:30
Fixed by https://github.com/spack/spack/pull/15003

**Closed by gartung** 2020-02-14 22:30 UTC
Labels: bug, utilities

**Comment by alecthomas** [comment] 2020-02-16 20:21
Thanks!
