### ISSUE TITLE
Remove git messages when cloning repositories

### ISSUE THREAD

**Issue by BarrySmith** [spack/spack#3179] opened 2017-02-17 22:32 UTC
I find this type of output annoying and unnecessary for users. Having to wade through tons of this stuff seems unproductive.

```
######################################################################## 
100.0%
==> Staging archive: /Users/barrysmith/Src/spack/var/spack/stage/veclibfort-0.4.2-yhwtrkestcxarpsqiciyizj3gdjhc6zr/0.4.2.tar.gz
==> Created stage in /Users/barrysmith/Src/spack/var/spack/stage/veclibfort-0.4.2-yhwtrkestcxarpsqiciyizj3gdjhc6zr
==> No patches needed for veclibfort

Cloning into 'superlu_dist'...
remote: Counting objects: 290, done.
remote: Compressing objects: 100% (228/228), done.
remote: Total 290 (delta 139), reused 95 (delta 60), pack-reused 0
Receiving objects: 100% (290/290), 1.38 MiB | 0 bytes/s, done.
Resolving deltas: 100% (139/139), done.
==> No checksum needed when fetching with git
==> Already staged superlu-dist-xsdk-0.2.0-o2kfsovjppappoxtlsvfuaeuhcuxbsae in /Users/barrysmith/Src/spack/var/spack/stage/superlu-dist-xsdk-0.2.0-o2kfsovjppappoxtlsvfuaeuhcuxbsae
==> No patches needed for superlu-dist
```

**Comment by davydden** [comment] 2017-02-17 22:43
I think
```
Cloning into 'superlu_dist'...
remote: Counting objects: 290, done.
remote: Compressing objects: 100% (228/228), done.
remote: Total 290 (delta 139), reused 95 (delta 60), pack-reused 0
Receiving objects: 100% (290/290), 1.38 MiB | 0 bytes/s, done.
Resolving deltas: 100% (139/139), done.
```
can be removed, but I would keep the rest (with `==>`). 

I don't recall what's the source of `superlu_dist`, but i recently made `svn` fetching quite https://github.com/LLNL/spack/pull/3070

**Comment by adamjstewart** [comment] 2017-02-17 23:00
Looks like it's a `git` checkout. I agree that we can probably hide this like we did `svn`.

**Comment by adamjstewart** [comment] 2017-02-17 23:01
I don't think we need to print `No patches needed` or `No checksum needed when fetching with git`.

**Comment by davydden** [comment] 2017-02-17 23:03
> I don't think we need to print No patches needed or No checksum needed when fetching with git.

agree.

**Comment by BarrySmith** [comment] 2017-03-30 19:14
Can these git messages also be eliminated from the output?

```
==> Trying to clone git repository: https://github.com/LLNL/hypre at tag xsdk-0.2.0-rc2
Note: checking out '82828f22df56dc9e6b9acf70f4a621bcbb593ce0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>
```

**Comment by adamjstewart** [comment] 2017-03-30 19:17
Can you give us an example package that prints this information?

**Comment by davydden** [comment] 2017-03-30 19:18
Are you sure you rebased/ merged in develop?

**Comment by BarrySmith** [comment] 2017-03-30 21:29
> Can you give us an example package that prints this information?

In the branch barry/xsdk

$ ./bin/spack install hypre@xsdk-0.2.0

> Are you sure you rebased/ merged in develop?

Yes, barry/xsdk was just merged with develop.

**Comment by adamjstewart** [comment] 2017-03-30 21:38
I can confirm that this is still present in develop. If I steal `xsdk-0.2.0` from `barry/xsdk` and modify the hypre package to add:
```python
version('xsdk-0.2.0', git='https://github.com/LLNL/hypre', tag='xsdk-0.2.0-rc2')
```
I get:
```
$ spack fetch hypre@xsdk-0.2.0
==> Trying to clone git repository: https://github.com/LLNL/hypre at tag xsdk-0.2.0-rc2
Note: checking out '82828f22df56dc9e6b9acf70f4a621bcbb593ce0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

==> No checksum needed when fetching with git
```

**Closed** 2021-01-28 19:41 UTC
Labels: fetching, user-experience
