### ISSUE TITLE
Concretizer Error: Cannot concretize pism

### ISSUE THREAD

**Issue by citibeth** [spack/spack#12936] opened 2019-09-24 21:51 UTC
@tgamblin I started with a band new clone of spack on the default branch.  Then try:
```
spack spec pism
```
This should work.  Unfortunately, it fails with a conflict on `hdf5~fortran`.  Note that `hdf5~fortran` is not requested by any packages in this DAG.
```
$ bin/spack spec pism
Input spec
--------------------------------
pism

Concretized
--------------------------------
==> Error: An unsatisfiable variant constraint has been detected for spec:

    hdf5@1.10.4%gcc@4.9.3~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe arch=linux-centos7-x86_64 


while trying to concretize the partial spec:

    petsc@3.10.3%gcc@4.9.3~X clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi~mumps+shared~suite-sparse+superlu-dist~trilinos arch=linux-centos7-x86_64 
        ^hypre@2.14:~int64~internal-superlu
            ^openblas@0.3.4%gcc@4.9.3 cpu_target= ~ilp64+pic+shared threads=none ~virtual_machine arch=linux-centos7-x86_64 
        ^superlu-dist@6.1:6.1.99~int64
            ^cmake@3.13.2%gcc@4.9.3~doc+ncurses+openssl+ownlibs~qt arch=linux-centos7-x86_64 
                ^ncurses@6.1%gcc@4.9.3~symlinks~termlib arch=linux-centos7-x86_64 
                    ^pkgconf@1.5.4%gcc@4.9.3 arch=linux-centos7-x86_64 
                ^openssl@1.1.1%gcc@4.9.3+systemcerts arch=linux-centos7-x86_64 
                    ^perl@5.26.2%gcc@4.9.3+cpanm+shared+threads arch=linux-centos7-x86_64 
                        ^gdbm@1.18.1%gcc@4.9.3 arch=linux-centos7-x86_64 
                            ^readline@7.0%gcc@4.9.3 arch=linux-centos7-x86_64 
                    ^zlib@1.2.11%gcc@4.9.3+optimize+pic+shared arch=linux-centos7-x86_64 
            ^metis@5:
            ^openmpi@3.1.3%gcc@4.9.3~cuda+cxx_exceptions fabrics= ~java~legacylaunchers~memchecker~pmi schedulers= ~sqlite3~thread_multiple+vt arch=linux-centos7-x86_64 
                ^hwloc@:1.999
                ^numactl
                    ^autoconf
                        ^m4@1.4.18%gcc@4.9.3+sigsegv arch=linux-centos7-x86_64 
                            ^libsigsegv
                    ^automake
                    ^libtool
            ^parmetis


petsc requires hdf5 variant +fortran, but spec asked for ~fortran
```
Note that adding the following line to `pism/package.py` makes the problem go away:
```
    depends_on('hdf5+fortran')
```

**Comment by alalazo** [comment] 2020-11-02 20:35
Duplicate of #1781

**Closed** 2020-11-02 20:35 UTC
Labels: bug, concretization
