### ISSUE TITLE
spack setup fails with AssertionError

### ISSUE THREAD

**Issue by davydden** [spack/spack#2597] opened 2016-12-15 08:20 UTC
First time tried using `spack setup` to develop a package with Spack, and unfortunately it did not work. Looks like something is failing here related to compiler (line `1373`), which does not make much sense to me:
```
$ spack setup dealii@develop
Traceback (most recent call last):
  File "/Users/davydden/spack/bin/spack", line 198, in <module>
    main()
  File "/Users/davydden/spack/bin/spack", line 175, in main
    return_val = command(parser, args)
  File "/Users/davydden/spack/lib/spack/spack/cmd/setup.py", line 178, in setup
    install.install(parser, inst_args)
  File "/Users/davydden/spack/lib/spack/spack/cmd/install.py", line 317, in install
    specs = spack.cmd.parse_specs(args.package, concretize=True)
  File "/Users/davydden/spack/lib/spack/spack/cmd/__init__.py", line 108, in parse_specs
    spec.concretize()  # implies normalize
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 1543, in concretize
    self._concretize_helper())
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 1362, in _concretize_helper
    changed |= dep.spec._concretize_helper(presets, visited)
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 1373, in _concretize_helper
    spack.concretizer.concretize_compiler(self),
  File "/Users/davydden/spack/lib/spack/spack/concretize.py", line 341, in concretize_compiler
    find_spec(spec, lambda x: x.compiler and not x.build_dep()) or
  File "/Users/davydden/spack/lib/spack/spack/concretize.py", line 474, in find_spec
    if condition(relative):
  File "/Users/davydden/spack/lib/spack/spack/concretize.py", line 341, in <lambda>
    find_spec(spec, lambda x: x.compiler and not x.build_dep()) or
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 1329, in build_dep
    return not (self.root in
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 951, in root
    assert(all(first_root is d.spec.root for d in depiter))
AssertionError
```
Then I try
```
$ spack setup dealii@develop%clang
Traceback (most recent call last):
  File "/Users/davydden/spack/bin/spack", line 198, in <module>
    main()
  File "/Users/davydden/spack/bin/spack", line 175, in main
    return_val = command(parser, args)
  File "/Users/davydden/spack/lib/spack/spack/cmd/setup.py", line 178, in setup
    install.install(parser, inst_args)
  File "/Users/davydden/spack/lib/spack/spack/cmd/install.py", line 317, in install
    specs = spack.cmd.parse_specs(args.package, concretize=True)
  File "/Users/davydden/spack/lib/spack/spack/cmd/__init__.py", line 108, in parse_specs
    spec.concretize()  # implies normalize
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 1543, in concretize
    self._concretize_helper())
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 1362, in _concretize_helper
    changed |= dep.spec._concretize_helper(presets, visited)
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 1372, in _concretize_helper
    (spack.concretizer.concretize_architecture(self),
  File "/Users/davydden/spack/lib/spack/spack/concretize.py", line 255, in concretize_architecture
    if spec.build_dep() and spec.disjoint_build_tree():
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 1329, in build_dep
    return not (self.root in
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 951, in root
    assert(all(first_root is d.spec.root for d in depiter))
AssertionError
```
and the error path is similar, BUT it now has something related to architecture (line `1372`).

---

`packages.yaml`:
```
packages:
  all:
    compiler: [clang, gcc]
    providers:
      mpi: [openmpi]
      blas: [openblas]
      lapack: [openblas]
  libtool:
    compiler: [clang]
  cmake:
    version: [3.6.1]
    compiler: [clang]
  curl:
    version: [7.50.3]
  openssl:
    version: [1.0.2j]
  boost:
    version: [1.62.0]
    variants: +python
  dealii:
    version: [develop]
    variants: ~oce~doc
```
and `compiler.yaml`
```
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
      cxx: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
      f77: /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.2.0-yuzfgyrrvsnlutzrys2hwgbr47km7cql/bin/gfortran
      fc: /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.2.0-yuzfgyrrvsnlutzrys2hwgbr47km7cql/bin/gfortran
    spec: clang@8.0.0-apple
    target: x86_64
```

**Comment by citibeth** [comment] 2016-12-15 12:38
Does `spack spec` work for you?

**Comment by davydden** [comment] 2016-12-15 12:39
> Does spack spec work for you?

sure. I would be very unhappy if it did not :smile:

**Comment by citibeth** [comment] 2016-12-15 13:02
:( @tgamblin

All I can say is... it works for me on what's now an out-of-date branch.  I
did a couple of updates to get it working again, but this is not one of the
problems I saw.

Things have been changing rapidly, and apparently `spack setup` has been
broken at least a few times.  This is why we need regression tests...

**Comment by davydden** [comment] 2016-12-15 13:10
For the record, I see this behaviour on f613445eb2c0bf89ae54803754d46e7cbca64c49 (which is very recent).

> This is why we need regression tests...

can one not add a few for `spack setup` using (preferably builtin packages or in the worst case mockup packages? Now idea in what part of the testing suite would they go, but it should be possible, right @tgamblin ?

**Comment by scheibelp** [comment] 2016-12-15 19:48
Once #2292 is reverted with https://github.com/LLNL/spack/pull/2549 this error should no longer occur. The issue should likely remain to promote testing spack setup

**Comment by citibeth** [comment] 2016-12-15 21:27
BTW... What do you mean by "frontend compiler?"

**Comment by scheibelp** [comment] 2016-12-15 21:40
>BTW... What do you mean by "frontend compiler?"

I mean building toward the frontend architecture (frontend target/os of the platform). It is potentially misleading for me to say "frontend compiler" since the same compiler could be used for both targets.

**Comment by citibeth** [comment] 2016-12-15 21:48
I see... so on non-HPC systems with just on architecture, in theory
building build deps with the frontend compiler should have no effect.

**Comment by scheibelp** [comment] 2016-12-15 21:53
>> I see... so on non-HPC systems with just on architecture, in theory building build deps with the frontend compiler should have no effect.

Yes although if there are multiple compilers available for the frontend right now the concretizer may choose different ones for the build dependencies. This will disappear temporarily when #2549 is merged (which is soon likely today) but may come up again with #2548

**Comment by citibeth** [comment] 2016-12-16 03:29
Hmm... for the average user of a simple installation who just wants to set
up one compiler... having Spack use more than the "primary" compiler would
seem to be counter-intuitive.

**Comment by scheibelp** [comment] 2016-12-16 05:20
I think I could make it so the build dependencies get the same compiler in cases where there isn't a frontend/backend distinction - I've added a TODO over at #2548

**Comment by davydden** [comment] 2016-12-20 21:03
#2292 is reverted with https://github.com/LLNL/spack/pull/2549, but still on 3f1cdbf5efb6092d806a25f35c87b7b6b3b78364  there is 
```
$ spack setup dealii@develop
Traceback (most recent call last):
  File "/Users/davydden/spack/bin/spack", line 198, in <module>
    main()
  File "/Users/davydden/spack/bin/spack", line 175, in main
    return_val = command(parser, args)
  File "/Users/davydden/spack/lib/spack/spack/cmd/setup.py", line 178, in setup
    install.install(parser, inst_args)
  File "/Users/davydden/spack/lib/spack/spack/cmd/install.py", line 317, in install
    specs = spack.cmd.parse_specs(args.package, concretize=True)
  File "/Users/davydden/spack/lib/spack/spack/cmd/__init__.py", line 108, in parse_specs
    spec.concretize()  # implies normalize
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 1506, in concretize
    self._concretize_helper())
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 1345, in _concretize_helper
    name].spec._concretize_helper(presets, visited)
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 1355, in _concretize_helper
    (spack.concretizer.concretize_architecture(self),
  File "/Users/davydden/spack/lib/spack/spack/concretize.py", line 254, in concretize_architecture
    root_arch = spec.root.architecture
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 951, in root
    assert(all(first_root is d.spec.root for d in depiter))
AssertionError
```

**Comment by scheibelp** [comment] 2016-12-21 03:44
I can replicate this; I'll see if I can track down the issue in the next couple days

**Closed** 2020-09-02 01:07 UTC
Labels: bug, tests
