### ISSUE TITLE
Error: Cannot Uninstall

### ISSUE THREAD

**Issue by citibeth** [spack/spack#7954] opened 2018-05-01 13:49 UTC
Summary
----------
Spack not able to uninstall a package, for unknown reason.  When the same `spack uninstall` command was repedated immediately thereafter, uninstall was successful.

Expected Result
-----------------
Spack should have been able to uninstall the first time.

```
$ spack uninstall --all -R petsc
==> The following packages will be uninstalled:

-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
2ohcasx petsc@3.7.4%gcc+boost clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi~mumps+shared~suite-sparse+superlu-dist~trilinos

htjzbhl petsc@3.7.4%gcc+boost clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi+mumps+shared~suite-sparse+superlu-dist~trilinos

slptbai petsc@3.8.4%gcc+boost clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi~mumps patches=22392530068e375ce8b62a1f552b43fbfd2e20822002c69dbafab4d3fa787cbb +shared~suite-sparse+superlu-dist~trilinos

fjv6g6y pism@0.7.3%gcc build_type=RelWithDebInfo ~doc+everytrace+examples~extra+icebin~parallel-hdf5~parallel-netcdf3~parallel-netcdf4+proj~python+shared

lre6rol pism@0.7.3%gcc build_type=RelWithDebInfo ~doc+everytrace+examples~extra+icebin~parallel-hdf5~parallel-netcdf3~parallel-netcdf4+proj~python+shared

yphtfji pism@0.7.3%gcc build_type=RelWithDebInfo ~doc+everytrace+examples~extra+icebin~parallel-hdf5~parallel-netcdf3~parallel-netcdf4+proj~python+shared

==> Do you want to proceed? [y/N] y
==> Successfully uninstalled pism@0.7.3%gcc@4.9.3 build_type=RelWithDebInfo ~doc+everytrace+examples~extra+icebin~parallel-hdf5~parallel-netcdf3~parallel-netcdf4+proj~python+shared arch=linux-centos7-x86_64 /fjv6g6y
==> Successfully uninstalled pism@0.7.3%gcc@4.9.3 build_type=RelWithDebInfo ~doc+everytrace+examples~extra+icebin~parallel-hdf5~parallel-netcdf3~parallel-netcdf4+proj~python+shared arch=linux-centos7-x86_64 /yphtfji
==> Successfully uninstalled pism@0.7.3%gcc@4.9.3 build_type=RelWithDebInfo ~doc+everytrace+examples~extra+icebin~parallel-hdf5~parallel-netcdf3~parallel-netcdf4+proj~python+shared arch=linux-centos7-x86_64 /lre6rol
==> Successfully uninstalled petsc@3.7.4%gcc@4.9.3+boost clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi~mumps+shared~suite-sparse+superlu-dist~trilinos arch=linux-centos7-x86_64 /2ohcasx
==> Error: Cannot uninstall petsc@3.8.4%gcc@4.9.3+boost clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi~mumps patches=22392530068e375ce8b62a1f552b43fbfd2e20822002c69dbafab4d3fa787cbb +shared~suite-sparse+superlu-dist~trilinos arch=linux-centos7-x86_64 ^hdf5@1.8.18%gcc@4.9.3~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe arch=linux-centos7-x86_64 ^hwloc@1.11.9%gcc@4.9.3~cairo~cuda+libxml2+pci+shared arch=linux-centos7-x86_64 ^hypre@2.13.0%gcc@4.9.3~int64~internal-superlu+mpi+shared arch=linux-centos7-x86_64 ^libpciaccess@0.13.5%gcc@4.9.3 arch=linux-centos7-x86_64 ^libxml2@2.9.4%gcc@4.9.3~python arch=linux-centos7-x86_64 ^metis@5.1.0%gcc@4.9.3 build_type=Release ~gdb~int64 patches=4991da938c1d3a1d3dea78e49bbebecba00273f98df2a656e38b83d55b281da1 ~real64+shared arch=linux-centos7-x86_64 ^numactl@2.0.11%gcc@4.9.3 arch=linux-centos7-x86_64 ^openblas@0.2.20%gcc@4.9.3 cpu_target= ~ilp64 patches=47cfa7a952ac7b2e4632c73ae199d69fb54490627b66a62c681e21019c4ddc9d +pic+shared threads=none ~virtual_machine arch=linux-centos7-x86_64 ^openmpi@3.0.1%gcc@4.9.3~cuda fabrics= ~java~memchecker~pmi schedulers= ~sqlite3~thread_multiple~ucx+vt arch=linux-centos7-x86_64 ^parmetis@4.0.3%gcc@4.9.3 build_type=RelWithDebInfo ~gdb patches=4f892531eb0a807eb1b82e683a416d3e35154a455274cf9b162fb02054d11a5b,50ed2081bc939269689789942067c58b3e522c269269a430d5d34c00edbc5870,704b84f7c7444d4372cb59cca6e1209df4ef3b033bc4ee3cf50f369bce972a9d +shared arch=linux-centos7-x86_64 ^superlu-dist@5.2.2%gcc@4.9.3~int64 arch=linux-centos7-x86_64 ^xz@5.2.3%gcc@4.9.3 arch=linux-centos7-x86_64 ^zlib@1.2.11%gcc@4.9.3+optimize+pic+shared arch=linux-centos7-x86_64
$ spack uninstall --all -R petsc
==> The following packages will be uninstalled:

-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
htjzbhl petsc@3.7.4%gcc+boost clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi+mumps+shared~suite-sparse+superlu-dist~trilinos

slptbai petsc@3.8.4%gcc+boost clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi~mumps patches=22392530068e375ce8b62a1f552b43fbfd2e20822002c69dbafab4d3fa787cbb +shared~suite-sparse+superlu-dist~trilinos

eyl27yz pism@icebin%gcc build_type=RelWithDebInfo ~doc+everytrace+examples~extra+icebin~parallel-hdf5~parallel-netcdf3~parallel-netcdf4+proj~python+shared

==> Do you want to proceed? [y/N] y
==> Successfully uninstalled petsc@3.7.4%gcc@4.9.3+boost clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi+mumps+shared~suite-sparse+superlu-dist~trilinos arch=linux-centos7-x86_64 /htjzbhl
==> Successfully uninstalled pism@icebin%gcc@4.9.3 build_type=RelWithDebInfo ~doc+everytrace+examples~extra+icebin~parallel-hdf5~parallel-netcdf3~parallel-netcdf4+proj~python+shared arch=linux-centos7-x86_64 /eyl27yz
==> Successfully uninstalled petsc@3.8.4%gcc@4.9.3+boost clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi~mumps patches=22392530068e375ce8b62a1f552b43fbfd2e20822002c69dbafab4d3fa787cbb +shared~suite-sparse+superlu-dist~trilinos arch=linux-centos7-x86_64 /slptbai
$ spack uninstall --all -R petsc
==> Error: petsc does not match any installed packages.
==> Error: You can either:
    a) use a more specific spec, or
    b) use `spack uninstall --all` to uninstall ALL matching specs.

**Comment by adamjstewart** [comment] 2018-05-01 14:03
Duplicate of #3690.

**Closed by adamjstewart** 2018-05-01 14:03 UTC
Labels: bug
