### ISSUE TITLE
spack checksum output fails when added to a package and spack install'ed

### ISSUE THREAD

**Issue by hartzell** [spack/spack#15273] opened 2020-02-28 23:44 UTC
### Spack version

```console
[ghartzell@bifx1n03 spack-update-kallisto]$ which spack
~/tmp/spack-update-kallisto/bin/spack
[ghartzell@bifx1n03 spack-update-kallisto]$ spack --version
0.9-11552-38d5d73
```

### Steps to reproduce the issue

```console
$ spack checksum kallisto
# tell it to just do 1 (which was 0.46.2 for me)
$ spack edit kallisto
# add the new version info
$ spack install kallisto
[+] /home/ghartzell/tmp/spack-update-kallisto/opt/spack/linux-centos7-skylake_avx512/gcc-8.2.0/pkgconf-1.6.3-ohs2mgjc3t3mwk7tmvryh5r5rsuyyqvq
[+] /home/ghartzell/tmp/spack-update-kallisto/opt/spack/linux-centos7-skylake_avx512/gcc-
[...]
==> Fetching https://github.com/pachterlab/kallisto/archive/v0.46.2.tar.gz
######################################################################## 100.0%
==> Error: ChecksumError: sha256 checksum failed for /tmp/ghartzell/spack-stage/spack-stage-kallisto-0.46.2-2cya5t4j2epry6ttce7w2bm5eeoqurjf/v0.46.2.tar.gz
    Expected 49574ca9c714a23437b7dbc4f6979b944243af7da62df3a90181c5999e2785b9 but got c447ca8ddc40fcbd7d877d7c868bc8b72807aa8823a8a8d659e19bdd515baaf2

```

### Error Message

see above

### Information on your system

CentOS 7 on amd64.

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output
    - see https://gist.github.com/hartzell/44eb1749ee93b9b63e4d8a36b5baad7d

**Comment by alalazo** [comment] 2020-02-29 13:15
I think there's a mismatch of `url` between what `spack checksum` found when crawling and the `url` that was expected in the package. The first `url` found by `spack checksum` is:
```
https://github.com/pachterlab/kallisto/releases/download/v0.46.2/kallisto_rock64-v0.46.2.tar.gz
```
but what the package tries to download is the source archive which is instead:
```
https://github.com/pachterlab/kallisto/archive/v0.46.2.tar.gz
```
Bounced a bit back and forth with triaging as I'm not even sure we should consider this a bug (spack checksum was never meant afaik to work automatically but is a simple helper that needs to be checked by a user).

**Comment by alalazo** [comment] 2020-02-29 13:19
OT:

> [ghartzell@bifx1n03 spack-update-kallisto]$ spack --version
0.9-11552-38d5d73

Forked at Spack 0.9 and now you are 11552 commit ahead of that. Can you please post the entire commit hash? We have a commit from a few days ago that starts like that, but moving at that commit I get:
```console
$ spack --version
0.14.0-70-38d5d7304
```
so I'm wondering if there's something going on here.

**Comment by hartzell** [comment] 2020-02-29 15:42
Yeah, I noticed that, but figured that it had something to do with how things were tagged or ... and then just blew it off.  Now that I think of it, it's kind of weird....

```
$ which spack
/usr/bin/which: no spack in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
$ ls
bin  CHANGELOG.md  COPYRIGHT  etc  lib  LICENSE-APACHE  LICENSE-MIT  NOTICE  opt  README.md  share  var
$ export PATH=$(pwd)/bin:$PATH
$ spack --version
0.9-11552-38d5d73
$ git log | head -3
commit 38d5d7304d36f92a383ebda280883171df228c3a
Author: Erik Schnetter <schnetter@gmail.com>
Date:   Fri Feb 28 12:32:41 2020 -0500
[ghartzell@bifx1n03 spack-update-kallisto]$
```

Looks like it's using the output of `git describe` ([details here](https://github.com/spack/spack/blob/develop/lib/spack/spack/main.py#L113-L139)).

```
$ git describe --tags
v0.9-11552-g38d5d7304
$ spack --version
0.9-11552-38d5d7304
$
```

I suspect that this is not part of the behavior that I'm seeing.

**Comment by hartzell** [comment] 2020-02-29 15:50
> spack checksum was never meant afaik to work automatically but is a simple helper that needs to be checked by a user

What's funny about this is that I was showing a new user how to update a spack package and went through my usual song and dance about copying-and-pasting an existing line, hacking the checksum, trying the build, and finally updating the checksum with the value reported in the error message.  

Then I explained, _sheepishly_, that there's a checksum command but that I have a vague memory of having trouble with it so I somewhat irrationally avoid it.

Then it didn't work when I demo'ed it and figured that I had a concrete case and should report it.

This isn't a big deal, but it seems like (famous last words...) it should be using the same code path as the `install` fetcher, so :open_mouth:?

**Comment by alalazo** [comment] 2020-02-29 19:46
> This isn't a big deal, but it seems like (famous last words...) it should be using the same code path as the install fetcher, so open_mouth?

Yeah, completely agree that it is kind of unexpected to have `spack checksum` not using the same pattern substitution as `spack install`.

**Comment by alalazo** [comment] 2020-02-29 19:51
> I suspect that this is not part of the behavior that I'm seeing.

It's definitely not related, but could you check if `git fetch --tags` changes the output?

**Comment by hartzell** [comment] 2020-02-29 20:22
Nope.  Err, yes I can check, no it does not seem to change the output:

```
$ git describe --tags
v0.9-11552-g38d5d73
$ git fetch --tags
$ git describe --tags
v0.9-11552-g38d5d73
$ ./bin/spack --version
0.9-11552-38d5d73
$ git tag --list
old-install-layout
v0.8
v0.8.10
v0.8.11
v0.8.15
v0.8.16
v0.8.17
v0.8.5
v0.9
v0.9.1
```

A bigger stick does change the output though:

```
$ git remote -v
origin	https://github.com/hartzell/spack (fetch)
origin	https://github.com/hartzell/spack (push)
$ git remote add upstream https://github.com/spack/spack
$ git fetch --tags upstream
remote: Enumerating objects: 146, done.
remote: Counting objects: 100% (146/146), done.
remote: Total 327 (delta 146), reused 146 (delta 146), pack-reused 181
Receiving objects: 100% (327/327), 107.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (160/160), completed with 69 local objects.
From https://github.com/spack/spack
 * [new tag]         NCSA-v1    -> NCSA-v1
 * [new tag]         NCSA-v2    -> NCSA-v2
 * [new tag]         efischer/docs-v1 -> efischer/docs-v1
 * [new tag]         v0.10.0    -> v0.10.0
 * [new tag]         v0.11.0    -> v0.11.0
 * [new tag]         v0.11.1    -> v0.11.1
 * [new tag]         v0.11.2    -> v0.11.2
 * [new tag]         v0.12.0    -> v0.12.0
 * [new tag]         v0.12.1    -> v0.12.1
 * [new tag]         v0.13.0    -> v0.13.0
 * [new tag]         v0.13.1    -> v0.13.1
 * [new tag]         v0.13.2    -> v0.13.2
 * [new tag]         v0.13.3    -> v0.13.3
 * [new tag]         v0.13.4    -> v0.13.4
 * [new tag]         v0.14.0    -> v0.14.0
$ git describe --tags
v0.14.0-70-g38d5d73
$ ./bin/spack --version
0.14.0-70-38d5d73
$
```

**Comment by alalazo** [comment] 2020-02-29 20:29
@hartzell Good to know this might happen with outdated tags in a fork. Thanks.

**Comment by adamjstewart** [comment] 2020-03-01 00:04
Interesting, I also experienced the same problem with `spack --version` (it said I was on 0.13.3-1352-d105807a48). Running `git fetch --tags upstream` fixed the problem.

**Comment by adamjstewart** [comment] 2021-01-16 20:26
Duplicate of #14129

**Closed by adamjstewart** 2021-01-16 20:26 UTC
Labels: bug, fetching, impact-low
