### ISSUE TITLE
MIT/Apache-2.0 Relicense Discussion

### ISSUE THREAD

**Issue by tgamblin** [spack/spack#9145] opened 2018-08-31 07:10 UTC
### Summary
See #9144 for details on what we're trying to do. This issue is for general discussion, since that issue is likely to become crowded with consent notifications.  If you just want to be part of the discussion, unsubscribe from #9137 and #9144, and subscribe to this issue.

### Why MIT / Apache-2.0?
We want to make this change so that Spack can be used as widely as possible. At many organizations, it is difficult or cumbersome to use LGPL-licensed packages, but a number of those organizations have expressed interest in contributing to Spack. The Apache 2.0 license contains important protection against patent aggression, but it is not compatible with the GPL, version 2. The MIT license allows Spack to be integrated with GPLv2 projects. We believe that this combination will appeal to the broadest possible base of users and contributors, and that it will enable us to grow the Spack community most effectively.

**Comment by HadrienG2** [comment] 2018-08-31 07:52
#9137 sounds like a gold mine for spambots. Wouldn't it be better to collect e-mail addresses via a private communication channel (e.g. ask everyone to send you an e-mail)?

**Comment by tgamblin** [comment] 2018-08-31 08:08
@HadrienG2: we didn't ask everyone to do so, as we wanted to make it as easy as possible for people to respond.  But we did give people that option.  Some people are sending private responses to maintainers@spack.io.

But in general, I am not sure it makes much of a difference. If someone wants to get all of these emails, they can simply clone the spack repository and see the emails.  They can also already spider github.  e.g., [see here](https://github.com/spack/spack/commit/a7f3fa01d5e06f2614087d35db51a400ff26c12c.patch).

**Comment by HadrienG2** [comment] 2018-08-31 09:39
Ah, sorry, I missed that part. I agree that DVCSes sadly give away that sensitive information by design. But if we can contain the leak to crawlers specialized in code repositories as opposed to general-purpose web crawlers that go the dumb route of jumping from one link to another, I think that's already a small win.

**Comment by paul-chelarescu** [comment] 2018-08-31 12:35
I agree with @HadrienG2, collecting all the emails should not be as easy as crawling an entire page. Unfortunately DVCSes do give away that information but the ease of collecting that information does matter in practice.

**Comment by boegel** [comment] 2018-08-31 13:35
Two questions:

* is there an easy way to re-check all contributions that were made
* what will happen with contributions for which no approval is received, will they be removed?

**Comment by wohlbier** [comment] 2018-08-31 13:39
A search for my name in the spack repo quickly showed me all of my activity. Don't use author: or user: stuff. Just your name.

**Comment by baberlevi** [comment] 2018-08-31 13:48
I don't have a good understanding on why the current license is troublesome for some organizations, so some additional explanation of that may be helpful.

If we reply that we're ok with the change, but only ok with moving to Apache 2.0 for instance, and not the MIT license for our contributions how would we record that ?

**Comment by boegel** [comment] 2018-08-31 13:51
@wohlbier That doesn't yield a complete list for me...

https://github.com/spack/spack/search?q=boegel&unscoped_q=boegel&type=Issues doesn't include stuff that is listed here https://github.com/spack/spack/pulls/boegel (+ click 'Closed')...

**Comment by tgamblin** [comment] 2018-08-31 14:30
The easiest way I know to search a repo for your commits is to clone it, then for each email you've used:

```console
$ git log --author="<your email>"
```

**Comment by tgamblin** [comment] 2018-08-31 14:39
@boegel:

> what will happen with contributions for which no approval is received, will they be removed?

We'll need to evaluate that if we can't get consent from all users.  The plan is:

1. We would like very much to get consent for everything.
2. Barring that, we would like to get consent for Spack core, which has many fewer contributors (~100) than all of Spack.  We will probably relicense the core first if we can, then update the packages as approvals come in.  LGPL packages can be distributed with an MIT/Apache-licensed Spack, but we'd like to eventually have the whole thing MIT/Apache-2.0 to avoid confusion.

If we don't get approval for everything, we will go back and work with LLNL legal to evaluate what's left and whether we should remove them, rewrite them, etc.  But we would rather not do that -- things are *much* easier with approval and we are trying to go that route.

**Comment by tgamblin** [comment] 2018-08-31 15:09
@baberlevi: 

> I don't have a good understanding on why the current license is troublesome for some organizations, so some additional explanation of that may be helpful.

There are a several scenarios we are trying to address (I might add to this list as I think of more):

1. **Corporate policies.** The main thing we're trying to do is reduce barriers to use and contribution.  We've been told by several companies that because Spack is LGPL-licensed, they have to go through an approval process to use it in their organization, while they could easily use licenses like Apache 2.0 and MIT with no trouble.  We'd like to make it easy for these people to contribute and help maintain packages.  Examples of companies with policies like this are Google ([see here](https://opensource.google.com/docs/thirdparty/licenses/#restricted)), Amazon, GE, and others.
2. **Other organizations.**  There are non-corporate projects like the [xSDK](https://xsdk.info/) under the U.S. [Exascale Project](https://exascaleproject.org) that are moving towards permissive licenses and want to require them for membership.  This isn't unprecedented, the European [GEANT](https://geant3plus.archive.geant.net/About/Documents/GN3_10_325GEANTIPRPolicyv1.2_30SEP11.pdf
) organization also only gives "Green" status to MIT, BSD, and Apache 2.0, and requires special approval for inclusion of other ("Red") licenses. This is similar to (1) -- we want to remove obstacles.
3. **NDA confusion.** There is extra worry around Non-disclosure Agreements (NDA).  We work with a lot of hardware vendors, and in many cases we'd like them to work on Spack support for hardware and compilers that may be NDA because they're not released yet. For example, they may need to update compiler descriptions, or rework some of the architecture support or the internals around dependency management, and LGPL is a red flag if the changes relate to unreleased hardware.  We'd like to make it easier for vendors to add support for new architectures before they are released.

The main thing we're heading off here is uncertainty.  There may not be *technical* obstacles to using LGPL in these scenarios, but people worry about them and they have to think about it. I've been asked by a lot of people why I can't make the license more permissive because of concerns like this, but no one has asked me to make the license more restrictive (e.g., GPL).

Finally, we think the potential benefit of more contributors is greater than the risk that some people won't contribute back. In my experience thus far, *most* companies want to contribute back to Spack, so that they don't have to maintain fixes.  I think they will do so, even under an Apache2 or MIT license, because the value of Spack is in inclusion in the mainline and the support of the community.  If the license isn't easy for people to use, or if there is uncertainty around it, we think we may lose these potential contributors.

**Comment by reidpr** [comment] 2018-08-31 15:32
> what will happen with contributions for which no approval is received, will they be removed?

You might also see if you really need approval for trivial contributions like mine. (I did send in my approval by e-mail though.)

**Comment by tgamblin** [comment] 2018-08-31 15:36
> You might also see if you really need approval for trivial contributions like mine. (I did send in my approval by e-mail though.)

Yep -- thanks!  This is another option, though I'd rather not have to do it.  Legal would have to decide what is "trivial" vs. copyrightable, and approval makes things much easier.

**Comment by paul-chelarescu** [comment] 2018-09-12 08:53
@tgamblin yes, that is fine. I have just sent an email to that address.

**Closed** 2018-10-17 21:42 UTC
Labels: discussion, relicense
