### ISSUE TITLE
Concretizations crashes if the same spec string is concretized twice.

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2666] opened 2016-12-22 05:48 UTC
@tgamblin In #2664, we seem to have discovered that many strange bugs happen when you concretize a spec more than once in a run of Spack.  We're solving the immediate problem by removing unnecessary (and VERY inefficient) multiple concretizations.  But I think this also points to a possible problem somewhere deep in the concretization / memoization logic; a bug that could bite us again elsewhere.

**Comment by tgamblin** [comment] 2016-12-22 05:51
What is this issue asking?  I don't know how to address it.  There are already issues open about concretization for 0.10 that I'm working on. Do you have a reproducer?  If not please close and reopen with something concrete.

**Comment by citibeth** [comment] 2016-12-22 14:19
> Do you have a reproducer?

See #2662 

> What is this issue asking?  There are already issues open about concretization for 0.10 that I'm working on.

This may be the first time we've suspected or concluded that concretizing the same thing more than once could be contributing to the problems.  It is therefore useful information, if it turns out that multiple concretization really is triggering a bug.

> I don't know how to address it.

Probably this is just something to be aware of.  I believe we're getting around this problem in #2664.  Although we shouldn't be concretizing multiple times anyway...

**Comment by tgamblin** [comment] 2016-12-22 14:44
Concretization is idempotent:
https://github.com/LLNL/spack/blob/3f1cdbf/lib/spack/spack/spec.py#L1497

If the problem is #2662, there is already have an issue for that.  I don't understand why one problem needs two issues.  One is sufficient.

**Comment by citibeth** [comment] 2016-12-22 15:06
> Concretization is idempotent:

I see... but something was not working.  Why else would `spack setup` and `spack install` give such different behavior in #2662?

>  I don't understand why one problem needs two issues.

#2662 is fixed by #2664, so I expect it will be closed soon.

**Comment by scheibelp** [comment] 2016-12-22 18:40
> Concretization is idempotent:
https://github.com/LLNL/spack/blob/3f1cdbf/lib/spack/spack/spec.py#L1497

The issue I think is being reported is

```
x = Spec('dealii@develop')
x.concretize()
y = Spec('dealii@develop')
y.concretize()
```

rather than

```
x = Spec('dealii@develop')
x.concretize()
x.concretize()
```

The referenced line handles the second case but not the first. And actually that also seems to be a good reproducer:

```
spack python
>>> from spack.spec import Spec
>>> x = Spec('dealii@develop')
>>> x.concretize()
>>> y = Spec('dealii@develop')
>>> y.concretize()
Traceback (most recent call last)...
```

**Comment by citibeth** [comment] 2016-12-22 18:46
Yes, I think you nailed the core issue.  I think this is a better explanation of the problem than #2662.
(Was not aware of the `spack python` command... I should review all Spack commands someday).

**Comment by alalazo** [comment] 2017-01-11 13:26
> Yes, I think you nailed the core issue. I think this is a better explanation of the problem than #2662.
(Was not aware of the spack python command... I should review all Spack commands someday).

@citibeth Can we close #2662 then?

**Comment by alalazo** [comment] 2017-11-22 13:25
Closing this:
```python
Spack version 0.10.0
Python 2.7.6, Linux x86_64
>>> from spack.spec import Spec
>>> x = Spec('dealii@develop')
>>> x.concretize()
>>> y = Spec('dealii@develop')
>>> y.concretize()
>>> 

```

**Closed by alalazo** 2017-11-22 13:25 UTC
Labels: bug, concretization
