### ISSUE TITLE
Spack broken out of the box on Cray (cle6.0).

### ISSUE THREAD

**Issue by CalvinDSeamons** [spack/spack#13223] opened 2019-10-15 18:07 UTC
Cloning the most current version of spack onto a Cray machine with OS cle6.0 results in the following error: 
```console
$ share/spack/setup-env.sh 
Traceback (most recent call last):
  File "/spack/bin/spack", line 63, in <module>
    import spack.main  # noqa
  File "/spack/lib/spack/spack/main.py", line 28, in <module>
    import spack.architecture
  File "/spack/lib/spack/spack/architecture.py", line 68, in <module>
    import spack.compiler
  File "/spack/lib/spack/spack/compiler.py", line 18, in <module>
    import spack.spec
  File "/spack/lib/spack/spack/spec.py", line 106, in <module>
    import spack.repo
  File "/spack/lib/spack/spack/repo.py", line 36, in <module>
    import spack.caches
  File "/spack/lib/spack/spack/caches.py", line 14, in <module>
    import spack.fetch_strategy
  File "/spack/lib/spack/spack/fetch_strategy.py", line 30, in <module>
    import xml.etree.ElementTree
  File "/usr/lib64/python3.4/_import_failed/xml.py", line 17, in <module>
    to install it.""".format(__name__, package))
ImportError: Module 'xml' is not installed.
Use:
  sudo zypper install python3
to install it.
```
I can work around this by unloading python2 and appending python 3 to my path. On `cle7` and `toss3` machines python2 works fine and spack runs normally without having to change this.  </br>
Any recommendations would be appreciated.

**Comment by adamjstewart** [comment] 2019-10-16 03:37
It looks like your Python 2 installation was built without `pyexpat` support. To solve this, you'll need to rebuild Python with the `expat` dependency present at install time. You could complain to your sys admins, or you could run Spack with Python 3 instead. You can also build `python+pyexpat` with Spack.

**Comment by alalazo** [comment] 2019-10-16 12:21
On top of what @adamjstewart says, I find strange that if you have the Python 2.7.X module loaded the error says:
```
[...]
File "/usr/lib64/python3.4/_import_failed/xml.py", line 17, in <module>
    to install it.""".format(__name__, package))
ImportError: Module 'xml' is not installed.
```
which means that default locations for Python 3.4 are still in `sys.path`? Also, note that Python 3.4 is not officially supported by Spack - for Python 3 we start testing from 3.5.

**Comment by adamjstewart** [comment] 2019-10-16 21:27
Oh, good point. Make sure your `PYTHONHOME` and `PYTHONPATH` are correctly set.

**Comment by Paul-Ferrell** [comment] 2019-10-21 20:28
Our Cray systems have a python3 that is missing a bunch of stdlib libraries. The missing ones are probably available via yum though.  

So, yes, it's a problem on our end.

**Comment by adamjstewart** [comment] 2019-10-21 20:33
Closing now that we've confirmed it's a problem with your Python installation and not a problem with Spack.

**Closed by adamjstewart** 2019-10-21 20:33 UTC
Labels: bug, python
