### ISSUE TITLE
no warn prompt after installing singularity

### ISSUE THREAD

**Issue by refraction-ray** [spack/spack#11561] opened 2019-05-25 07:29 UTC
OS: ubuntu 18.04 server
spack version: develop branch head

By reading `spack edit singularity`, I believe that there should be a warning prompt telling the users to run `spack_perms_fix.sh`, which seems to fix some permission issues and necessary for singularity to run by normal user.

However I don't see such warning prompt somehow by `spack install singularity`, which might confuse users when later they find singularity doesn't work as they expected.

## addition info
Though I dont think it relevant, but anyway below is the singularity spec in my case

```bash
$ spack spec singularity
Input spec
--------------------------------
singularity

Concretized
--------------------------------
singularity@3.1.1%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
    ^go@1.11.5%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
        ^git@2.21.0%gcc@7.4.0~tcltk arch=linux-ubuntu18.04-x86_64
            ^autoconf@2.69%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
                ^m4@1.4.18%gcc@7.4.0 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-ubuntu18.04-x86_64
                    ^libsigsegv@2.11%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
                ^perl@5.26.2%gcc@7.4.0+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-ubuntu18.04-x86_64
                    ^gdbm@1.18.1%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
                        ^readline@7.0%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
                            ^ncurses@6.1%gcc@7.4.0~symlinks~termlib arch=linux-ubuntu18.04-x86_64
                                ^pkgconf@1.6.0%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
            ^automake@1.16.1%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
            ^curl@7.63.0%gcc@7.4.0~darwinssl~gssapi~libssh~libssh2~nghttp2 arch=linux-ubuntu18.04-x86_64
                ^openssl@1.1.1b%gcc@7.4.0+systemcerts arch=linux-ubuntu18.04-x86_64
                    ^zlib@1.2.11%gcc@7.4.0+optimize+pic+shared arch=linux-ubuntu18.04-x86_64
            ^expat@2.2.5%gcc@7.4.0+libbsd arch=linux-ubuntu18.04-x86_64
                ^libbsd@0.9.1%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
            ^gettext@0.19.8.1%gcc@7.4.0+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=linux-ubuntu18.04-x86_64
                ^bzip2@1.0.6%gcc@7.4.0+shared arch=linux-ubuntu18.04-x86_64
                    ^diffutils@3.7%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
                ^libxml2@2.9.9%gcc@7.4.0~python arch=linux-ubuntu18.04-x86_64
                    ^libiconv@1.15%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
                    ^xz@5.2.4%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
                ^tar@1.31%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
            ^libtool@2.4.6%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
            ^pcre@8.42%gcc@7.4.0+jit+multibyte+utf arch=linux-ubuntu18.04-x86_64
        ^go-bootstrap@1.4-bootstrap-20171003%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
    ^libgpg-error@1.27%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
    ^libuuid@1.0.3%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
    ^squashfs@4.3%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
```

**Comment by adamjstewart** [comment] 2019-05-27 21:33
Currently, Spack captures all stdout and stderr, including `tty.warn`, during installation. See #2566, #10412, and #11331. Closing as a duplicate of #11244.

**Closed by adamjstewart** 2019-05-27 21:33 UTC
Labels: bug
