### ISSUE TITLE
checksum does not work while install works for dislin

### ISSUE THREAD

**Issue by fanne-stat** [spack/spack#7584] opened 2018-03-23 21:18 UTC
The old dislin tar.gz file dislin-11.0.linux.i586_64.tar.gz was removed from the directory ftp://ftp.gwdg.de/pub/grafik/dislin/linux/i586_64/, so I tried `spack checksum dislin` and `spack -k checksum dislin`to add the new version, (the new one is still in the same directory) but I got
```
==> Error: Could not find any versions for dislin
``` 

The weird thing is that after I manually add the new version with the hash, then `spack install dislin` works. And still 'spack checksum' cannot find anything.

**Comment by healther** [comment] 2018-03-24 06:31
What happens if you update the default url to the new one?

**Comment by adamjstewart** [comment] 2018-03-26 17:10
I tried debugging this, but couldn't figure out why it isn't working. It should be able to find the most recent version. Perhaps it's because of the `linux.i586_64`? It doesn't have any trouble figuring out what part is the version:
```
$ spack url parse -s ftp://ftp.gwdg.de/pub/grafik/dislin/linux/i586_64/dislin-11.0.linux.i586_64.tar.gz
==> Parsing URL: ftp://ftp.gwdg.de/pub/grafik/dislin/linux/i586_64/dislin-11.0.linux.i586_64.tar.gz

==> Matched version regex 14: r'^[a-zA-Z\\d+-]+-v?(\\d[\\da-zA-Z._]*)$'
==> Matched  name   regex  7: r'^([A-Za-z\\d+\\._-]+)$'

==> Detected:
    ftp://ftp.gwdg.de/pub/grafik/dislin/linux/i586_64/dislin-11.0.linux.i586_64.tar.gz
                                                      ------ ~~~~~~~~~~~~~~~~~~
    name:    dislin
    version: 11.0.linux.i586_64

==> Substituting version 9.9.9b:
    ftp://ftp.gwdg.de/pub/grafik/dislin/linux/i586_64/dislin-9.9.9b.tar.gz
                                                      ------ ~~~~~~

==> Spidering for versions:
  Found no versions for dislin
```

**Comment by alalazo** [comment] 2019-12-17 13:32
I can't reproduce this error:
```console
$ spack checksum dislin
==> Found 1 version of dislin:
  
  11.0  ftp://ftp.gwdg.de/pub/grafik/dislin/linux/i586_64/dislin-11.0.linux.i586_64.tar.gz

==> How many would you like to checksum? (default is 1, q to abort) q
```
Closing, but feel free to reopen with more details if the issue persists.

**Closed by alalazo** 2019-12-17 13:32 UTC
Labels: fetching, unreproducible
