### ISSUE TITLE
r@3.5.0 +X +external-lapack ^intel-mkl

### ISSUE THREAD

**Issue by mforde84** [spack/spack#10348] opened 2019-01-15 00:05 UTC
Hi all, having an issue installing with R with X support and specifically cairo pdf support. Running the following:

```
[root@gosset:~]# uname -r
3.10.0-693.21.1.el7.x86_64
[root@gosset:~]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[root@gosset:~]# spack --version
0.12.0
```

Compile is generating the following error:

```
make[7]: Entering directory `/mnt/beegfs/spackroot/var/spack/stage/r-3.5.0-r6gj4fvdxmjbevpx3wagkh5nwtgucyxf/R-3.5.0/src/library/grDevices/src/cairo'
making cairoBM.d from cairoBM.c
In file included from cairoBM.h:51:0,
                 from cairoBM.c:60:
/usr/include/cairo/cairo-pdf.h:91:3: error: #error Cairo was not compiled with support for the pdf backend
 # error Cairo was not compiled with support for the pdf backend
   ^~~~~
make[7]: *** [cairoBM.d] Error 1
make[7]: Leaving directory `/mnt/beegfs/spackroot/var/spack/stage/r-3.5.0-r6gj4fvdxmjbevpx3wagkh5nwtgucyxf/R-3.5.0/src/library/grDevices/src/cairo'
make[6]: *** [cairodevice] Error 2
make[6]: Leaving directory `/mnt/beegfs/spackroot/var/spack/stage/r-3.5.0-r6gj4fvdxmjbevpx3wagkh5nwtgucyxf/R-3.5.0/src/library/grDevices/src'
make[5]: *** [all] Error 2
make[5]: Leaving directory `/mnt/beegfs/spackroot/var/spack/stage/r-3.5.0-r6gj4fvdxmjbevpx3wagkh5nwtgucyxf/R-3.5.0/src/library/grDevices/src'
make[4]: *** [mksrc] Error 1
make[4]: Leaving directory `/mnt/beegfs/spackroot/var/spack/stage/r-3.5.0-r6gj4fvdxmjbevpx3wagkh5nwtgucyxf/R-3.5.0/src/library/grDevices'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/mnt/beegfs/spackroot/var/spack/stage/r-3.5.0-r6gj4fvdxmjbevpx3wagkh5nwtgucyxf/R-3.5.0/src/library/grDevices'
make[2]: *** [R] Error 1
make[2]: Leaving directory `/mnt/beegfs/spackroot/var/spack/stage/r-3.5.0-r6gj4fvdxmjbevpx3wagkh5nwtgucyxf/R-3.5.0/src/library'
make[1]: *** [R] Error 1
make[1]: Leaving directory `/mnt/beegfs/spackroot/var/spack/stage/r-3.5.0-r6gj4fvdxmjbevpx3wagkh5nwtgucyxf/R-3.5.0/src'
make: *** [R] Error 1

```

It looks to be referencing the systems host cairo installation: /usr/include/cairo
This doesn't appear to be the desired behavior, as cairo is installed under the $SPACK_ROOT/opt. This is still the case after explicitly loading the cairo package:

```
[root@gosset:~]# module list

Currently Loaded Modules:
  1) gcc/7.4.0   2) cairo/1.16.0

```

I dont think it's pkg-config oriented, because the module load prepends the cflags appropriately:

```
[root@gosset:~]# module purge
[root@gosset:~]# pkg-config --cflags cairo-pdf
-I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng15 -I/usr/include/libdrm
[root@gosset:~]# module load gcc cairo
[root@gosset:~]# pkg-config --cflags cairo-pdf
-I/mnt/beegfs/spackroot/opt/spack/linux-centos7-x86_64/gcc-7.4.0/cairo-1.16.0-jeocqqxc7fn7m5oo5ugepyu4tcyowmmo/include/cairo -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng15

```

**Comment by hartzell** [comment] 2019-01-15 02:17
You need to build R with X support `spack install r+X`, which will pull in Cairo with X support and Pango with X support and *etc*....

**Comment by mforde84** [comment] 2019-01-15 02:31
So I used:

spack install  r@3.5.0 +X +external-lapack ^intel-mkl

That should pull the pango, and Cairo dependancies, or am I missing something?

**Comment by adamjstewart** [comment] 2019-01-15 03:42
@mforde84 Can you see if your problem is fixed by #10350? I made `+pdf` an optional variant back in #10135 and it looks like `r` actually requires `cairo+pdf`.

**Comment by mforde84** [comment] 2019-01-15 03:44
Cool. I'll check when I get into office tomorrow. Thanks for the help. :)

**Comment by mforde84** [comment] 2019-01-15 03:46
I bet that's what it is, because I initially install Cairo as a depend for r/3.5.2 without x. So I doubt it compiled with x support. Thanks again, learning this bit by bit

**Comment by hartzell** [comment] 2019-01-15 05:24
I suspect that Adam has it right, but....

> I initially install Cairo as a depend for r/3.5.2 without x. So I doubt it compiled with x support.

Just FYI, Spack doesn't care what you already have installed.  If the concretization of the thing you're currently installing calls for a particular variant, Spack will build that one for you.  Even if you have other variants, or versions, or *etc*  already installed.

`spack spec r` will show you how it's being concretized.  Ditto `spack spec r@3.5.0 +X +external-lapack ^intel-mkl`.

You have to be a bit careful because sometimes folks (e.g. *me*) pin down variants and versions in a `package.yaml` file so you might get something that doesn't appear to be the default, but it's always driven by a repeatable/reproducible set of specs.

**Comment by mforde84** [comment] 2019-01-15 15:03
So follow up on this with regards to hierarchical lmod. Whenever I install a variant, I end up with name collisions in my lmod tree, eg.,

```
# spack module lmod refresh --delete-tree -y
==> Error: Name clashes detected in module files:

file: /mnt/beegfs/spackroot/share/spack/lmod/linux-centos7-x86_64/gcc/7.4.0/gobject-introspection/1.49.2.lua
spec: gobject-introspection@1.49.2%gcc@7.4.0 patches=6f90bb267efa043ed70b900b4b8e2faf9e8133afae311893b01060356ea81bba arch=linux-centos7-x86_64
spec: gobject-introspection@1.49.2%gcc@7.4.0 patches=6f90bb267efa043ed70b900b4b8e2faf9e8133afae311893b01060356ea81bba arch=linux-centos7-x86_64
spec: gobject-introspection@1.49.2%gcc@7.4.0 patches=6f90bb267efa043ed70b900b4b8e2faf9e8133afae311893b01060356ea81bba arch=linux-centos7-x86_64

file: /mnt/beegfs/spackroot/share/spack/lmod/linux-centos7-x86_64/gcc/7.4.0/harfbuzz/2.1.3.lua
spec: harfbuzz@2.1.3%gcc@7.4.0 arch=linux-centos7-x86_64
spec: harfbuzz@2.1.3%gcc@7.4.0 arch=linux-centos7-x86_64
spec: harfbuzz@2.1.3%gcc@7.4.0 arch=linux-centos7-x86_64

file: /mnt/beegfs/spackroot/share/spack/lmod/linux-centos7-x86_64/gcc/7.4.0/cairo/1.16.0.lua
spec: cairo@1.16.0%gcc@7.4.0~X~pdf arch=linux-centos7-x86_64
spec: cairo@1.16.0%gcc@7.4.0+X~pdf arch=linux-centos7-x86_64
spec: cairo@1.16.0%gcc@7.4.0+X+pdf arch=linux-centos7-x86_64

file: /mnt/beegfs/spackroot/share/spack/lmod/linux-centos7-x86_64/gcc/7.4.0/pango/1.41.0.lua
spec: pango@1.41.0%gcc@7.4.0~X arch=linux-centos7-x86_64
spec: pango@1.41.0%gcc@7.4.0+X arch=linux-centos7-x86_64
spec: pango@1.41.0%gcc@7.4.0+X arch=linux-centos7-x86_64

```

I understand that the naming convention is controlled through modules.yaml under lmod:all:suffixes

```
 lmod:
    core_compilers:
      - 'gcc@4.8.5'
      - 'llvm@7.0.0'
      - 'singularity@2.6.0'
    hierarchy:
      - mpi
    hash_length: 0
    whitelist:
      - gcc
      - llnm@7.0.0
      - singularity
    blacklist:
      - '%gcc@4.8.5'
    all:
      suffixes:
        '^openblas': openblas
        '^netlib-lapack': netlib
      filter:
        environment_blacklist: ['CPATH', 'LIBRARY_PATH']
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'

```

How would I include variant tags in the naming convention to avoid these conflicts?

Thanks,
M

**Comment by mforde84** [comment] 2019-01-15 15:55
but yes, more directly to the point ^cairo+pdf fixed the issue. thanks!

**Comment by adamjstewart** [comment] 2019-01-15 15:58
> How would I include variant tags in the naming convention to avoid these conflicts?

```yaml
      suffixes:
        '+foo': foo
        '+bar': bar
```

**Closed** 2019-01-15 15:58 UTC
Labels: build-error
