### ISSUE TITLE
`spack mirror remove` doesn't work

### ISSUE THREAD

**Issue by pramodskumbhar** [spack/spack#5300] opened 2017-09-07 07:30 UTC
I tried to add and remove mirror as: 
```
$ spack mirror list
local_filesystem    file://~/SPACK_HOME/install_home/mirror

$ spack mirror remove local_filesystem
==> Removed mirror local_filesystem with url file://~/SPACK_HOME/install_home/mirror

$ spack mirror list
local_filesystem    file://~/SPACK_HOME/install_home/mirror

$ cat ~/.spack/linux/mirrors.yaml
mirrors:
  local_filesystem: file://~/SPACK_HOME/install_home/mirror
```

Edit: related

the doc says we can add mirror as:

```
$ spack mirror add local_filesystem file://~/SPACK_HOME/install_home/mirror


$ ll ~/SPACK_HOME/install_home/mirror/
total 0
drwxr-xr-x 2 kumbhar-adm bbp 4096 Sep  7 09:22 pgi

# But install now fails

$ spack install -v pgi
==> Installing pgi
==> Fetching file://~/SPACK_HOME/install_home/mirror/pgi/pgi-17.7.tar.gz
curl: (37) Couldn't open file /SPACK_HOME/install_home/mirror/pgi/pgi-17.7.tar.gz
```
I thought Spack will open `~/SPACK_HOME/install_home` and not `/SPACK_HOME/install_home`. Is this a bug?  (providing absolute path works).

**Comment by scheibelp** [comment] 2017-09-11 18:30
Spack doesn't have an expansion for `SPACK_HOME`. If you want the prefix of the Spack installation (i.e. the base directory of the git repo), you can use `$spack`; if you do, then you shouldn't use `~`.

The section http://spack.readthedocs.io/en/latest/configuration.html#config-file-variables provides full details.

**Comment by pramodskumbhar** [comment] 2017-09-12 17:32
@scheibelp : `SPACK_HOME ` was just the name of folder in my home directory. Am I missing anything here?

**Comment by scheibelp** [comment] 2017-09-12 17:38
Oh sorry I assumed `SPACK_HOME` was intended to be an expansion or environment variable. I'll have to look into why it's not expanding `~` then.

**Comment by alalazo** [comment] 2017-11-23 15:50
Closing as duplicate of #4573

**Closed by alalazo** 2017-11-23 15:50 UTC
Labels: duplicate, mirrors
