### ISSUE TITLE
Pango install fails on macOS with Clang

### ISSUE THREAD

**Issue by azukaitis** [spack/spack#6892] opened 2018-01-10 21:55 UTC
New to SPACK, just tried installing on my Mac and get a problem with gnuplot and fails on the pango package.  Couldn't easily find anything with google.
```
$ spack install gnuplot
...
==> Installing pango
==> Using cached archive: /Users/zukaitis/spack/var/spack/cache/pango/pango-1.41.0.tar.xz
==> Staging archive: /Users/zukaitis/spack/var/spack/stage/pango-1.41.0-ixmiyl2qtc5pbbh52mxwsh6zbd7k6xoa/pango-1.41.0.tar.xz
==> Created stage in /Users/zukaitis/spack/var/spack/stage/pango-1.41.0-ixmiyl2qtc5pbbh52mxwsh6zbd7k6xoa
==> No patches needed for pango
==> Building pango [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

4 errors found in build log:
     [ ... ]
     194       import copy as _copy
     195     File "/Users/zukaitis/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/python-2.7.14-kwvfv6h3xgxwpmpteiygy4iqo5jadzwc/lib/python2.7/copy.py", line 52, in <module>
     196       import weakref
     197     File "/Users/zukaitis/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/python-2.7.14-kwvfv6h3xgxwpmpteiygy4iqo5jadzwc/lib/python2.7/weakref.py", line 14, in <module>
     198       from _weakref import (
     199   ImportError: cannot import name _remove_dead_weakref
  >> 200   make[2]: *** [s-enum-types-c] Error 1
     201   make[2]: *** Waiting for unfinished jobs....
     202   Traceback (most recent call last):
     203     File "/Users/zukaitis/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/glib-2.55.1-a7tnppl2qqdgh7nucknlzuap5bov7byq/bin/glib-mkenums", line 12, in <module>
     204       import argparse
     205     File "/Users/zukaitis/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/python-2.7.14-kwvfv6h3xgxwpmpteiygy4iqo5jadzwc/lib/python2.7/argparse.py", line 86, in <module>
     206       import copy as _copy
     207     File "/Users/zukaitis/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/python-2.7.14-kwvfv6h3xgxwpmpteiygy4iqo5jadzwc/lib/python2.7/copy.py", line 52, in <module>
     208       import weakref
     209     File "/Users/zukaitis/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/python-2.7.14-kwvfv6h3xgxwpmpteiygy4iqo5jadzwc/lib/python2.7/weakref.py", line 14, in <module>
     210       from _weakref import (
     211   ImportError: cannot import name _remove_dead_weakref
  >> 212   make[2]: *** [s-enum-types-h] Error 1
  >> 213   make[1]: *** [all-recursive] Error 1
  >> 214   make: *** [all] Error 2
```

**Comment by adamjstewart** [comment] 2018-01-10 23:45
Let me try to reproduce this. @davydden don't you use `gnuplot` on macOS?

**Comment by adamjstewart** [comment] 2018-01-11 01:16
I was able to reproduce this problem, albeit with a slightly different error message:
```
6 errors found in build log:
     [ ... ]
     184   ==> Executing phase: 'build'
     185   ==> 'make' '-j4'
     186   /Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
     187   Making all in pango
     188     GEN      s-enum-types-h
     189     GEN      s-enum-types-c
  >> 190   Fatal Python error: Py_Initialize: unable to load the file system codec
  >> 191   Fatal Python error: Py_Initialize: unable to load the file system codec
     192   ModuleNotFoundError: No module named 'encodings'
     193   ModuleNotFoundError:
     194   No module named 'encodings'Current thread 0x
     195   
     196   Current thread 0x00007fffa0d08340 (most recent call first):
     197   00007fffa0d08340 (most recent call first):
     198   /bin/sh: line 1: 45289 Abort trap: 6           glib-mkenums --template pango-enum-types.c.template pango.h pango-attributes.h pango-bidi-type.h pango-break.h pango-context.h pango-coverage.h pango-engine.h pango-font.h pango-fontmap.h pango-fontset.h pango-glyph.h pango-glyph-item.h pango-gravity.h pango-item.h pango-language.h pango-layout.h pango-matrix.h pango-modules.h pango-renderer.h pango-script.h pango-tabs.h pango-types.h pango-utils.h pango-version-macros.h
     199   /bin/sh: line 1: 45288 Abort trap: 6           glib-mkenums --template pango-enum-types.h.template pango.h pango-attributes.h pango-bidi-type.h pango-break.h pango-context.h pango-coverage.h pango-engine.h pango-font.h pango-fontmap.h pango-fontset.h pango-glyph.h pango-glyph-item.h pango-gravity.h pango-item.h pango-language.h pango-layout.h pango-matrix.h pango-modules.h pango-renderer.h pango-script.h pango-tabs.h pango-types.h pango-utils.h pango-version-macros.h
  >> 200   make[2]: *** [s-enum-types-c] Error 134
     201   make[2]: *** Waiting for unfinished jobs....
  >> 202   make[2]: *** [s-enum-types-h] Error 134
  >> 203   make[1]: *** [all-recursive] Error 1
  >> 204   make: *** [all] Error 2
```
It looks like this is a problem with `pango`, not with `gnuplot`. I'll change the issue title to reflect this.

**Comment by adamjstewart** [comment] 2018-01-11 01:22
My first thought is that somehow the system Python and the Spack-installed Python are conflicting, but both the system Python and Spack-installed Python can import `encodings`, so I'm not really sure what's going on here. We may need to open up an issue with the `pango` developers if we can't get to the bottom of this.

**Comment by davydden** [comment] 2018-01-11 07:32
I do  have gnuplot installed on macOS high sierra via Spack.

**Comment by javdg** [comment] 2018-01-11 14:54
Hi,
building pango fails here as well with similar symptoms (Debian 9.3, gcc@6.3.0):

```
4 errors found in build log:
     [ ... ]
     198     File "/path/to/spack/provided/python-2.7.14-uxzmizo2mhofuolris7whnn2xjqbrxpa/lib/python2.7/weakref.py", line 14, in <module>
     199       from _weakref import (
     200       from _weakref import (
     201   ImportError: ImportErrorcannot import name _remove_dead_weakref:
     202   cannot import name _remove_dead_weakref
     203   Makefile:1601: recipe for target 's-enum-types-h' failed
  >> 204   make[2]: *** [s-enum-types-h] Error 1
     205   make[2]: *** Waiting for unfinished jobs....
     206   Makefile:1609: recipe for target 's-enum-types-c' failed
  >> 207   make[2]: *** [s-enum-types-c] Error 1
     208   make[2]: Leaving directory '/tmp/user/spack-stage/spack-stage-qXZThU/pango-1.41.0/pango'
     209   Makefile:565: recipe for target 'all-recursive' failed
  >> 210   make[1]: *** [all-recursive] Error 1
     211   make[1]: Leaving directory '/tmp/user/spack-stage/spack-stage-qXZThU/pango-1.41.0'
     212   Makefile:464: recipe for target 'all' failed
  >> 213   make: *** [all] Error 2
```
Encountered while installing R via spack, which consequently fails...

**Comment by javdg** [comment] 2018-01-16 08:55
Commit 498c522 (I would assume) fixed it for me. Thanks a lot!

**Comment by adamjstewart** [comment] 2018-01-16 14:00
That's weird. That commit should definitely not affect whether or not the package builds, only whether or not it downloads.

**Comment by javdg** [comment] 2018-01-16 14:08
Right, I didn't look too closely, but the build worked today and this was the last commit directly affecting the pango package (and apparently the only one  since pango version 1.41.0 was introduced), so I assumed...

**Comment by alalazo** [comment] 2019-12-13 09:39
Closing as the issue seems solved looking at comments.

**Closed by alalazo** 2019-12-13 09:39 UTC
Labels: build-error, clang, macOS
