### ISSUE TITLE
Inheriting a builtin package definition with locally stored patches leads to "No such file" error

### ISSUE THREAD

**Issue by gartung** [spack/spack#11844] opened 2019-06-25 16:27 UTC
Creating a package for gcc in our repo fnal_art that inherits from builtin.gcc

```
from spack.pkg.builtin.gcc import Gcc as BuiltinGcc
class Gcc(BuiltinGcc):

    def patch(self):
        BuiltinGcc.patch()

    def install(self):
        BuiltinGcc.install()

```
### Steps to reproduce the issue

```console
$ spack install fnal_art.gcc
```

### Error Message

```console
$ spack -d --stacktrace install fnal_art.gcc
Traceback (most recent call last):
  File "/home/gartung/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/home/gartung/spack/lib/spack/spack/main.py", line 696, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/gartung/spack/lib/spack/spack/main.py", line 446, in _invoke_command
    return_val = command(parser, args)
  File "/home/gartung/spack/lib/spack/spack/cmd/install.py", line 263, in install
    args.package, concretize=True, tests=tests)
  File "/home/gartung/spack/lib/spack/spack/cmd/__init__.py", line 137, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/home/gartung/spack/lib/spack/spack/spec.py", line 1924, in concretize
    self._expand_virtual_packages(),
  File "/home/gartung/spack/lib/spack/spack/spec.py", line 1832, in _expand_virtual_packages
    candidates = concretizer.choose_virtual_or_external(spec)
  File "/home/gartung/spack/lib/spack/spack/concretize.py", line 131, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_externals(spec)
  File "/home/gartung/spack/lib/spack/spack/concretize.py", line 105, in _valid_virtuals_and_externals
    if is_spec_buildable(cspec):
  File "/home/gartung/spack/lib/spack/spack/package_prefs.py", line 230, in is_spec_buildable
    allpkgs = get_packages_config()
  File "/home/gartung/spack/lib/spack/spack/package_prefs.py", line 37, in get_packages_config
    if spack.repo.path.is_virtual(pkg_name)]
  File "/home/gartung/spack/lib/spack/spack/repo.py", line 681, in is_virtual
    return pkg_name in self.provider_index
  File "/home/gartung/spack/lib/spack/spack/repo.py", line 547, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "/home/gartung/spack/lib/spack/spack/repo.py", line 950, in provider_index
    return self.index['providers']
  File "/home/gartung/spack/lib/spack/spack/repo.py", line 383, in __getitem__
    self._build_all_indexes()
  File "/home/gartung/spack/lib/spack/spack/repo.py", line 398, in _build_all_indexes
    self.indexes[name] = self._build_index(name, indexer)
  File "/home/gartung/spack/lib/spack/spack/repo.py", line 428, in _build_index
    indexer.update(namespaced_name)
  File "/home/gartung/spack/lib/spack/spack/repo.py", line 338, in update
    self.index.update_package(pkg_fullname)
  File "/home/gartung/spack/lib/spack/spack/patch.py", line 342, in update_package
    partial_index = self._index_patches(pkg)
  File "/home/gartung/spack/lib/spack/spack/patch.py", line 360, in _index_patches
    patch_dict = patch.to_dict()
  File "/home/gartung/spack/lib/spack/spack/patch.py", line 127, in to_dict
    super(FilePatch, self).to_dict(),
  File "/home/gartung/spack/lib/spack/spack/patch.py", line 93, in to_dict
    'sha256': self.sha256,
  File "/home/gartung/spack/lib/spack/spack/patch.py", line 122, in sha256
    self._sha256 = checksum(hashlib.sha256, self.path)
  File "/home/gartung/spack/lib/spack/spack/util/crypto.py", line 96, in checksum
    with open(filename, 'rb') as file:
IOError: [Errno 2] No such file or directory: '/home/gartung/spack/var/spack/repos/fnal-art/packages/gcc/stack_t.patch'
```

### Information on your system

 Scientific Linux 7 (RHEL7 ) with system python

**Comment by gartung** [comment] 2019-06-25 16:27
@becker33

**Comment by becker33** [comment] 2019-07-03 18:12
@gartung it looks like this is caused by how Spack handles relative paths in patches. If you're interested, see `lib/spack/spack/patch.py:113` I think the simplest way to to fix it would be to check at `__init__` time whether the file exists and use `pkg.get_mro()` to iterate up the class hierarchy until we find it.

If you want to take a stab at fixing it let me know, otherwise I'll probably get to it next week but no promises, depends how feature development is coming along.

**Comment by white238** [comment] 2023-02-23 00:59
@becker33 this is happening again with package repositories that duplicate packages that do not include all patch files that are in spack's package repo

**Comment by white238** [comment] 2023-03-13 21:14
Closing due to not being exactly the same issue. Spoke to @becker33 offline. My issue is that i have a duplicate package in a local package repository and I would like to not duplicate all patches locally.

**Closed by white238** 2023-03-13 21:14 UTC
Labels: bug, impact-medium, patch
