### ISSUE TITLE
It shouldn't be necessary to add Spack-built compilers manually to "compilers.yaml"

### ISSUE THREAD

**Issue by eschnett** [spack/spack#3331] opened 2017-03-03 13:29 UTC
Spack already knows everything about Spack-built compilers. It should simply consult `spack find` in addition to looking at `compilers.yaml`. This is similar to the way other dependencies are resolved; for these, Spack looks at the available packages as well as at `packages.yaml`.

This would also allow the next step: Spack should remember which package depends on a Spack-built compiler, since this is usually a run-time dependency as well (because of the run-time support libraries). Spack should take this into account with its other dependencies, e.g. when there is a request to uninstall a particular Spack-built compiler.

**Comment by alalazo** [comment] 2017-03-03 19:17
Can we close this as duplicate of #449 ?

**Comment by eschnett** [comment] 2017-03-03 22:09
No, I would close #449 instead. What I suggest above is more far-reaching. In particular, if there's a Spack command that adds a compiler `compilers.yaml`, then this wouldn't ensure that Spack keeps track of this compiler as run-time dependency of other installed packages. I rather think this needs to be done in the database of installed packages.

**Comment by becker33** [comment] 2022-08-19 00:05
This is partially resolved by #10761. The other component is not something we intend to add before #31357 is resolved, which will completely change the compiler configuration model and render this issue moot.

**Closed by becker33** 2022-08-19 00:05 UTC
Labels: feature, compilers
