### ISSUE TITLE
CXXFLAGS and CFLAGS not automatically passed to CMake

### ISSUE THREAD

**Issue by naromero77** [spack/spack#11223] opened 2019-04-18 20:51 UTC
### Summary
I am tempted to file this as a bug, but I suppose it is technically a feature request :)

`cxxflags` and `cflags` as specified in `package.yaml` or even on the command line do not automatically get passed into CMake. (both ways just get into the `spec`.)

### Rationale
I currently have to explictly pass `cxxflags` and `cflags` into CMake in the QMCPACK Spack package:
https://github.com/spack/spack/blob/eb7c79720de66cc7b74ac0c6a1ce1d44ee670cd5/var/spack/repos/builtin/packages/qmcpack/package.py#L183-L191

If you search through the contributed Spack packages that use CMake, it appears that many users are aware of this shortcoming and have implemented a similar solution. However, it would be much more preferable if this was not done on a per package basis but consistently in the Spack environment.

### Description
I think the best solution would be to have some code in the CMake base Python class to handle passing `cxxflags` and `cflags` into CMake automatically.

BTW, `extra_rpath`, as specified in `packages.yaml`, is not passed into CMake either. I am not a CMake guru, but looked at this for a while and it was unclear how to properly pass an `rpath` to CMake.

**Comment by svenevs** [comment] 2019-04-19 08:43
It seems like something related to this is going down here:

https://github.com/spack/spack/blob/3f50dcf6d91192253af320aaf72fcb13d307e137/lib/spack/spack/build_systems/cmake.py#L185-L196

I don't really understand how it gets called, but I'm pretty sure these are the [flags from `compilers.yaml`](https://spack.readthedocs.io/en/latest/spack.schema.html?highlight=flags)

> `cxxflags` and `cflags` as specified in `package.yaml` or even on the command line do not automatically get passed into CMake.

Are you sure they can be added in `packages.yaml`?  Maybe you want to move them to `compilers.yaml`?  (I don't actually know if it can go in `packages.yaml`, I'm not up to date on spack).

Primary reason for posting was to link you to the code that appears to be responsible for doing what you want.  I don't have any actual answers :/

**Comment by naromero77** [comment] 2019-04-19 13:05
Sorry, I meant `compilers.yaml` but wrote the wrong yaml filename by accident.

**Comment by mwkrentel** [comment] 2019-04-19 21:03
@naromero77 How did you determine that cxxflags are not passed to
cmake?  Did something outright fail, or run differently than running
ccmake manually?  Or, did you just not see the flags from
'spack install -v'?

Actually, I think that cflags and cxxflags are already included in
the build system, even without the `args.append()` patch.  The real
problem is that sometimes they're hard to find.

But first, let me back up.  What flags are you trying to insert?

If the flags are opt or debug flags (-O2, -g), then the way to do that
for Cmake packages is with `build_type` set to `Debug`, `Release`,
`RelWithDebInfo` or `MinSizeRel`.  This is now builtin to all Cmake
packages.

If the flags are more general, maybe arch or prereq specific (eg, I
needed `-DBOOST_NO_CXX11_CONSTEXPR` for something a while back), then
`cxxflags='...'` should work.

Flags are handled by the `flag_handler` method.

https://spack.readthedocs.io/en/latest/packaging_guide.html#compiler-flags

The default is `inject_flags` which adds them to the cc/c++/ftn
wrappers.  They really are there, they're just hard to see.

You need the `spack -d` (debug) flag, not just `spack install -v`.
For example:

```
spack -d install -v dyninst cxxflags='-DXYZZY=1'
```

This produces a compiler wrapper debug log with a line for every time
the wrapper is invoked, something like:

```
spack-cc-dyninst-rvltieo.out.log:

[cc] /usr/bin/g++ -DXYZZY=1 ...
```

The flag is there, you just have to know where to look.  Technically,
the flag is not passed to cmake, but it is used on every compile line.

Another option is:

```
flag_handler = build_system_flags
```

This will pass cflags, cxxflags, etc directly to cmake with
`-DCMAKE_C_FLAGS`.  This is what you did manually with
`args.append()`, except now you probably have two copies of the flags.

It probably doesn't really matter if you use `inject_flags` (default)
or `build_system_flags`.  In the second, cmake can actually see the
flags, in the first, it doesn't.  But unless cmake is going to look at
the flags and adjust them somehow, it probably doesn't matter.  In
autotools, it's common to tweak the flags for some need, but not so
much in cmake.

Anyway, the spack thematic way of doing what you want is with
`build_system_flags`.

So really, there's no bug here, and not really a feature request.  It
might be tempting to make `build_system_flags` the default, but that's
likely to break something somewhere.

ping @becker33 for comments or corrections to my claims.

**Comment by naromero77** [comment] 2019-04-19 21:51
@mwkrentel There is a file called spack-build.env (or something like that). `cflags` and `cxxflags` can be seen in the `spec` but they are not passed into the CMake command. Just to be clear.  These are `cflags` and `cxxflags` as specified in `compiler.yaml`. They also seem to not be passed in if specified at the command line. Additionally, yes, the build fails. Upon examination of the CMake build log, these flags are just missing. (The CMake internally does add some basic `cflags` and `cxxflags` like `-g` and `-O3`, but the custom ones are not being passed through).

I was unaware of the different flag handlers. And as I infer from your comment, `inject_flags` may not work in an intuitively obviously manner with CMake-based packages as it does with autotools based one.

I will read the documentation more closely soon and check to see if changing the flag handler resolves my issue.

Thanks for taking the time to write a detailed message.

**Comment by mwkrentel** [comment] 2019-04-19 22:56
I've really only used cflags from the command line.  I don't think it
matters if you specify them there or in `compilers.yaml`.  If it does,
then we're talking past each other, and I apologize.  (Unless one flag
overrides another and thus erases it, instead of appending it.)

> Upon examination of the CMake build log, these flags are just
> missing. (The CMake internally does add some basic cflags and cxxflags
> like -g and -O3, but the custom ones are not being passed through).

Right.  If you look at the cmake logs (or `spack install -v`), I think
you'll see that the compiler is the spack wrapper.

```
/home/krentel/cmake-flags/spack-repo/lib/spack/env/gcc/gcc
```

With the default `inject_flags`, the cflags are hidden in the spack
wrapper.  Cmake doesn't see them, but when the wrapper invokes the
actual compiler, they're there.  (You need `spack -d` to see them.)

With `flag_handler = build_system_flags`, then they're passed to cmake
and cmake will see them.

The only way I can think of where these would ever be different is if
cmake looks at cflags and then changes them (something more than
adding -g -O2).  Either that, or it's the order on the compiler line
and something later is overriding them.

What exactly are the flags that went missing?

Anyway, I'll bet that `flag_handler = build_system_flags` instead of
`args.append()` will do exactly what you have now, except it won't
insert the flags twice.

**Comment by naromero77** [comment] 2019-04-20 05:42
The missing flags are specific to the Intel compiler. The Intel compiler requires bits of the GCC compiler to properly work (I think mostly the header file but probably also some libraries). In a sandboxed environment like Spack, you would want to specify which GCC compiler you need the Intel compiler to be compatible with using the `-gcc-name=<path to GCC C compiler>` and `-gxx-name=<path to GCC C++ compiler`. I find that if I don't set these files explicitly from `compilers.yaml` or the command line, I pick up whatever version of GCC is in my current terminal session which I consider undesirable.

Getting back to flags being injecting into the spack compiler wrapper with the default `inject_flags`. I wonder if I have another mistake in my Spack package. I explicitly pass the **MPI compiler** to QMCPACK's CMake `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER`, instead of passing Spack's compiler wrapper. (or perhaps, I should not explicitly be passing any compiler wrappers in since Spack's environment might do this automatically)
https://github.com/spack/spack/blob/eb7c79720de66cc7b74ac0c6a1ce1d44ee670cd5/var/spack/repos/builtin/packages/qmcpack/package.py#L203-L205
BTW, I don't even remember why I put those lines of code in. The package was written near the end of ECP year 1.

I will keep a couple of your ideas a try and see if they help.

**Comment by mwkrentel** [comment] 2019-04-22 18:59
Ok, now it makes sense.  When you set `-DCMAKE_C_COMPILER={0}` with
`+mpi`, you're setting CC to `mpi.mpicc`, not the spack wrapper.  That
explains why you don't see the flags with the default `inject_flags`.
It's the wrapper that would add them just fine, but you've bypassed
the wrapper.  Does that make sense?

I bet it would work without `args.append('-DCMAKE_C_FLAGS=%s')` when
you're not using mpi.

What I think you need to do is: first come to terms with how you want
to handle CC/CXX for the plain C/C++ compilers and mpicc/mpicxx for
the MPI compilers.  When using MPI, do you want to compile all of
QMCPACK with the MPI compiler, or do you want separate MPI and non-MPI
compilers.  Part of your answer depends on whether you're a maintainer
for QMCPACK itself (and can edit the cmake build), or if you're just
trying to get the spack version to work with the existing cmake.

Spack recognizes 6 flags: cflags, cxxflags, fflags, cppflags, ldflags
and ldlibs.  By using `build_system_flags`, you get all six.  What
you've done is set the first two, but drop the other four.

https://spack.readthedocs.io/en/latest/basic_usage.html#specs-dependencies

If you're committed to using the MPI compilers everywhere in the
build, then I suggest using `build_system_flags` and declare victory.
That will make the flags visible for any compiler.

Anyway IMO, this is not a bug, and not really a valid feature request.
QMCPACK has unusual needs and this is not something that all cmake
packages would need.  But fortunately, spack does provide sufficient
tools for this case.

If you like, you could close this and open a separate issue for a
discussion on the best way to handle compiler flags for MPI compilers,
especially in the case that you're using the MPI compiler as the
primary C/C++ compiler.  I don't know if spack has fully thought out
this case (maybe, I just don't know).

**Comment by naromero77** [comment] 2019-04-22 19:41
I do not believe the QMCPACK has any unique needs. Only my understanding is lacking :)

**Comment by naromero77** [comment] 2019-04-22 21:36
@mwkrentel Actually, it looks like I have to retract my previous statement. The way that QMCPACK's CMake is designed, `-DCMAKE_C_COMPILER` and `-DCMAKE_CXX_COMPILER`, must receive an MPI compiler wrapper when MPI is enable. Otherwise, CMake just bombs out. When MPI support is enable (the default), everything is compiled with the MPI wrappers (whether it has MPI or not). Its possible to redesign QMCPACK's CMake, but this would be a discussion with the other developers.

I have to think about whether its better `build_system_flags` or 'inject_flags`, but otherwise I think that I made need a bit of custom code.

**Comment by naromero77** [comment] 2019-05-01 19:04
I was doing it wrong and here is the fix.
https://github.com/spack/spack/pull/11326

I will close this github issue tomorrow.

**Comment by scheibelp** [comment] 2019-05-03 02:14
https://github.com/spack/spack/pull/11326 is merged so I'll close this (although if I missed something feel free to reopen)

**Closed by scheibelp** 2019-05-03 02:14 UTC
Labels: feature
