### ISSUE TITLE
Installation issue: cp2k@6.1

### ISSUE THREAD

**Issue by jabl** [spack/spack#10602] opened 2019-02-14 12:27 UTC
### Steps to reproduce the issue

```console
$ spack install cp2k@6.1
... 
==> Error: ProcessError: Command exited with status 2:
    'make' '-j40' 'ARCH=linux-ubuntu18.04-x86_64-gcc' 'VERSION=popt'
...
/usr/bin/gcc -c -O2 -mtune=native -funroll-loops -ffast-math -ftree-vectorize -D__FFTW3 -D__LIBINT -D__LIBINT_MAX_AM=6 -D__LIBDERIV_MAX_AM1=5 -I/usr/include -I/usr/include/python3.6m -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/hwloc/autogen -I/usr/include/x86_64-linux-gnu/gnu -I/usr/include/x86_64-linux-gnu/asm -I/usr/include/x86_64-linux-gnu/sys -I/usr/include/x86_64-linux-gnu/c++/7/ext -I/usr/include/x86_64-linux-gnu/c++/7/bits -I/usr/include/x86_64-linux-gnu/bits -I/usr/include/x86_64-linux-gnu/bits/types -I/usr/include/x86_64-linux-gnu/python3.6m -I/usr/include/layout -I/usr/include/icu-le-hb/layout -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0/gio -I/usr/include/lzma -I/usr/include/unicode -I/usr/include/graphite2 -I/usr/include/readline -I/usr/include/glib-2.0 -I/usr/include/glib-2.0/gio -I/usr/include/glib-2.0/gobject -I/usr/include/glib-2.0/glib -I/usr/include/glib-2.0/glib/deprecated -I/usr/include/neteconet -I/usr/include/hwloc -I/usr/include/infiniband -I/usr/include/rdma -I/usr/include/rdma/hfi -I/usr/include/libltdl -I/usr/include/rpc -I/usr/include/arpa -I/usr/include/netinet -I/usr/include/misc -I/usr/include/netatalk -I/usr/include/asm-generic -I/usr/include/netax25 -I/usr/include/drm -I/usr/include/xen -I/usr/include/netrom -I/usr/include/video -I/usr/include/nfs -I/usr/include/netiucv -I/usr/include/sound -I/usr/include/netipx -I/usr/include/scsi -I/usr/include/scsi/fc -I/usr/include/netash -I/usr/include/net -I/usr/include/linux -I/usr/include/linux/netfilter_ipv6 -I/usr/include/linux/tc_act -I/usr/include/linux/nfsd -I/usr/include/linux/caif -I/usr/include/linux/hsi -I/usr/include/linux/netfilter_ipv4 -I/usr/include/linux/genwqe -I/usr/include/linux/netfilter_bridge -I/usr/include/linux/netfilter_arp -I/usr/include/linux/android -I/usr/include/linux/tc_ematch -I/usr/include/linux/dvb -I/usr/include/linux/hdlc -I/usr/include/linux/cifs -I/usr/include/linux/sunrpc -I/usr/include/linux/iio -I/usr/include/linux/wimax -I/usr/include/linux/raid -I/usr/include/linux/can -I/usr/include/linux/netfilter -I/usr/include/linux/netfilter/ipset -I/usr/include/linux/sched -I/usr/include/linux/mmc -I/usr/include/linux/byteorder -I/usr/include/linux/isdn -I/usr/include/linux/spi -I/usr/include/linux/usb -I/usr/include/c++/7 -I/usr/include/c++/7/debug -I/usr/include/c++/7/backward -I/usr/include/c++/7/decimal -I/usr/include/c++/7/ext -I/usr/include/c++/7/parallel -I/usr/include/c++/7/experimental/bits -I/usr/include/c++/7/tr1 -I/usr/include/c++/7/profile -I/usr/include/c++/7/profile/impl -I/usr/include/c++/7/bits -I/usr/include/netpacket -I/usr/include/rpcsvc -I/usr/include/protocols -I/usr/include/netrose -I/usr/include/mtd -D__MPI_VERSION=3 -D__parallel -D__SCALAPACK -D__LIBXC -I/benchmarks/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/libxc-4.3.2-y5cncqwewxgnmbi4iwbdud54yliqkx65/include -D__LIBXSMM  /benchmarks/spack/var/spack/stage/cp2k-6.1-vc2sbev7ppgzzcfo2cdqytqunlcnl6mi/cp2k-6.1/src/sockets.c

...

       41     In file included from /benchmarks/spack/var/spack/stage/cp2k-6.1-vc2sbev7ppgzzcfo2cdqytqunlcnl6mi/cp2k-6.1/src/sockets.c:38:0:
  >> 42     /usr/include/x86_64-linux-gnu/bits/stdio.h:20:3: error: #error "Never include <bits/stdio.h> directly; use <stdio.h> instead."
     43      # error "Never include <bits/stdio.h> directly; use <stdio.h> instead."

```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux 546a2df817b6 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# grep PRETTY /etc/os-release 
PRETTY_NAME="Ubuntu 18.04.1 LTS"
``` 

and, if relevant, post or attach:

- `packages.yaml`
```
---
# Tell spack to use system packages for openblas, openmpi etc.
packages:
  openmpi:
    paths:
      openmpi@2.1.1%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  openblas:
    paths:
      openblas@0.2.20%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  fftw:
    paths:
      fftw@3.3.7%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  autoconf:
    paths:
      autoconf@2.69%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  automake:
    paths:
      automake@1.15%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  libtool:
    paths:
      libtool@2.4.6%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  python:
    paths:
      python@2.7.15%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  libsigsegv:
    paths:
      libsigsegv@2.12%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  diffutils:
    paths:
      diffutils@3.6%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  bzip2:
    paths:
      bzip2@1.0.6%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  pkgconf:
    paths:
      pkgconf@0.9.12%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  ncurses:
    paths:
      ncurses@6.1%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  readline:
    paths:
      readline@7.0%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  gdbm:
    paths:
      gdbm@1.14.1%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  perl:
    paths:
      perl@5.26.1%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  zlib:
    paths:
      zlib@1.2.11%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  openssl:
    paths:
      openssl@1.1.0g%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  curl:
    paths:
      curl@7.58.0%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  libbsd:
    paths:
      libbsd@0.8.7%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  expat:
    paths:
      expat@2.2.5%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  xz:
    paths:
      xz@5.2.2%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  libxml2:
    paths:
      libxml2@2.9.4%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  lz4:
    paths:
      lz4@0.0~r131%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  lzo:
    paths:
      lzo@2.08%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  m4:
    paths:
      m4@1.4.18%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  gmp:
    paths:
      gmp@6.1.2%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  nettle:
    paths:
      nettle@3.4%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  libarchive:
    paths:
      libarchive@3.2.2%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  libuv:
    paths:
      libuv@1.18.0%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  rhash:
    paths:
      rhash@1.3.6%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  cmake:
    paths:
      cmake@3.10.2%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  numactl:
    paths:
      numactl@2.0.11%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  hwloc:
    paths:
      hwloc@1.11.9%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  libpciaccess:
    paths:
      libpciaccess@0.14%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False
  netlib-scalapack:
    paths:
      netlib-scalapack@2.0.2%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64: /usr
    buildable: False

```

### Additional information

So the reason for this error seems to be that in the compile command there's spurious extra include paths that are causing the problems. That is, since /usr/include/bits is before /usr/include, `#include <stdio.h>` leads to trying to include `bits/stdio.h` rather than `stdio.h`.

If I don't use the packages.yaml above it all seems to work. So somehow using the packages.yaml spack adds these extra include paths?

Output of:
```console
# spack spec --install-status cp2k@6.1
Input spec
--------------------------------
 -   cp2k@6.1

Concretized
--------------------------------
 -   cp2k@6.1%gcc@7.3.0 blas=openblas ~elpa+libxc+mpi~openmp~pexsi~plumed smm=libxsmm arch=linux-ubuntu18.04-x86_64 
[+]      ^fftw@3.3.7%gcc@7.3.0+double+float~fma+long_double+mpi~openmp~pfft_patches~quad simd=avx,avx2,sse2 arch=linux-ubuntu18.04-x86_64 
[+]      ^libint@1.1.6%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
[+]          ^autoconf@2.69%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
[+]          ^automake@1.15%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
[+]          ^libtool@2.4.6%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
[+]      ^libxc@4.3.2%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
[+]      ^libxsmm@1.10%gcc@7.3.0~debug~header-only arch=linux-ubuntu18.04-x86_64 
[+]      ^netlib-scalapack@2.0.2%gcc@7.3.0 build_type=RelWithDebInfo patches=e8f30dd1f26e523dfb552f8d7b8ad26ac88fc0c8d72e3d4f9a9717a3383e0b33 ~pic+shared arch=linux-ubuntu18.04-x86_64 
[+]      ^openblas@0.2.20%gcc@7.3.0 cpu_target=auto ~ilp64 patches=47cfa7a952ac7b2e4632c73ae199d69fb54490627b66a62c681e21019c4ddc9d +pic+shared threads=none ~virtual_machine arch=linux-ubuntu18.04-x86_64 
[+]      ^openmpi@2.1.1%gcc@7.3.0~cuda+cxx_exceptions fabrics=auto ~java~legacylaunchers~memchecker~pmi schedulers=auto ~sqlite3~thread_multiple+vt arch=linux-ubuntu18.04-x86_64 
[+]      ^pkgconf@0.9.12%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
[+]      ^python@2.7.15%gcc@7.3.0+dbm~optimizations patches=123082ab3483ded78e86d7c809e98a804b3465b4683c96bd79a2fd799f572244 +pic+pythoncmd+shared~tk~ucs4 arch=linux-ubuntu18.04-x86_64 
...
```

**Comment by alalazo** [comment] 2019-02-14 12:35
I wonder if:
- The recently merged #10570 introduced the issue (I tried many configurations but without this custom `packages.yaml`)
- This is another manifestation of #10601 
- The problem is unrelated two the two items above and got unnoticed until now

Can you help trimming down the root cause?

**Comment by jabl** [comment] 2019-02-14 12:46
It used to build without the packages.yaml, but that was also before #10570 was merged. I'll try removing my packages.yaml and see if it goes away or if I still have the same issue.

**Comment by alalazo** [comment] 2019-02-14 15:09
@jabl Can you check if #10604 solves this issue too?

**Comment by jabl** [comment] 2019-02-14 15:20
Throwing away my own packages.yaml ended up with the same error as reported in issue #10603, applying patch #10604 at least let it go past that, lets see how far it gets now.

**Comment by jabl** [comment] 2019-02-14 15:30
Yes, success, cp2k@6.1 built with the #10604 patch!

This was without my packages.yaml, I'll try one more time with it.

**Comment by jabl** [comment] 2019-02-14 16:52
Oof, the cp2k build still fails with the same issue (trying to include bits/stdio.h) with my packages.yaml. Just to double-check I blew away my spack installation and did it all from scratch (checkout, apply #10604, etc.) with the same result.

**Comment by jabl** [comment] 2019-02-18 13:30
Turns out that if I comment out the entries for `fftw` and `netlib-scalapack` from the `packages.yaml` above the build succeeds. It's fftw that causes these problems with trying to include `bits/foo.h` directly, but I don't see how fftw per se could be the culprit. The issue with scalapack seems to be due to not finding some symbols when trying to link against the ubuntu package, so not spack's fault in any way.

**Comment by dwcloud** [comment] 2019-03-14 16:07
Tried installing cp2k@6.1 under Spack 0.11.2 using the latest package copied from the 0.12.1 develop branch.

Getting the following " 'module' object has no attribute 'set_env' " error in the build stage, could this be related to diff in spack version and the new cp2k package template getting in the way? :

```

spack -V
0.11.2

spack install cp2k %gcc@4.8.5
...
==> Executing phase: 'build'
==> Error: AttributeError: 'module' object has no attribute 'set_env'
AttributeError: AttributeError: 'module' object has no attribute 'set_env'

/global_app/Linux/spack_custom_repo/packages/cp2k/package.py:377, in build:
     1             # Apparently the Makefile bases its paths on PWD
     2             # so we need to set PWD = self.build_directory
     3             with spack.util.environment.set_env(PWD=self.build_directory):
  >> 4                 super(Cp2k, self).build(spec, prefix)


spack spec --install-status cp2k

Input spec
--------------------------------
     cp2k

Concretized
--------------------------------
     cp2k@6.1%gcc@4.9.4 blas=openblas ~elpa+libxc+mpi~openmp~pexsi~plumed smm=libxsmm arch=linux-centos7-x86_64 
         ^fftw@3.3.7%gcc@4.9.4+double+float~fma+long_double+mpi~openmp~pfft_patches~quad simd=avx,avx2,sse2 arch=linux-centos7-x86_64 
             ^binutils@2.29.1%gcc@4.9.4+gold~libiberty patches=0a0ca84889b6727dc0cc88650f55fd79452dddba762674a83a153374792fdaac ~plugins arch=linux-centos7-x86_64 
[+]              ^bison@3.0.4%gcc@4.9.4 patches=b72914fe38e54a6fc25f29019e0a0786705c4f61ce20d414cc2010c8d62448c7 arch=linux-centos7-x86_64 
[+]                  ^m4@1.4.18%gcc@4.9.4 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00 +sigsegv arch=linux-centos7-x86_64 
[+]                      ^libsigsegv@2.11%gcc@4.9.4 arch=linux-centos7-x86_64 
[+]              ^flex@2.6.3%gcc@4.9.4+lex arch=linux-centos7-x86_64 
[+]                  ^gettext@0.19.8.1%gcc@4.9.4+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=linux-centos7-x86_64 
[+]                      ^bzip2@1.0.6%gcc@4.9.4+shared arch=linux-centos7-x86_64 
[+]                          ^diffutils@3.6%gcc@4.9.4 arch=linux-centos7-x86_64 
[+]                      ^libxml2@2.9.8%gcc@4.9.4~python arch=linux-centos7-x86_64 
[+]                          ^pkgconf@1.4.2%gcc@4.9.4 arch=linux-centos7-x86_64 
[+]                          ^xz@5.2.4%gcc@4.9.4 arch=linux-centos7-x86_64 
[+]                          ^zlib@1.2.11%gcc@4.9.4+optimize+pic+shared arch=linux-centos7-x86_64 
[+]                      ^ncurses@6.1%gcc@4.9.4~symlinks~termlib arch=linux-centos7-x86_64 
[+]                      ^tar@1.30%gcc@4.9.4 arch=linux-centos7-x86_64 
[+]                  ^help2man@1.47.4%gcc@4.9.4 arch=linux-centos7-x86_64 
             ^openmpi@3.1.0%gcc@4.9.4~cuda fabrics=verbs ~java~memchecker~pmi schedulers= ~sqlite3~thread_multiple+vt arch=linux-centos7-x86_64 
                 ^hwloc@1.11.9%gcc@4.9.4~cairo~cuda+libxml2+pci+shared arch=linux-centos7-x86_64 
                     ^libpciaccess@0.13.5%gcc@4.9.4 arch=linux-centos7-x86_64 
[+]                      ^libtool@2.4.6%gcc@4.9.4 arch=linux-centos7-x86_64 
[+]                      ^util-macros@1.19.1%gcc@4.9.4 arch=linux-centos7-x86_64 
                     ^numactl@2.0.11%gcc@4.9.4 arch=linux-centos7-x86_64 
[+]                      ^autoconf@2.69%gcc@4.9.4 arch=linux-centos7-x86_64 
[+]                          ^perl@5.24.1%gcc@4.9.4+cpanm+shared+threads arch=linux-centos7-x86_64 
[+]                              ^gdbm@1.14.1%gcc@4.9.4 arch=linux-centos7-x86_64 
[+]                                  ^readline@7.0%gcc@4.9.4 arch=linux-centos7-x86_64 
[+]                      ^automake@1.16.1%gcc@4.9.4 arch=linux-centos7-x86_64 
         ^libint@1.1.6%gcc@4.9.4 arch=linux-centos7-x86_64 
         ^libxc@4.3.2%gcc@4.9.4 arch=linux-centos7-x86_64 
         ^libxsmm@develop%gcc@4.9.4~debug~header-only arch=linux-centos7-x86_64 
         ^netlib-scalapack@2.0.2%gcc@4.9.4 build_type=RelWithDebInfo ~pic+shared arch=linux-centos7-x86_64 
[+]          ^cmake@3.11.2%gcc@4.9.4~doc+ncurses+openssl+ownlibs~qt arch=linux-centos7-x86_64 
[+]              ^openssl@1.0.2n%gcc@4.9.4+systemcerts arch=linux-centos7-x86_64 
[+]          ^openblas@0.2.20%gcc@4.9.4 cpu_target= ~ilp64 patches=47cfa7a952ac7b2e4632c73ae199d69fb54490627b66a62c681e21019c4ddc9d +pic+shared threads=none ~virtual_machine arch=linux-centos7-x86_64 
         ^python@2.7.14%gcc@4.9.4+dbm~optimizations patches=123082ab3483ded78e86d7c809e98a804b3465b4683c96bd79a2fd799f572244 +pic+pythoncmd+shared~tk~ucs4 arch=linux-centos7-x86_64 
[+]          ^sqlite@3.23.1%gcc@4.9.4 arch=linux-centos7-x86_64 
```

By the way, there are jdk issues trying to spec or install anything with the current develop branch...

```
spack -V
0.12.1

spack spec cp2k

Input spec
--------------------------------
cp2k

Concretized
--------------------------------
==> Error: Class constructor failed for package 'builtin.commons-logging'.

Caused by:
ValueError: Package jdk is not extendable!
  File "/global_app/Linux/spack/lib/spack/spack/repo.py", line 896, in get
    return package_class(spec)
  File "/global_app/Linux/spack/lib/spack/spack/package.py", line 518, in __init__
    spack.repo.get(self.extendee_spec)._check_extendable()
  File "/global_app/Linux/spack/lib/spack/spack/package.py", line 1971, in _check_extendable
    raise ValueError("Package %s is not extendable!" % self.name)
```

**Comment by RMeli** [comment] 2024-04-29 15:54
Closing for lack of activity. `cp2k@6.1` was marked as deprecated in https://github.com/spack/spack/pull/39652 and later removed.

**Closed by RMeli** 2024-04-29 15:54 UTC
Labels: build-error
