### ISSUE TITLE
Why is spack re-installing a second CMake?

### ISSUE THREAD

**Issue by ax3l** [spack/spack#5167] opened 2017-08-19 13:56 UTC
If I am running an explicit install of a CMake version, and then a following install of a package build with CMake, why does spack install yet another CMake?

e.g.
```bash
spack install cmake@3.7.2
spack install pngwriter@0.6.0
# builds cmake@3.9.0 first
```

This looks illogical to me, since the pngwriter package makes no claim about a minimum version of CMake. Should it?

**Comment by adamjstewart** [comment] 2017-08-19 14:21
**Spack does not look at already installed packages before choosing what to install.** This is probably the most common confusion over Spack. If you want to know what Spack is going to install _before_ it installs it, run:
```
$ spack spec cmake@3.7.2
Input spec
--------------------------------
cmake@3.7.2

Normalized
--------------------------------
cmake@3.7.2

Concretized
--------------------------------
cmake@3.7.2%clang@8.1.0-apple~doc+ncurses+openssl+ownlibs~qt arch=darwin-sierra-x86_64 
    ^ncurses@6.0%clang@8.1.0-apple~symlinks arch=darwin-sierra-x86_64 
        ^pkg-config@0.29.2%clang@8.1.0-apple+internal_glib arch=darwin-sierra-x86_64 
    ^openssl@1.0.2k%clang@8.1.0-apple arch=darwin-sierra-x86_64 
        ^zlib@1.2.11%clang@8.1.0-apple+pic+shared arch=darwin-sierra-x86_64 

$ spack spec pngwriter@0.6.0
Input spec
--------------------------------
pngwriter@0.6.0

Normalized
--------------------------------
pngwriter@0.6.0
    ^cmake
    ^freetype
        ^bzip2
        ^libpng
            ^zlib@1.0.4:
        ^pkg-config@0.24:

Concretized
--------------------------------
pngwriter@0.6.0%clang@8.1.0-apple build_type=RelWithDebInfo arch=darwin-sierra-x86_64 
    ^cmake@3.9.0%clang@8.1.0-apple~doc+ncurses+openssl+ownlibs~qt arch=darwin-sierra-x86_64 
        ^ncurses@6.0%clang@8.1.0-apple~symlinks arch=darwin-sierra-x86_64 
            ^pkg-config@0.29.2%clang@8.1.0-apple+internal_glib arch=darwin-sierra-x86_64 
        ^openssl@1.0.2k%clang@8.1.0-apple arch=darwin-sierra-x86_64 
            ^zlib@1.2.11%clang@8.1.0-apple+pic+shared arch=darwin-sierra-x86_64 
    ^freetype@2.7.1%clang@8.1.0-apple arch=darwin-sierra-x86_64 
        ^bzip2@1.0.6%clang@8.1.0-apple+shared arch=darwin-sierra-x86_64 
        ^libpng@1.6.29%clang@8.1.0-apple arch=darwin-sierra-x86_64 
```
One of the goals of Spack is reproducibility. If both of us install `pngwriter@0.6.0` (or any package) and find that it uses a different version of `cmake` (or any dependency), this breaks reproducibility. For this reason, Spack does not (currently) take into account already installed packages. There has been a lot of talk about doing this, and most people seem to be in favor, but it hasn't been implemented yet. Until then, **there is no benefit in incrementally installing packages and their dependencies.** If you want to control what version of a dependency Spack uses, you must be explicit:
```
$ spack spec pngwriter@0.6.0 ^cmake@3.7.2
Input spec
--------------------------------
pngwriter@0.6.0
    ^cmake@3.7.2

Normalized
--------------------------------
pngwriter@0.6.0
    ^cmake@3.7.2
    ^freetype
        ^bzip2
        ^libpng
            ^zlib@1.0.4:
        ^pkg-config@0.24:

Concretized
--------------------------------
pngwriter@0.6.0%clang@8.1.0-apple build_type=RelWithDebInfo arch=darwin-sierra-x86_64 
    ^cmake@3.7.2%clang@8.1.0-apple~doc+ncurses+openssl+ownlibs~qt arch=darwin-sierra-x86_64 
        ^ncurses@6.0%clang@8.1.0-apple~symlinks arch=darwin-sierra-x86_64 
            ^pkg-config@0.29.2%clang@8.1.0-apple+internal_glib arch=darwin-sierra-x86_64 
        ^openssl@1.0.2k%clang@8.1.0-apple arch=darwin-sierra-x86_64 
            ^zlib@1.2.11%clang@8.1.0-apple+pic+shared arch=darwin-sierra-x86_64 
    ^freetype@2.7.1%clang@8.1.0-apple arch=darwin-sierra-x86_64 
        ^bzip2@1.0.6%clang@8.1.0-apple+shared arch=darwin-sierra-x86_64 
        ^libpng@1.6.29%clang@8.1.0-apple arch=darwin-sierra-x86_64 
```
Alternatively, if you _always_ want to build _every_ package with `cmake@3.7.2`, you can make this the preferred version in `packages.yaml`.

**Comment by ax3l** [comment] 2017-08-19 14:45
Thanks @adamjstewart for the detailed explanation! Now its clearer to me, all right.

Can we maybe make this part of the docs or did I overlook it?

**Comment by tgamblin** [comment] 2017-08-20 00:36
This will be implemented!  But it's not implemented yet 😞 .  It requires better dependency resolution than what we currently do, and we'll also retain a deterministic mode, per @adamjstewart's comment above.

**Comment by markcmiller86** [comment] 2017-08-24 22:12
I am not totally sure because cmake is a _build_ dependency for pngwriter, but wouldn't this have worked...

```
spack install cmake@3.7.2
spack install pngwriter@0.6.0 ^cmake@3.7.2
```

In other words, if you explicitly want to a) incrementally build the parts and b) specify specific versions, then you have to include those versions explicitly on the `spack install` command lines for each part.

Otherwise, pngwriter

**Comment by ax3l** [comment] 2017-09-11 14:57
Yes, that works since it's explicitly requesting the cmake version.

I was just confused on how concretization works in that case and if it is influenced by already installed packages or not.

**Comment by v-dobrev** [comment] 2017-10-04 21:32
I had a similar issue - having to explicitly include dependencies that I already have installed. I was going to suggest an option for all spack commands that perform concretization: e.g. `--preffer-installed-dependencies` which should also be a globally configurable option.

So, I vote  to `+1` the priority of this issue. :-)

**Comment by alalazo** [comment] 2019-12-09 14:26
@ax3l Closing as we already have a lot of duplicate issues asking for a new concretization algorithm :smile:

**Closed by alalazo** 2019-12-09 14:26 UTC
Labels: concretization, question

**Comment by ax3l** [comment] 2019-12-09 17:49
Hihi, yes this seams to be one of the first questions for new users :laughing:
