### ISSUE TITLE
How to use packages that are installed

### ISSUE THREAD

**Issue by certik** [spack/spack#3295] opened 2017-03-01 23:47 UTC
I read the documentation:

http://spack.readthedocs.io/en/latest/tutorial_sc16_spack_basics.html

I can install packages using `spack install`. What is the "spack" way to actually use them? How do I find the path to the installed library, so that I can use it in my own projects? How do I find the path to the `bin` directory of the `paraview` package, so that I can launch paraview?

The only mention I found was in the "advanced usage", but I would think this should be the most basic usage:

http://spack.readthedocs.io/en/latest/tutorial_sc16_spack_basics.html#advanced-spack-find-usage

it says that `spack find -pe` will give me the full path to the installed packages, so then I can use it to launch things.

**Comment by adamjstewart** [comment] 2017-03-02 01:39
The "spack" way would probably be to use modules, which are generated automatically for everything you install. Spack is designed as a "Supercomputer PACKage manager", so we expect most users to use some form of modules. If you don't, then yes, you can find the path to the installed package with `spack find -p`. You may also want to take a look at `spack view` if you are more familiar with package managers that install everything into the same directory.

**Comment by davydden** [comment] 2017-03-02 05:20
Yes, modules is the most convenient way of using. You may also do 'spack location -i foo-spec>' to, for example, set env variables. Note that foo-spec should uniquely identify the installed package. Say I u have complex and real valued petsc, you need to petsc+complex when you need the path to the complex version.

**Comment by citibeth** [comment] 2017-03-03 19:29
See #2698 for a more in-depth discussion on this issue.  The core problem is that spack find/load/etc. fails when you have more than one instance of a package installed.

**Comment by adamjstewart** [comment] 2017-03-03 20:04
"fails" is a strong word. You just have to be more specific 😝

**Comment by citibeth** [comment] 2017-03-03 20:38
The problem is that the level of specificity you need to use *depends on
what else happens to be installed in your Spack*.  Something that worked
yesterday could break tomorrow because someone else installed a new
version.  It's not a way to build a reliable system.

**Comment by adamjstewart** [comment] 2017-03-03 21:07
I agree, it's certainly not something I would use in a script.

**Comment by whitfin** [comment] 2019-02-20 16:37
I would like to bump this, as the documentation is still extremely non-obvious. I installed openssl, and spent the last 30 minutes figuring out how to invoke it from the command line.

Best I can tell, the way to do this is via:

```shell
bin/spack bootstrap
source share/spack/setup-env.sh
spack load openssl
```

I'm coming from Homebrew, and I'm loving Spack so far, but this is definitely "odd" to me. Is there some way I can automatically load these modules in my `.bashrc` dynamically? I'ave migrated ~25 packages; it would be a pain to have to list them all in `.bashrc` and update the list constantly. Would that be done by something like `eval $(spack module tcl loads)` in my `.bashrc`?

**Comment by citibeth** [comment] 2019-02-20 16:43
Isaac,

I would suggest you use Spack Environments to build all the packages you
want into an envrionment.  You can then use those packages in one of two
ways:
 1. Spack Environments can produce a list of `module load` commands that
you can `source` in your `.bashrc`.
 2. Spack Environments can symlink all your packages into a single tree (a
Spack View); and you manually configure your env vars to point to that tree
in your `.bashrc`.

`spack load` is not recommend for production use because: (a) it is not
deterministic, and (b) it is slow.

Sorry about the docs; Spack Environments are newly merged, and we're just
starting about thinking of how to nudge people to use them.

-- Elizabeth

**Comment by certik** [comment] 2019-02-20 16:44
@citibeth is this the link to get started with Spack Environments?

https://spack.readthedocs.io/en/latest/tutorial_environments.html

**Comment by citibeth** [comment] 2019-02-20 16:48
Yes

**Comment by whitfin** [comment] 2019-02-21 01:52
@citibeth thanks for the reference! I've built an environment with everything I need. I think I'm going to opt for #1 that you listed above, which appears to be done via `spack env loads`? This makes a lot more sense now!

**Comment by citibeth** [comment] 2019-02-21 01:53
Yes that what I do.  Some people like views, some like modules

**Comment by alalazo** [comment] 2019-12-03 15:06
I think both module files and environments are treated extensively in the docs. Closing this issue, feel free to reopen if you think something is still missing.

**Closed by alalazo** 2019-12-03 15:06 UTC
Labels: documentation
