### ISSUE TITLE
How to create a hybrid spack compiler (Intel ifort and gcc)?

### ISSUE THREAD

**Issue by garvct** [spack/spack#7638] opened 2018-03-29 18:01 UTC
I have a code that requires an Intel fortran compiler (ifort) and gcc (not icc) to build.

When I attempt to use the spack intel compiler, gcc does not work.

spack compiler list
==> Available compilers
-- gcc sles11-x86_64 --------------------------------------------
gcc@5.5.0  gcc@4.9.4  gcc@4.3.4

-- intel sles11-x86_64 ------------------------------------------
intel@12.1.6

e.g
spack env mcnp6%intel bash

which ifort
/hpc-common/software/spack/0.11.2/spack/lib/spack/env/intel/ifort
which icc
/hpc-common/software/spack/0.11.2/spack/lib/spack/env/intel/icc
which gcc
/usr/bin/gcc

gcc main.c
gcc: error trying to exec 'cc1': execvp: No such file or directory

Outside spack main.c compiles fine with the default gcc compiler.

I tried modifying the compiler.yaml to create a hybrid intel+gcc compiler
- compiler:
     environment: {}
     extra_rpaths: []
     flags: {}
    modules: []
    operating_system: sles11
    paths:
     cc: /usr/bin/gcc
     cxx: /usr/bin/g++
     f77: /apps/local/easybuild/software/ifort/2011.13.367/bin/intel64/ifort
     fc: /apps/local/easybuild/software/ifort/2011.13.367/bin/intel64/ifort
    spec: intel@12.1.6_gcc
    target: x86_64

But when I used intel@12.1.6_gcc, I got the same error attempting to compile with gcc.

How do I set-up an spack to compile with a hybrid compiler (Intel ifort (for fortran) and gcc (for c code))?

Thanks,

**Comment by alalazo** [comment] 2018-07-05 20:57
Duplicate of #5655

**Comment by alalazo** [comment] 2019-12-17 10:27
Closing this as both stale and duplicate. Feel free to comment in the linked issue if any further information is needed.

**Closed by alalazo** 2019-12-17 10:27 UTC
Labels: compilers, question
