### ISSUE TITLE
Qt build fails, missing header files

### ISSUE THREAD

**Issue by futuretristan** [spack/spack#3011] opened 2017-02-03 09:03 UTC
When running
`spack install paraview~mpi+opengl2+qt`
then the build of dependency qt fails due to missing header files, e.g.
"db2.cpp:42:20: fatal error: sqlcli.h: No such file or directory"
"ibase.cpp:42:19: fatal error: ibase.h: No such file or directory"
"../mysql/mysql.cpp:42:19: fatal error: mysql.h: No such file or directory"

**Comment by davydden** [comment] 2017-02-03 09:25
Tristan, can you also mention your OS/compiler (including version) for completeness?

**Comment by futuretristan** [comment] 2017-02-03 09:37
I'm on Linuxmint 18.1 running in a VirtualBox. The compiler is GCC 5.4.0.

**Comment by luigi-calori** [comment] 2017-02-03 10:34
I' m also  trying to build ParaView in Spack with Gui. 
As my target now is without GPU, I added some dependencies regarding Mesa.
If you want, have a look on the [branch in my clone ](https://github.com/RemoteConnectionManager/spack/tree/pr/qt_on_headless_mesa),  I could publish it as WIP PR

**Comment by davydden** [comment] 2017-02-03 10:39
> I could publish it as WIP PR

:+1:

**Comment by luigi-calori** [comment] 2017-02-03 11:10
@davydden  I use this patch with other patches that I try to keep in sync with upstream development.
In order to keep clean history, I merge with rebase option, so, when pushing, I have to force push..
Is this a good practice for branch submitted as PR or do I have to follow a different workflow?
I have other branches that ar PR ready and also some packages on a separate repo that could be added. I did not publish them as unsure if force pushing is OK and the number of Spack open PR is ever increasing.

**Comment by davydden** [comment] 2017-02-03 11:29
> Is this a good practice for branch submitted as PR or do I have to follow a different workflow?

Not sure if I understand exactly what you mean. But in general, if you have some changes on your local branch, then you create a feature branch off it, rebased it on top of the current `develop` branch in Spack and create a PR. If you have more on that branch than what you would like to use for a PR, then you can `git reset --soft develop` the feature branch w.r.t the `develop` and add/commit only those changes that are relevant (followed by push to your remote, of course). Bottom line, a branch for a PR is normally a fresh one and should not require `push --force`. But maybe i misunderstand your workflow.

p.s. I also keep my own branch with extra minor changes, but I don't `merge-rebase` it, i just merge `develop` into it from time to time. This is a matter of personal preference and is irrelevant, IMO, to PRs. When I see that I need to fix something quickly and use it, I create a fresh branch off `develop`, commit changes, create a PR. However I don't wait until it's accepted, I also merge this feature branch into my own stable branch.

**Comment by davydden** [comment] 2017-02-03 11:31
@luigi-calori p.s. you have probably already gone through http://spack.readthedocs.io/en/latest/contribution_guide.html#git-workflows ,but just in case post the link.

**Comment by adamjstewart** [comment] 2017-02-03 13:12
@luigi-calori I do my best to keep my develop in sync with upstream develop. If I have a new feature I want to add/bug I want to fix, I create a new branch, make the change, and submit a PR. I never merge this back into my own develop branch. The upside is that life is really simple and I don't need a mastery of git to prevent embarrassing git mistakes. The downside is that I have to wait until it is merged to use it.

**Comment by adamjstewart** [comment] 2017-02-03 13:13
@luigi-calori Were you ever able to get Mesa to build? I spent a very long time on it but never got it working on my vanilla CentOS 6.

**Comment by luigi-calori** [comment] 2017-02-03 14:34
@adamjstewart I managed to build mesa non a headless node, ( login nod of our Marconi cluster) with gallium... It seems to support, to some extent, binary opengl applications such as ParaView provided you set up LD_LIBRARY_PATH
Here is my [devel branch](https://github.com/RemoteConnectionManager/spack/tree/develop) 
As I' m not so confident on rapid merging of my patches, I' ve tried to keep them separate, so to be able to submit PR, keep them updated by rebase on develop but also merge them into my development. The problem is that if I rebase, then I can not push without forcing.

**Comment by luigi-calori** [comment] 2017-02-03 14:45
I can publish my stuff as PR, as they are, and then sync them as I usually do, forcing the push and see what happen. I' ve been told force pushing is not good on PR... but this seems unovoidable if I have to rebase... 
@davydden referring to the [git workflow tutorial](http://spack.readthedocs.io/en/latest/contribution_guide.html#git-workflows), yes, my develop is a Frankestain branch, I have a [script](https://github.com/RemoteConnectionManager/RCM_spack_deploy/blob/master/deploy_integrate.sh) that help me to mantain it: it get all the pr/* + wip/* branches of my clone plus a list of wothwhile other PR and this is my current develop

**Comment by davydden** [comment] 2017-05-05 08:32
@luigi-calori i tried your develop[https://github.com/RemoteConnectionManager/spack/tree/develop] branch (https://github.com/RemoteConnectionManager/spack/commit/4c8060bc68bc378598be8249059b8506c42430fe) and by adding
```
diff --git a/var/spack/repos/builtin/packages/paraview/package.py b/var/spack/repos/builtin/packages/paraview/package.py
index a029544..4f440db 100644
--- a/var/spack/repos/builtin/packages/paraview/package.py
+++ b/var/spack/repos/builtin/packages/paraview/package.py
@@ -67,6 +67,7 @@ class Paraview(Package):
     # depends_on('protobuf') # version mismatches?
     # depends_on('sqlite') # external version not supported
     depends_on('zlib')
+    depends_on('mesa+gallium', when='+osmesa')

     def url_for_version(self, version):
         """Handle ParaView version-based custom URLs."""
@@ -115,6 +116,13 @@ class Paraview(Package):
                 feature_args.append(
                     '-DPARAVIEW_DO_UNIX_STYLE_INSTALLS:BOOL=ON')

+            if '+osmesa' in spec:
+                feature_args.extend([
+                    '-DOSMESA_INCLUDE_DIR=%s' % spec['mesa'].prefix.include,
+                    '-DOSMESA_LIBRARY=%s' % join_path(
+                        spec['mesa'].prefix.lib, 'libOSMesa.so')
+                ])
+
             cmake('..',
                   '-DCMAKE_INSTALL_PREFIX:PATH=%s' % prefix,
                   '-DBUILD_TESTING:BOOL=OFF',
```
`spack install paraview+osmesa` works just fine on Centos 7 cluster with `gcc@4.8.5` and `openmpi`. Not sure if it's working, but at least it builds!

**Comment by davydden** [comment] 2017-05-05 08:44
@luigi-calori do you think you could create a pull-request with updates to `mesa` (and dependencies) you did in your `develop` branch so that it can be merged _upstream_ to Spack?

**Comment by davydden** [comment] 2017-05-05 08:56
@luigi-calori to that end one could do
```
git checkout develop # your current Frankestain branch
git checkout -b pr/mesa_updates   # a new branch for the PR with contents form your `develop`
git reset --soft <llvm_remote>/develop  # reset the new branch to Spack's develop
git reset HEAD -- . # reset all staged files
```
At this point you will have whole lot of modified files, including `mesa`. Now you can 
```
git add <usefull-file> 
git commit -m <some message>
```
to pick out only those things which are relevant. The reset cant be unstaed by
```
git checkout <file>
```

**Comment by luigi-calori** [comment] 2017-05-05 10:19
Sorry, I'm not really proficient in git, I did not know your suggested workflow.
 I am already keeping separate branches for things could be worthwile for a PR in separate branches:
I use one branch for each possible pr and try to keep them in sync with current spack devel
my own devel is obtained by merging all these branches + some useful spack PR that is not merged yet.
I' ve just created  #4134 with current status of the branch.
Still untested on the target platform

**Comment by davydden** [comment] 2017-05-05 11:46
> I did not know your suggested workflow.

no worries, there are many ways to do the same thing in git. I just thought I summarize what I would do with `git` in your case.

**Comment by chuckatkins** [comment] 2019-12-04 18:03
Closing based on a wide array of more recent PR's addressing paraview, qt, and mesa.  To the best of my knowledge this is no longer an issue.  If it is then please let me know and I'm happy to re-open it.

**Closed by chuckatkins** 2019-12-04 18:03 UTC
Labels: build-error
