### ISSUE TITLE
Bazel build fails with a Java java.lang.OutOfMemoryError exception

### ISSUE THREAD

**Issue by mdorier** [spack/spack#14149] opened 2019-12-13 15:16 UTC
I'm trying to install Bazel on a Debian machine. The machine has 8 GB of RAM so it shouldn't pose any problem, yet the build fails:

```
==> Building bazel [Package]
==> Executing phase: 'bootstrap'
==> Executing phase: 'install'
==> Error: FileNotFoundError: [Errno 2] No such file or directory: 'output/bazel'

/projects/spack/var/spack/repos/builtin/packages/bazel/package.py:136, in install:
        134    def install(self, spec, prefix):
        135        mkdir(prefix.bin)
  >>    136        install('output/bazel', prefix.bin)
```

When I inspect spack-build-out.txt, I see that the build failed with a `java.lang.OutOfMemoryError` exception. I read somewhere that it might be that javac isn't allocating enough (despite the machine having plenty).

Any has this error? How could the Bazel package be updated to avoid it?

**Comment by adamjstewart** [comment] 2019-12-13 16:44
Closing as a duplicate of #14058, let’s continue the discussion there.

**Closed by adamjstewart** 2019-12-13 16:44 UTC
Labels: build-error
