### ISSUE TITLE
`spack env loads` broken

### ISSUE THREAD

**Issue by citibeth** [spack/spack#12104] opened 2019-07-23 20:28 UTC
I created, concretized and installed a Spack Environment.  `module avail` verified that a bunch of modules had been created.  Then I ran:
```
spack -e myenv env loads -r
```
It replied:
```
To load this environment, type:
   source .../spack/var/spack/environments/research/loads
```
The `loads` file is created, but NOTHING IS IN IT.  This used to work, now it's mysteriously stopped working.  Frustrating.

**Comment by scheibelp** [comment] 2019-08-03 00:30
Hi @citibeth this looks like a duplicate of https://github.com/spack/spack/issues/12062 so I'm closing it. Please reopen if I was mistaken there. I opened https://github.com/spack/spack/pull/12203 to address this.

**Closed by scheibelp** 2019-08-03 00:30 UTC
Labels: bug, environments
