### ISSUE TITLE
py-ipython : An unsatisfiable version constraint has been detected for spec:

### ISSUE THREAD

**Issue by yrevaz** [spack/spack#7876] opened 2018-04-23 21:23 UTC
While trying to install py-ipython for python@3.6.5,
I get the following error:

```console
$ spack install py-ipython       ^python@3.6.5
==> Error: An unsatisfiable version constraint has been detected for spec:

    python@3.6.5
        ^bzip2
        ^ncurses
            ^pkgconfig
        ^openssl
            ^zlib
        ^readline
        ^sqlite


while trying to concretize the partial spec:

    py-backports-shutil-get-terminal-size


py-backports-shutil-get-terminal-size requires python version :3.2, but spec asked for 3.6.5

...
```

This has been obtained on CentOS7 with spack 0.11.2

**Comment by citibeth** [comment] 2018-04-23 22:13
@adamjstewart @tgamblin 

Do a `git blame` on `py-ipython/package.py` (below).  The `depends_on()` for `py-backports-shutil-get-terminal-size` and `py-pathlib2` should be qualified on the Python version, since they don't make sense for the latest Ptyhon.  But at some point in the past (#2793), this broke concretization.

It looks like #2793 is still an open issue.  For your case, I recommend commenting out those two packages, since you don't need them for Python 3.6 anyway.  Everything should work find then.

```
c0aaa8fc var/spack/repos/builtin/packages/py-ipython/package.py (Adam J. Stewart  2017-01-16 18:13:37 -0800 42)     # These dependencies breaks concretization
05fa3026 var/spack/repos/builtin/packages/py-ipython/package.py (Todd Gamblin     2017-11-04 17:08:04 -0700 43)     # See https://github.com/spack/spack/issues/2793
4e17ae91 var/spack/repos/builtin/packages/py-ipython/package.py (Adam J. Stewart  2017-04-22 17:31:50 -0500 44)     # depends_on('py-backports-shutil-get-terminal-size', type=('build', 'run'), when="^python@:3.2")  # noqa
4e17ae91 var/spack/repos/builtin/packages/py-ipython/package.py (Adam J. Stewart  2017-04-22 17:31:50 -0500 45)     # depends_on('py-pathlib2', type=('build', 'run'), when="^python@:3.3")
c0aaa8fc var/spack/repos/builtin/packages/py-ipython/package.py (Adam J. Stewart  2017-01-16 18:13:37 -0800 46)     depends_on('py-backports-shutil-get-terminal-size', type=('build', 'run'))
1e6871ad var/spack/repos/builtin/packages/py-ipython/package.py (healther         2017-03-04 14:45:07 +0100 47)     depends_on('py-pathlib2',                   type=('build', 'run'))
c0aaa8fc var/spack/repos/builtin/packages/py-ipython/package.py (Adam J. Stewart  2017-01-16 18:13:37 -0800 48) 
```

**Comment by adamjstewart** [comment] 2018-04-24 12:14
Sounds like you got it working. Closing this as a duplicate of #2793.

**Closed by adamjstewart** 2018-04-24 12:14 UTC
Labels: bug, concretization, duplicate
