### ISSUE TITLE
Package commit hashes don't coincide with release tags

### ISSUE THREAD

**Issue by markcmiller86** [spack/spack#11881] opened 2019-06-28 17:46 UTC
Looking at [h5z-zfp package logic for 0.7.0 and 0.8.0 releases](https://github.com/spack/spack/blob/46c15132964b482ca0808cc8700c980407562095/var/spack/repos/builtin/packages/h5z-zfp/package.py#L17), the commit hashes do not agree with what I see for that package (pictured below) when I look at those releases on GitHub. Is this a problem or am I confused?

![Untitled 2](https://user-images.githubusercontent.com/5720676/60360981-d9821780-9991-11e9-9600-353cd4441fe3.png)

**Comment by scheibelp** [comment] 2019-07-02 19:02
Ideally they would match. It looks like you added those versions (that's what it looks like anyhow when I look at the history for this package), was there a reason you chose the commits that you did?

**Comment by markcmiller86** [comment] 2019-07-02 19:38
I can't think of a reason other than I went poking around on GitHub for those hashes and obviously poked the wrong place to obtain them.

**Comment by scheibelp** [comment] 2019-07-03 00:38
It's possible they changed the commits associated with the tags in their repo. It's not a bug from Spack's perspective. You can submit a PR if you prefer that the versions match those in the Repo. If you are not inclined to do so I think it's fine and would be inclined to close this.

**Closed** 2019-07-03 16:12 UTC
Labels: question, triage
