### ISSUE TITLE
os variant for external package in packages.yaml is ignored sometimes

### ISSUE THREAD

**Issue by JaroslavHron** [spack/spack#15464] opened 2020-03-12 12:18 UTC
Specifing external package in packages.yaml for specific `os` seems to be inconsistent somehow.

### Spack version

```console
$ spack --version
0.14.0
```

### Steps to reproduce the issue
For heterogenous cluster (part is ubuntu16 other part ubuntu18) we have in packages.yaml
```
  slurm:
    paths:
      slurm@17.11 os=ubuntu18.04 : /opt/slurm/17.11.u18
      slurm@17.11 os=ubuntu16.04 : /opt/slurm/17.11.u16
    version: [17.11]
    buildable: False
```

```console
$ spack arch
linux-ubuntu18.04-skylake_avx512

$ spack install -v slurm
==> slurm@17.11 : externally installed in /opt/slurm/17.11.u16
==> slurm@17.11 : already registered in DB

$ spack install -v slurm arch=linux-ubuntu18.04-skylake_avx512
==> slurm@17.11 : externally installed in /opt/slurm/17.11.u18
==> slurm@17.11 : already registered in DB
```

installing it as dependency it seems to pick the wrong one, for example
```console
$ spack install -v py-mpi4py
==> Warning: Missing a source id for slurm@17.11
[+] /usr/work/clusterbuild/pkg/Installs/linux-ubuntu18.04-skylake_avx512/gcc7.4.0/libsigsegv/2.12/bpuylljhki6fwjib
[+] /usr/work/clusterbuild/pkg/Installs/linux-ubuntu18.04-skylake_avx512/gcc7.4.0/pkg-config/0.29.2/wxvd3lsbhreatn2g
[+] /usr/work/clusterbuild/pkg/Installs/linux-ubuntu18.04-skylake_avx512/gcc7.4.0/util-macros/1.19.1/zi422lmibbf53v7o
[+] /usr/work/clusterbuild/pkg/Installs/linux-ubuntu18.04-skylake_avx512/gcc7.4.0/libiconv/1.16/ajkkpczfc3ijoubp
[+] /usr/work/clusterbuild/pkg/Installs/linux-ubuntu18.04-skylake_avx512/gcc7.4.0/xz/5.2.4/hla46hjrwymcu54g
[+] /usr/work/clusterbuild/pkg/Installs/linux-ubuntu18.04-skylake_avx512/gcc7.4.0/zlib/1.2.11/x66fs6ohfo7s33yq
==> slurm@17.11 : externally installed in /opt/slurm/17.11.u16
==> slurm@17.11 : already registered in DB
[+] /opt/slurm/17.11
.....
```

**Comment by adamjstewart** [comment] 2020-03-12 13:11
Duplicate of #3508

**Comment by scheibelp** [comment] 2020-07-08 20:23
We have #3508 on our project board so I will close this since #3508 is considered to cover this

**Closed by scheibelp** 2020-07-08 20:23 UTC
Labels: bug, impact-medium
