### ISSUE TITLE
`spack install` should print spec!

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2661] opened 2016-12-22 00:05 UTC
When you run `spack install` (or `spack setup`), Spack should print the entire concretized spec BEFORE it prints anything else (or does anything).  What it prints should be the same as if one runs `spack spec -Il`.

This would be good for debugging.

Any comments?

**Comment by tgamblin** [comment] 2016-12-22 00:08
Seems very non-orthogonal.  Most users don't care.  You can just run `spack spec -whateveryoulike` before `spack install`.

**Comment by tgamblin** [comment] 2016-12-22 00:09
And, after install, you can run `spack spec /abc123` on the install hash to see what happened.

**Comment by citibeth** [comment] 2016-12-22 01:41
When `spack spec` takes 40 seconds, that suggestion is a non-starter.
There should at least be an option to print it as you install.  I'm going
crazy debugging this.

**Comment by adamjstewart** [comment] 2016-12-22 02:50
Duplicate of #2149.

**Comment by citibeth** [comment] 2016-12-22 04:30
I'm working on a PR for this...

**Comment by alalazo** [comment] 2017-11-22 13:16
> When `spack spec` takes 40 seconds, that suggestion is a non-starter.
There should at least be an option to print it as you install.  I'm going
crazy debugging this.

We optimized a lot concretization since this (credits to @tgamblin). Closing.

**Closed by alalazo** 2017-11-22 13:16 UTC
Labels: duplicate, feature, ready
