### ISSUE TITLE
"url" is always required in packages

### ISSUE THREAD

**Issue by BarrySmith** [spack/spack#3788] opened 2017-04-11 01:45 UTC
```
$ ./bin/spack install pflotran@xsdk-0.2.2
==> Error: Class constructor failed for package 'pflotran'.

Caused by:
NoURLError: Package Pflotran has no version with a URL.
  File "/Users/barrysmith/Src/spack/lib/spack/spack/repository.py", line 579, in get
    self._instances[key] = package_class(copy)
  File "/Users/barrysmith/Src/spack/lib/spack/spack/package.py", line 564, in __init__
    f = fs.for_package_version(self, self.version)
  File "/Users/barrysmith/Src/spack/lib/spack/spack/fetch_strategy.py", line 898, in for_package_version
    url = pkg.url_for_version(version)
  File "/Users/barrysmith/Src/spack/lib/spack/spack/package.py", line 684, in url_for_version
    raise NoURLError(cls)

```

Why are you forcing me to provide a "url" when my only distribution mechanism is git? This use to work fine.

**Comment by alalazo** [comment] 2017-04-11 08:49
@BarrySmith Is some description missing here, or is it just like that?

**Comment by tgamblin** [comment] 2017-04-11 15:24
@BarrySmith: ?

**Comment by adamjstewart** [comment] 2017-04-11 15:25
_curiosity intensifies_

**Comment by tgamblin** [comment] 2017-04-11 15:27
> **old school**
> *noun*
> used, usually approvingly, to refer to someone or something that is old-fashioned or traditional.
> "amenities that my parents, being of the old school, still take for granted"

**Comment by BarrySmith** [comment] 2017-04-18 01:11
@tgamblin @adamjstewart @alalazo Looks like github may not be good at notifying you when someone updates an already existing issue by editing (to actually say something).

Anyways I think my now complete issue report explains the problem.

**Comment by scheibelp** [comment] 2017-09-29 22:37
See also #2788

**Comment by alalazo** [comment] 2017-11-23 11:26
Still present:
````console
$ spack spec pflotran@xsdk-0.2.2
Input spec
--------------------------------
pflotran@xsdk-0.2.2

Normalized
--------------------------------
pflotran@xsdk-0.2.2
    ^hdf5@1.8.12:+fortran+mpi
        ^mpi
        ^numactl
            ^autoconf
                ^m4@1.4.6:
                ^perl
                    ^gdbm
                        ^readline
                            ^ncurses
                                ^pkg-config
            ^automake
            ^libtool
        ^zlib@1.1.2:

Concretized
--------------------------------
==> Error: Class constructor failed for package 'builtin.pflotran'.

Caused by:
NoURLError: Package Pflotran has no version with a URL.
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/repository.py", line 836, in get
    self._instances[key] = package_class(copy)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/package.py", line 601, in __init__
    f = fs.for_package_version(self, self.version)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/fetch_strategy.py", line 930, in for_package_version
    url = pkg.url_for_version(version)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/package.py", line 719, in url_for_version
    raise NoURLError(cls)
```

**Comment by adamjstewart** [comment] 2017-11-23 13:48
Closing this as a duplicate of #2788. Let's continue any discussion there.

**Closed by adamjstewart** 2017-11-23 13:48 UTC
Labels: bug, duplicate, xSDK

**Comment by alalazo** [comment] 2017-11-23 13:49
@adamjstewart Maybe we'll get under 550 issues at the end of this first sweep :laughing:
