### ISSUE TITLE
incorrect repos.yaml namespace precedence in dependencies

### ISSUE THREAD

**Issue by burgreen** [spack/spack#8850] opened 2018-07-31 16:32 UTC
Within the builtin repo are the standard packages `mpich` and `zoltan`. I want to use a customized version of `mpich` to build `zoltan` and have added a modified `mpich` package into a thirdparty repo.  

So, I created a etc/spack/repos.yaml as below along with packages in the thirdparty dir and a var/spack/repos/thirdparty/repo.yaml.
```
repos:
  - $spack/var/spack/repos/thirdparty
  - $spack/var/spack/repos/builtin
```
There is no ~/.spack/repos.yaml.

The problem is: for some dependencies, the builtin packages are being preferred over corresponding thirdparty packages. For dependencies, the builtin namespace packages take precedence over the thirdparty namespace packages defined in my site-level `repos.yaml`.

### Expected Result

Concretization of `mpich` should consistently reflect my thirdparty repo. 
```
$ spack spec mpich
Concretized
--------------------------------
mpich@3.2.1%clang@9.1.0-apple device=ch3 +hydra netmod=tcp +pmi+romio~verbs arch=darwin-highsierra-x86_64

$ spack spec zoltan
Concretized
--------------------------------
<snip>
    ^mpich@3.2.1%clang@9.1.0-apple device=ch3 +hydra netmod=tcp +pmi+romio~verbs arch=darwin-highsierra-x86_64
```

### Actual Result
For the `zoltan` package, the `mpich` dependency is being concretized from the builtin repo, not my thirdparty repo. Since I have a site-level `repos.yaml`, shouldn't the first valid package for `mpich` be discovered in the namespace of the thirdparty repo? 
```
$ spack spec mpich
Concretized
--------------------------------
   ^mpich@3.2.1%clang@9.1.0-apple device=ch3 +hydra netmod=tcp +pmi+romio~verbs arch=darwin-highsierra-x86_64

$ spack spec zoltan
Concretized
--------------------------------
<snip>
    ^mpich@3.2.1%clang@9.1.0-apple device=ch3 +hydra netmod=tcp patches=e591891fae6a1d029b95edbc93865c57d165784e77cf8b5822ae7d014b137a03 +pmi+romio~verbs arch=darwin-highsierra-x86_64
```

**Comment by JaroslavHron** [comment] 2019-02-05 19:52
If the mpi provider in `packages.yaml` is set explicitly to the site-level repo then it seems to work.
(see #1801)
```
packages:
  all:
     providers:
         mpi: [thirdparty.mpich]
```

**Comment by alalazo** [comment] 2019-12-09 11:04
Duplicate of #1801

**Closed** 2022-03-10 10:01 UTC
Labels: bug, duplicate, repos
