### ISSUE TITLE
package requires python version 3:, but spec asked for 2.7.16

### ISSUE THREAD

**Issue by danlipsa** [spack/spack#11531] opened 2019-05-22 14:35 UTC
I am trying to change the paraview package so that version 5.6 uses python3 and all previous version use python2. So I have the following code:

```console
depends_on('python@3:', when='@5.6:+python', type=('build', 'link', 'run'))
depends_on('python@2.7:2.8', when='@:5.5+python', type=('build', 'link', 'run'))
```

If I don't do the same branching on all python packages, I will get the error in the title for the following command:
```console
spack spec paraview+python
```
However, if I specify the version that the previous command chooses, the command works correctly.
```console
spack spec paraview@5.6.0+python
```

Numpy is one of the packages that are needed in paraview. I will have to use:
```console
depends_on('py-numpy', when='@:5.5+python', type=('build', 'run'))
depends_on('py-numpy', when='@5.6:+python', type=('build', 'run'))
```
instead of the simpler:
```console
depends_on('py-numpy', when='+python', type=('build', 'run'))
```
to avoid the error in the title. Attached is the package.py that shows this error.
[paraview.zip](https://github.com/spack/spack/files/3207883/paraview.zip)

**Comment by citibeth** [comment] 2019-05-22 19:28
Could you please look over and comment on #11468?  The central question is... is it possible / feasible to produce a single version of Spack that supports Python2 and Python3 stacks?  Or starting 2020-Jan-01 should we stop trying to make things work for Python2?  I was leaning toward the former.  But if we can't figure out how to make things like this package work, then maybe it's more practical to drop Python2 support.

**Comment by baberlevi** [comment] 2019-05-22 22:38
I've run into similar issues, and have found if I add a 3.x version preference for python in packages.yaml or an equivalent section in spack.yaml (if using spack env) that fixes the problem, e.g.
```
python:
      variants: +tkinter+ucs4
      version: [3.7.2, 2.7.16]
```
I just tried this with your two python dependency lines added to paraview, and it is working for me.

maybe we should consider adding a something like that to the default packages.yaml distributed with spack?

**Comment by danlipsa** [comment] 2019-05-23 14:03
@baberlevi Yes, this works! Thanks! Yes, it may make sense to add something like this to the default packages.yaml. I used a slightly simpler version:
`   python:
      version: [3, 2]
`

**Comment by adamjstewart** [comment] 2019-05-23 19:45
> maybe we should consider adding a something like that to the default packages.yaml distributed with spack?

Currently, the `python` package defaults to Python 2. If we want to switch the default to Python 3, that should fix this issue. See #10319.

**Comment by sunandosamaddar** [comment] 2019-10-09 15:15
> I've run into similar issues, and have found if I add a 3.x version preference for python in packages.yaml or an equivalent section in spack.yaml (if using spack env) that fixes the problem, e.g.
> 
> ```
> python:
>       variants: +tkinter+ucs4
>       version: [3.7.2, 2.7.16]
> ```
> 
> I just tried this with your two python dependency lines added to paraview, and it is working for me.
> 
> maybe we should consider adding a something like that to the default packages.yaml distributed with spack?

Hi, I have below in `package.yaml`.
```
packages:
  python:
    version: [3.6.8, 2.7.10]        <<< However, cannot install py-jupyter-notebook (`... but spec asked for 2.7.16`)
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag, fj]
    providers:
      D: [ldc]
      awk: [gawk]
      blas: [openblas]
```

**Comment by sunandosamaddar** [comment] 2019-10-10 08:30
Thanks @adamjstewart!

**Comment by alalazo** [comment] 2020-11-02 20:10
Duplicate of #1781

**Comment by alalazo** [comment] 2020-11-02 20:13
This happens because being a Python package implies an unconditional dependence on `python`:
```python
    extends('python')
    depends_on('python', type=('build', 'run'))
```
The conditional dependencies in the description create the same case as in #1781.

**Closed by alalazo** 2020-11-02 20:13 UTC
Labels: bug, concretization, python3, triage
