### ISSUE TITLE
Cannot concretize ecp-proxy-apps

### ISSUE THREAD

**Issue by junghans** [spack/spack#8133] opened 2018-05-15 01:46 UTC
```
$ spack spec ecp-proxy-apps
Input spec
--------------------------------
ecp-proxy-apps

Concretized
--------------------------------
==> Error: Multiple providers found for 'jpeg': ['libjpeg', 'libjpeg-turbo@1.5.90%gcc@5.4.0 arch=linux-gentoo2-x86_64']
```
then
```
$ spack spec ecp-proxy-apps ^libjpeg-turbo
Input spec
--------------------------------
ecp-proxy-apps
    ^libjpeg-turbo

Concretized
--------------------------------
==> Error: ecp-proxy-apps does not depend on libjpeg-turbo
```

@adamjstewart  any idea?

**Comment by scheibelp** [comment] 2018-05-15 03:32
I'll be able to look at this tomorrow

**Comment by junghans** [comment] 2018-05-15 23:04
That is a good workaround.

**Comment by citibeth** [comment] 2018-05-15 23:14
@tgamblin 
Glad it worked.  I use `packages.yaml` almost exclusively.  In an ideal world, giving the Concretizer information ('hints') on the command line vs. `packages.yaml` should be equivalent.  In reality, the two have subtly different semantics.  For example, adding a `^xyz` clause if `xyz` is not used in your DAG will result in an error; whereas adding it to `packages.yaml` will not.  In so many ways, I have found the semantics of the way this information is processed in `packages.yaml` to be more robust.  I would advocate for re-doing the command line stuff to be semantically equivalent to `packages.yaml`.

Another issue I came across is... if I'm building a bunch of inter-related projects, I found myself putting more and more `^xyz` clauses on my command lines --- and repeating them from one `spack install` to the next.  It's convenient for a quick install here or there, but can quickly become unwieldy.

**Comment by scheibelp** [comment] 2018-05-16 02:49
Short story: this is related to look-ahead issues in the concretizer and @citibeth's suggestion to enforce globally choosing virtuals at https://github.com/spack/spack/issues/8133#issuecomment-389343963 is the best approach for the time being.

Note: this error is reproducible without any customized `packages.yaml` on the latest develop Spack.

> `==> Error: ecp-proxy-apps does not depend on libjpeg-turbo`

This happens because the dependency is activated by some variant, which is not specified by the user. More info is available at https://github.com/spack/spack/issues/5707. 

> `Error: Multiple providers found for 'jpeg': ['libjpeg', 'libjpeg-turbo@1.5.90%gcc@5.4.0 arch=linux-gentoo2-x86_64']`

This happens because the package specifications contain a mix of generic and specific constraints on the `jpeg` virtual: in one case a package asks for `jpeg` in another some dependency asks for `libjpeg` (namely `vtk`). The greedy concretization algorithm performs its work in passes and it so happens that in one pass it resolves the `jpeg` virtual, and in some later pass it encounters a specific demand for the `libjpeg` provider. It could report a better error message like `greedy concretization has painted itself into a corner`.

Swapping `depends_on(libjpeg)` with `depends_on(jpeg)` in `vtk` eliminates the reported error for me, although another error of the same kind (for `opengl`/`mesa`) comes up (so I'm guessing you've dealt with that in another manner).

A short term change which I think would reduce these sorts of issues would be to make it possible for the user to specify constraints on conditional dependencies (which would allow one to specify `^libjpeg` without getting the second error in https://github.com/spack/spack/issues/8133#issue-323038076). I'll have to do some thinking on that.

**Comment by scheibelp** [comment] 2018-10-02 21:09
As noted in https://github.com/spack/spack/issues/9408#issuecomment-426365758, if you want to build `ecp-proxy-apps` with mesa, you must enable the `osmesa` variant on the `vtk` dependency (which otherwise requires a system version of `gl`). For example:

`spack spec ecp-proxy-apps ^libjpeg ^python@3: ^vtk+osmesa ^mesa`

This is the same issue as described here (in https://github.com/spack/spack/issues/8133#issuecomment-389378055) for `libjpeg`.

**Comment by weijianwen** [comment] 2018-10-29 05:01
Find a solution in #8133 by @scheibelp .

```
$ spack spec visit ^vtk+osmesa
```

**Comment by alalazo** [comment] 2020-11-01 22:05
> This happens because the dependency is activated by some variant, which is not specified by the user.

Duplicate of #1781

**Closed by alalazo** 2020-11-01 22:05 UTC
Labels: concretization
