### ISSUE TITLE
Allow parallel build of packages

### ISSUE THREAD

**Issue by hegner** [spack/spack#636] opened 2016-03-25 16:25 UTC
To speed up the build of large stacks, it would be nice of the DAG of package dependencies could be build in parallel. A late-failure option would be useful for automated testing. Late-failure means, that if e.g. A depends on B and C, and the build of B fails, C is still being tried to build. 

This ticket is an outcome of the discussion on:
https://groups.google.com/forum/#!topic/spack/RF_jbW8qY9I

**Comment by adamjstewart** [comment] 2016-03-25 16:30
A different but closely related issue: It would be nice if multiple people could use Spack at the same time. Currently, I can't even run `spack list` at the same time as someone else builds a package. This is fine if only a single developer handles Spack installations, but if we want users to be able to build their own packages locally with Spack, this is a deal breaker.

**Comment by hegner** [comment] 2016-04-27 02:55
See 
  https://github.com/LLNL/spack/pull/843
for a proof-of-principle

**Comment by tgamblin** [comment] 2016-04-27 18:43
Does #843 lock the build directory instead of the DB?  That's really all that is needed to make @adamjstewart's wish come true.

**Comment by hegner** [comment] 2016-04-28 07:43
No. It still assumes being the only job around. Can have a look on how to increase the lock granularity.

**Comment by alalazo** [comment] 2016-04-28 10:23
What if we agree on a plan that involves : 
 1. making the lock granularity finer (I think per-package would be fine, per-spec would be optimal)
 1. refactor `spack.package.Package.install` into something that 
   - builds a queue of things that needs to be installed
   - process the queue later using a well defined 'interface' (the default implementation will process the queue sequentially, to maintain the current behavior)

The idea is to make it easy to write different way of processing the installations to be done. For instance here we would like quite much the idea of having a scheduler that will submit independent jobs to be executed on back-end nodes.

@tgamblin @hegner @adamjstewart Would you be interested in something like that?

**Comment by tgamblin** [comment] 2016-04-28 16:56
@alalazo:

1. was intended to be "per install" which is pretty much per spec.  Spack only modifies things per build directory, and stages correspond 1:1 to install prefixes.
2. In the parallel case it actually makes more sense to have each node fetch its own tarball.  So I'm not sure putting the queue on the front-end is always the right idea.  

But yes i'm really interested in the direction.

**Comment by alalazo** [comment] 2017-11-22 06:52
Closing as multiple users are now supported, and #843 has been closed since a while

**Closed by alalazo** 2017-11-22 06:52 UTC
Labels: feature
