### ISSUE TITLE
Question: Dependency resolution

### ISSUE THREAD

**Issue by healther** [spack/spack#4189] opened 2017-05-10 07:57 UTC
Even though I still didn't manage to reproduce the behavior in a minimal example, here is what we observed: 

```
$ spack load --dependencies py-cython py-pytest py-setuptools cmake py-multiarray py-numpy py-matplotlib "^python +ucs4"
$ module list 2>&1 | grep mock
 17) py-mock-2.0.0-gcc-4.9.2-itikmwv
 76) py-mock-2.0.0-gcc-4.9.2-5lzv2ds
```
and
```
$ spack find -fdv /5lzv2ds > out5lzv
$ spack find -fdv /itikmwv > outitik
$ diff out5lzv outitik 
3c3
<         ^py-pbr@1.10.0%gcc cflags="-O2 -march=core2 -pipe" cxxflags="-O2 -march=core2 -pipe" fflags="-O2 -march=core2 -pipe" 
---
>         ^py-pbr@1.8.1%gcc cflags="-O2 -march=core2 -pipe" cxxflags="-O2 -march=core2 -pipe" fflags="-O2 -march=core2 -pipe"
```

My guess is that this problem occured, because ```py-pbr``` got a new version between the install of two of the loaded packages, so that one of those now depends on ```@1.8.1``` and the other on ```@1.10.0```.  

There are now two questions: 
1. Is this intended behavior? I.e. should a package with ```depends_on("py-pbr@1.8:")``` resolve to ```py-pbr@1.8.1``` or to ```@1.10.0``` if ```py-pbr@1.8.1``` is already installed and ```@1.8.1``` and ```@1.10.0``` are known to ```spack```?
2. Should ```spack load``` perform a sanity check, i.e. check that the modules that are loaded only contain exactly one module per package?

In our case this wasn't a problem, and manually unloading ```py-pbr@1.8.1``` made the environment consistent. However, that may not always be possible (think about ```depends_on("A@:1.10")``` and ```depends_on("A@0.9:")```). I'll mark #3827 as WIP until question 2) is answered.

**Comment by adamjstewart** [comment] 2017-05-10 12:55
1. This is the intended behavior. Spack does not currently look to see what is already installed. If you don't specify, it installs the latest version of every dependency. If a dependency far down the DAG has been updated, it will reinstall everything. There has been talk of changing this behavior so that Spack doesn't unnecessarily reinstall packages, but it hasn't happened yet.

2. There is a PR open right now to fix this. If you try to load a package and there are multiple versions that match, it will raise an error asking you to be more specific, much like spack uninstall would.

**Comment by adamjstewart** [comment] 2017-05-10 12:57
2. And I see that the PR I'm referring to is your own :laughing: I guess your real question is what the desired behavior is?

**Comment by healther** [comment] 2017-05-10 13:21
The problem with my solution in #3827 is, that it would strictly allow a user to specify exactly one spec, but checks whether the provided spec was unique.

The following ideas come to mind:
1. Allow only one spec to be specified
2. Allow an arbitrary combination of specs to be specified and provide an environment that is the sum of all environments of each package specified.
3. Allow an arbitrary combination of specs to be specified and ensure that the environment is valid.

1 and 2 are straight forward to implement (1 is done in #3827 and 2 would mean splitting the loads function), but I would rather expect spack to perform 3 if I tell it ```spack load list-of-packages```. The question now is: Is this how other people feel about it too?

**Comment by alalazo** [comment] 2017-05-10 16:38
@healther For 3 you may want to read [this discussion](https://groups.google.com/forum/#!topic/spack/ECirfnwHXlo).

**Comment by adamjstewart** [comment] 2020-08-23 22:59
@healther is this still an issue or can we close it?

**Comment by healther** [comment] 2020-09-29 07:36
We do not use `spack load` or `spack loads` anymore, so I do not really care. But afaik spack never learned to enforce consistency in manual `spack load`s. So feel free to close, but I'm not sure if the underlying problem was ever resolved :)

**Closed** 2022-05-13 09:34 UTC
Labels: question, modules
