### ISSUE TITLE
Improve error message when package name is not consistent with Spack's conventions

### ISSUE THREAD

**Issue by JavierCVilla** [spack/spack#3728] opened 2017-04-06 12:14 UTC
Trying to install a new own package in local (probably wrong created by myself) I got this trace error:

```
Traceback (most recent call last):
  File "/my/path/spack/bin/spack", line 220, in <module>
    main(sys.argv)
  File "/my/path/spack/bin/spack", line 216, in main
    _main(args, unknown)
  File "/my/path/spack/bin/spack", line 183, in _main
    return_val = command(parser, args)
  File "/mnt/my/path/spack/lib/spack/spack/cmd/install.py", line 317, in install
    specs = spack.cmd.parse_specs(args.package, concretize=True)
  File "/mnt/my/path/spack/lib/spack/spack/cmd/__init__.py", line 116, in parse_specs
    spec.concretize()  # implies normalize
  File "/mnt/my/path/spack/lib/spack/spack/spec.py", line 1681, in concretize
    self._expand_virtual_packages(),
  File "/mnt/my/path/spack/lib/spack/spack/spec.py", line 1598, in _expand_virtual_packages
    spec)
  File "/mnt/my/path/spack/lib/spack/spack/concretize.py", line 113, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_externals(spec)
  File "/mnt/my/path/spack/lib/spack/spack/concretize.py", line 87, in _valid_virtuals_and_externals
    if is_spec_buildable(cspec):
  File "/mnt/my/path/spack/lib/spack/spack/package_prefs.py", line 239, in is_spec_buildable
    allpkgs = get_packages_config()
  File "/mnt/my/path/spack/lib/spack/spack/package_prefs.py", line 53, in get_packages_config
    if spack.repo.is_virtual(pkg_name)]
  File "/mnt/my/path/spack/lib/spack/spack/repository.py", line 347, in is_virtual
    return pkg_name in self.provider_index
  File "/mnt/my/path/spack/lib/spack/spack/repository.py", line 233, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "/mnt/my/path/spack/lib/spack/spack/repository.py", line 652, in provider_index
    self._update_provider_index()
  File "/mnt/my/path/spack/lib/spack/spack/repository.py", line 646, in _update_provider_index
    self._provider_index.to_yaml(new)
  File "/mnt/my/path/spack/lib/spack/llnl/util/lock.py", line 312, in __exit__
    if self._as.__exit__(type, value, traceback):
  File "/mnt/my/path/spack/lib/spack/spack/file_cache.py", line 152, in __exit__
    raise value
TypeError: exceptions must be old-style classes or derived from BaseException, not str
```

The last error comes from [here](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/file_cache.py#L152). The trace suggests that `value` does not derive from an Exception class. Any idea what is happening?

**Comment by adamjstewart** [comment] 2017-04-06 12:51
Are you using Python 3? I noticed a similar bug when trying out Spack's Python 3 support. As you have surmised, to solve this problem you need to figure out what error class this is and make sure it extends Exception. A print statement or repr on value might help with that.

**Comment by citibeth** [comment] 2017-04-06 15:47
Note the following from the Python manual:

> Note that __exit__() methods should not reraise the passed-in exception; this is the caller’s responsibility.

The line `raise value` should be removed from __exit__ in file_cache.py (close to line 152).

I don't believe this is Python3.  Python3 exceptions are chained;

https://blog.ionelmc.ro/2014/08/03/the-most-underrated-feature-in-python-3/

**Comment by JavierCVilla** [comment] 2017-04-07 09:00
I think it doesn't have to do with Python3 either. I have just realized how to reproduce the error.

Just create or duplicate an existing package in builtin, Python for instance.

```
cp python python-a
```

Then if the name is modified to `Python_a` using the underscore, the mentioned error appears when trying to install any package:

```
class Python_a(Package):
    """The Python programming language."""
     ...
```

Somehow, Spack detects this wrong class name (using underscore instead of dash) when trying to install any other package and it raises the error. It is a bit confuse and tricky to find the reason. I've not touched a lot the insides of Spack, do you think it would be possible to easily produce a better error output for that case?

**Comment by citibeth** [comment] 2017-04-07 11:52
Have you tried my suggestion?  Spack is doing something the python manual
saya you shouldn't do, and my suggestion fixes that problem.

**Comment by tgamblin** [comment] 2017-04-07 13:22
@javiercvilla: what is `type(value)` when this happens?

**Comment by tgamblin** [comment] 2017-04-07 13:28
And what happens if you try @citibeth's suggestion?  That may cause the same error but it will tell you where the real exception happened, as the trace won't originate from __exit__ (masking the root cause).

**Comment by JavierCVilla** [comment] 2017-04-11 07:21
Sorry for the late answer. 

> @javiercvilla: what is type(value) when this happens?

@tgamblin It refers to the package with the wrong name just created (`Python_a`)

```
Output:  'module' object has no attribute 'PythonA'
```

Following @citibeth's suggestion, the error trace shows the same as the previous `type(value)`, so I guess the line with `raise value` should be just removed .

```
Traceback (most recent call last):
  File "spack/bin/spack", line 220, in <module>
    main(sys.argv)
  File "spack/bin/spack", line 216, in main
    _main(args, unknown)
  File "spack/bin/spack", line 183, in _main
    return_val = command(parser, args)
  File "spack/lib/spack/spack/cmd/install.py", line 317, in install
    specs = spack.cmd.parse_specs(args.package, concretize=True)
  File "spack/lib/spack/spack/cmd/__init__.py", line 116, in parse_specs
    spec.concretize()  # implies normalize
  File "spack/lib/spack/spack/spec.py", line 1677, in concretize
    self._expand_virtual_packages(),
  File "spack/lib/spack/spack/spec.py", line 1594, in _expand_virtual_packages
    spec)
  File "spack/lib/spack/spack/concretize.py", line 113, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_externals(spec)
  File "spack/lib/spack/spack/concretize.py", line 87, in _valid_virtuals_and_externals
    if is_spec_buildable(cspec):
  File "spack/lib/spack/spack/package_prefs.py", line 239, in is_spec_buildable
    allpkgs = get_packages_config()
  File "spack/lib/spack/spack/package_prefs.py", line 53, in get_packages_config
    if spack.repo.is_virtual(pkg_name)]
  File "spack/lib/spack/spack/repository.py", line 347, in is_virtual
    return pkg_name in self.provider_index
  File "spack/lib/spack/spack/repository.py", line 233, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "spack/lib/spack/spack/repository.py", line 652, in provider_index
    self._update_provider_index()
  File "spack/lib/spack/spack/repository.py", line 644, in _update_provider_index
    self._provider_index.update(namespaced_name)
  File "spack/lib/spack/spack/provider_index.py", line 100, in update
    pkg = spec.package
  File "spack/lib/spack/spack/spec.py", line 1116, in package
    return spack.repo.get(self)
  File "spack/lib/spack/spack/repository.py", line 74, in converter
    return function(self, spec_like, *args, **kwargs)
  File "spack/lib/spack/spack/repository.py", line 317, in get
    return self.repo_for_pkg(spec).get(spec)
  File "spack/lib/spack/spack/repository.py", line 74, in converter
    return function(self, spec_like, *args, **kwargs)
  File "spack/lib/spack/spack/repository.py", line 576, in get
    package_class = self.get_pkg_class(spec.name)
  File "spack/lib/spack/spack/repository.py", line 832, in get_pkg_class
    cls = getattr(module, class_name)
**AttributeError: 'module' object has no attribute 'PythonA'**
```

**Comment by adamjstewart** [comment] 2017-04-11 11:43
If you're still wondering why the error is happening in the first place, the package class should be `PythonA`, not `Python_a`. But I agree that we should fix things so the error message is more clear.

In general, there's no reason to create a package by hand anymore. Even if there is no download for your package, you can still run `spack create --name python-a` and spack will choose the appropriate class name.

**Comment by JavierCVilla** [comment] 2017-04-11 13:01
Thanks @adamjstewart, I knew that was the reason of the error. I accidentally created a package with the wrong name and then I started to suffer the previous error for every package I tried to install.

> you can still run `spack create --name python-a` and spack will choose the appropriate class name.

Good to know !

**Comment by alalazo** [comment] 2022-03-02 14:48
On 8d118104c79bca646b193f84857b75b7f54359df I get:
```console
 spack spec zlib
==> Error: module 'spack.pkg.builtin.zlib' has no attribute 'Zlib'
```
after changing `Zlib` class name. I'll be closing the issue.

**Closed by alalazo** 2022-03-02 14:48 UTC
Labels: bug
