### ISSUE TITLE
Concretizer issue using variants

### ISSUE THREAD

**Issue by junghans** [spack/spack#12851] opened 2019-09-17 21:48 UTC
If I have two packages `a` and `b` with `a` being:
```python
class A(BundlePackage):
    """package A"""

    version('1')
    depends_on('hwloc')
```
and `b` being:
```python
class B(BundlePackage):
    """Package B"""
    version('1')
    depends_on('a')
    variant("hwloc", default=True, description="enable hwloc")
    depends_on('hwloc@1.11.8', when= "+hwloc")
```
I am getting the following concretization error:
```
spack spec b
Input spec
--------------------------------
b

Concretized
--------------------------------
==> Error: An unsatisfiable version constraint has been detected for spec:

    hwloc@2.0.2%gcc@4.8.5~cairo~cuda~gl+libxml2~nvml+pci+shared arch=linux-centos7-x86_64
        ^libpciaccess
            ^libtool
                ^m4@1.4.6:
            ^pkgconf@1.6.1%gcc@4.8.5 arch=linux-centos7-x86_64
            ^util-macros
        ^libxml2
            ^libiconv
            ^xz
            ^zlib


while trying to concretize the partial spec:

    b@1%gcc@4.8.5+hwloc arch=linux-centos7-x86_64
        ^a@1%gcc@4.8.5 arch=linux-centos7-x86_64
            ^hwloc@2.0.2%gcc@4.8.5~cairo~cuda~gl+libxml2~nvml+pci+shared arch=linux-centos7-x86_64
                ^libpciaccess
                    ^libtool
                        ^m4@1.4.6:
                    ^pkgconf@1.6.1%gcc@4.8.5 arch=linux-centos7-x86_64
                    ^util-macros
                ^libxml2
                    ^libiconv
                    ^xz
                    ^zlib


b requires hwloc version 1.11.8, but spec asked for 2.0.2
```
However if I drop the variant in `b`:
```python
class B(BundlePackage):
    """package B"""
    version('1')
    depends_on('a')
    depends_on('hwloc@1.11.8')
```
concretization works:
```
pack spec b
Input spec
--------------------------------
b

Concretized
--------------------------------
b@1%gcc@4.8.5+hwloc arch=linux-centos7-x86_64
    ^a@1%gcc@4.8.5 arch=linux-centos7-x86_64
        ^hwloc@1.11.8%gcc@4.8.5~cairo~cuda~gl+libxml2~nvml+pci+shared arch=linux-centos7-x86_64
            ^libpciaccess@0.13.5%gcc@4.8.5 arch=linux-centos7-x86_64
                ^libtool@2.4.6%gcc@4.8.5 arch=linux-centos7-x86_64
                    ^m4@1.4.18%gcc@4.8.5 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-centos7-x86_64
                        ^libsigsegv@2.11%gcc@4.8.5 arch=linux-centos7-x86_64
                ^pkgconf@1.6.1%gcc@4.8.5 arch=linux-centos7-x86_64
                ^util-macros@1.19.1%gcc@4.8.5 arch=linux-centos7-x86_64
            ^libxml2@2.9.9%gcc@4.8.5~python arch=linux-centos7-x86_64
                ^libiconv@1.15%gcc@4.8.5 arch=linux-centos7-x86_64
                ^xz@5.2.4%gcc@4.8.5 arch=linux-centos7-x86_64
                ^zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-x86_64
            ^numactl@2.0.12%gcc@4.8.5 arch=linux-centos7-x86_64
                ^autoconf@2.69%gcc@4.8.5 arch=linux-centos7-x86_64
                    ^perl@5.26.2%gcc@4.8.5+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-centos7-x86_64
                        ^gdbm@1.18.1%gcc@4.8.5 arch=linux-centos7-x86_64
                            ^readline@7.0%gcc@4.8.5 arch=linux-centos7-x86_64
                                ^ncurses@6.1%gcc@4.8.5~symlinks~termlib arch=linux-centos7-x86_64
                ^automake@1.16.1%gcc@4.8.5 arch=linux-centos7-x86_64
```

**Comment by scheibelp** [comment] 2019-09-17 21:57
This is a duplicate of https://github.com/spack/spack/issues/5465

See also: other issues mentioned under item [1] of https://github.com/spack/spack/wiki/Issue-Disambiguation

In short: this happens because the concretizer algorithm is greedy and finalizes details of specs before it is certain that will not lead to constraint errors. To handle things like this in full generality the current plan is to handle this with a SAT solver (an approximate one), which is being pursued by @tgamblin. 

Your observation about removing the constraint is correct. In other cases people manually specify the constraint on the command line `spack spec b ^hwloc@1.11.8`.

If this seems unique or not captured by one of the listed issues in [1] of https://github.com/spack/spack/wiki/Issue-Disambiguation then feel free to reopen.

**Closed by scheibelp** 2019-09-17 21:57 UTC
Labels: bug, concretization
