### ISSUE TITLE
I try to build mysql,but there is a ChecksumError about cmake,I do not know how to solve it.

### ISSUE THREAD

**Issue by luxianjun** [spack/spack#12238] opened 2019-08-02 09:22 UTC
ARM centos7.6-----
[root@localhost home]# spack install mysql
==> diffutils is already installed in /home/spack/opt/spack/linux-centos7-aarch64/gcc-4.8.5/diffutils-3.7-bil5xacyoqeoaid5ojaiuj36smsqe24l
==> bzip2 is already installed in /home/spack/opt/spack/linux-centos7-aarch64/gcc-4.8.5/bzip2-1.0.8-zyo7dbmun5d2dgvqmw6ugbovpbmmhwcq
==> zlib is already installed in /home/spack/opt/spack/linux-centos7-aarch64/gcc-4.8.5/zlib-1.2.11-6yywoqcw7vz3u4o6hs2v4avlhb24ynli
==> boost is already installed in /home/spack/opt/spack/linux-centos7-aarch64/gcc-4.8.5/boost-1.68.0-c3teu7kcrykxmnqgnaaenia6zuw4vwpc
==> pkgconf is already installed in /home/spack/opt/spack/linux-centos7-aarch64/gcc-4.8.5/pkgconf-1.6.1-blgthphw2rq4boczzktzjigyknswb33c
==> ncurses is already installed in /home/spack/opt/spack/linux-centos7-aarch64/gcc-4.8.5/ncurses-6.1-nqcj65nig4sckrjy5drqbdf7arx56hib
==> readline is already installed in /home/spack/opt/spack/linux-centos7-aarch64/gcc-4.8.5/readline-7.0-id45zluu6nhktnw5hzc6mxkj33xkr7rn
==> gdbm is already installed in /home/spack/opt/spack/linux-centos7-aarch64/gcc-4.8.5/gdbm-1.18.1-wa33dg4l7kwfblkeswbgah5gn272dsi3
==> perl is already installed in /home/spack/opt/spack/linux-centos7-aarch64/gcc-4.8.5/perl-5.26.2-pqcauvosaaz5jjaurh7n2xe5eytnv3ec
==> openssl is already installed in /home/spack/opt/spack/linux-centos7-aarch64/gcc-4.8.5/openssl-1.1.1b-wgjyu6h2jiddjcw5pweeihl3b3pngod7
==> Installing cmake
==> Searching for binary cache of cmake
==> Warning: No Spack mirrors are currently configured
==> No binary for cmake found: installing from source
==> Fetching https://github.com/Kitware/CMake/releases/download/v3.15.1/cmake-3.15.1.tar.gz
######################################################################## 100.0%
==> Error: ChecksumError: sha256 checksum failed for /home/spack/var/spack/stage/cmake-3.15.1-xh27knfhtwfzydhavtrtmta2xzpr47wn/cmake-3.15.1.tar.gz
    Expected cdee72c5ef934c4972f1ad4e9c35712589345f3470a3cf15f7be493c170cc965 but got 18dec548d8f8b04d53c60f9cedcebaa6762f8425339d1e2c889c383d3ccdd7f7

/home/spack/lib/spack/spack/package.py:1055, in do_fetch:
       1052        self.stage.fetch(mirror_only)
       1053        self._fetch_time = time.time() - start_time
       1054
  >>   1055        if checksum and self.version in self.versions:
       1056            self.stage.check()
       1057
       1058        self.stage.cache_local()

[root@localhost home]#
no problem before,
Could anyone help me to solve it? Thanks!

**Comment by scheibelp** [comment] 2019-08-03 00:59
`spack stage cmake@3.15.1` works for me. I think that a temporary error may have resulted in a botched download of CMake. Can you try the following:

* `spack clean cmake` (and try `spack stage cmake@3.15.1`)
* (if the first suggestion doesn't work) `spack clean -d` (this purges cached downloads of all package sources)

If one of those works, could you close this? If neither works, could you post that here?

**Comment by adamjstewart** [comment] 2019-08-03 02:53
Duplicate of #12181. Fixed by #12182. Update to the latest develop branch and this should be fixed.

**Closed by adamjstewart** 2019-08-03 02:53 UTC
Labels: build-error, impact-low
