### ISSUE TITLE
sqlite install failed on power 9

### ISSUE THREAD

**Issue by fwang2** [spack/spack#6698] opened 2017-12-15 19:08 UTC
Steps to reproduce:

```console
$ spack install sqlite
==> Building sqlite [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j160'

26 errors found in build log:
     [ ... ]
     115   In file included from /usr/include/termios.h:40:0,
     116                    from /usr/include/bits/ioctl-types.h:5,
     117                    from /usr/include/sys/ioctl.h:29,
     118                    from /usr/include/editline/readline.h:77,
     119                    from shell.c:103:
     120   shell.c: In function ‘KeccakF1600Step’:
  >> 121   shell.c:894:7: error: expected identifier or ‘(’ before numeric constant
     122      u64 B0, B1, B2, B3, B4;
     123          ^
  >> 124   shell.c:950:8: error: lvalue required as left operand of assignment
     125        B0 = (A00^D0);
     126           ^
  >> 127   shell.c:951:5: error: ‘B1’ undeclared (first use in this function)
     128        B1 = ROL64((A11^D1), 44);
     129        ^
     130   shell.c:951:5: note: each undeclared identifier is reported only once for each function it appears in
  >> 131   shell.c:952:5: error: ‘B2’ undeclared (first use in this function)
     132        B2 = ROL64((A22^D2), 43);
     133        ^
  >> 134   shell.c:953:5: error: ‘B3’ undeclared (first use in this function)
     135        B3 = ROL64((A33^D3), 21);
     136        ^
  >> 137   shell.c:954:5: error: ‘B4’ undeclared (first use in this function)
     138        B4 = ROL64((A44^D4), 14);
     139        ^
  >> 140   shell.c:965:8: error: lvalue required as left operand of assignment
     141        B0 = ROL64((A03^D3), 28);
     142           ^
  >> 143   shell.c:974:8: error: lvalue required as left operand of assignment
     144        B0 = ROL64((A01^D1), 1);
     145           ^
  >> 146   shell.c:988:8: error: lvalue required as left operand of assignment
     147        B0 = ROL64((A04^D4), 27);
     148           ^
  >> 149   shell.c:997:8: error: lvalue required as left operand of assignment
     150        B0 = ROL64((A02^D2), 62);
     151           ^
  >> 152   shell.c:1017:8: error: lvalue required as left operand of assignment
     153        B0 = (A00^D0);
     154           ^
  >> 155   shell.c:1032:8: error: lvalue required as left operand of assignment
     156        B0 = ROL64((A33^D3), 28);
     157           ^
  >> 158   shell.c:1041:8: error: lvalue required as left operand of assignment
     159        B0 = ROL64((A11^D1), 1);
     160           ^
  >> 161   shell.c:1055:8: error: lvalue required as left operand of assignment
     162        B0 = ROL64((A44^D4), 27);
     163           ^
  >> 164   shell.c:1064:8: error: lvalue required as left operand of assignment
     165        B0 = ROL64((A22^D2), 62);
     166           ^
  >> 167   shell.c:1084:8: error: lvalue required as left operand of assignment
     168        B0 = (A00^D0);
     169           ^
  >> 170   shell.c:1099:8: error: lvalue required as left operand of assignment
     171        B0 = ROL64((A43^D3), 28);
     172           ^
  >> 173   shell.c:1108:8: error: lvalue required as left operand of assignment
     174        B0 = ROL64((A31^D1), 1);
     175           ^
  >> 176   shell.c:1122:8: error: lvalue required as left operand of assignment
     177        B0 = ROL64((A24^D4), 27);
     178           ^
  >> 179   shell.c:1131:8: error: lvalue required as left operand of assignment
     180        B0 = ROL64((A12^D2), 62);
     181           ^
  >> 182   shell.c:1151:8: error: lvalue required as left operand of assignment
     183        B0 = (A00^D0);
     184           ^
  >> 185   shell.c:1166:8: error: lvalue required as left operand of assignment
     186        B0 = ROL64((A13^D3), 28);
     187           ^
  >> 188   shell.c:1175:8: error: lvalue required as left operand of assignment
     189        B0 = ROL64((A21^D1), 1);
     190           ^
  >> 191   shell.c:1189:8: error: lvalue required as left operand of assignment
     192        B0 = ROL64((A34^D4), 27);
     193           ^
  >> 194   shell.c:1198:8: error: lvalue required as left operand of assignment
     195        B0 = ROL64((A42^D2), 62);
     196           ^
  >> 197   make: *** [sqlite3-shell.o] Error 1
     198   make: *** Waiting for unfinished jobs....
     199   libtool: compile:  /autofs/nccs-svm1_home2/fwang2/spack/lib/spack/env/gcc/gcc -DPACKAGE_NAME=\"sqlite\" -DPACKAGE_TARNAME=\"sqlite\" -DPACKAGE_VERSION=\"3.21.0\" "-DPACKAGE_STRING=\"sqlite 3.21.0\"" -DPACKAGE_BUGREPORT=\"http://www.sqlite.org\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sqlite\" -DVERSION=\"3.21.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_FDATASYNC=1 -DHAVE_USLEEP=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_DECL_STRERROR_R=1 -DHAVE_STRERROR_R=1 -DHAVE_EDITLINE_READLINE_H=1 -DHAVE_EDITLINE=1 -DHAVE_POSIX_FALLOCATE=1 -I. -I/autofs/nccs-svm1_home2/fwang2/spack/var/spack/stage/sqlite-3.21.0-pgplvagylbxch2vp3k6uugynpmrdku4j/sqlite-autoconf-3210000 -D_REENTRANT=1 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_RTREE -MT sqlite3.lo -MD -MP -MF .deps/sqlite3.Tpo -c sqlite3.c  -fPIC -DPIC -o .libs/sqlite3.o
     200   mv -f .deps/sqlite3-sqlite3.Tpo .deps/sqlite3-sqlite3.Po
     201   libtool: compile:  /autofs/nccs-svm1_home2/fwang2/spack/lib/spack/env/gcc/gcc -DPACKAGE_NAME=\"sqlite\" -DPACKAGE_TARNAME=\"sqlite\" -DPACKAGE_VERSION=\"3.21.0\" "-DPACKAGE_STRING=\"sqlite 3.21.0\"" -DPACKAGE_BUGREPORT=\"http://www.sqlite.org\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sqlite\" -DVERSION=\"3.21.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_FDATASYNC=1 -DHAVE_USLEEP=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_DECL_STRERROR_R=1 -DHAVE_STRERROR_R=1 -DHAVE_EDITLINE_READLINE_H=1 -DHAVE_EDITLINE=1 -DHAVE_POSIX_FALLOCATE=1 -I. -I/autofs/nccs-svm1_home2/fwang2/spack/var/spack/stage/sqlite-3.21.0-pgplvagylbxch2vp3k6uugynpmrdku4j/sqlite-autoconf-3210000 -D_REENTRANT=1 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_RTREE -MT sqlite3.lo -MD -MP -MF .deps/sqlite3.Tpo -c sqlite3.c -o sqlite3.o >/dev/null 2>&1
     202   mv -f .deps/sqlite3.Tpo .deps/sqlite3.Plo


```

### Information on your system

- This is on Power 9 running Redhat 7 el7.ppc64le
- GCC 6.3.1 20170110 (I also tried the default gcc4.8.5, same error)

**Comment by scheibelp** [comment] 2017-12-15 19:22
It appears @lee218llnl encountered a similar issue and reported it at http://sqlite.1065341.n5.nabble.com/Macro-expansion-of-B0-on-Linux-PPC-system-td95630.html

You may have to add a patch which makes the edits suggested in his post.

**Comment by lee218llnl** [comment] 2017-12-15 22:14
Thanks @scheibelp, looks like no one ever responded to my SQLite query! I will ping them again.

**Comment by justinclift** [comment] 2017-12-16 04:13
There's a reply this time: :smile:

* http://sqlite.1065341.n5.nabble.com/Macro-expansion-of-B0-on-Linux-PPC-system-tp95630p99255.html

**Comment by fwang2** [comment] 2017-12-16 04:23
Thanks for following this up, everyone. I believe I tried both 3.20 and
3.21, the problem is still there.

**Comment by justinclift** [comment] 2017-12-16 04:27
Damn.  @lee218llnl are you ok to keep following this up on the sqlite-users mailing list? :smile:

**Comment by fwang2** [comment] 2017-12-18 15:40
A bit more on this: Apparently, spack sqlite already have a patch for it, but is wasn't written to apply for all version except the specified version. 
This can be resolved by
```
diff --git a/var/spack/repos/builtin/packages/sqlite/package.py b/var/spack/repos/builtin/packages/sqlite/package.py
index 5c1b825..f7eb4cb 100644
--- a/var/spack/repos/builtin/packages/sqlite/package.py
+++ b/var/spack/repos/builtin/packages/sqlite/package.py
@@ -51,6 +51,7 @@ class Sqlite(AutotoolsPackage):
     # variable named B0 and will fail to compile when the macro is found. The
     # following patch undefines the macro in shell.c
     patch('sqlite_b0.patch', when='@3.18.0')
+    patch('sqlite_b0.patch', when='@3.21.0')

     # Starting version 3.17.0, SQLite uses compiler built-ins
     # __builtin_sub_overflow(), __builtin_add_overflow(), and
```
I guess this should be arch specific, version specific patch ... This will enable sqlite built properly, and python built properly as well on PPC platform.

**Comment by lee218llnl** [comment] 2017-12-18 17:15
I still see the problem with sqlite 3.21 on Power 8 too. I have sent another message with configure/build logs to the sqlite email list. Stay tuned.

**Comment by lee218llnl** [comment] 2017-12-19 16:20
Just created a PR #6728 to apply the patch through version 3.21.0. The sqlite community had a fix, but then a regression. Hopefully this will get fixed for good in the next release. In the meantime, just apply the patch to the 3.21.0 version.

**Comment by scheibelp** [comment] 2017-12-20 23:41
I'm closing this since #6728 is now merged. Feel free to reopen if problems continue.

**Closed by scheibelp** 2017-12-20 23:41 UTC
Labels: build-error
