### ISSUE TITLE
Modules loaded with spack don't show up in module list

### ISSUE THREAD

**Issue by JanKleine** [spack/spack#15373] opened 2020-03-06 09:47 UTC
When loading a module with `spack load` the module doesn't show up in `module list`, however the module still takes effect.

I checked an older system where spack is on version `0.12.1` and there it works, though rolling back to that version didn't help.
The spack git repo also defaults to the `develop` branch, which I found interesting, but checking out `releases/v0.14` also didn't help.

### Spack version

```console
$ spack --version
0.14.0-126-9edf812
```

### Steps to reproduce the issue

```console
$ nvim --version
-bash: nvim: command not found
$ spack load neovim
$ nvim --version
NVIM v0.3.4
[...]
$ module list
No Modulefiles Currently Loaded.
```

### Information on your system

OS: `CentOS 7.7.1908`
Module version: `Modules Release 4.4.0 (2019-11-17)`

The system was just setup, I cloned `https://github.com/spack/spack.git` and activated it with `source /path/to/spack/share/spack/setup-env.sh` in my `.bashrc`

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment] 2020-03-06 10:14
Hi @JanKleine ! Since #14062 has been merged `spack load` does not depend anymore on module files - so this is the expected behavior. Feel free to reopen if you think there are other issues I missed.

**Closed by alalazo** 2020-03-06 10:14 UTC
Labels: bug, wontfix

**Comment by mrzv** [comment] 2020-03-13 21:07
@alalazo Is there a way to list loaded modules now? `module list` was the only way I knew how to do this.

**Comment by mrzv** [comment] 2020-03-13 21:14
Never mind, I found it: `spack find --loaded`

**Comment by sjpb** [comment] 2020-05-15 15:45
Glad I found this - I think the https://spack-tutorial.readthedocs.io/en/latest/tutorial_modules.html still suggests this is the case
