### ISSUE TITLE
Canceling/interrupting spack install result into invalid install 

### ISSUE THREAD

**Issue by pramodk** [spack/spack#10080] opened 2018-12-11 21:13 UTC
If I cancel building a package in the middle of build phase, I don’t expect that package in db. But instead I see following:

Here I terminated jenkins job during configure step :

```
==> Building gettext [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
Sending interrupt signal to process
sh: line 1: 431746 Terminated              JENKINS_SERVER_COOKIE=$jsc '/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/deploy/spack/deploy@tmp/durable-2c521847/script.sh' > '/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/deploy/spack/deploy@tmp/durable-2c521847/jenkins-log.txt' 2>&1
```

If I look at install prefix, only spec.yaml exist:

```
$ tree -a /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/tools/1986-01-01/linux-rhel7-x86_64/gcc-6.4.0/gettext-0.19.8.1-e3ptifce2s
/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/tools/1986-01-01/linux-rhel7-x86_64/gcc-6.4.0/gettext-0.19.8.1-e3ptifce2s
└── .spack
    └── spec.yaml

1 directory, 1 file
```

and `.spack-db/index.json` has entry :

```
{
 "database": {
  "installs": {
   "e3ptifce2s3zbs6qeb667cbm2mxs3p2i": {
    "explicit": true,
    "installation_time": 1544507891.338126,
    "ref_count": 1,
    "installed": true,
    "path": "/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/tools/1986-01-01/linux-rhel7-x86_64/gcc-6.4.0/gettext-0.19.8.1-e3ptifce2s",
    "spec": {
     "gettext": {
      "version": "0.19.8.1",
      "arch": {
       "platform": "linux",
       "platform_os": "rhel7",
       "target": "x86_64"
      },
      "compiler": {
       "name": "gcc",
       "version": "6.4.0"
....
```

and spack find shows :

```
==> 10 installed packages
-- linux-rhel7-x86_64 / gcc@6.4.0 -------------------------------
e3ptifc gettext@0.19.8.1+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz
```

I couldn't re-produce this issue on my laptop when I manually cancelled build using `Ctl^C`. I wonder if this is different if process is terminated/killed.

**Comment by scheibelp** [comment] 2018-12-12 02:03
Did you `spack reindex` after the install failed?

**Comment by pramodk** [comment] 2018-12-12 22:41
yes..I am quite sure about the issue. Here is another example from today (posted on slack):

Matplotlib failed with below error :

```Error
ProcessError: Command exited with status 1: '/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/python-packages/1987-01-01/linux-rhel7-x86_64/gcc-6.4.0/python-2.7.15-r4qk3mmkiv/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'build'
Stacktrace
Traceback (most recent call last):
File "/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/deploy/spack/lib/spack/spack/build_environment.py", line 726, in child_process
return_value = function()
File "/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/deploy/spack/lib/spack/spack/package.py", line 1509, in build_process
phase(self.spec, self.prefix)
File "/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/deploy/spack/lib/spack/spack/package.py", line 101, in phase_wrapper
phase(spec, prefix)
File "/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/deploy/spack/lib/spack/spack/build_systems/python.py", line 153, in build
self.setup_py('build', *args)
File "/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/deploy/spack/lib/spack/spack/build_systems/python.py", line 121, in setup_py
self.python('-s', setup, '--no-user-cfg', *args, **kwargs)
File "/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/deploy/spack/lib/spack/spack/build_systems/python.py", line 115, in python
inspect.getmodule(self).python(*args, **kwargs)
File "/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/deploy/spack/lib/spack/spack/util/executable.py", line 189, in __call__
proc.returncode, long_msg)
ProcessError: Command exited with status 1:
'/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/python-packages/1987-01-01/linux-rhel7-x86_64/gcc-6.4.0/python-2.7.15-r4qk3mmkiv/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'build'
Standard Output
==> Executing phase: 'build'
==> '/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/python-packages/1987-01-01/linux-rhel7-x86_64/gcc-6.4.0/python-2.7.15-r4qk3mmkiv/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'build'
Matplotlib 3.0+ does not support Python 2.x, 3.0, 3.1, 3.2, 3.3, or 3.4.
Beginning with Matplotlib 3.0, Python 3.5 and above is required.
This may be due to an out of date pip.
Make sure you have pip >= 9.0.1.
```

But `spack reindex && spack find` still shows the package. Hence, I did:

```
mv .spack-db .spack-db-old
spack reindex
```

which created new `.spack-db`. But if I look at `.spack-db/index.json` file there is an entry:

```
"ztz7ckyxo4b3cxfe6ohn6zr57pfiv4v3": {
    "explicit": false,
    "installation_time": 1544647265.505449,
    "ref_count": 1,
    "installed": true,
    "path": "/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/python-packages/1987-01-01/linux-rhel7-x86_64/gcc-6.4.0/py-matplotlib-3.0.0-ztz7ckyxo4",
    "spec": {
     "py-matplotlib": {
      "version": "3.0.0",
```

and obviously that path doesn’t exist:

```
$ ll /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/python-packages/1987-01-01/linux-rhel7-x86_64/gcc-6.4.0/py-matplotlib-3.0.0-ztz7ckyxo4
ls: cannot access /gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/install/python-packages/1987-01-01/linux-rhel7-x86_64/gcc-6.4.0/py-matplotlib-3.0.0-ztz7ckyxo4: No such file or directory
```
I am confused how `spack reindex` works. (i.e. from where it re-construct database)

**Comment by scheibelp** [comment] 2018-12-12 23:04
> yes..I am quite sure about the issue. Here is another example from today (posted on slack):

I was specifically asking about reindex, because depending on when you invoke reindex, you can force Spack to recognize a failed install as a successful install. This partly comes from how the install proceeds:

1. create the install/metadata directory
2. do the build
3. if successful, add the build to the install directory and update the DB

`spack reindex` works with the metadata directory, so a failed install that is not removed can be interpreted as a successful install. Generally then, if you fail an install in the middle, it is currently advisable to redo the install or remove the prefix before invoking `spack reindex`.

It is possible we could avoid instances of this problem by moving the creation of the metadata directory to step 4. I would have to investigate why that doesn't happen already.

Does that sound like what might have happened here?

**Comment by alalazo** [comment] 2022-03-10 10:27
Closing as I can't reproduce this either on my laptop and https://github.com/spack/spack/issues/10080#issuecomment-446777686 never got answered. Feel free to open a new issue if you still have troubles.

**Closed by alalazo** 2022-03-10 10:27 UTC
Labels: bug, build-error, pkg-database
