### ISSUE TITLE
'spack env package %compiler' error

### ISSUE THREAD

**Issue by jrood-nrel** [spack/spack#2519] opened 2016-12-07 23:55 UTC
`spack env package %compiler` appears to error for me
`spack env package%compiler` appears to work for me

I believe the space should be legal, correct?

**Comment by becker33** [comment] 2016-12-08 19:05
I see the same error. From a comment in the python file for the env command:

"# Specs may have spaces in them, so if they do, require that the
# caller put a '--' between the spec and the command to be
# executed.  If there is no '--', assume that the spec is the
# first argument."

So this seems like the designed behavior. @tgamblin is this really the behavior we want for `spack env`? It makes the spec parser for `spack env` dissimilar to every other command in Spack. If so, we should probably document it better, but I would be inclined to require the `--` separator for all specs in `spack env` to keep the spec parser consistent.

**Comment by alalazo** [comment] 2017-11-22 12:55
Closing as a duplicate of #659

**Closed by alalazo** 2017-11-22 12:55 UTC
Labels: bug, duplicate
