### ISSUE TITLE
filter_file can't handle non-UTF8 files

### ISSUE THREAD

**Issue by omor1** [spack/spack#7358] opened 2018-02-28 18:08 UTC
PAPI never completes building; spack appears to hang on `filter_file`, running at 100% CPU.

### Expected Result
PAPI builds and installs.

### Actual Result
Spack hangs after filtering files, consuming 100% CPU on a single core.
It never appears to actually get to `make()`, from looking at the build log.

### Steps to reproduce the issue
```console
$ spack install papi
```

### Information on your system
* Arch Linux
* x86_64
* glibc 2.26
* GCC 7.3.0
* Python 3.6.4

**Comment by omor1** [comment] 2018-02-28 18:09
This could be related to #5029, but I _do_ have a Fortran compiler installed (`gfortran`), and I don't get any error message—the build just never finishes and I have to kill it.

**Comment by adamjstewart** [comment] 2018-02-28 23:49
@sknigh Since I know you've installed PAPI before, have you ever encountered this?

**Comment by alalazo** [comment] 2018-03-06 11:52
So far I built `papi` on `ubuntu:14.04`, `ubuntu:16.04` and `centos:latest` without issues using #7204. I'll try to add a template for an Arch linux image. If that succeeds I'll post here and close the issue.

**Comment by alalazo** [comment] 2018-03-06 12:38
@adamjstewart @omor1 Confirmed the issue with an `archlinux` container:
```console
top - 12:36:33 up  5:15,  0 users,  load average: 1.22, 1.26, 0.96
Tasks:   5 total,   2 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.7 us,  2.2 sy,  0.0 ni, 88.5 id,  0.6 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8051388 total,   295832 free,  6016188 used,  1739368 buff/cache
KiB Swap:  8265724 total,  7700100 free,   565624 used.  1182848 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
  118 root      20   0  241288 130852   3456 R 100.0  1.6  13:00.24 python      
    1 root      20   0  239868 136416   9596 S   0.0  1.7   0:08.55 python      
  114 root      20   0  241288 132180   4752 S   0.0  1.6   0:00.16 python      
 2036 root      20   0   14320   3364   2884 S   0.0  0.0   0:00.01 bash        
 2055 root      20   0   30308   3036   2636 R   0.0  0.0   0:00.00 top         

[root@e820bbe67a8d spack]# python --version
Python 3.6.4

[root@e820bbe67a8d spack]# gcc --version
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by omor1** [comment] 2018-03-06 21:40
After much frustration, I've figured out that it hangs on [line 138 of filesystem.py](../blob/b0795d84c70cdfbb0f69bb65f713e967899d86d2/lib/spack/llnl/util/filesystem.py#L138) when filtering `sw_multiplex.c`.  `sw_multiplex.c` is encoded using cp1252 (windows-1252); it contains some bullet point characters (encoded with 0x95). I think that this is the reason for the issues.

It might be possible to pass `fileinput.hook_encoded()` as the `openhook` parameter to fix this. I'm not sure why there is different behavior on other systems, or why that causes `fileinput.input()` to hang.

**Comment by deleeke** [comment] 2018-03-09 21:04
This is happening for me as well:

```
[deleeke@dogwood-login2 bin]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[deleeke@dogwood-login2 bin]$ python --version
Python 3.6.3
[deleeke@dogwood-login2 bin]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.3 (Maipo)
[deleeke@dogwood-login2 bin]$ 
```

**Comment by deleeke** [comment] 2018-03-09 21:15
I have a build of PAPI that I would like to use but I'm having trouble figuring out how to use the external packages syntax laid out here:
https://spack.readthedocs.io/en/latest/build_settings.html#external-packages

This is blocking me from building openspeedshop

**Comment by deleeke** [comment] 2018-03-09 21:32
I temporarily switched this line to read like this and I got through building papi:
```diff
 try:                                                                                                                                     
-             for line in fileinput.input(filename, inplace=True):
+            for line in fileinput.input(filename, openhook=fileinput.hook_encoded("cp1252"))                                                                               
                 print(re.sub(regex, repl, line.rstrip('\n'))) 
```

Apparently does not work with the `inplace=True` option. Maybe you could try and detect the encoding? :man_shrugging: 

After papi built, I changed it back. now seeing if cbtf-krell will build...

**Comment by omor1** [comment] 2018-03-10 05:03
So we have confirmation that it is because of the cp1252 file?
I've looked through the source code and there are some other files that use non-ASCII and non-UTF8 characters (mostly cp1252 and ISO 8859-1 (latin1)). We could try enumerating all these and patch them to replace them with ASCII or UTF8 equivalents (or try to get upstream to do it), but a more general solution is probably better.

As a side note, it appears that PAPI 5.6.0 was released last December—it should probably be added to the Spack package.

**Comment by adamjstewart** [comment] 2018-05-19 17:33
I'm seeing a similar problem with another package. I'm trying to add a package for `fyba`, but their installation instructions require me to replace all occurrences of `sys/vfs.h` with `sys/mount.h`. I'm using `filter_file` to do this, but all of the files are Norwegian and contain a lot of non-ASCII characters.  This results in the following error message:
```console
==> Error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 731: invalid start byte
```
Here is the package if you want to try to reproduce the bug:
```python
from spack import *                                                             
                                                                                
                                                                                
class Fyba(AutotoolsPackage):                                                   
    """OpenFYBA is the source code release of the FYBA library, distributed     
    by the National Mapping Authority of Norway (Statens kartverk) to read      
    and write files in the National geodata standard format SOSI."""            
                                                                                
    homepage = "https://github.com/kartverket/fyba"                             
    url      = "https://github.com/kartverket/fyba/archive/4.1.1.tar.gz"        
                                                                                
    version('4.1.1', 'ab687582efdef26593796271529a10cb')                        
                                                                                
    # configure: error: cannot find install-sh or install.sh                    
    force_autoreconf = True                                                     
                                                                                
    depends_on('autoconf', type='build')                                        
    depends_on('automake', type='build')                                        
    depends_on('libtool',  type='build')                                        
    depends_on('m4',       type='build')                                        
                                                                                
    @when('platform=darwin')                                                    
    def patch(self):                                                            
        # fatal error: 'sys/vfs.h' file not found                               
        # https://github.com/kartverket/fyba/issues/12                          
        filter_file(                                                            
            'sys/vfs.h', 'sys/mount.h',                                         
            'configure.ac',                                                     
            'src/UT/INQSIZE.cpp',                                               
            'src/UT/INQTID.cpp',                                                
            'src/UT/DISKINFO.cpp'                                               
        )                  
```
Note that you'll either need to build on macOS, or uncomment the `@when('platform=darwin')` line if you want to reproduce this issue. This bug only occurred for me when using Python 3, I didn't encounter the bug when using Python 2.

**Comment by angel-devicente** [comment] 2019-08-19 09:37
I was just bitten by this bug while trying to install TAU. 

My temporary hack around this was to do:

```
spack load python@2.7
spack install papi
spack unload python@2.7
```
And then continue with the rest of the TAU installation, but of course it would be nice to make it work properly with Python3.

AdV

**Comment by alalazo** [comment] 2019-09-08 06:32
Hi, there's the same issue building PAPI 5.7.0. Note that the issue is present only when using Python 3 due to [some changes in behavior when processing text files](http://python-notes.curiousefficiency.org/en/latest/python3/text_file_processing.html#). Apparently detecting the encoding of a file [is not an easy task](https://stackoverflow.com/a/436299/771663) - so making it such that we open a file with its own encoding before changing it in place is not an option I see feasible.

I'll try to make `filter_file` behave as much as possible like it would in Python 2 also when using Python 3 and submit a PR if successful.

**Closed** 2019-10-15 03:35 UTC
Labels: bug, impact-medium, python3
