### ISSUE TITLE
The papi package installation does not terminate

### ISSUE THREAD

**Issue by zephyr111** [spack/spack#8719] opened 2018-07-16 22:12 UTC
The install phase of the papi package never ends.
The issue appears only when the spack function filter_file is call in papi/package.py:
- when the call is disabled, the installation succeeds (at least with gcc 6.2.0, but not currently with gcc 8.1.0);
- when when the call is enabled, a UnicodeDecodeError exception seems to be silently raised internally without terminating the program nor reporting any visible error (the full error is: 'utf-8' codec can't decode byte 0xae in position 3433: invalid start byte).

**Comment by adamjstewart** [comment] 2018-07-16 22:46
Duplicate of #7358.

**Closed by adamjstewart** 2018-07-16 22:46 UTC
