### ISSUE TITLE
Installation issue: py-torchvision

### ISSUE THREAD

**Issue by iarspider** [spack/spack#13821] opened 2019-11-21 16:42 UTC
### Steps to reproduce the issue

```console
$ spack install py-torchvision
==> Error: Multiple providers found for 'blas': ['intel-mkl', 'openblas@0.3.7%gcc@8.3.0+avx2~avx512 cpu_target=auto ~ilp64+pic+shared threads=none ~virtual_machine arch=linux-centos7-skylake']
$ spack install py-torchvision ^openblas
```

Tried also this:
```console
==> Error: Multiple providers found for 'blas': ['intel-mkl', 'openblas@0.3.7%gcc@8.3.0+avx2~avx512 cpu_target=auto ~ilp64+pic+shared threads=none ~virtual_machine arch=linux-centos7-skylake']
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux 0c9821f2e4c1 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    CentOS Linux release 7.7.1908 (Core)
``` 

- `packages.yaml` and `compilers.yaml` 
https://gist.github.com/iarspider/7a9a7685e9c93fb214b608bb85bf9f19

### Additional information

**Comment by adamjstewart** [comment] 2019-11-21 23:08
Duplicate of #4107, #7339, #7901, #8059, #8133, #9753, #11987

**Comment by adamjstewart** [comment] 2020-08-23 22:54
Closing this as a duplicate

**Closed by adamjstewart** 2020-08-23 22:54 UTC
Labels: concretization, duplicate, virtual-dependencies
