### ISSUE TITLE
Concretization bug when multiple variants and versioning of dependencies

### ISSUE THREAD

**Issue by briedel** [spack/spack#9462] opened 2018-10-08 22:20 UTC
In the [namd package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/namd/package.py) there are  multiple FFTW versions supported, see [here](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/namd/package.py#L40-L51). The default is is to depend on FFTW.

When trying to use to a certain FFTW (no MPI support):

```
[centos@cvmfs-rhel7-build-machine spack]$ ./bin/spack install namd ^fftw~mpi ^charm backend=multicore ~smp
==> Error: namd does not depend on fftw
```

Yet the spec

```
[centos@cvmfs-rhel7-build-machine spack]$ ./bin/spack spec namd ^charm backend=multicore ~smp
Input spec
--------------------------------
namd
    ^charm backend=multicore ~smp

Concretized
--------------------------------
namd@2.12%gcc@6.2.0 fftw=3 interface=none arch=linux-rhel7-x86_64
    ^charm@6.7.1%gcc@6.2.0 backend=multicore ~papi patches=92d507d8b72ac01f114f7772510049cc7656f93daeadef46e1f2b00ad8533d2b,e636c3f88a6944c87d910d4c8fdf25146b60f57e09228497a6cc01c7dbae9569 +shared~smp~tcp arch=linux-rhel7-x86_64
    ^fftw@3.3.7%gcc@6.2.0+double+float~fma+long_double+mpi~openmp~pfft_patches~quad simd=avx,avx2,sse2 arch=linux-rhel7-x86_64
...
```

I do not have to define an explicitly FFTW version. 

I had to define FFTW dependency explicitly:

```
[centos@cvmfs-rhel7-build-machine spack]$ ./bin/spack install namd fftw=3 ^fftw~mpi ^charm backend=multicore ~smp
==> charm is already installed in /cvmfs/connect.opensciencegrid.org/modules/el7/spack/opt/spack/linux-rhel7-x86_64/gcc-6.2.0/charm-6.7.1-thgr7t35uddrcv75zb7fs6hbib62k526
==> Installing fftw
```

even though there is a default value, see [here](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/namd/package.py#L40-L41)

**Comment by alalazo** [comment] 2020-11-02 11:04
Duplicate of #1781

**Comment by alalazo** [comment] 2020-11-02 11:06
This issue is not reproducible with `develop` anymore, I suspect the root cause was the same as #1781 and right now `namd` depends on `fftw` only in a conditional way.

**Closed by alalazo** 2020-11-02 11:06 UTC
Labels: concretization
