### ISSUE TITLE
Installation issue: pflotran

### ISSUE THREAD

**Issue by solalito** [spack/spack#12716] opened 2019-09-05 11:57 UTC
### Steps to reproduce the issue

```console
$ spack install pflotran
==> Error: An unsatisfiable variant constraint has been detected for spec:

    hdf5@1.10.5%gcc@9.2.0~cxx~debug+fortran~hl+mpi+pic+shared~szip~threadsafe arch=linux-centos7-x86_64


while trying to concretize the partial spec:

    petsc@3.11.3%gcc@9.2.0~X clanguage=C ~complex~debug+double~fftw+hdf5+hypre~int64~knl+metis+mpi~mumps+shared~suite-sparse+superlu-dist~trilinos arch=linux-centos7-x86_64
        ^hypre@2.14:~int64~internal-superlu
            ^openblas@0.3.7%gcc@9.2.0+avx2~avx512 cpu_target=auto ~ilp64+pic+shared threads=none ~virtual_machine arch=linux-centos7-x86_64
        ^superlu-dist@6.1:6.1.99~int64
            ^cmake@2.8:
            ^metis@5:
            ^openmpi@3.1.4%gcc@9.2.0~cuda+cxx_exceptions fabrics=none ~java~legacylaunchers~memchecker~pmi schedulers=none ~sqlite3~thread_multiple+vt arch=linux-centos7-x86_64
                ^hwloc@1.11.11%gcc@9.2.0~cairo~cuda~gl+libxml2~nvml+pci+shared arch=linux-centos7-x86_64
                    ^libpciaccess
                        ^libtool@2.4.6%gcc@9.2.0 arch=linux-centos7-x86_64
                            ^m4@1.4.18%gcc@9.2.0+sigsegv arch=linux-centos7-x86_64
                                ^libsigsegv@2.11%gcc@9.2.0 arch=linux-centos7-x86_64
                        ^pkgconf@1.6.1%gcc@9.2.0 arch=linux-centos7-x86_64
                        ^util-macros
                    ^libxml2
                        ^libiconv
                        ^xz
                        ^zlib@1.2.11%gcc@9.2.0+optimize+pic+shared arch=linux-centos7-x86_64
                    ^numactl@2.0.12%gcc@9.2.0 arch=linux-centos7-x86_64
                        ^autoconf@2.69%gcc@9.2.0 arch=linux-centos7-x86_64
                            ^perl@5.26.2%gcc@9.2.0+cpanm+shared+threads arch=linux-centos7-x86_64
                                ^gdbm@1.18.1%gcc@9.2.0 arch=linux-centos7-x86_64
                                    ^readline@7.0%gcc@9.2.0 arch=linux-centos7-x86_64
                                        ^ncurses@6.1%gcc@9.2.0~symlinks~termlib arch=linux-centos7-x86_64
                        ^automake@1.16.1%gcc@9.2.0 arch=linux-centos7-x86_64
            ^parmetis


petsc requires hdf5 variant +hl, but spec asked for ~hl
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux arthemis.localdomain 5.0.10-1.el7.elrepo.x86_64 #1 SMP Sat Apr 27 08:40:16 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
LSB Version:    :core-4.1-amd64:core-4.1-ia32:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core
``` 

### Additional information

Related issues: #7404 and #7145

**Comment by adamjstewart** [comment] 2019-09-09 21:22
This is a bug in the concretizer that should hopefully be fixed in the next release. In the meantime, you can do:
```console
$ spack install pflotran ^hdf5+hl
```

**Comment by alalazo** [comment] 2019-09-10 12:26
@adamjstewart Are we keeping track of all the issues that are different manifestations of this concretizer bug somewhere?

**Comment by adamjstewart** [comment] 2019-09-10 14:04
Nope. There's too many to keep track of...

**Comment by nsccap** [comment] 2020-02-06 17:11
> This is a bug in the concretizer that should hopefully be fixed in the next release.

Has this been fixed in any of the releases since?

**Comment by adamjstewart** [comment] 2020-02-06 17:28
Nope, no changes to the concretizer have been made. @tgamblin is working on a complete rewrite of the concretizer that is expected sometime this spring.

**Comment by alalazo** [comment] 2020-11-02 20:32
Duplicate of #1781

**Closed by alalazo** 2020-11-02 20:33 UTC
Labels: build-error, concretization
