### ISSUE TITLE
lz4 v1.8.1 compilation fails on centos6

### ISSUE THREAD

**Issue by Sinan81** [spack/spack#7552] opened 2018-03-21 23:43 UTC
Summary

installation of lz4 (defaulting to latest version 1.8.1) fails on centos6 although it works on centos7. installation of the previous version 1.7.5 works on centos6.

### Expected Result
spack install -j1 lz4 installs
### Actual Result
install fails on centos6 for version 1.8.1
````console
==> Executing phase: 'install'
==> 'make' '-j128'
make[1]: Entering directory `/var/tmp/sbulut/spack-stage/spack-stage-UTGHYg/lz4-1.8.1.2/lib'
compiling static library
compiling dynamic library 1.8.1
creating versioned links
make[1]: Leaving directory `/var/tmp/sbulut/spack-stage/spack-stage-UTGHYg/lz4-1.8.1.2/lib'
make[1]: Entering directory `/var/tmp/sbulut/spack-stage/spack-stage-UTGHYg/lz4-1.8.1.2/programs'
/gsc/software/spack/lib/spack/env/gcc/gcc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  -c -o bench.o bench.c
/gsc/software/spack/lib/spack/env/gcc/gcc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  -c -o datagen.o datagen.c
/gsc/software/spack/lib/spack/env/gcc/gcc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  -c -o lz4cli.o lz4cli.c
/gsc/software/spack/lib/spack/env/gcc/gcc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  -c -o lz4io.o lz4io.c
/gsc/software/spack/lib/spack/env/gcc/gcc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  ../lib/lz4.o ../lib/lz4frame.o ../lib/lz4hc.o ../lib/xxhash.o bench.o datagen.o lz4cli.o lz4io.o -o lz4
bench.o: In function `BMK_benchMem':
bench.c:(.text+0x317): undefined reference to `clock_gettime'
bench.c:(.text+0x423): undefined reference to `clock_gettime'
bench.c:(.text+0x4d7): undefined reference to `clock_gettime'
bench.c:(.text+0x586): undefined reference to `clock_gettime'
bench.c:(.text+0x5ce): undefined reference to `clock_gettime'
bench.o:bench.c:(.text+0x636): more undefined references to `clock_gettime' follow
collect2: error: ld returned 1 exit status
make[1]: *** [lz4] Error 1
make[1]: Leaving directory `/var/tmp/sbulut/spack-stage/spack-stage-UTGHYg/lz4-1.8.1.2/programs'
make: *** [lz4-release] Error 2
````

### Steps to reproduce the issue

```console
$ spack install lz4
```

### Information on your system

centos6
gcc7.2 (spack)

**Comment by adamjstewart** [comment] 2018-03-22 13:08
I was able to reproduce this on CentOS 6. Based on [StackOverflow](https://stackoverflow.com/questions/2418157/ubuntu-linux-c-error-undefined-reference-to-clock-gettime-and-clock-settim) it looks like we need to add `-lrt` somewhere. We already do this in several other Spack packages:
```
$ grep -- '-lrt' */package.py
git/package.py:            # Don't link with -lrt; the system has no (and needs no) librt
git/package.py:            filter_file(r' -lrt$', '', 'Makefile')
libdrm/package.py:                  'LIBS=-lrt')  # This fixes a bug with `make check`
mesa/package.py:            args.append('LIBS=-lrt')
mfem/package.py:                ss_lib += ' -lrt'
osu-micro-benchmarks/package.py:            config_args.append('LDFLAGS=-lrt')
scotch/package.py:            ldflags.append('-lm -lrt -lpthread')
scotch/package.py:            ldflags.append('-lm -lrt -pthread')
```
We just need to be sure not to add it for darwin as it doesn't have this library. I don't know exactly which Makefile variable to set but if you can figure it out it shouldn't be hard to do.

**Comment by Sinan81** [comment] 2018-03-22 17:34
Yeah, it looks simple. I can work on it.

**Comment by omsai** [comment] 2018-10-10 16:39
I still see this error even with the `make('LIBS=-lrt')` line in lz4's `package.py` using the Intel 2017 compiler.

I have the librt system library installed:
```
$ ldconfig -p | grep librt
        librt.so.1 (libc6,x86-64, OS ABI: Linux 2.6.18) => /lib64/librt.so.1
        librt.so (libc6,x86-64, OS ABI: Linux 2.6.18) => /usr/lib64/librt.so
```

Spack error:
```
$ cat /home/pan14001admin/38262-wrf-hydro/spack/var/spack/stage/lz4-1.8.1.2-c4x5easwrpjnzyb2viqbai2osxsadexz/lz4-1.8.1.2/spack-build.out
==> Executing phase: 'install'
==> 'make' '-j12' 'LIBS=-lrt'
make[1]: Entering directory `/tmp/pan14001admin/spack-stage/spack-stage-stm0Vf/lz4-1.8.1.2/lib'
compiling static library
compiling dynamic library 1.8.1
creating versioned links
make[1]: Leaving directory `/tmp/pan14001admin/spack-stage/spack-stage-stm0Vf/lz4-1.8.1.2/lib'
make[1]: Entering directory `/tmp/pan14001admin/spack-stage/spack-stage-stm0Vf/lz4-1.8.1.2/programs'
/home/pan14001admin/38262-wrf-hydro/spack/lib/spack/env/intel/icc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  -c -o bench.o bench.c
/home/pan14001admin/38262-wrf-hydro/spack/lib/spack/env/intel/icc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  -c -o datagen.o datagen.c
/home/pan14001admin/38262-wrf-hydro/spack/lib/spack/env/intel/icc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  -c -o lz4cli.o lz4cli.c
/home/pan14001admin/38262-wrf-hydro/spack/lib/spack/env/intel/icc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  -c -o lz4io.o lz4io.c
/home/pan14001admin/38262-wrf-hydro/spack/lib/spack/env/intel/icc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  ../lib/lz4.o ../lib/lz4frame.o ../lib/lz4hc.o ../lib/xxhash.o bench.o datagen.o lz4cli.o lz4io.o -o lz4
bench.o: In function `BMK_benchFiles':
bench.c:(.text+0xd22): undefined reference to `clock_gettime'
bench.c:(.text+0xde8): undefined reference to `clock_gettime'
bench.c:(.text+0xe8d): undefined reference to `clock_gettime'
bench.c:(.text+0xf37): undefined reference to `clock_gettime'
bench.c:(.text+0xf6e): undefined reference to `clock_gettime'
bench.o:bench.c:(.text+0xfcb): more undefined references to `clock_gettime' follow
make[1]: *** [lz4] Error 1
make[1]: Leaving directory `/tmp/pan14001admin/spack-stage/spack-stage-stm0Vf/lz4-1.8.1.2/programs'
make: *** [lz4-release] Error 2
```

Compiler info:
```
$ ./spack compiler info intel
intel@17.0.0:
        paths:
                cc = /gpfs/gpfs1/apps2/intelics/2017/compilers_and_libraries_2017.0.098/linux/bin/intel64/icc
                cxx = /gpfs/gpfs1/apps2/intelics/2017/compilers_and_libraries_2017.0.098/linux/bin/intel64/icpc
                f77 = /gpfs/gpfs1/apps2/intelics/2017/compilers_and_libraries_2017.0.098/linux/bin/intel64/ifort
                fc = /gpfs/gpfs1/apps2/intelics/2017/compilers_and_libraries_2017.0.098/linux/bin/intel64/ifort
        Extra rpaths:
                /apps2/intelics/2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64
        modules  = []
        operating system  = rhel6
```

Instances of `-lrt` usage currently in spack:
```
$ grep -F -- '-lrt' */package.py
git/package.py:            # Don't link with -lrt; the system has no (and needs no) librt
git/package.py:            filter_file(r' -lrt$', '', 'Makefile')
libdrm/package.py:                  'LIBS=-lrt')  # This fixes a bug with `make check`
lz4/package.py:            make('LIBS=-lrt')  # fixes make error on CentOS6
mesa/package.py:            args.append('LIBS=-lrt')
osu-micro-benchmarks/package.py:            config_args.append('LDFLAGS=-lrt')
scotch/package.py:            ldflags.append('-lm -lrt -lpthread')
scotch/package.py:            ldflags.append('-lm -lrt -pthread')
```

spack repo info:
```
$ git status
# On branch develop
nothing to commit (working directory clean)
$ GIT_PAGER= git log -n1
commit cf52083b74d5aac369906e6b32776e362d7fe72a
Author: Strahinja Trecakov <trecakov@nmsu.edu>
Date:   Mon Oct 8 01:12:13 2018 -0600

    perl-module-build new version (#9404)
```

**Comment by omsai** [comment] 2018-10-24 18:32
`LIBS` has now been replaced with `MOREFLAGS` as part of d1db12e15347567ad23fc6bd6d27b0a415e08691 for #9510 and I can confirm the change fixes the issue with Intel's `icc`.

I also independently found using `LDFLAGS` instead of `LIBS` works for Intel's `icc` but which is a bit sledge hammer-y.

Anyway, feel free to close this bug.

**Comment by alalazo** [comment] 2019-12-16 18:04
Closing as solve according to comments above

**Closed by alalazo** 2019-12-16 18:04 UTC
Labels: build-error
