### ISSUE TITLE
How do I use this on Windows?

### ISSUE THREAD

**Issue by rcdailey** [spack/spack#1515] opened 2016-08-13 22:57 UTC
Looks like there are shell scripts only. I don't see any instructions for using/running this thing on Windows. Could someone point me in the right direction? Or is Spack for linux only?

**Comment by tgamblin** [comment] 2016-08-13 23:42
Unfortunately it's only for unix (Linux, MacOS, and various HPC systems) at the moment.  Not opposed to Windows, but we use forks and symlinks in a few too many places at the moment.

**Comment by buaaluwentao** [comment] 2017-02-21 08:31
@tgamblin , what is you meaning by saying " but we use forks and symlinks in a few too many places at the moment.", does it mean we are misleaded to thinking the SPACK is just for windows?

**Comment by tgamblin** [comment] 2017-02-21 09:58
@buaaluwentao: Windows doesn't support forking or symlinks.  We actually do not use `os.fork()` in Spack anymore, so there may be a better chance of getting things to work in a windows environment.

We do, however, use symlinks a lot.  That would need to be fixed to make the core of Spack work well on Windows.  We would probably also need to do add a new platform support class and do some significant work on the packages themselves to get them to build.

**Comment by rcdailey** [comment] 2017-02-21 12:06
Actually Windows does support symlinks. Look into junctions. Vista and
onward also have the mklink command. Even on XP there is junction support.

**Comment by ebkalderon** [comment] 2018-09-29 14:34
Junctions are a poor replacement for symbolic links because they can only reference directories, not files. Additionally, they also cannot point at remote resources like network mounts or remote locations. They are much more akin to Unix hard links rather than symbolic links.

`mklink` is a much better solution that behaves identically to a symbolic link and is perfect for Spack's use case, but it requires administrator privileges to create, delete, and modify on Windows versions before Windows 10 Creators Update with Developer Mode enabled ([relevant blog post](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/#oY8xkzvmiRr4M6ue.97)). If native Windows support for Spack does land eventually, I imagine it will only support Windows 10 Creators Update or newer. Otherwise, I assume that Spack could be made to work well on the Windows Subsystem for Linux (WSL) with little change from the native Linux version. Still, I am not really familiar with the inner workings of Spack to say for sure.

**Comment by healther** [comment] 2018-10-01 06:37
If you mean the Ubuntu on Windows thingy, then I've tested it and it let me use my software against spack-build packages without any problems (this information is probably out of date by a year or so)

**Comment by citibeth** [comment] 2019-05-18 14:07
@healther Do you have any further updates on using Spack with WSL?  It's something I'm considering, and I'm looking for others who have blazed the trail before me.  Do you know about WSL-1 vs WSL2?  Thanks!

**Comment by citibeth** [comment] 2019-05-18 14:07
(Reopening because with WSL, the "only works on Linux" answer is no longer the final word.)

**Comment by KineticTheory** [comment] 2019-05-18 15:21
@citibeth FYI - I've been using spack with WSL for about a year and I haven't had any issues with spack in this environment.  I build out a fairly complete Trilinos install and that brings in a big stack of tools provided by spack.  The big downside with current WSL is that the Linux disk subsystem is slow -- [but this is supposed to be fixed by Microsoft later in 2019.](https://devblogs.microsoft.com/commandline/shipping-a-linux-kernel-with-windows/)

**Comment by healther** [comment] 2019-05-22 08:01
@citibeth I haven't used my desktop at home for quite some time now, but what I remember is the same as @KineticTheory there weren't more problems than on a native Linux (that was back in the days where spack had significant holes in its package repository and dependencies where somewhat hit-and-miss). I haven't really had speed problems but then again I compared a high end CPU (from 2018 on WSL) to my old MacBookAir (from 2013).

**Comment by adamjstewart** [comment] 2020-08-13 01:40
Just to update on the WSL debate, I've been using Spack on WSL all summer and have yet to encounter a single issue. To echo what @KineticTheory mentioned, WSL-1 is extremely slow for filesystem access, but WSL-2 has now fixed this. You still need to manually switch from WSL-1 to WSL-2, but it took my environment symlinking times down from 20 minutes to 30 seconds.

**Comment by alalazo** [comment] 2022-05-13 07:39
Possibly closed by #27021

**Closed by alalazo** 2022-05-13 07:39 UTC
Labels: platform-support, windows

**Comment by x2v0** [comment] 2022-06-22 11:53
Hi, seems the problems are still exist and connected with `start_build_process` in `build_enviroment.py`

To reproduce it try: 
```console
$ spack install libx11
[+] /home/xtovo/wrk/fairsoft/linux-centos7-skylake/gcc-11.2.1/pkgconf-1.8.0-e6upgqa4gpcosaauhjqzpuloj5lspifz
[+] /home/xtovo/wrk/fairsoft/linux-centos7-skylake/gcc-11.2.1/util-macros-1.19.3-gnnjvcx656se66x4734qqa2gp24yaunv
[+] /home/xtovo/wrk/fairsoft/linux-centos7-skylake/gcc-11.2.1/libpthread-stubs-0.4-u5fdbpksiif5xtfpszwuqdd7we4s64ri
[+] /home/xtovo/wrk/fairsoft/linux-centos7-skylake/gcc-11.2.1/libmd-1.0.4-azdigqmpxcmntgwynmqxzltfyave4r6v
==> Installing xcb-proto-1.14.1-5yoxwi4ms7duphpfy4q4otelm3zjym63
==> No binary for xcb-proto-1.14.1-5yoxwi4ms7duphpfy4q4otelm3zjym63 found: installing from source
==> Using cached archive: /home/xtovo/spack/var/spack/cache/_source-cache/archive/f0/f04add9a972ac334ea11d9d7eb4fc7f8883835da3e4859c9afa971efdf57fcc3.tar.xz
==> No patches needed for xcb-proto
==> xcb-proto: Executing phase: 'autoreconf'
==> xcb-proto: Executing phase: 'configure'
==> xcb-proto: Executing phase: 'build'
==> xcb-proto: Executing phase: 'install'
==> Warning: Module file /home/xtovo/spack/share/spack/modules/linux-centos7-skylake/xcb-proto-1.14.1-gcc-11.2.1-5yoxwi4 exists and will not be overwritten
==> Error: PermissionError: [Errno 1] Operation not permitted: '/home/xtovo/wrk/fairsoft/linux-centos7-skylake/gcc-11.2.1/xcb-proto-1.14.1-5yoxwi4ms7duphpfy4q4otelm3zjym63/lib/python3.1/site-packages/xcbgen/__pycache__'

/home/xtovo/spack/lib/spack/spack/build_environment.py:1076, in _setup_pkg_and_run:
       1073        tb_string = traceback.format_exc()
       1074
       1075        # build up some context from the offending package so we can
  >>   1076        # show that, too.
       1077        package_context = get_package_context(tb)
       1078
       1079        logfile = None

See build log for details:
  /tmp/xtovo/spack-stage/spack-stage-xcb-proto-1.14.1-5yoxwi4ms7duphpfy4q4otelm3zjym63/spack-build-out.txt

==> Warning: Skipping build of libxcb-1.14-2zj5z2xolzoysm7lwiwvqpv5rgjiwwxi since xcb-proto-1.14.1-5yoxwi4ms7duphpfy4q4otelm3zjym63 failed
==> Warning: Skipping build of libx11-1.7.0-27fjqskjfgghi3xzrhynvfgijybfeook since libxcb-1.14-2zj5z2xolzoysm7lwiwvqpv5rgjiwwxi failed
==> Error: Could not remove prefix /home/xtovo/wrk/fairsoft/linux-centos7-skylake/gcc-11.2.1/xcb-proto-1.14.1-5yoxwi4ms7duphpfy4q4otelm3zjym63 for xcb-proto@1.14.1%gcc@11.2.1 arch=linux-centos7-skylake/5yoxwi4 : [Errno 13] Permission denied: 'align.cpython-310.opt-1.pyc'
```
Mess by mix  **fork/spawn** ?

Regards. Valeriy

**Comment by adamjstewart** [comment] 2022-06-22 15:49
@x2v0 from your output it seems like you're building on CentOS 7, not Windows. Are you using WSL? WSL should behave identically to Linux.

**Comment by x2v0** [comment] 2022-06-23 03:57
yes, WSL2
As far as I understood some packages use Python for building, and it seems that Spack run this  Python build script as subprocess -> that makes a trouble
