### ISSUE TITLE
Failure to apply patch during spack install perl@5.26.2 %gcc@7.3.0 

### ISSUE THREAD

**Issue by llpesce** [spack/spack#8334] opened 2018-05-31 15:39 UTC
System: Theta, Cray XC40 with KNL nodes.
Building with Cray's PrgEnv-gnu. 
> spack find
-- cray-cnl6-mic_knl / gcc@7.3.0 --------------------------------
bzip2@1.0.6   font-util@1.3.1    gdbm@1.14.1       libffi@3.2.1   ncurses@6.1     pkg-config@0.29.2  util-macros@1.19.1
cmake@3.9.4   fontconfig@2.12.3  gettext@0.19.8.1  libpng@1.6.34  openssl@1.0.2n  readline@7.0       xz@5.2.4
cmake@3.11.2  freetype@2.7.1     gperf@3.0.4       libxml2@2.9.8  pcre@8.42       tar@1.30           zlib@1.2.11
 

Build failed with outcome
==> Installing perl
==> Using cached archive: /<path>/perl-5.26.2.tar.gz
==> Using cached archive: /<path>/cpanm-5.26.2.tar.gz
==> Staging archive: /../perl-5.26.2.tar.gz
==> Created stage in /../perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r
==> Staging archive: /.../App-cpanminus-1.7042.tar.gz
==> Created stage in /.../resource-cpanm-v4v4a5ocskntdqjvoi5dfote7agb272r
==> Moving resource stage
        source : /.../App-cpanminus-1.7042/
        destination : /.../perl-5.26.2/cpanm/cpanm
==> Using cached archive: /../perl-5.26.1-guard_old_libcrypt_fix.patch
**File pp.c is read-only; trying to patch anyway**
==> Applied patch https://src.fedoraproject.org/rpms/perl/raw/004cea3a67df42e92ffdf4e9ac36d47a3c6a05a4/f/perl-5.26.1-guard_old_libcrypt_fix.patch
==> Building perl [Package]
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    './Configure' '-des' '-Dprefix=/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r' '-Dlocincpth=/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/include' '-Dloclibpth=/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/lib' '-Accflags=-DAPPLLIB_EXP=\"/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r/lib/perl5\"' '-Duseshrplib' '-Dusethreads'

1 error found in build log:
     71         cc -o try -O2 -D_REENTRANT -D_GNU_SOURCE -DAPPLLIB_EXP="/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r/lib/
           perl5" -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtf
           trvt5yx/include -fstack-protector-strong -L/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/lib try.c -lpthrea
           d -lnsl -lgdbm -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
     72          ./try
     73    
     74    and I got the following output:
     75    
     76    /opt/cray/pe/cce/8.7.0/binutils/x86_64/x86_64-pc-linux-gnu/bin/ld: warning: libgdbm.so.4, needed by /home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1
           .14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/lib/libgdbm.so, may conflict with libgdbm.so.5
  >> 77    ./try: error while loading shared libraries: libgdbm.so.5: cannot open shared object file: No such file or directory
     78    The program compiled OK, but exited with status 127.
     79    You have a problem.  Shall I abort Configure [y]
     80    Ok.  Stopping Configure.

I untarred the perl source tarball and in fact all .c and .h files are read only. Other config files are read write. There is no read write issue on the system, the issue appears to be associated with the perl tarball. 

Thank you

**Comment by llpesce** [comment] 2018-05-31 15:53
I tried to recreate the tar file by 
tar -xvf perl-5.26.2.tar.gz 
chmod -R uga+w perl-5.26.2/
tar -zcvf perl-5.26.2.tar.gz perl-5.26.2
, but what I got was
<...>
==> Fetching from /gpfs/mira-home/lpesce/SPACK/spack/var/spack/cache/perl/perl-5.26.2.tar.gz failed.
<...>

**Comment by scheibelp** [comment] 2018-05-31 17:34
> Fetching from /gpfs/mira-home/lpesce/SPACK/spack/var/spack/cache/perl/perl-5.26.2.tar.gz failed.

To make sure, was `/gpfs/mira-home/lpesce/SPACK/spack/var/spack/cache/perl/perl-5.26.2.tar.gz` the tarball you edited? Are the permissions on the tarball itself OK?

Could you rerun the command with `-sd` like `spack -sd install ...` and include the full stack trace (I assume you truncated the error output for the benefit of readers but I don't see anything in it so at this point the full output would be great).

**Comment by llpesce** [comment] 2018-05-31 18:42
> Fetching from /gpfs/mira-home/lpesce/SPACK/spack/var/spack/cache/perl/perl-5.26.2.tar.gz failed.
> 
> To make sure, was /gpfs/mira-home/lpesce/SPACK/spack/var/spack/cache/perl/perl-5.26.2.tar.gz the tarball you edited? Are the permissions on the tarball itself OK?
> 
> 

They are identical to the original, so I think that they are what it expects. Of course the archives are different (I don’t know if it checks for md5 or related signatures).
The resulting archive is a chunk bigger.
> Could you rerun the command with -sd like spack -sd install ... and include the full stack trace (I assume you truncated the error output for the benefit of readers but I don't see anything in it so at this point the full output would be great).
> 
I can’t find an -sd flag, probably my ignorance. Here is the output with -v

> spack install -v perl@5.26.2 %gcc@7.3.0
==> pkg-config is already installed in /home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/pkg-config-0.29.2-3kbmsvbtih5nfsgoemxm6kamun3v5v63
==> ncurses is already installed in /home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/ncurses-6.1-xv5au6xhsumoz37ushxeermpk52xe7lg
==> readline is already installed in /home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/readline-7.0-2kq6nunmhxsyyflchnazo7zk3i5rjt23
==> gdbm is already installed in /home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx
==> Installing perl
==> Fetching from /gpfs/mira-home/lpesce/SPACK/spack/var/spack/cache/perl/perl-5.26.2.tar.gz failed.
==> Fetching http://www.cpan.org/src/5.0/perl-5.26.2.tar.gz
######################################################################## 100.0%
==> Using cached archive: /gpfs/mira-home/lpesce/SPACK/spack/var/spack/cache/perl/cpanm-5.26.2.tar.gz
==> Staging archive: /gpfs/mira-home/lpesce/SPACK/spack/var/spack/stage/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r/perl-5.26.2.tar.gz
==> Created stage in /gpfs/mira-home/lpesce/SPACK/spack/var/spack/stage/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r
==> Staging archive: /gpfs/mira-home/lpesce/SPACK/spack/var/spack/stage/resource-cpanm-v4v4a5ocskntdqjvoi5dfote7agb272r/App-cpanminus-1.7042.tar.gz
==> Created stage in /gpfs/mira-home/lpesce/SPACK/spack/var/spack/stage/resource-cpanm-v4v4a5ocskntdqjvoi5dfote7agb272r
==> Moving resource stage
        source : /gpfs/mira-home/lpesce/SPACK/spack/var/spack/stage/resource-cpanm-v4v4a5ocskntdqjvoi5dfote7agb272r/App-cpanminus-1.7042/
        destination : /gpfs/mira-home/lpesce/SPACK/spack/var/spack/stage/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r/perl-5.26.2/cpanm/cpanm
==> Using cached archive: /gpfs/mira-home/lpesce/SPACK/spack/var/spack/cache/perl/perl-5.26.1-guard_old_libcrypt_fix.patch
File pp.c is read-only; trying to patch anyway
==> Applied patch https://src.fedoraproject.org/rpms/perl/raw/004cea3a67df42e92ffdf4e9ac36d47a3c6a05a4/f/perl-5.26.1-guard_old_libcrypt_fix.patch
==> Building perl [Package]
==> Executing phase: 'configure'
==> Warning: Quotes in command arguments can confuse scripts like configure.
  The following arguments may cause problems when executed:
      -Accflags=-DAPPLLIB_EXP=\"/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r/lib/perl5\"
  Quotes aren't needed because spack doesn't use a shell.
  Consider removing them
==> './Configure' '-des' '-Dprefix=/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r' '-Dlocincpth=/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/include' '-Dloclibpth=/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/lib' '-Accflags=-DAPPLLIB_EXP=\"/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r/lib/perl5\"' '-Duseshrplib' '-Dusethreads'
First let's make sure your kit is complete.  Checking...
Locating common programs...
Checking compatibility between /usr/bin/echo and builtin echo (if any)...
Symbolic links are supported.
Checking how to test for symbolic links...
You can test for symbolic links with 'test -h'.
Checking for cross-compile
No targethost for running compiler tests against defined, running locally
Good, your tr supports [:lower:] and [:upper:] to convert case.
Using [:upper:] and [:lower:] to convert case.
aix           dragonfly       irix_4            nonstopux     stellar   
aix_3         dynix           irix_5            openbsd       sunos_4_0   
aix_4         dynixptx        irix_6            opus          sunos_4_1   
altos486      epix            irix_6_0          os2           super-ux   
amigaos       esix4           irix_6_1          os390         svr4   
atheos        fps             isc               os400         svr5   
aux_3         freebsd         isc_2             posix-bc      ti1500   
bitrig        freemint        linux-android     powerux       ultrix_4   
bsdos         genix           linux             qnx           umips   
catamount     gnu             lynxos            riscos        unicos   
convexos      gnukfreebsd     midnightbsd       sco           unicosmk   
cxux          gnuknetbsd      mips              sco_2_3_0     unisysdynix   
cygwin        greenhills      mirbsd            sco_2_3_1     utekv   
darwin        haiku           mpc               sco_2_3_2     uwin   
dcosx         hpux            ncr_tower         sco_2_3_3     vos   
dec_osf       i386            netbsd            sco_2_3_4   
dos_djgpp     interix         newsos4           solaris_2   
Which of these apply, if any? [linux]  
Operating system name? [linux]  
Operating system version? [4.4.103-92.56-default]  
Installation prefix to use? (~name ok)
[/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r]  
AFS does not seem to be running...
What installation prefix should I use for installing files? (~name ok)
[/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r]  
Getting the current patchlevel...
Build a threading Perl? [y]  
Use which C compiler? [cc]  
Checking for GNU cc in disguise and/or its version number...
Now, how can we feed standard input to your C preprocessor...
Directories to use for library searches?
[/opt/cray/pe/libsci/18.04.1/GNU/7.1/x86_64/lib /opt/cray/pe/mpt/7.7.0/gni/mpich-gnu/5.1/lib /opt/cray-hss-devel/8.0.0/lib /usr/local/lib /opt/gcc/7.3.0/snos/lib /opt/gcc/7.3.0/snos/lib/gcc/x86_64-suse-linux/7.3.0/include-fixed /usr/lib /home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/lib /lib/../lib64 /usr/lib/../lib64 /lib /lib64 /usr/lib64 /usr/local/lib64]  
What is the file extension used for shared libraries? [so]  
Make shared library basenames unique? [n]  
Build Perl for SOCKS? [n]  
Try to use long doubles if available? [n]  
Checking for optional libraries...
What libraries to use?
[-lpthread -lnsl -lgdbm -ldl -lm -lcrypt -lutil -lc -lgdbm_compat]  
What optimizer/debugger flag should be used? [-O2]  
Any additional cc flags?
[-D_REENTRANT -D_GNU_SOURCE -DAPPLLIB_EXP="/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r/lib/perl5" -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/include]  
Let me guess what the preprocessor flags are...
Any additional ld flags (NOT including libraries)?
[ -fstack-protector-strong -L/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/lib]  
Checking your choice of C compiler and flags for coherency...
I've tried to compile and run the following simple program:

#include <stdio.h>
int main() { printf("Ok\n"); return(0); }

I used the command:

        cc -o try -O2 -D_REENTRANT -D_GNU_SOURCE -DAPPLLIB_EXP="/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r/lib/perl5" -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/include -fstack-protector-strong -L/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/lib try.c -lpthread -lnsl -lgdbm -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
         ./try

and I got the following output:

/opt/cray/pe/cce/8.7.0/binutils/x86_64/x86_64-pc-linux-gnu/bin/ld: warning: libgdbm.so.4, needed by /home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/lib/libgdbm.so, may conflict with libgdbm.so.5
./try: error while loading shared libraries: libgdbm.so.5: cannot open shared object file: No such file or directory
The program compiled OK, but exited with status 127.
You have a problem.  Shall I abort Configure [y]  
Ok.  Stopping Configure.
==> Error: ProcessError: Command exited with status 1:
    './Configure' '-des' '-Dprefix=/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r' '-Dlocincpth=/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/include' '-Dloclibpth=/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/lib' '-Accflags=-DAPPLLIB_EXP=\"/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r/lib/perl5\"' '-Duseshrplib' '-Dusethreads'

1 error found in build log:
     71         cc -o try -O2 -D_REENTRANT -D_GNU_SOURCE -DAPPLLIB_EXP="/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r/lib/
           perl5" -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtf
           trvt5yx/include -fstack-protector-strong -L/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/lib try.c -lpthrea
           d -lnsl -lgdbm -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
     72          ./try
     73    
     74    and I got the following output:
     75    
     76    /opt/cray/pe/cce/8.7.0/binutils/x86_64/x86_64-pc-linux-gnu/bin/ld: warning: libgdbm.so.4, needed by /home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1
           .14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/lib/libgdbm.so, may conflict with libgdbm.so.5
  >> 77    ./try: error while loading shared libraries: libgdbm.so.5: cannot open shared object file: No such file or directory
     78    The program compiled OK, but exited with status 127.
     79    You have a problem.  Shall I abort Configure [y]
     80    Ok.  Stopping Configure.

See build log for details:
  /gpfs/mira-home/lpesce/SPACK/spack/var/spack/stage/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r/perl-5.26.2/spack-build.out

**Comment by llpesce** [comment] 2018-05-31 18:43
Let me know what you think @tgamblin @scheibelp

**Comment by scheibelp** [comment] 2018-05-31 22:05
I forgot that changing the timestamp on the file changes the md5 sum, so it will be difficult to edit it without updating the checksum in the package.py definition for `perl`. That being said, when examining this closer the permissions don't appear to actually stop the patch:

> ==> Applied patch https://src.fedoraproject.org/rpms/perl/raw/004cea3a67df42e92ffdf4e9ac36d47a3c6a05a4/f/perl-5.26.1-guard_old_libcrypt_fix.patch

The error later on is:

> ./try: error while loading shared libraries: libgdbm.so.5: cannot open shared object file: No such file or directory

If you do `spack find -p gdbm` it will give the install prefix of `gdbm`, is `libgdbm.so.5` there? If so, could you mention its full path and permissions? Also, can you locate the `try` binary in the `perl` staging directory (`spack cd perl` will take you there) and check if the RPATHs for the binary include the `lib/` directory of the Spack `gdbm` install?

> I can’t find an -sd flag

note that the `-sd` flag goes after "spack" but *before* the subcommand (e.g. before "install" in `spack install`). The following should work:

` spack -sd install -v ***@***.*** ***@***.***`

**Comment by llpesce** [comment] 2018-06-01 18:48
> If you do spack find -p gdbm it will give the install prefix of gdbm, is libgdbm.so.5 there?
> 

> spack find -p gdbm
==> 1 installed packages.
-- cray-cnl6-mic_knl / gcc@7.3.0 --------------------------------
    gdbm@1.14.1  /home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx


> If so, could you mention its full path and permissions?
> 

lrwxrwxrwx ... /home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/lib/libgdbm.so -> libgdbm.so.5.0.0

> Also, can you locate the try binary in the perl staging directory (spack cd perl will take you there)
> 
Interesting:
> spack cd perl
==> Error: [Errno 2] No such file or directory: '/gpfs/mira-home/lpesce/SPACK/spack/var/spack/stage/perl-5.26.2-nshb56kztqm7d6jzkqaaxrgbgugt3j3f’
However, there is
/gpfs/mira-home/lpesce/SPACK/spack/var/spack/stage/perl-5.26.2-v4v4a5ocskntdqjvoi5dfote7agb272r/
 and indeed for gdbm doesn’t have a path.
> ldd ./perl-5.26.2/UU/try
        linux-vdso.so.1 (0x00007ffcd05c1000)
        /soft/buildtools/trackdeps/$LIB/trackdeps.so => /soft/buildtools/trackdeps/lib64/trackdeps.so (0x00007fd0414c7000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd0412aa000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007fd041092000)
        libgdbm.so.5 => not found
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fd040e8e000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fd040b91000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fd040956000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007fd040753000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fd0403b0000)
        libgdbm_compat.so.4 => /usr/lib64/libgdbm_compat.so.4 (0x00007fd0401ac000)
        libAtpSigHandler.so.0 => /opt/cray/pe/lib64/libAtpSigHandler.so.0 (0x00007fd03ffa2000)
        librca.so.0 => /opt/cray/rca/default/lib64/librca.so.0 (0x00007fd03fd9e000)
        libstdc++.so.6 => /opt/cray/pe/gcc-libs/libstdc++.so.6 (0x00007fd03fa14000)
        libgcc_s.so.1 => /opt/cray/pe/gcc-libs/libgcc_s.so.1 (0x00007fd03f7fd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd0416d7000)
        libgdbm.so.4 => /usr/lib64/libgdbm.so.4 (0x00007fd03f5f4000)


If I type
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/gdbm-1.14.1-e2hcx6crv6eplf5dkz4e76qtftrvt5yx/lib/

> ./perl-5.26.2/UU/try
Ok

Which actually surprises me because I am installing for the knl and this should not work (but sometimes they do). So I proceeded to a
Spack install —dirty… 

That one failed to bootstrap perl because the logins are haswell and the build is for the KNL. 

So. 

OK--: We could fix the gdbm by making a dirty build. I guess that I can live with that.
FAIL: However, the problem of dealing with the heterogenous cluster isn’t resolved. The Cray doesn’t let my compute nodes access the online repo and the login nodes can’t run the programs built for the login node. Any ideas about how can I work around that?

**Comment by llpesce** [comment] 2018-06-01 19:32
Adding the path to gdbm and building dirty from the compute nodes produced a perl installation.
> spack find
==> 27 installed packages.
-- cray-CNL-mic_knl / gcc@7.3.0 ---------------------------------
cmake@3.9.4  ncurses@6.0  openssl@1.0.2k  pkg-config@0.29.2  zlib@1.2.11

-- cray-cnl6-mic_knl / gcc@7.3.0 --------------------------------
bzip2@1.0.6   font-util@1.3.1    gdbm@1.14.1       libffi@3.2.1   ncurses@6.1     perl@5.26.2        tar@1.30            zlib@1.2.11
cmake@3.9.4   fontconfig@2.12.3  gettext@0.19.8.1  libpng@1.6.34  openssl@1.0.2n  pkg-config@0.29.2  util-macros@1.19.1
cmake@3.11.2  freetype@2.7.1     gperf@3.0.4       libxml2@2.9.8  pcre@8.42       readline@7.0       xz@5.2.4

**Comment by scheibelp** [comment] 2018-06-01 23:35
I think there are a couple issues here:

Part of the problem is that the configure script is running using the compiler which targets the backend, so the executables generated during the configure step fail.

@mamelara was working on a context manager to perform the configure step with the frontend compiler - could you (mamelara) point me to that PR?

> Adding the path to gdbm and building dirty from the compute nodes produced a perl installation.

> indeed for gdbm doesn’t have a path.

I'm thinking the other problem here is that the loaded modules are overriding the compiler wrapper settings established by Spack (in part because there aren't *any* spack prefixes showing up in the RPATH's reported by readelf) - see https://github.com/spack/spack/issues/8345; there is work to fix that which should get merged early next week.

**Comment by mamelara** [comment] 2018-06-02 03:43
#7345 is the PR. I'm lacking tests since I need to figure out a good way to test a mock modules system.

**Comment by llpesce** [comment] 2018-06-02 21:34
As I move down the build chain, I have found a new problem, that might be related. I am not sure why the r config is trying to use gcc and fortran as opposed to the wrappers.
When I would usually build R from outside spack, I would specify CC, CXX and FC. Just for the amusement value, I defined them, exported them, and built dirty, it produced the same exact error.

> spack compiler info gcc@7.3.0
gcc@7.3.0:
        paths:
                cc = cc
                cxx = CC
                f77 = ftn
                fc = ftn
        modules  = ['PrgEnv-gnu', 'gcc/7.3.0']
        operating system  = cnl6
gcc@7.3.0:
        paths:
                cc = cc
                cxx = CC
                f77 = ftn
                fc = ftn
        modules  = ['PrgEnv-gnu', 'gcc/7.3.0']
        operating system  = CNL


>spack install  --dirty r %gcc@7.3.0


==> Error: ProcessError: Command exited with status 1:
    '/gpfs/mira-home/lpesce/SPACK/spack/var/spack/stage/r-3.5.0-epygoabxmv2thnc57pkt6bkxnlln433y/R-3.5.0/configure' '--prefix=/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/r-3.5.0-epygoabxmv2thnc57pkt6bkxnlln433y' '--libdir=/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/r-3.5.0-epygoabxmv2thnc57pkt6bkxnlln433y/rlib' '--enable-R-shlib' '--enable-BLAS-shlib' '--enable-R-framework=no' '--with-tcl-config=/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/tcl-8.6.8-ilolq2lm43bmsda3oaecih3cgdvbv4t4/lib/tclConfig.sh' '--with-tk-config=/home/lpesce/SPACK/spack/cray-cnl6-mic_knl/gcc-7.3.0/tk-8.6.8-anwztuq2v6ytzkuxcwaphzybkiepba34/lib/tkConfig.sh' '--without-x'

1 error found in build log:
     315    checking for dummy main to link with Fortran 77 libraries... none
     316    checking for Fortran 77 name-mangling scheme... lower case, underscore, no extra underscore
     317    checking whether /gpfs/mira-home/lpesce/SPACK/spack/lib/spack/env/gcc/gfortran appends underscores to external names... yes
     318    checking whether /gpfs/mira-home/lpesce/SPACK/spack/lib/spack/env/gcc/gfortran appends extra underscores to external names... no
     319    checking whether mixed C/Fortran code can be run... yes
     320    checking whether /gpfs/mira-home/lpesce/SPACK/spack/lib/spack/env/gcc/gfortran and /gpfs/mira-home/lpesce/SPACK/spack/lib/spack/env/gcc/gcc agree on int and double... configure: WARNING: /gpfs/mira-home/lpesce/SPACK/spack/lib/spack/env/gcc/gfortran and /gpfs/mira-home/lpesce/SPACK/spack/lib/spack/env/gcc/gcc disagree on int and double
  >> 321    configure: error: Maybe change CFLAGS or FFLAGS?

**Comment by weijianwen** [comment] 2018-06-05 03:12
I can reproduce this issue when building Perl 5.26.2 against GCC 5.4.0 on CentOS 7.4.

```
$ spack clean; spack install perl@5.26.2 %gcc@5.4.0
...
File pp.c is read-only; trying to patch anyway
/usr/bin/patch: setting attribute lustre.lov for lustre.lov: Permission denied
==> Patch https://src.fedoraproject.org/rpms/perl/raw/004cea3a67df42e92ffdf4e9ac36d47a3c6a05a4/f/perl-5.26.1-guard_old_libcrypt_fix.patch failed.
==> Error: ProcessError: Command exited with status 2:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/lustre/home/rpm/spack/var/spack/stage/spack-stage-U0r0IJ/perl-5.26.1-guard_old_libcrypt_fix.patch' '-d' '.'
==> Error: [Errno 2] No such file or directory: '/lustre/home/rpm/spack/var/spack/stage/perl-5.26.2-3hb3ckyx55br4huklbm7tv5vt3r6m6me/perl-5.26.2/spack-build.out'
```

This issue also affects Perl 5.24.1 which should **NOT** be patched.

```
$ spack clean; spack install perl@5.24.1 %gcc@5.4.0
...
File pp.c is read-only; trying to patch anyway
/usr/bin/patch: setting attribute lustre.lov for lustre.lov: Permission denied
==> Patch https://src.fedoraproject.org/rpms/perl/raw/004cea3a67df42e92ffdf4e9ac36d47a3c6a05a4/f/perl-5.26.1-guard_old_libcrypt_fix.patch failed.
==> Error: ProcessError: Command exited with status 2:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/lustre/home/rpm/spack/var/spack/stage/spack-stage-FoCVpk/perl-5.26.1-guard_old_libcrypt_fix.patch' '-d' '.'
==> Error: [Errno 2] No such file or directory: '/lustre/home/rpm/spack/var/spack/stage/perl-5.24.1-grrfeppk37gmstefrigzjydjlxg7pndr/perl-5.24.1/spack-build.out'
```

**Comment by scheibelp** [comment] 2018-06-05 18:31
@llpesce https://github.com/spack/spack/pull/8346 was just merged so the latest develop should resolve the issue

@weijianwen I think you are getting a different error: it's true that the same package isn't installing, but the error messages look different

```
==> Error: [Errno 2] No such file or directory: '/lustre/home/rpm/spack/var/spack/stage/perl-5.24.1-grrfeppk37gmstefrigzjydjlxg7pndr/perl-5.24.1/spack-build.out'
```

This is quite strange and different from any of the other error messages reported in this thread. I'm inclined to pursue this in another issue.

> This issue also affects Perl 5.24.1 which should NOT be patched.

Note that the Spack perl package now has two patches and one of them applies universally - are you saying it shouldn't?

**Comment by scheibelp** [comment] 2018-06-06 00:39
Regarding https://github.com/spack/spack/issues/8334#issuecomment-394118791: 

I think the problem is not the same based on:

> WARNING: /gpfs/mira-home/lpesce/SPACK/spack/lib/spack/env/gcc/gfortran and /gpfs/mira-home/lpesce/SPACK/spack/lib/spack/env/gcc/gcc disagree on int and double

This would probably benefit from a separate issue.

**Comment by michaelkuhn** [comment] 2018-06-06 13:02
> This issue also affects Perl 5.24.1 which should NOT be patched.

The perl patch you are referring to applies to all versions. This actually looks like a Lustre problem: https://jira.hpdd.intel.com/browse/LU-692
We could probably work around this by first making `pp.c` read-write.

**Comment by llpesce** [comment] 2018-06-06 14:03
I agree. I put it there because it was the next serious issue I had found while trying to build R on the cray XC40. I just have no clear idea whether it is related in some way to how I worked around the previous issues.

I am going to create a new issue. Starting from those lines. I am going to try and build R outside of spack to see if I can figure out why is the configuration steps concluding that gcc and gfortran produce different numbers (my uneducated guess is that there is a cross wired cross compilation call to different archs) 





Lorenzo Pesce, Ph.D.
The Computation Institute
The University of Chicago, Northwestern University and  Argonne National laboratories
lpesce@uchicago.edu

**Comment by scheibelp** [comment] 2018-06-06 17:39
I forgot to mention: for https://github.com/spack/spack/pull/8346 to work you will need to rebuild all libraries. If this was the problem then it means that the compiler wrappers were not used so none of the Spack-built packages contain the necessary RPATHs

**Comment by scheibelp** [comment] 2018-06-07 17:52
Based on https://github.com/spack/spack/issues/8402#issuecomment-395189023 it looks like this particular issue is resolved, so I'm going to close it. Feel free to reopen if I am mistaken.

**Closed** 2018-06-07 17:52 UTC
Labels: patch, perl

**Comment by jrood-nrel** [comment] 2018-07-19 19:13
I see the `perl-5.26.1-guard_old_libcrypt_fix.patch failed` problem on a lustre machine on the latest spack `develop`. I'm hoping to solve it externally with something like `umask`, but I may just need to recreate the cached perl download with different permissions.
