### ISSUE TITLE
Error message : "Error: YAML ProviderIndex was not a dict"

### ISSUE THREAD

**Issue by pramodk** [spack/spack#2891] opened 2017-01-20 13:30 UTC
I was using older version of `spack`. For some testing switched to `v0.10.0` and got :

```
$ spack install -j1 --keep-stage -v tau
==> Error: YAML ProviderIndex was not a dict.

$ spack spec tau
Input spec
--------------------------------
tau

Normalized
--------------------------------
tau
    ^pdt

Concretized
--------------------------------
==> Error: YAML ProviderIndex was not a dict.
```

Doing `rm -rf ~/.spack/cache` solved the problem.

Would it be possible to improve the error message (to get some hint) ?

**Comment by alalazo** [comment] 2019-12-09 13:06
Closing as I couldn't reproduce this. Feel free to reopen if you have a reproducer.

**Closed by alalazo** 2019-12-09 13:06 UTC
Labels: documentation, error-messages, unreproducible
