### ISSUE TITLE
Move ~/.spack

### ISSUE THREAD

**Issue by mathstuf** [spack/spack#506] opened 2016-03-08 18:02 UTC
Dropping files directly into `$HOME` is annoying. It would be better to use `$HOME/.config/spack/` and `$HOME/.local/share/spack/` to store files for spack. See the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for more. Of course, OS X and Windows will probably want something different anyways.

**Comment by citibeth** [comment] 2016-03-08 18:07
Actually... I doubt that $HOME/.spack will be useful for me at all.  I'll want to build different software with different default configs.

**Comment by tgamblin** [comment] 2016-03-08 18:38
OS X seems happy enough with `~/.spack` (and `~/.emacs`, and `~/.bashrc`, and `~/.tcshrc`, and etc.
etc.).

I don't see this particular change adding a lot of value other than compliance with the XDG spec and "less clutter", and users are already used to `~/.spack` and dot files are hidden...

Also, XDG doesn't seem to be catching on:

On my mac:
```
$ ls -d ~/.config/* | wc -l
3
$ ls -d ~/.* | wc -l
123
```

On a Linux machine at LLNL:
```
$ ls -d ~/.config/* | wc -l
5
$ ls -d ~/.* | wc -l
91
```

**Comment by mathstuf** [comment] 2016-03-08 18:58
I'm not surprised OS X isn't using it. As for Linux, lots of apps support XDG preferably if it exists, but fall back to their old paths if the XDG one doesn't exist. As for it not catching on, I have 60+ directories in `~/.config`, [Qt supports it](https://doc.qt.io/qt-5/qsettings.html#platform-specific-notes) too. Plus, it doesn't mean that spack should continue piling onto the heap of cruft that accumulates in `$HOME`. In any case, backwards compatible support is something to keep.

**Comment by mpbelhorn** [comment] 2016-08-10 18:04
I don't mind `~/.spack` (I also don't mind the XDG standard - I use it on my personal machines). However, I do have a similar/related issue. Our resources share a common home filesystem but need custom `compilers.yaml`, `packages.yaml`, etc.

In production, these system-specific settings will go in `${spack}/etc/spack` but for development and testing it would be nice if spack running on each resource could write updated user-config files as needed without clobbering the same file names. I have the following change to allow me to run spack on several resources at the same time, each with their own user configs under `~/.spack/$HOSTNAME`:

```
diff --git a/lib/spack/spack/__init__.py b/lib/spack/spack/__init__.py
index 3d508d0..585b89c 100644
--- a/lib/spack/spack/__init__.py
+++ b/lib/spack/spack/__init__.py
@@ -52,7 +52,8 @@ share_path     = join_path(spack_root, "share", "spack")
 cache_path     = join_path(var_path, "cache")
 
 # User configuration location
-user_config_path = os.path.expanduser('~/.spack')
+user_config_path = os.path.expanduser(os.environ.get('SPACK_USER_CONFIG',
+                                                     '~/.spack'))
 
 import spack.fetch_strategy
 fetch_cache = spack.fetch_strategy.FsCache(cache_path)
```
however, the same could be accomplished with host-specifc `$XDG_CONFIG_HOME`s for each resource. I'm not sure which I prefer - most other applications tolerate a common XDG_CONFIG_HOME to the point that I think I'd rather have just and separate dirs just for spack.

**Comment by tgamblin** [comment] 2016-08-10 18:11
Ok two questions:

1. Does this make more sense as a default user config, or is there a need for some site configuration?  e.g., could there be an `/etc/spack/` directory on the system where these settings come from?  Users could override that in `~/.spack/config.py`

2. If not, would it make more sense to allow a `~/.spack/defaults` scope, similar to how we have `$spack/etc/spack/defaults`?

Both of these seem less complicated than an environment variable, at least to me.

For the XDG stuff, would people like it better if Spack used ~/.config/spack when `~/.local` exists?  I just think it's going to be confusing to tell users where to look.  A larger conversation would be whether `.local/spack/opt` would be a good default install location, so users could share a common spack instance.

**Comment by adamjstewart** [comment] 2016-08-11 18:00
@mpbelhorn I would love a feature like that! We have two clusters which will both be running CentOS 7 but with different MPI network types. They share a single GPFS software and home filesystem, so we currently can't use separate Spack configurations without installing Spack twice. I would love to set MPI to build with psm on one cluster and verbs/mrail on the other.

**Comment by tgamblin** [comment] 2016-08-11 18:15
@adamjstewart: do you prefer a system-level config scope (`/etc` or similar) or an additional user-home-directory scope?

**Comment by adamjstewart** [comment] 2016-08-11 18:25
@tgamblin I haven't been using the system level scope (`$SPACK_ROOT/etc`) because I have so many different Spack installations at this point.

**Comment by tgamblin** [comment] 2016-08-11 18:40
@adamjstewart: maybe I should be more clear.  I'm actually suggesting a _new_ scope at the OS level.  Not `$SPACK_ROOT/etc/spack`, but `/etc/spack` or some other location.  That would probably take precedence over `$SPACK_ROOT/etc/defaults` but not over `$SPACK_ROOT/etc`.

So the order of precedence would be:

1. user config: `~/.spack`
1. NEW: user defaults from your HPC center: `~/.spack/defaults`
1. spack repo config: `$SPACK_ROOT/etc/spack`
1. NEW: system defaults: `/etc/spack` (or maybe something from an env var?)
1. spack defaults: `$SPACK_ROOT/etc/spack/defaults`

(2) above is what Matt is suggesting (I believe) and I'm suggesting (4).  Having both could also make sense.

**Comment by adamjstewart** [comment] 2016-08-11 18:48
I believe Matt is suggesting `~/.spack/$HOSTNAME`. Or an env var that lets him use that directory. But I think this use case isn't all that uncommon, so it might be good to support config files per hostname, or specify hostnames in the config files.

`/etc/spack/` could work, but we use diskless login nodes that are NFS mounted, so editing `/etc/spack/` is slightly more work. Of course, I probably wouldn't be doing it that often.

**Comment by tgamblin** [comment] 2016-08-11 18:55
We've talked about having architecture-dependent subdirectories of each config scope root.  Sounds like people want several different criteria... How about allowing `by-hostname` and `by-arch` subdirectories?  Seems like this could get out of hand though.

**Comment by adamjstewart** [comment] 2016-08-11 19:06
Yeah, I prefer to keep it simple too... But I think both of those would be useful. Our clusters will have identical arch, just different MPI network types. Unless you want to add network type to the arch tuple haha. It might be better to support hostname and arch in the config files instead of having dozens of config files. Imagine trying to debug someone's build and asking them for **all** of their config files.

**Comment by mathstuf** [comment] 2016-08-11 19:30
> Imagine trying to debug someone's build and asking them for all of their config files.

Spack could have a way to dump a config file which is the result of all config files.

**Comment by tgamblin** [comment] 2016-08-11 19:31
The `spec.yaml` is the result of all the config files getting considered.  It's the output of concretization.  So you can send that along.  Spack currently doesn't have a good way to input one to `install` from the command line but it would be really easy.

**Comment by tgamblin** [comment] 2016-08-11 19:33
Note that technically the environment, the `package.py` files, and the particular version of spack are also required for fully reproducing a build, so you really want to tar up `$prefix/.spack`, but `spec.yaml` covers at least what is in the config files.  We try to mitigate environment effects, and `package.py` files will one day be included in hashes, _after_ we can concretize based on what is installed.

**Comment by mpbelhorn** [comment] 2016-08-11 20:44
To clarify, @adamjstewart's interpretation of my use case is correct: I said hostname, but really I use a human-friendly system name that is not the spack-determined `arch` nor the actual hostname.

The actual hostnames for our XK7's login nodes are `titan-ext[0-8]` but I keep my Titan-specific configs under `~/.spack/titan`. This same file system is mounted on our XC30 and I keep the configs for that under `~/.spack/eos`.

And even though we maintain user software on these systems, @robertdfrench and I don't typically have write access to `/etc`. Additionally, I like that spack generates missing configs in my home directory: it's just that my home dir is the same mounted filesystem on several wildly different machines.

**Comment by adamjstewart** [comment] 2016-08-11 20:47
Yeah, our hostnames depend on the login node I'm on, so `flogin[1-4]` or `blogin[1-4]`. I think for our cases it would be easier to just allow config files to be specified by env vars. We can handle the details ourselves.

**Comment by adamjstewart** [comment] 2018-12-17 18:03
Closing this as I think the discussion is mostly dead. We have a [ton of new configuration scopes](https://spack.readthedocs.io/en/latest/configuration.html#configuration-scopes) now.

**Closed by adamjstewart** 2018-12-17 18:03 UTC
Labels: proposal
