### ISSUE TITLE
Installation issue: quantum-espresso not building with hdf5=serial variant 

### ISSUE THREAD

**Issue by glennpj** [spack/spack#13267] opened 2019-10-19 21:42 UTC
The quantum-espresso package can not be built with hdf5=serial support since #12765 was merged. 
---

### Steps to reproduce the issue

```console
$ spack install quantum-espresso%intel hdf5=serial # or hdf5=parallel
... 
  >> 460    ifort: error #10236: File not found:  '='
  >> 461    make[2]: *** [iotk_base.o] Error 1
     462    make[2]: Leaving directory `/dev/shm/gpjohnsn/spack-stage-quantum-espresso-6.4.1-kvtuqt4gelumn6f6gyslwve76y4ahip4/spack-src/S3D
            E/iotk/src'
  >> 463    make[1]: *** [libiotk] Error 2
     464    make[1]: Leaving directory `/dev/shm/gpjohnsn/spack-stage-quantum-espresso-6.4.1-kvtuqt4gelumn6f6gyslwve76y4ahip4/spack-src/ins
            tall'
  >> 465    make: *** [libiotk] Error 2
```
Using `git bisect` shows this started failing with commit 5cd28847e81b3a1bf659d184c990ba9144974624, when #12765 was merged. The relevant code in the quantum-espresso package.py is:
```
        if spec.variants['hdf5'].value != 'none':
            make_inc = join_path(self.stage.source_path, 'make.inc')
            hdf5_libs = ' '.join(spec['hdf5:hl,fortran'].libs)
            filter_file(r'HDF5_LIB([\s]*)=([\s\w\-\/.,]*)',
                        'HDF5_LIB = {0}'.format(hdf5_libs),
                        make_inc)
```
@alalazo I am not sure if this should be fixed in the package or in core. The failure for hdf5=serial and hdf5=parallel cases fail at different points but with similar errors. For the hdf5=parallel case:
```
  >> 4033    ifort: error #10236: File not found:  '/opt/packages/gpjohnsn/opt/ssoft/apps/linux-centos7-sandybridge/intel-19.0.4/hdf5-1.10.
             5-25uu6hf3mdit6daagrurrxmwso3uzxn6/lib/libhdf5.soFOX_LIB'
  >> 4034    ifort: error #10236: File not found:  '='
  >> 4035    make[2]: *** [pw.x] Error 1
     4036    make[2]: Leaving directory `/dev/shm/gpjohnsn/spack-stage-quantum-espresso-6.4.1-tza2u5govp32lyk47qmqci6ffdkv6tgb/spack-src/PW
             /src'
  >> 4037    make[1]: *** [pw] Error 1
     4038    make[1]: Leaving directory `/dev/shm/gpjohnsn/spack-stage-quantum-espresso-6.4.1-tza2u5govp32lyk47qmqci6ffdkv6tgb/spack-src/PW
             '
  >> 4039    make: *** [pw] Error 1
```

**Comment by alalazo** [comment] 2019-10-26 10:25
@glennpj @naromero77 I had a brief look at this and it seems that after the change in #12765 made `\s` in a regex also match the newline char (I guess that's a feature?). Anyhow, the following diff seems to fix the build for me:
```console
$ git diff
diff --git a/var/spack/repos/builtin/packages/quantum-espresso/package.py b/var/spack/repos/builtin/packages/quantum-espresso/package.py
index 2c68a6fbf..c0c88d1ad 100644
--- a/var/spack/repos/builtin/packages/quantum-espresso/package.py
+++ b/var/spack/repos/builtin/packages/quantum-espresso/package.py
@@ -251,14 +251,11 @@ class QuantumEspresso(Package):
             make_inc = join_path(self.stage.source_path, 'make.inc')
             hdf5_libs = ' '.join(spec['hdf5:hl,fortran'].libs)
             filter_file(r'HDF5_LIB([\s]*)=([\s\w\-\/.,]*)',
-                        'HDF5_LIB = {0}'.format(hdf5_libs),
+                        'HDF5_LIB = {0}\n'.format(hdf5_libs),
                         make_inc)
             if spec.variants['hdf5'].value == 'serial':
-                # Note that there is a benign side effect with this filter
-                # file statement. It replaces an instance of MANUAL_DFLAGS
-                # that is a comment in make.inc.
-                filter_file(r'MANUAL_DFLAGS([\s]*)=([\s]*)',
-                            'MANUAL_DFLAGS = -D__HDF5_SERIAL',
+                filter_file(r'^MANUAL_DFLAGS([\s]*)=([\s]*)',
+                            'MANUAL_DFLAGS = -D__HDF5_SERIAL\n',
                             make_inc)
 
         if '+epw' in spec:
```
Let me know if I should submit a PR or if we want to close this issue with #13406

**Comment by naromero77** [comment] 2019-10-26 18:40
@alalazo I am glad that multiple people are able to reproduced this issue -- I was afraid that I was getting sloppy at testing these Spack packages.

I would vote for closing this issue with #13406 

To me `filter_file` are not good long-term solutions. Its always desirable to contact the developers and fix in the upstream source.

Putting my "captain obvious" hat on, the fact that #12765 broken this package shows that there is a coverage gap in the test suite. The fact that `\s` matches the newline character looks like a bug to me, not a feature. It violates the principle of least surprises :)

**Comment by alalazo** [comment] 2019-10-28 07:18
> I would vote for closing this issue with #13406

:+1: 

> Putting my "captain obvious" hat on, the fact that #12765 broken this package shows that there is a coverage gap in the test suite. 

Before #12765 there were no tests for `filter_file`. I am sure we still miss some cases but at least the issues reported in that PR now are tested for regressions :slightly_smiling_face: 

> The fact that \s matches the newline character looks like a bug to me, not a feature. It violates the principle of least surprises :)

Surprise, as beauty, might be in the eye of the beholder. To me the facts that:
1. The docstring says *"Filters every line of each file through regex and replaces the file with a filtered version."*
2. [re docs](https://docs.python.org/3/library/re.html) says that `\s` matches `[ \t\n\r\f\v]`

makes this behavior more expected than the previous one.

Anyhow, let me know if this issue can be closed or if you feel like there's something more to be addressed.

**Comment by naromero77** [comment] 2019-10-28 16:26
@alalazo 

Sorry, I am not very familiar with regular expression in Python.

Thanks for your link. I do believe Spack is now more compliant.

I would vote to close this issue.

**Comment by alalazo** [comment] 2019-10-28 16:31
@glennpj Feel free to reopen if you feel like this is not resolved.

**Closed by alalazo** 2019-10-28 16:31 UTC
Labels: build-error
