### ISSUE TITLE
NetCDF-cxx4 checksum mismatch

### ISSUE THREAD

**Issue by citibeth** [spack/spack#15774] opened 2020-03-31 02:02 UTC
@adamjstewart The package `netcdf-cxx4@4.3.1` has a checksum error.  Any idea why?  `netcdf-cxx4@4.3.0` is fine.

```
Error: ChecksumError: sha256 checksum failed for /import/unsupported/TWOWAY/spack/var/spack/stage/netcdf-cxx4-4.3.1-eqi2ln3ps5xln7tb5kac7gslqus6xoiz/v4.3.1
    Expected 6a1189a181eed043b5859e15d5c080c30d0e107406fbb212c8fb9814e90f3445 but got 714339bba765077e03af62f32c35a2f96fded59fc01a1dd215266a8e2af39a53
```

**Comment by adamjstewart** [comment] 2020-03-31 02:08
This may be related to #15641 and #15752

**Comment by citibeth** [comment] 2020-03-31 02:18
Hmmm... maybe.  But 4.3.0 checksum matches.  Maybe something careless happened on the way to GitHub?

In any case, `netcdf-cxx@4.3.1` does not work with `netcdf@4.4.0` (I believe now it's called `netcdf-c`).  I went back to `netcdf-cxx@4.3.0`, and things seem to build.

**Comment by alalazo** [comment] 2020-04-07 13:11
Closing as I can't reproduce it:
```console
$ $ spack fetch netcdf-cxx4@4.3.1
[ ... ]
$ ls -larth $SPACK_ROOT/var/spack/cache/_source-cache/archive/6a/6a1189a181eed043b5859e15d5c080c30d0e107406fbb212c8fb9814e90f3445.tar.gz
-rw-rw-r-- 1 culpo culpo 585K apr  7 15:02 /home/culpo/PycharmProjects/spack/var/spack/cache/_source-cache/archive/6a/6a1189a181eed043b5859e15d5c080c30d0e107406fbb212c8fb9814e90f3445.tar.gz

$ sha256sum /home/culpo/PycharmProjects/spack/var/spack/cache/_source-cache/archive/6a/6a1189a181eed043b5859e15d5c080c30d0e107406fbb212c8fb9814e90f3445.tar.gz
6a1189a181eed043b5859e15d5c080c30d0e107406fbb212c8fb9814e90f3445  /home/culpo/PycharmProjects/spack/var/spack/cache/_source-cache/archive/6a/6a1189a181eed043b5859e15d5c080c30d0e107406fbb212c8fb9814e90f3445.tar.gz
```
What I download seems to have the checksum that is expected also in the case reported in the description.

**Closed by alalazo** 2020-04-07 13:11 UTC
Labels: build-error, checksum
