### ISSUE TITLE
Error: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#13608] opened 2019-11-05 22:43 UTC
We seem to be hitting the maximum open filehandle limit during `spack env activate`.

### Steps to reproduce the issue

```console
$ spack env activate -d .
```

Interestingly enough, if I use:
```console
$ spack -d env activate -d .
```
I can avoid the bug.

### Error Message

```console
==> Error: filedescriptor out of range in select()
```

### Information on your system

Blue Waters, Cray CNL5, Python 2.6.9

`spack.yaml`:
```yaml
spack:
  specs:
  - 'gdal+python'
  - 'python@3.7:+sqlite3'
  - 'py-flake8'
  - 'py-matplotlib'
  - 'py-numpy'
  - 'py-pandas'
  - 'py-pytest@3.9:'
  - 'py-scikit-learn'
  - 'py-scipy@0.14:'
  - 'py-tables@3.0.0:'
  - 'py-torch@0.4:'
  - 'py-torchvision'
  concretization: together
```

This bug seems to be very intermittent and hard to reproduce...

**Comment by alalazo** [comment] 2022-12-15 10:02
Closing as unreproducible, since it's also related to a Python version we don't support anymore. Let me know if you see it again.

**Closed by alalazo** 2022-12-15 10:02 UTC
Labels: bug, unreproducible, environments
