### ISSUE TITLE
Spack cannot use pip-installed python packages at build time

### ISSUE THREAD

**Issue by mdorier** [spack/spack#15886] opened 2020-04-05 20:45 UTC
I have a python package A that can be installed with spack; this package depends on a python package B at build time (i.e. it imports B in its setup.py script). I install B using pip, rather than spack, and provide spack with the path to B in my packages.yaml file. When I try `spack install A`, B is correctly found by spack and added to spack's database, but the installation of A fails on the "import B" statement: B cannot be found. This may hint at some PYTHONPATH issues during spack install. Dependencies might not be added to it.

### Steps to reproduce the issue

I have tried these steps with one of my own packages as package A, and with both py-numpy and py-tensorflow as B. I believe this bug could be reproduced by, for instance, installing setuptools as B, and any package that imports setuptools in its setup.py script as A.

Here is the example with py-numpy.

```console
$ spack install python
$ spack py-pip
$ spack load -r python
$ spack load -r py-pip
$ pip install py-numpy --user
```
At this point you can call python and import numpy, you will see that it works.

Then edit your packages.yaml file to add a py-numpy entry pointing to ~/.local (this is where numpy has been installed by pip because of the --user flag; though I have tried without the --user flag and the same thing happens).

Finally run:
```
spack install B
```
Where B is a package that calls `import numpy` in its setup.py script. The build will fail, and the log will show that python couldn't find the numpy package.

**Comment by adamjstewart** [comment] 2020-04-05 20:48
> provide spack with the path to B in my packages.yaml

Can you share this file?

**Comment by mdorier** [comment] 2020-04-05 20:56
Sure, in the case of numpy I had this:
```
packages:
  py-numpy:
    buildable: False
	paths:
	  py-numpy@1.18.2: /home/mdorier/.local
```
And I tried as well with tensorflow, where I had this:
```
packages:
  py-tensorflow:
    buildable: False
	paths:
	  py-tensorflow@2.1.0: /home/mdorier/.local
```

**Comment by adamjstewart** [comment] 2020-04-05 20:58
What does your `/home/mdorier/.local` directory look like? Does it contain `lib/pythonX.Y/site-packages` for both numpy and tensorflow?

**Comment by mdorier** [comment] 2020-04-05 21:04
Is it does. And I can import numpy and tensorflow from a python prompt without any problem.

**Comment by adamjstewart** [comment] 2020-04-05 21:07
Can you upload the `spack-build-out.txt` and `spack-build-env.txt` from the failing build? That will give me more info.

**Comment by adamjstewart** [comment] 2020-04-05 21:09
Another thing you can try is to remove `--no-user-cfg` from [this line](https://github.com/spack/spack/blob/develop/lib/spack/spack/build_systems/python.py#L121). That's my first guess as to why it isn't working.

**Comment by mdorier** [comment] 2020-04-05 21:46
Here are the files:
[spack-build-out.txt](https://github.com/spack/spack/files/4434957/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/4434959/spack-build-env.txt)

Same problem happens when I remove `--no-user-cfg`; here are the corresponding files:
[spack-build-out-2.txt](https://github.com/spack/spack/files/4434962/spack-build-out-2.txt)
[spack-build-env-2.txt](https://github.com/spack/spack/files/4434965/spack-build-env-2.txt)

**Comment by adamjstewart** [comment] 2020-04-05 22:30
It looks like `py-mochi-tmci` is the package you are trying to build? Are you able to share the `package.py` for that package?

Based on your `spack-build-env.txt`, it looks like the dependencies aren't being added to the `PYTHONPATH`. That shouldn't happen as far as I know unless you don't have the dependencies listed as build dependencies.

**Comment by mdorier** [comment] 2020-04-05 22:38
If you do:
```
https://xgitlab.cels.anl.gov/sds/sds-repo.git
spack repo add sds-repo
```
You will see the py-mochi-tmci package. The package does have a dependency on `py-tensorflow@2.0.0:`.

**Comment by adamjstewart** [comment] 2020-04-05 23:57
I don't see anything in there that looks suspicious.

Maybe this is related to #9149? I've had problems like this in the past, where dependencies of external packages aren't included in the concretized spec. Can you run `spack spec py-mochi-tmci` and post the output here?

**Comment by adamjstewart** [comment] 2020-04-06 00:01
[This section of code](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/python/package.py#L757,L765) is responsible for setting `PYTHONPATH` for all Python extensions. Maybe you can add print statements in there. I'm guessing that `py-tensorflow` is listed as a dependency in `dependent_spec.traverse(...)`, but since the `python` dependency isn't included in the spec, `d.package.extends(self.spec)` returns False.

**Comment by mdorier** [comment] 2020-04-06 08:16
> Can you run `spack spec py-mochi-tmci` and post the output here?

Here it it:
```
$ spack spec py-mochi-tmci
Input spec
--------------------------------
py-mochi-tmci

Concretized
--------------------------------
py-mochi-tmci@master%gcc@8.3.0~theta arch=linux-debian10-sandybridge
    ^py-pybind11@2.5.0%gcc@8.3.0 build_type=RelWithDebInfo arch=linux-debian10-sandybridge
        ^cmake@3.17.0%gcc@8.3.0~doc+ncurses+openssl+ownlibs~qt arch=linux-debian10-sandybridge
            ^ncurses@6.1%gcc@8.3.0~symlinks+termlib arch=linux-debian10-sandybridge
            ^openssl@1.1.1f%gcc@8.3.0+systemcerts arch=linux-debian10-sandybridge
                ^perl@5.28.1%gcc@8.3.0+cpanm+shared+threads arch=linux-debian10-sandybridge
                ^zlib@1.2.11%gcc@8.3.0+optimize+pic+shared arch=linux-debian10-sandybridge
        ^py-setuptools@41.4.0%gcc@8.3.0 arch=linux-debian10-sandybridge
            ^python@3.7.4%gcc@8.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-debian10-sandybridge
                ^bzip2@1.0.6%gcc@8.3.0+shared arch=linux-debian10-sandybridge
                ^expat@2.2.9%gcc@8.3.0+libbsd arch=linux-debian10-sandybridge
                    ^libbsd@0.10.0%gcc@8.3.0 arch=linux-debian10-sandybridge
                ^gdbm@1.18.1%gcc@8.3.0 arch=linux-debian10-sandybridge
                    ^readline@8.0%gcc@8.3.0 arch=linux-debian10-sandybridge
                ^gettext@0.19.8.1%gcc@8.3.0+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=linux-debian10-sandybridge
                ^libffi@3.2.1%gcc@8.3.0 arch=linux-debian10-sandybridge
                ^pkg-config@0.29%gcc@8.3.0+internal_glib patches=49ffcd644e190dc5efcb2fab491177811ea746c1a526f75d77118c2706574358 arch=linux-debian10-sandybridge
                ^sqlite@3.30.1%gcc@8.3.0+column_metadata+fts~functions~rtree arch=linux-debian10-sandybridge
                ^xz@5.2.4%gcc@8.3.0 arch=linux-debian10-sandybridge
    ^py-tensorflow@2.1.0%gcc@8.3.0~android~aws~computecpp~cuda cuda_arch=none ~dynamic_kernels~gcp~gdr~hdfs~ignite~ios~jemalloc~kafka~mkl~monolithic~mpi~nccl~ngraph~numa~opencl~rocm~tensorrt~verbs~xla arch=linux-debian10-sandybridge
```

If I remove py-tensorflow from my packages.yaml file (actually removing the path and the `buildable: False`, but keeping the variants) I get this:

```
$ spack spec py-mochi-tmci
Input spec
--------------------------------
py-mochi-tmci

Concretized
--------------------------------
py-mochi-tmci@master%gcc@8.3.0~theta arch=linux-debian10-sandybridge
    ^py-pybind11@2.5.0%gcc@8.3.0 build_type=RelWithDebInfo arch=linux-debian10-sandybridge
        ^cmake@3.17.0%gcc@8.3.0~doc+ncurses+openssl+ownlibs~qt arch=linux-debian10-sandybridge
            ^ncurses@6.1%gcc@8.3.0~symlinks+termlib arch=linux-debian10-sandybridge
            ^openssl@1.1.1f%gcc@8.3.0+systemcerts arch=linux-debian10-sandybridge
                ^perl@5.28.1%gcc@8.3.0+cpanm+shared+threads arch=linux-debian10-sandybridge
                ^zlib@1.2.11%gcc@8.3.0+optimize+pic+shared arch=linux-debian10-sandybridge
        ^py-setuptools@41.4.0%gcc@8.3.0 arch=linux-debian10-sandybridge
            ^python@3.7.4%gcc@8.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-debian10-sandybridge
                ^bzip2@1.0.6%gcc@8.3.0+shared arch=linux-debian10-sandybridge
                ^expat@2.2.9%gcc@8.3.0+libbsd arch=linux-debian10-sandybridge
                    ^libbsd@0.10.0%gcc@8.3.0 arch=linux-debian10-sandybridge
                ^gdbm@1.18.1%gcc@8.3.0 arch=linux-debian10-sandybridge
                    ^readline@8.0%gcc@8.3.0 arch=linux-debian10-sandybridge
                ^gettext@0.19.8.1%gcc@8.3.0+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=linux-debian10-sandybridge
                ^libffi@3.2.1%gcc@8.3.0 arch=linux-debian10-sandybridge
                ^pkg-config@0.29%gcc@8.3.0+internal_glib patches=49ffcd644e190dc5efcb2fab491177811ea746c1a526f75d77118c2706574358 arch=linux-debian10-sandybridge
                ^sqlite@3.30.1%gcc@8.3.0+column_metadata+fts~functions~rtree arch=linux-debian10-sandybridge
                ^xz@5.2.4%gcc@8.3.0 arch=linux-debian10-sandybridge
    ^py-tensorflow@2.1.0%gcc@8.3.0~android~aws~computecpp~cuda cuda_arch=none ~dynamic_kernels~gcp~gdr~hdfs~ignite~ios~jemalloc~kafka~mkl~monolithic~mpi~nccl~ngraph~numa~opencl~rocm~tensorrt~verbs~xla arch=linux-debian10-sandybridge
        ^bazel@0.29.1%gcc@8.3.0 patches=3e6448a0dde42bbd72568d29c5646d370dd62ca300cdd10a630908c086844167,75fad08d2a118372ed86696832942c7903bb716af28e5af969d8e20857655cf4,dbbf38bd17c63aa923f2433a2013d302739f8043ca427c816e8737dab05ac528 arch=linux-debian10-sandybridge
            ^jdk@1.8.0_241-b07%gcc@8.3.0 arch=linux-debian10-sandybridge
            ^zip@3.0%gcc@8.3.0 arch=linux-debian10-sandybridge
        ^py-absl-py@0.7.1%gcc@8.3.0 arch=linux-debian10-sandybridge
            ^py-six@1.12.0%gcc@8.3.0 arch=linux-debian10-sandybridge
        ^py-astor@0.8.0%gcc@8.3.0 patches=edc5eeddabe153b08e938f52edaeb2d880ee3128082967f310db0f98510fe6e0 arch=linux-debian10-sandybridge
        ^py-gast@0.2.2%gcc@8.3.0 arch=linux-debian10-sandybridge
        ^py-google-pasta@0.1.8%gcc@8.3.0 arch=linux-debian10-sandybridge
        ^py-grpcio@1.27.2%gcc@8.3.0 arch=linux-debian10-sandybridge
            ^c-ares@1.15.0%gcc@8.3.0 build_type=RelWithDebInfo arch=linux-debian10-sandybridge
            ^py-cython@0.29.14%gcc@8.3.0 arch=linux-debian10-sandybridge
        ^py-keras-applications@1.0.8%gcc@8.3.0 arch=linux-debian10-sandybridge
        ^py-keras-preprocessing@1.1.0%gcc@8.3.0 arch=linux-debian10-sandybridge
        ^py-numpy@1.18.2%gcc@8.3.0+blas+lapack arch=linux-debian10-sandybridge
            ^openblas@0.3.9%gcc@8.3.0~consistent_fpcsr~ilp64+pic+shared threads=none arch=linux-debian10-sandybridge
        ^py-opt-einsum@3.1.0%gcc@8.3.0 arch=linux-debian10-sandybridge
        ^py-protobuf@3.11.2%gcc@8.3.0~cpp arch=linux-debian10-sandybridge
        ^py-scipy@1.4.1%gcc@8.3.0 arch=linux-debian10-sandybridge
        ^py-termcolor@1.1.0%gcc@8.3.0 arch=linux-debian10-sandybridge
        ^py-wheel@0.33.4%gcc@8.3.0 arch=linux-debian10-sandybridge
        ^py-wrapt@1.11.2%gcc@8.3.0 arch=linux-debian10-sandybridge
        ^swig@4.0.1%gcc@8.3.0 arch=linux-debian10-sandybridge
            ^pcre@8.43%gcc@8.3.0~jit+multibyte+utf arch=linux-debian10-sandybridge
```

**Comment by mdorier** [comment] 2020-04-06 08:24
> [This section of code](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/python/package.py#L757,L765) is responsible for setting `PYTHONPATH` for all Python extensions. Maybe you can add print statements in there. I'm guessing that `py-tensorflow` is listed as a dependency in `dependent_spec.traverse(...)`, but since the `python` dependency isn't included in the spec, `d.package.extends(self.spec)` returns False.

How do I print something on the console? the simple `print` statement doesn't seem to work...

**Comment by adamjstewart** [comment] 2020-04-06 13:00
You may need to run `spack install -v`, otherwise the output of print will go to the build log.

**Comment by mdorier** [comment] 2020-04-06 13:16
Here is the content of the `python_paths` variable after the loop:
```
['/projects/spack/opt/spack/linux-debian10-sandybridge/gcc-8.3.0/py-mochi-tmci-master-wopxq7u4gorohneubjasxnqxefojj355/lib/python3.7/site-packages', '/projects/spack/opt/spack/linux-debian10-sandybridge/gcc-8.3.0/py-pybind11-2.5.0-ixjbj6jh24i3i3z7mtblkftrz5ozystq/lib/python3.7/site-packages', '/projects/spack/opt/spack/linux-debian10-sandybridge/gcc-8.3.0/py-setuptools-41.4.0-pwcivhpik4qn7yt53rblnpxgvd2jsfhm/lib/python3.7/site-packages']
```
No trace of `/home/mdorier/.local`.

**Comment by adamjstewart** [comment] 2020-04-06 14:12
Does it loop over the tensorflow dependency and then reject it because it doesn't satisfy `extends`?

**Comment by mdorier** [comment] 2020-04-06 14:18
Yes, it's included in the loop, but doesn't pass the condition.

**Comment by mdorier** [comment] 2020-04-06 14:19
Is it because it's not a PythonPackage? (it inherits from Package and from CudaPackage).

**Comment by adamjstewart** [comment] 2020-04-06 14:26
> Is it because it's not a PythonPackage?

Nope, it should be fine since it `extends('python')` in the package.

**Comment by mdorier** [comment] 2020-04-06 14:29
> > Is it because it's not a PythonPackage?
> 
> Nope, it should be fine since it `extends('python')` in the package.

Ok then that's more consistent with the fact that the same happened with py-numpy (and I suspect with other python packages if I install them with pip).

**Comment by mdorier** [comment] 2020-06-08 13:23
Any idea for a fix? I keep having to comment the condition here: https://github.com/spack/spack/blob/3ea65818e1827835864c6c073175eb5edf7b4213/var/spack/repos/builtin/packages/python/package.py#L812 for pip-installed packages to be added to PYTHONPATH.

**Comment by adamjstewart** [comment] 2021-08-27 20:45
This may be related to https://github.com/spack/spack/issues/9149. When external packages get registered in a spec, their dependencies don't.

**Comment by adamjstewart** [comment] 2022-01-07 21:16
Closing this as a duplicate of #9149, let's continue the discussion there.

**Closed by adamjstewart** 2022-01-07 21:16 UTC
Labels: bug, python, external-packages, triage
