### ISSUE TITLE
icu4c package build fails

### ISSUE THREAD

**Issue by thomasbrTTU** [spack/spack#15664] opened 2020-03-24 23:45 UTC
#15486 # Spack version
```console
$ spack --version
0.14.1-342-3b7c79b
```

### Steps to reproduce the issue
```console
$ spack install icu4c 
==> 125999: icu4c: Building icu4c [AutotoolsPackage]
==> 125999: icu4c: Executing phase: 'autoreconf'
==> 125999: icu4c: Executing phase: 'configure'
==> 125999: icu4c: Executing phase: 'build'
==> Error: Exception occurred in writer daemon!
Traceback (most recent call last):
  File "/home/prdawar/spack/lib/spack/llnl/util/tty/log.py", line 499, in _writer_daemon
    br, fe = handle_write(force_echo)
  File "/home/prdawar/spack/lib/spack/llnl/util/tty/log.py", line 453, in handle_write
    line = in_pipe.readline()
  File "/usr/lib64/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 88: ordinal not in range(128)
==> Error: ProcessError: Command exited with status -13:
    'make' '-j16'
See build log for details:
  /tmp/prdawar/spack-stage/spack-stage-icu4c-65.1-55wm4t2wm3y7ibzmdsn5jwhgqhplfxna/spack-build-out.txt

==> Error: Failed to install icu4c due to ChildError: ProcessError: Command exited with status -13:
    'make' '-j16'See build log for details:
  /tmp/prdawar/spack-stage/spack-stage-icu4c-65.1-55wm4t2wm3y7ibzmdsn5jwhgqhplfxna/spack-build-out.txt
Traceback (most recent call last):
  File "/home/prdawar/spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/home/prdawar/spack/lib/spack/spack/installer.py", line 1113, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/home/prdawar/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/home/prdawar/spack/lib/spack/spack/build_systems/autotools.py", line 290, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/home/prdawar/spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/home/prdawar/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status -13:
    'make' '-j16'
```

### Platform and user environment
```commandline
$ uname -a 
Linux quanah 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux x86_64 GNU/Linux
$ lsb_release -d
Description:    CentOS Linux release 7.4.1708 (Core)
``` 

### Additional information
```console
$ spack spec --install-status icu4c
Input spec
--------------------------------
 -   icu4c

Concretized
--------------------------------
==> Warning: gcc@4.8.5 cannot build optimized binaries for "broadwell". Using best target possible: "haswell"
 -   icu4c@65.1%gcc@4.8.5 cxxstd=11 arch=linux-centos7-haswell
[+]      ^python@3.7.6%gcc@4.8.5+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-centos7-haswell
[+]          ^bzip2@1.0.8%gcc@4.8.5+shared arch=linux-centos7-haswell
[+]              ^diffutils@3.7%gcc@4.8.5 arch=linux-centos7-haswell
[+]                  ^libiconv@1.16%gcc@4.8.5 arch=linux-centos7-haswell
[+]          ^expat@2.2.9%gcc@4.8.5+libbsd arch=linux-centos7-haswell
[+]              ^libbsd@0.10.0%gcc@4.8.5 arch=linux-centos7-haswell
[+]          ^gdbm@1.18.1%gcc@4.8.5 arch=linux-centos7-haswell
[+]              ^readline@8.0%gcc@4.8.5 arch=linux-centos7-haswell
[+]                  ^ncurses@6.2%gcc@4.8.5~symlinks+termlib arch=linux-centos7-haswell
[+]                      ^pkgconf@1.6.3%gcc@4.8.5 arch=linux-centos7-haswell
[+]          ^gettext@0.20.1%gcc@4.8.5+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-haswell
[+]              ^libxml2@2.9.9%gcc@4.8.5~python arch=linux-centos7-haswell
[+]                  ^xz@5.2.4%gcc@4.8.5 arch=linux-centos7-haswell
[+]                  ^zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-haswell
[+]              ^tar@1.32%gcc@4.8.5 arch=linux-centos7-haswell
[+]          ^libffi@3.2.1%gcc@4.8.5 arch=linux-centos7-haswell
[+]          ^openssl@1.1.1e%gcc@4.8.5+systemcerts arch=linux-centos7-haswell
[+]              ^perl@5.30.1%gcc@4.8.5+cpanm+shared+threads arch=linux-centos7-haswell
[+]          ^sqlite@3.30.1%gcc@4.8.5+column_metadata+fts~functions~rtree arch=linux-centos7-haswell

```

**Comment by iarspider** [comment] 2020-03-27 16:00
Possible duplicate of #15285

**Closed** 2020-03-29 15:10 UTC
Labels: build-error
