### ISSUE TITLE
Support relative file paths in spack.yaml mirrors section

### ISSUE THREAD

**Issue by AndrewGaspar** [spack/spack#12710] opened 2019-09-04 22:51 UTC
The "mirrors" section of "spack.yaml" should support file paths that are relative to the spack.yaml.

### Rationale

I have some dependencies I've "vendored" into my source control via a spack mirror for systems where those dependencies aren't accessible. I'd like the included spack environment to point to that mirror. Currently mirrors can not be to a relative path.

### Description

Allow relative file paths in the mirrors section of spack.yaml

**Comment by tylerjereddy** [comment] 2019-09-21 17:53
Not sure if related but I'm pretty sure `spack mirror add` can have problems with relative paths simply not working, with no exception raised when provided. Perhaps I'll take a look..

**Comment by haampie** [comment] 2021-12-14 15:17
@psakievich is this also something that you worked on?

**Comment by psakievich** [comment] 2021-12-14 15:26
@haampie no but it is related to two other PR's I have open

**Comment by alalazo** [comment] 2021-12-21 10:03
The issue is that we store mirrors by `url`, we should probably differentiate by type and allow for relative paths on local mirrors

**Comment by psakievich** [comment] 2021-12-21 15:25
@alalazo I like that idea.  Probably the most straightforward way to do things.  This is probably a bigger scope than this PR, but I've been thinking we should look into making all paths in spack be typed.  This would allow a uniform solution to the relative path, absolute path, environment variable expansion, and url vs filesystem issues.  You could then do existence checks, decide to expand or not, etc all within the path class(es) and wrap a lot of code into a small set of business rules.  IMO we are  chasing down lots of similar instances path issues, and applying ad-hoc fixes to each one rather than setting up a uniform set of business rules for how to handle paths.  Should have put this in my spack survey.

**Comment by haampie** [comment] 2023-01-17 17:40
Should be fixed in #34891

**Closed by haampie** 2023-01-17 17:40 UTC
Labels: feature, configuration, radiuss
