### ISSUE TITLE
Spack install randomly failing with patch errors since v0.13.0

### ISSUE THREAD

**Issue by bartlettroscoe** [spack/spack#13505] opened 2019-10-30 13:31 UTC
snl-atdm-issue

We are seeing failures of the patch command when trying to install perl (which is a required dependency for cgns).  I saw this after upgrading to a recent version of spack 'develop' and I am still seeing this again after upgrading to version `v0.13.0` so I am going to report this.

We are seeing errors like:

```
==> Installing perl
==> Searching for binary cache of perl
==> Finding buildcaches in /ascldap/users/rabartl/Spack.base4/atdm-spack/atdm-spack-tarball-mirror/build_cache
==> No binary for perl found: installing from source
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/fflush.c.orig m4-1.4.18/lib/fflush.c
|--- m4-1.4.18/lib/fflush.c.orig	2018-05-02 12:35:59.536851666 +0200
|+++ m4-1.4.18/lib/fflush.c	2018-05-02 12:37:02.768958606 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
3 out of 3 hunks ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/fpending.c.orig m4-1.4.18/lib/fpending.c
|--- m4-1.4.18/lib/fpending.c.orig	2018-05-02 12:35:32.305806774 +0200
|+++ m4-1.4.18/lib/fpending.c	2018-05-02 12:35:44.944827347 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/fpurge.c.orig m4-1.4.18/lib/fpurge.c
|--- m4-1.4.18/lib/fpurge.c.orig	2018-05-02 12:38:13.586078669 +0200
|+++ m4-1.4.18/lib/fpurge.c	2018-05-02 12:38:38.785121867 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/freadahead.c.orig m4-1.4.18/lib/freadahead.c
|--- m4-1.4.18/lib/freadahead.c.orig	2016-12-31 14:54:41.000000000 +0100
|+++ m4-1.4.18/lib/freadahead.c	2018-05-02 11:43:19.570336724 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/freading.c.orig m4-1.4.18/lib/freading.c
|--- m4-1.4.18/lib/freading.c.orig	2018-05-02 12:37:33.970011368 +0200
|+++ m4-1.4.18/lib/freading.c	2018-05-02 12:37:59.393054359 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/fseeko.c.orig m4-1.4.18/lib/fseeko.c
|--- m4-1.4.18/lib/fseeko.c.orig	2018-05-02 11:44:17.947460233 +0200
|+++ m4-1.4.18/lib/fseeko.c	2018-05-02 12:39:49.537216897 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
2 out of 2 hunks ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/stdio-impl.h.orig m4-1.4.18/lib/stdio-impl.h
|--- m4-1.4.18/lib/stdio-impl.h.orig	2016-12-31 14:54:42.000000000 +0100
|+++ m4-1.4.18/lib/stdio-impl.h	2018-05-02 11:43:19.570336724 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
==> Fetching http://www.cpan.org/src/5.0/perl-5.26.2.tar.gz
==> Using cached archive: /home/rabartl/Spack.base4/atdm-spack/spack/var/spack/cache/_source-cache/archive/9d/9da50e155df72bce55cb69f51f1dbb4b62d23740fb99f6178bb27f22ebdf8a46.tar.gz
==> Fetching https://src.fedoraproject.org/rpms/perl/raw/004cea3a67df42e92ffdf4e9ac36d47a3c6a05a4/f/perl-5.26.1-guard_old_libcrypt_fix.patch
==> Staging archive: /tmp/rabartl/spack-stage/spack-stage-perl-5.26.2-rvc7wh45wlmdgpwk3fj2avhaweqkighs/perl-5.26.2.tar.gz
==> Created stage in /tmp/rabartl/spack-stage/spack-stage-perl-5.26.2-rvc7wh45wlmdgpwk3fj2avhaweqkighs
==> Staging archive: /tmp/rabartl/spack-stage/resource-cpanm-rvc7wh45wlmdgpwk3fj2avhaweqkighs/App-cpanminus-1.7042.tar.gz
==> Created stage in /tmp/rabartl/spack-stage/resource-cpanm-rvc7wh45wlmdgpwk3fj2avhaweqkighs
==> Moving resource stage
	source : /tmp/rabartl/spack-stage/resource-cpanm-rvc7wh45wlmdgpwk3fj2avhaweqkighs/spack-src/
	destination : /tmp/rabartl/spack-stage/spack-stage-perl-5.26.2-rvc7wh45wlmdgpwk3fj2avhaweqkighs/spack-src/cpanm/cpanm
==> Patch https://src.fedoraproject.org/rpms/perl/raw/004cea3a67df42e92ffdf4e9ac36d47a3c6a05a4/f/perl-5.26.1-guard_old_libcrypt_fix.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/tmp/rabartl/spack-stage/spack-stage-CbarWr/m4-1.4.18-glibc-change-work-around.patch' '-d' '.'
```

I don't remember seeing this with older versions of spack.  Is this expected?

Before, I had to run `spack install` over and over again (3-4 times) to get a successful install.

**Comment by bartlettroscoe** [comment] 2019-10-30 17:59
> the patches should always apply successfully and automatically.

After the upgrade, this appears to happen every time I run `spack install` for the first time with the given spack.yaml file.

Do you think I have a shot at not letting Spack build perl@5.26.2 and instead just use the native perl@5.10.1 already on RHEL6 systems:

```
$ which perl
/usr/bin/perl

$ perl --version

This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi
```

?

I would like for spack to build an updated python (because that would be useful for our customers) but I can't see any value in building a new perl.  (And any package that requires a newer version of perl should be expelled from Spack.)

**Comment by scheibelp** [comment] 2019-10-30 19:49
> Do you think I have a shot at not letting Spack build perl@5.26.2 and instead just use the native perl@5.10.1 already on RHEL6 systems:

Yes: see https://spack.readthedocs.io/en/latest/build_settings.html#external-packages and `buildable: False`

Could you add the other info requested in https://github.com/spack/spack/issues/13505#issuecomment-548034270?

**Comment by bartlettroscoe** [comment] 2019-11-03 18:27
> Could you add the other info requested in https://github.com/spack/spack/issues/13505#issuecomment-548034270?

This seems to be quite random, and it is not just for the perl packages (see below).  I have more than a dozen builds from scratch over the last few days and have only had this happen a couple of times. 

Has really else experienced this?

-----

I just encountered a patch error for the  package `mpfr`:

```
==> Installing mpfr
==> Searching for binary cache of mpfr
==> Finding buildcaches in /scratch/rabartl/Spack.base2/atdm-spack/atdm-spack-tarball-mirror/build_cache
==> No binary for mpfr found: installing from source
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/fflush.c.orig m4-1.4.18/lib/fflush.c
|--- m4-1.4.18/lib/fflush.c.orig	2018-05-02 12:35:59.536851666 +0200
|+++ m4-1.4.18/lib/fflush.c	2018-05-02 12:37:02.768958606 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
3 out of 3 hunks ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/fpending.c.orig m4-1.4.18/lib/fpending.c
|--- m4-1.4.18/lib/fpending.c.orig	2018-05-02 12:35:32.305806774 +0200
|+++ m4-1.4.18/lib/fpending.c	2018-05-02 12:35:44.944827347 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/fpurge.c.orig m4-1.4.18/lib/fpurge.c
|--- m4-1.4.18/lib/fpurge.c.orig	2018-05-02 12:38:13.586078669 +0200
|+++ m4-1.4.18/lib/fpurge.c	2018-05-02 12:38:38.785121867 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/freadahead.c.orig m4-1.4.18/lib/freadahead.c
|--- m4-1.4.18/lib/freadahead.c.orig	2016-12-31 14:54:41.000000000 +0100
|+++ m4-1.4.18/lib/freadahead.c	2018-05-02 11:43:19.570336724 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/freading.c.orig m4-1.4.18/lib/freading.c
|--- m4-1.4.18/lib/freading.c.orig	2018-05-02 12:37:33.970011368 +0200
|+++ m4-1.4.18/lib/freading.c	2018-05-02 12:37:59.393054359 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/fseeko.c.orig m4-1.4.18/lib/fseeko.c
|--- m4-1.4.18/lib/fseeko.c.orig	2018-05-02 11:44:17.947460233 +0200
|+++ m4-1.4.18/lib/fseeko.c	2018-05-02 12:39:49.537216897 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
2 out of 2 hunks ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/stdio-impl.h.orig m4-1.4.18/lib/stdio-impl.h
|--- m4-1.4.18/lib/stdio-impl.h.orig	2016-12-31 14:54:42.000000000 +0100
|+++ m4-1.4.18/lib/stdio-impl.h	2018-05-02 11:43:19.570336724 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
==> Fetching https://ftpmirror.gnu.org/mpfr/mpfr-3.1.6.tar.bz2
==> Fetching https://www.mpfr.org/mpfr-3.1.6/allpatches
==> Staging archive: /tmp/rabartl/spack-stage/spack-stage-mpfr-3.1.6-owkqyfaeljyr46zrkex6dy27bfqrfyc5/mpfr-3.1.6.tar.bz2
==> Created stage in /tmp/rabartl/spack-stage/spack-stage-mpfr-3.1.6-owkqyfaeljyr46zrkex6dy27bfqrfyc5
==> Patch https://www.mpfr.org/mpfr-3.1.6/allpatches failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/tmp/rabartl/spack-stage/spack-stage-EDxZi0/m4-1.4.18-glibc-change-work-around.patch' '-d' '.'
```

**Comment by bartlettroscoe** [comment] 2019-11-03 18:29
> > Do you think I have a shot at not letting Spack build perl@5.26.2 and instead just use the native perl@5.10.1 already on RHEL6 systems:
> 
> Yes: see https://spack.readthedocs.io/en/latest/build_settings.html#external-packages and `buildable: False`

BTW, no dice on using externally provided packages (see #13516).  My workarounds are getting narrow at this point.

**Comment by bartlettroscoe** [comment] 2019-11-05 13:42
And it happened again:

```
==> Installing mpfr
==> Searching for binary cache of mpfr
==> Finding buildcaches in /projects/atdm_devops/atdm-spack/2019-11-04/atdm-spack/atdm-spack-tarball-mirror/build_cache
==> No binary for mpfr found: installing from source
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/fflush.c.orig m4-1.4.18/lib/fflush.c
|--- m4-1.4.18/lib/fflush.c.orig	2018-05-02 12:35:59.536851666 +0200
|+++ m4-1.4.18/lib/fflush.c	2018-05-02 12:37:02.768958606 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
3 out of 3 hunks ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/fpending.c.orig m4-1.4.18/lib/fpending.c
|--- m4-1.4.18/lib/fpending.c.orig	2018-05-02 12:35:32.305806774 +0200
|+++ m4-1.4.18/lib/fpending.c	2018-05-02 12:35:44.944827347 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/fpurge.c.orig m4-1.4.18/lib/fpurge.c
|--- m4-1.4.18/lib/fpurge.c.orig	2018-05-02 12:38:13.586078669 +0200
|+++ m4-1.4.18/lib/fpurge.c	2018-05-02 12:38:38.785121867 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/freadahead.c.orig m4-1.4.18/lib/freadahead.c
|--- m4-1.4.18/lib/freadahead.c.orig	2016-12-31 14:54:41.000000000 +0100
|+++ m4-1.4.18/lib/freadahead.c	2018-05-02 11:43:19.570336724 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/freading.c.orig m4-1.4.18/lib/freading.c
|--- m4-1.4.18/lib/freading.c.orig	2018-05-02 12:37:33.970011368 +0200
|+++ m4-1.4.18/lib/freading.c	2018-05-02 12:37:59.393054359 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/fseeko.c.orig m4-1.4.18/lib/fseeko.c
|--- m4-1.4.18/lib/fseeko.c.orig	2018-05-02 11:44:17.947460233 +0200
|+++ m4-1.4.18/lib/fseeko.c	2018-05-02 12:39:49.537216897 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
2 out of 2 hunks ignored
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/stdio-impl.h.orig m4-1.4.18/lib/stdio-impl.h
|--- m4-1.4.18/lib/stdio-impl.h.orig	2016-12-31 14:54:42.000000000 +0100
|+++ m4-1.4.18/lib/stdio-impl.h	2018-05-02 11:43:19.570336724 +0200
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
==> Fetching https://ftpmirror.gnu.org/mpfr/mpfr-3.1.6.tar.bz2
==> Fetching https://www.mpfr.org/mpfr-3.1.6/allpatches
==> Staging archive: /tmp/atdm-devops-admin/spack-stage/spack-stage-mpfr-3.1.6-owkqyfaeljyr46zrkex6dy27bfqrfyc5/mpfr-3.1.6.tar.bz2
==> Created stage in /tmp/atdm-devops-admin/spack-stage/spack-stage-mpfr-3.1.6-owkqyfaeljyr46zrkex6dy27bfqrfyc5
==> Patch https://www.mpfr.org/mpfr-3.1.6/allpatches failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/tmp/atdm-devops-admin/spack-stage/spack-stage-Yz4tHz/m4-1.4.18-glibc-change-work-around.patch' '-d' '.'
```

I guess I am going to need to turn on debug output for `spack install` from now on until I can catch this error occurring.

**Comment by bartlettroscoe** [comment] 2019-11-05 14:09
@fryeguy52, have you see these random patch errors during `spack install` or it is just me?

**Comment by scheibelp** [comment] 2019-11-05 19:58
Apologies but this is a tough one to decipher (and I haven't been able to reproduce it) so I have some follow up questions:

* Does the issue occur repeatedly if you `spack install` exactly the same spec multiple times?
* Does this occur for some specs and not others?
* Do you run any `spack clean` operations between the failed/succeeding installations, or have you just been repeatedly running `spack install` until there is a success?

Also, for a `spack install` invocation that fails (even if it eventually succeeds) can you include the output of `spack spec` for the same arguments here? e.g. if you tried `spack install perl` and that failed can you include the output of `spack spec perl` here?

**Comment by bartlettroscoe** [comment] 2019-11-06 00:02
> Does the issue occur repeatedly if you `spack install` exactly the same spec multiple times?

It is somewhat random but I have so far only seen it with the 'perl' and the 'mpfr' packages.

> Does this occur for some specs and not others?

So far only the 'perl' and 'mpfr' packages.

> Do you run any `spack clean` operations between the failed/succeeding installations, or have you just been repeatedly running spack install until there is a success?

No, when it fails, I just run `spack install` again and if I do that enough times, it works.  But it seems to occur most often when starting from 100% clean state.  (I added a `--wipe-clean` argument that wipes absolutely everything that the script or spack generates to know that I am starting from complete scratch.)

> Also, for a `spack install` invocation that fails (even if it eventually succeeds) can you include the output of `spack spec` for the same arguments here? 

You mean the output from containerization?  Here is the spec for 'perl'

```
perl@5.26.2%gcc@7.2.0+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-rhel6-x86_64
```

Here is the concretized spec for 'mpfr':

```
mpfr@3.1.6%gcc@4.4.7 patches=66a5d58364113a21405fc53f4a48f4e8 arch=linux-rhel6-x86_64
```

It is strange because there are several packages that show patches.  I don't know why only these two are having problems.

**Comment by scheibelp** [comment] 2019-11-07 23:35
The `mpfr` error could possibly be related to https://github.com/spack/spack/pull/13622 (or at the very least I should say there is *an* error with `mpfr` in mirrors right now); although

* `perl` wouldn't have the same problem
* The error messages/behavior is different here vs. in #13611 

So overall I don't think this is the same thing.

**Comment by scheibelp** [comment] 2019-11-07 23:36
@bartlettroscoe would it work for you if I created a debugging branch that you could pull and run to output more information?

**Comment by bartlettroscoe** [comment] 2019-11-07 23:37
> @bartlettroscoe would it work for you if I created a debugging branch that you could pull and run to output more information?

@scheibelp, would the debug output only be helpful if it failed?

**Comment by scheibelp** [comment] 2019-11-07 23:56
> would the debug output only be helpful if it failed?

Most likely yes: you would have to reinstall a few times to create the failure case, then post the output for that particular run.

**Comment by alalazo** [comment] 2020-03-04 10:25
@bartlettroscoe I just tried to reproduce this using:
```console
$ spack --version
0.14.0-110-b472c13
```
different versions of Python (3.5 which has randomized dicts, 3.6 which has ordered dicts) and different machines:
```console
$ #Machine 1
$ uname -a
Linux nuvolari 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ #Machine 2
$ uname -a
Linux davidefe02 3.10.0-862.3.2.el7.ppc64le #1 SMP Tue May 22 03:45:03 BST 2018 ppc64le ppc64le ppc64le GNU/Linux
```
I installed all the dependencies of `mpfr` and then did:
```console
$ for i in $(seq 10); do python3.5 $(which spack) install  mpfr && spack uninstall -y mpfr ; done
```
Closing since I couldn't reproduce the issue, but feel free to reopen with additional details if you are able to find a reproducer.

**Closed by alalazo** 2020-03-04 10:25 UTC
Labels: build-error, snl-atdm

**Comment by tueda** [comment] 2021-10-02 14:40
Somehow I hit the `mpfr` problem:
```
==> Installing mpfr-4.0.2-a6dh4j2xaxpysfwxa6wnvr2mhuhezsl3
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for mpfr-4.0.2-a6dh4j2xaxpysfwxa6wnvr2mhuhezsl3 found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/c0/c05e3f02d09e0e9019384cdd58e0f19c64e6db1fd6f5ecf77b4b1c61ca253acc.tar.bz2
######################################################################## 100.0%
==> Fetching https://mirror.spack.io/_source-cache/archive/3f/3f80b836948aa96f8d1cb9cc7f3f55973f19285482a96f9a4e1623d460bcccf0
######################################################################## 100.0%
The text leading up to this was:
--------------------------
|diff -up m4-1.4.18/lib/fflush.c.orig m4-1.4.18/lib/fflush.c
|--- m4-1.4.18/lib/fflush.c.orig        2018-05-02 12:35:59.536851666 +0200
|+++ m4-1.4.18/lib/fflush.c     2018-05-02 12:37:02.768958606 +0200
--------------------------
File to patch: 
```
Retrying `spack install` worked fine.

Version:
```
* **Spack:** 0.16.3
* **Python:** 3.7.4
* **Platform:** linux-centos6-nehalem
```
