### ISSUE TITLE
py-matplotlib build fails on Fedora

### ISSUE THREAD

**Issue by fmahebert** [spack/spack#7855] opened 2018-04-21 02:52 UTC
On my Fedora 27 system, `spack install py-matplotlib` from a clean Spack clone fails. Spack installs all the Matplotlib dependencies, but then `py-matplotlib` itself fails during its build phase.

It looks like Matplotlib is failing to find FreeType, even though this package was installed.

### Expected Result

`py-matplotlib` is installed.

### Actual Result

Build log:
```
==> Executing phase: 'build'
==> '/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/python-2.7.14-belgizkwgkpujlt5kj2ukdfemba65kpf/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'build'
============================================================================
Edit setup.cfg to change the build options

BUILDING MATPLOTLIB
            matplotlib: yes [2.2.2]
                python: yes [2.7.14 (default, Apr 20 2018, 18:36:46)  [GCC
                        7.3.1 20180303 (Red Hat 7.3.1-5)]]
              platform: yes [linux2]

REQUIRED DEPENDENCIES AND EXTENSIONS
                 numpy: yes [version 1.13.3]
      install_requires: yes [handled by setuptools]
                libagg: yes [pkg-config information for 'libagg' could not
                        be found. Using local copy.]
              freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                        could not be found.  You may need to install the
                        development package.]
                   png: yes [version 1.6.34]
                 qhull: yes [pkg-config information for 'libqhull' could not
                        be found. Using local copy.]

OPTIONAL SUBPACKAGES
           sample_data: yes [installing]
              toolkits: yes [installing]
                 tests: no  [skipping due to configuration]
        toolkits_tests: no  [skipping due to configuration]

OPTIONAL BACKEND EXTENSIONS
                macosx: no  [Mac OS-X only]
                qt5agg: no  [PySide2 not found; PyQt5 not found]
                qt4agg: no  [PySide not found; PyQt4 not found]
               gtk3agg: no  [Requires pygobject to be installed.]
             gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                gtkagg: no  [Requires pygtk]
                 tkagg: yes [installing; run-time loading from Python Tcl /
                        Tk]
                 wxagg: no  [requires wxPython]
                   gtk: no  [Requires pygtk]
                   agg: yes [installing]
                 cairo: no  [cairocffi or pycairo not found]
             windowing: no  [Microsoft Windows only]

OPTIONAL LATEX DEPENDENCIES
                dvipng: yes [version 1.15]
           ghostscript: yes [version 9.22]
                 latex: yes [version 3.14159265]
               pdftops: yes [version 0.57.0]

OPTIONAL PACKAGE DATA
                  dlls: no  [skipping due to configuration]

============================================================================
                        * The following required packages can not be built:
                        * freetype
                        * Try installing freetype with `dnf install
                        * freetype-devel` and pkg-config with `dnf install
                        * pkg-config`
```

### Steps to reproduce the issue

```console
$ git clone https://github.com/llnl/spack.git
$ spack/bin/spack install py-matplotlib
```

This is using today's `develop`, i.e. c8e3c94c6

### Information on your system

 1. `$ spack arch` reports `linux-fedora27-x86_64`
 2. `packages.yaml` sets the default compiler to `gcc`, BLAS/LAPACK to `openblas`, OpenSSL to system
 3. The system's package manager provides `freetype-devel`.

**Comment by azukaitis** [comment] 2018-04-27 17:35
Ran into the same issue also on OSX.

**Comment by s-sajid-ali** [comment] 2018-04-27 21:07
Can you try 
```
spack load freetype
```
before installing py-matpltolib ? 

Also, if you're building the latest version of py-matplotlib, make sure to install freetype@2.9 and load it.

**Comment by fmahebert** [comment] 2018-04-27 22:06
`spack load freetype` before `spack install py-matplotlib` did not help.

Installing and loading freetype@2.9 also did not help.

**Comment by s-sajid-ali** [comment] 2018-04-27 22:14
Can you check the error log ? Is it still saying that ft2build.h is missing ? 

I had the same issue and installing and loading freetype@2.9 did the job since it had the required header file. 
```
[sajid@xrmlite freetype2]$ pwd
/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/freetype-2.9-rurfb6m3uiet6oejx2xnvlqglf4vy7pm/include/freetype2
[sajid@xrmlite freetype2]$ ls
freetype  ft2build.h
```

**Comment by fmahebert** [comment] 2018-04-27 22:25
That's right, the log still says:
```
              freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                        could not be found.  You may need to install the
                        development package.]
```
I'm not seeing a difference between freetype@2.7.1 and @2.9 in this regard: both present the header file `ft2build.h` in the corresponding dir `spack/opt/spack/linux/gcc/freetype-version-hash/include/freetype2`, but it is not found by py-matplotlib.

**Comment by s-sajid-ali** [comment] 2018-04-27 22:29
Are you able to confirm that freetype is indeed loaded with 
```
module list
``` 
?

**Comment by fmahebert** [comment] 2018-04-27 22:47
Yes:

```
$ module list
Currently Loaded Modulefiles:
  1) freetype-2.9-gcc-7.3.1-tiryf2k
```

then `spack install py-matplotlib` fails with a build log as pasted above.

**Comment by s-sajid-ali** [comment] 2018-04-27 22:59
One last thing I'd try is :
```
spack install ^freetype@2.9 py-matplotlib
```
If that fails, we'd have to ask someone who knows more about spack

**Comment by scheibelp** [comment] 2018-04-28 00:41
It appears the Spack freetype install doesn't place `ft2build.h` exactly where `py-matplotlib`'s `setupext.py` build script expects. As a short term hack you can replace `include/freetype2/` with `include/` in the Spack freetype prefix.

I'll look into sorting this out on Monday and my solution may be along the lines of doing that automatically.

**Comment by scheibelp** [comment] 2018-04-28 01:53
According to `https://github.com/matplotlib/matplotlib/issues/3029/`, `pkg-config` should be handling this sort of thing automatically (and it it listed as a build dep of `py-matplotlib`). Do you have anything set up in `~/.spack/.../packages.yaml`?

**Comment by scheibelp** [comment] 2018-04-28 01:56
Also as a sanity check: `spack-build.env` should be included in the stage directory for `py-matplotlib`: could you add the value of `PKG_CONFIG_PATH` here as listed in that file?

**Comment by fmahebert** [comment] 2018-04-28 07:05
My `packages.yaml` has the following (snipping out comments and sections that should be (?) irrelevant):

```
packages:
  all:
    compiler: [gcc]
    providers:
      blas: [openblas]
      lapack: [openblas]
      mpi: [mpich]
  openssl:
    # snip
  hdf5:
    # snip
```

The `PKG_CONFIG_PATH` as listed the matplotlib staging directory's `spack-build.env` file has value:
```
/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/libxcb-1.13-iqekgfrzkx62mzsgn4cxw5u7emhcw2ls/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/libpthread-stubs-0.4-xqcgs6542x43dyfeb23yh72nifpdccg5/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/python-2.7.14-belgizkwgkpujlt5kj2ukdfemba65kpf/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/tcl-8.6.8-tzm3mv33jghcscgodkfvp66ump44zvjv/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/pkgconf-1.4.0-y7htlzbrinrly6rckw7facn5unpgt2va/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/tk-8.6.8-ejbnysmaubvfx5kdft6apllg3v2eecuc/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/libxau-1.0.8-kcpuyfbymgkpanr3xwi3wiokifjdguwf/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/libxdmcp-1.1.2-jd3zri4v4ua77ygvq5xnqyspurvictyl/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/zlib-1.2.11-y5oiya3aolzfqr475pqosgwe4eeqpqta/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/freetype-2.7.1-7fvthrfrhhzlfiotzb2yuimarnuku63b/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/xproto-7.0.31-gcmvkycjlukxits2u5i2sjyca7td5sc6/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/xextproto-7.3.0-b5xvu77tm3zc5ha53u5b2ucztgvnoaoy/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/sqlite-3.22.0-su5rw6jtml2wef2pw72daixr5f7gbrcn/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/libx11-1.6.5-zhz54tmxc7bbg74jjjd4bbvekvraqzjg/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/ncurses-6.0-2n7s6ueyh6ftthpyizeum654ezasc65l/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/kbproto-1.0.7-2yqsfo2aqkdqpzcbnpqomoxykt33q2bq/lib/pkgconfig:/home/francois/spack/opt/spack/linux-fedora27-x86_64/gcc-7.3.1/libpng-1.6.34-pg2y2p2rweggf5gkdkqlnf5lwqlavlql/lib/pkgconfig
```

Reorganizing this string to remove the shared prefix and make the contents more apparent:
```
libxcb-1.13-iqekgfrzkx62mzsgn4cxw5u7emhcw2ls/lib/pkgconfig
libpthread-stubs-0.4-xqcgs6542x43dyfeb23yh72nifpdccg5/lib/pkgconfig
python-2.7.14-belgizkwgkpujlt5kj2ukdfemba65kpf/lib/pkgconfig
tcl-8.6.8-tzm3mv33jghcscgodkfvp66ump44zvjv/lib/pkgconfig
pkgconf-1.4.0-y7htlzbrinrly6rckw7facn5unpgt2va/lib/pkgconfig
tk-8.6.8-ejbnysmaubvfx5kdft6apllg3v2eecuc/lib/pkgconfig
libxau-1.0.8-kcpuyfbymgkpanr3xwi3wiokifjdguwf/lib/pkgconfig
libxdmcp-1.1.2-jd3zri4v4ua77ygvq5xnqyspurvictyl/lib/pkgconfig
zlib-1.2.11-y5oiya3aolzfqr475pqosgwe4eeqpqta/lib/pkgconfig
freetype-2.7.1-7fvthrfrhhzlfiotzb2yuimarnuku63b/lib/pkgconfig
xproto-7.0.31-gcmvkycjlukxits2u5i2sjyca7td5sc6/lib/pkgconfig
xextproto-7.3.0-b5xvu77tm3zc5ha53u5b2ucztgvnoaoy/lib/pkgconfig
sqlite-3.22.0-su5rw6jtml2wef2pw72daixr5f7gbrcn/lib/pkgconfig
libx11-1.6.5-zhz54tmxc7bbg74jjjd4bbvekvraqzjg/lib/pkgconfig
ncurses-6.0-2n7s6ueyh6ftthpyizeum654ezasc65l/lib/pkgconfig
kbproto-1.0.7-2yqsfo2aqkdqpzcbnpqomoxykt33q2bq/lib/pkgconfig
libpng-1.6.34-pg2y2p2rweggf5gkdkqlnf5lwqlavlql/lib/pkgconfig
```

**Comment by scheibelp** [comment] 2018-04-30 23:10
Thanks for the extra info @fmahebert 

For the time being, adding the following to packages.yaml may help you build:

```
packages:
...
  pkg-config:
    buildable: False
    paths:
      pkg-config: /usr/
  pkgconf:
    buildable: False
```

I'm still looking into why this is the case, but the Spack-built `pkgconf` (and `pkg-config` as well) omits the `freetype` include directory, which is used by `setupext.py` in `matplotlib`. Interestingly, if I set `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1` it keeps the `freetype` include directory. The system `pkg-config` did not appear to have this issue, so that's why I suggest it above.

I'm going to continue looking at this, but likely won't have any updates until tomorrow evening.

**Comment by scheibelp** [comment] 2018-05-02 22:02
Update: not finished yet, but I understand the problem better.

Recent versions of pkgconfig (and presumably pkgconf) check `CPATH` as part of system include paths. Generally Spack unsets `CPATH` but allows package-specific updates to `CPATH` after clearing it. https://github.com/spack/spack/pull/7818 updates `CPATH` for `freetype` specifically (presumably to help some other package that isn't `py-matplotlib` build).

I'll have to think up some way to generally handle this: perhaps Spack should be updated to unset CPATH completely when `pkg-config` is run (although it would have to avoid doing that if `dirty` is set). If e.g. the system pkg-config version is >= `0.29.2` my above suggestion to set it as an external will not likely work (see: https://lists.freedesktop.org/archives/pkg-config/2017-March/001084.html).

**Comment by jrood-nrel** [comment] 2018-05-08 02:33
Just chiming in to say I'm seeing this as well.

**Comment by scheibelp** [comment] 2018-05-08 02:43
I'm planning on having a longer term fix available in a PR in the next two days: by 5/9.

**Comment by azukaitis** [comment] 2018-05-08 04:41
that's great!  Thanks!

**Comment by s-sajid-ali** [comment] 2018-06-12 01:20
Are the fixes for this still WIP ? I'm trying to build matplotlib with ipython support for python 3 and it would be great if the fix for this is merged.

**Comment by scheibelp** [comment] 2018-06-13 23:57
Hi @s-sajid-ali, I'd say that https://github.com/spack/spack/pull/8136 is no longer WIP but it is pending a review before merging.

**Comment by s-sajid-ali** [comment] 2018-06-14 00:19
No problem! 

One more thing I wanted to ask regarding matplotlib was regarding the qhull dependency. For some reason matplotlib tries to build qhull even though qhull is already installed. Does this also have something to the pkg-config ?

This re-building is fine with gcc but causes an issue with icc as described [here](https://github.com/spack/spack/issues/8303). Qhull is already patched in spack, but matplotlib doesn't pick up the patches. 

I suspect that this is coming from : 
```
                 qhull: yes [pkg-config information for 'libqhull' could not
                        be found. Using local copy.]
```

**Comment by scheibelp** [comment] 2018-06-16 01:36
@s-sajid-ali this appears to be a separate problem: `qhull` does not create a `.pc` file for `pkg-config` to find, see also `https://github.com/matplotlib/matplotlib/issues/5745` (I formatted the URL in that way to avoid cluttering that thread). Further discussion on this should likely move to its own issue.

**Comment by briedel** [comment] 2018-07-10 17:40
Seeing this issue as well... Is there an ETA for this?

**Comment by s-sajid-ali** [comment] 2018-07-10 17:42
@briedel  :  There's a WIP PR that fixes this (qhull issue) at ```https://github.com/spack/spack/pull/8594```

**Comment by nrichart** [comment] 2018-09-07 13:37
It seams to be a bug with `pkg-config@0.29.2`
```
$ pkg-config --cflags freetype2
-I/softs/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/zlib-1.2.11-5nus6knzumx4ik2yl44jxtgtsl7d54xb/include -I/softs/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/libpng-1.6.34-a5oblht5r7sql6oimuiq3cn2w4kaikqp/include/libpng16 -I/softs/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/freetype-2.7.1-dmpx2kzjsnfr6h3kgkvbco2c4o5kly7n/include/freetype2
```

**Comment by nrichart** [comment] 2018-09-07 13:41
Sorry that was a mis click, I thought I found the culprit in pkgconf since by imposing pkg-config as a dependency it installed but I could not reproduce my observation will wanting to write the comment.

And I miss clicked "close"...

In case it helps I still give my observation. pkg-config --cflags freetype2 was not giving the correct output

And with `py-matplotlib^pkg-config` it worked fine

**Closed** 2019-02-13 23:38 UTC
Labels: build-error
