### ISSUE TITLE
gcc package does not include 'cc'

### ISSUE THREAD

**Issue by sknigh** [spack/spack#3884] opened 2017-04-18 15:49 UTC
I had a user's build fail because their configure script searched for ```cc```, was unable to find it in the gcc package, and scooped up ```/usr/bin/cc```. On most linux systems, ```cc``` and ```cxx``` are symbolic links the to a local compiler installation.

**Comment by adamjstewart** [comment] 2017-04-18 15:59
I'm actually surprised it didn't find the `cc` in `spack/lib/spack/env` first. I thought that was in the `PATH`. But this problem isn't specific to `gcc`, it affects all compilers. For most packages like this, we hack the package to look for the correct compiler name. This normally involves editing a `Makefile`. I don't think I've ever seen `configure` do the wrong thing.

**Comment by sknigh** [comment] 2017-04-18 16:01
They weren't using spack's environment, they were using environment modules to load a gcc compiler.

**Comment by adamjstewart** [comment] 2017-04-18 16:09
Ooh, I see what you're saying. The problem is that the `gcc` package doesn't install a `cc` symlink. You could tell them to specify their compiler:
```
$ ./configure CC=gcc CXX=g++
```
or we could talk about adding our own symlinks to the `gcc` package. I'm not opposed to the latter.

**Comment by citibeth** [comment] 2017-04-18 19:47
I would lean against adding our own symlinks.  The standard GCC package installs a program called `gcc`, not `cc`.  Whatever configure script was used here was clearly not a standard Autotools script.  Upstream authors who want their software to be buildable with gcc should really make it possible to configure using a compiler named `gcc`.  I don't think we (Spack) should try to cover for every problematic upstream build process.

**Comment by citibeth** [comment] 2017-04-18 19:48
For comparison, consider a Python-based ball of software that expects a Python3 executable named `python`.  Again... although *some* systems create such an executable, it is not part of how the standard Python distro works.

**Comment by sknigh** [comment] 2017-04-18 20:01
If changing ```cc``` is a bad idea, then why do it ```spack/lib/spack/env```? Generating a module that results in parts of the environment pointing to different compilers is tricky for build systems. 

Would a change to the module file generation to set ```CC``` and ```CXX``` be better?

**Comment by adamjstewart** [comment] 2017-04-18 20:02
> Would a change to the module file generation to set `CC` and `CXX` be better?

I would support that change.

**Comment by citibeth** [comment] 2017-04-18 20:03
> If changing ```cc``` is a bad idea, then why do it ```spack/lib/spack/env```?

Good question for @tgamblin.  But in general.. `lib/spack/env` is a hack that is used only within Spack and not exposed to the user.  And it does not affect the actually GCC install directory.

> Would a change to the module file generation to set ```CC``` and ```CXX``` be better?

Yes, I think so.  That makes a LOT of sense to me.

**Comment by tgamblin** [comment] 2017-04-18 22:55
> I had a user's build fail because their configure script searched for cc, was unable to find it in the gcc package.

This is kind of odd -- I believe most configure scripts will search the `PATH` for `gcc` first, and only revert to `cc` if nothing else is available.  See [`AC_PROG_CC`](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/C-Compiler.html).

> If changing `cc` is a bad idea, then why do it spack/lib/spack/env? Generating a module that results in parts of the environment pointing to different compilers is tricky for build systems.

We use compiler wrappers to make it easy to find dependencies, swap compilers, build with `RPATHs`, and to inject compiler flags into builds.  We'd also like Spack to one day be a vehicle for injecting things like LLVM thread sanitizers and other instrumentation tools into complex builds.  Without the compiler wrappers that's hard.

We use `cc` as the name of the *wrapper script* because it's a generic name for a C compiler.  I don't believe `cc` is actually guaranteed to be any particular compiler; it's just a convention (AFAICT it's not part of POSIX).  Most build systems will prefer to find a known, named compiler.

Many build systems are also sensitive to the compiler name, e.g. `libtool` will deduce incorrect linker arguments for non-gcc compilers if they're called `cc` instead of some more specific name (see #255).  So, we actually *don't* point to `cc` in the build environment anymore -- `CC`, `CXX`, etc. are set to point to the various more specifically named symlinks in subdirectories of `lib/spack/env`.  `cc` is there just as a fallback, and as a convenient way for people patching Makefiles directly to get the compiler wrapper script into the Makefile without having to think about the compiler name.

We try to keep the run environment more vanilla and, so we definitely don't inject all the same things there as we do at build time.  The spack compiler wrappers want to know things like where their dependencies live, so they're really not suited to generic builds -- they're designed to make a single package build easy.

Setting `CC`, `CXX`, and `FC` in the modules for `gcc` and `clang` seems reasonable -- I'm pretty sure some sites do this.    I don't think we have a good reason not to -- we avoid paths like `LIBRARY_PATH` and `CPATH` because they can cause issues with build systems (e.g., they can cause `CMake` to get `CMAKE_<lang>_IMPLICIT_LINK_LIBRARIES` wrong), but I can't remember seeing `CC` and `CXX` cause problems.

@sknigh: want to [add this to `run_env` in setup_environment](https://spack.readthedocs.io/en/latest/module_file_support.html#package-file-api) in the `gcc` and `clang` packages?

**Comment by citibeth** [comment] 2017-04-18 23:44
On Tue, Apr 18, 2017 at 6:55 PM, Todd Gamblin <notifications@github.com>
wrote:

> I had a user's build fail because their configure script searched for cc,
> was unable to find it in the gcc package.
>
> This is kind of odd -- I believe most configure scripts will search the
> PATH for gcc first, and only revert to cc if nothing else is available.
> See AC_PROG_CC
> <https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/C-Compiler.html>
> .
>

My guess is it's probably not an Autotools build.

**Comment by mplegendre** [comment] 2017-04-19 01:00
We recently hit this problem with our Spack produced gcc's on our RHEL7 systems.  In that case it was cmake trying to find a 'cc' compiler, and going right past the spack-built gcc in PATH and straight to the system version that had a cc link.

In our case we made the decision that the 'cc' was necessary, and have been manually adding it as a symlink to our Spack-produced gcc builds.

**Comment by citibeth** [comment] 2017-04-19 01:19
Did you try setting the CC env var or CMAKE_C_COMPILER CMake var?

**Comment by tgamblin** [comment] 2017-04-19 16:00
Given @mplegendre's comment, I guess the question is what we should try to enforce.  All of these issues are cases where the user is *not* specifying the compiler explicitly, but Spack's `gcc` is on the `PATH`.  

Should we take steps beyond what build systems do to ensure that Spack-build compilers are detected when they're on a user's `PATH`:
    a. when the package's module is loaded?
    b. regardless of whether the module is loaded?

We can handle (a) pretty easily -- I think setting `CC` should be sufficient.  (b) would require a symlink from `gcc` to `cc`.  

I actually don't think (b) will hurt anything as long as you're using `gcc` out of its own `PATH`.  It will cause conflicts if you try to link multiple `gcc`'s into a single prefix, as with `spack view`, but that's not altogether bad -- we will see this more as we move to environments and we would probably just add `cc` to a per-package ignore list to prevent it from being linked into an environment.

I don't personally have a strong preference on this.  I do think that users should always specify the compiler they want explicitly when they build, since we're not going to be able to solve this stuff in all cases. 😄

**Comment by tgamblin** [comment] 2017-04-19 16:01
@sknigh: RE: title of this post: I have not seen any systems that install an alias called `cxx`.  On my mac and on linux systems I know of, there is a `c++` program.  Is that what you meant?

**Comment by sknigh** [comment] 2017-04-19 17:26
I removed the ```cxx``` from the title, I double checked my environment and did not see that symlink; nor was it part of my user's original problem.

**Comment by alalazo** [comment] 2017-11-23 11:45
Closed in #3954

**Closed by alalazo** 2017-11-23 11:45 UTC
Labels: compilers, modules
