### ISSUE TITLE
setup-env.sh causes problems on SLES11 Supercomputer

### ISSUE THREAD

**Issue by citibeth** [spack/spack#8425] opened 2018-06-08 03:14 UTC
Sourcing `setup-env.sh` causes errors on our SLES11 supercomputer.

### Expected Result

No Error, and things "just work"

### Actual Result

1. Error running the script:
```
rpfische@discover17:~> source $HOME/spack6/share/spack/setup-env.sh
-bash: _sp_sys_type=linux-suse_linux11-x86_64: command not found
```

2. Adds `/` to the front of `MODULEPATH`, which causes all kinds of problems (it breaks `module avail`):
```
echo $MODULEPATH
/:/usr/local/share/modules/modulefiles.slurm:/usr/local/share/modules/modulefiles.vis:/usr/local/other/modules/modulefiles:/home/rpfische/spack6/share/spack/modules/linux-suse_linux11-x86_64
```
### Steps to reproduce the issue

```console
$ source $HOME/spack6/share/spack/setup-env.sh
```

### Information on your system

1. SLES11
2. All sorts of other unknown (to me) configurations.

**Comment by g-mathias** [comment] 2018-07-17 09:58
I could reproduce your problem on SuperMUC (SLES11SP4). It seem to be the old python version  (2.6.9).
Loading a python@2.7: fixes the problem, on SuperMUC eg.
module load python/2.7_intel
Both the command not found error and the /: in MODULEPATH are gone.

**Comment by citibeth** [comment] 2018-07-17 13:34
@scheibelp Does Spack support running on Python 2.6?  If so, then this looks like a bug that should be addressed.

**Comment by g-mathias** [comment] 2018-07-17 17:22
spack.pdf says:
<cite>Spack has the following minimum requirements, which must be installed before Spack is run:
1.  Python 2 (2.6 or 2.7) or 3 (3.3 - 3.6)
</cite>
but the problem seems to be rather subtle.

The actual problem is:
```
set -vx
. share/spack/setup-env.sh
...
 _assignment_command=$(spack-python -c "exec('${_python_command}')") spack-python -c "exec('${_python_command}')"
+++ spack-python -c 'exec('\''print(\'\''_sp_sys_type={0}\'\''.format(spack.architecture.sys_type()))\nprint(\'\''_sp_dotkit_root={0}\'\''.format(spack.util.path.canonicalize_path(
++ _assignment_command='ESC[?1034h_sp_sys_type=linux-sles11-x86_64```
```
google for the escape sequence yields:

https://community.cloudera.com/t5/Interactive-Short-cycle-SQL/Funny-characters-in-output-file-from-Impala-shell/td-p/24902

on SuperMUC:
```
> echo $TERM                                                                                                                                                      
xterm-256color
```         
setting
```
> export TERM=linux
```
fixes the problem.
Maybe somebody has an idea how to fix the issue in setup-env.sh .

**Comment by alalazo** [comment] 2022-03-10 09:43
Support for Python 2.6 was removed after v0.17 Closing this issue.

**Closed by alalazo** 2022-03-10 09:43 UTC
Labels: bug, python, shell-support
