### ISSUE TITLE
emacs build error unsatisfied contraint meson with incompatible python

### ISSUE THREAD

**Issue by OH-AU** [spack/spack#9979] opened 2018-11-29 04:22 UTC
### Steps to reproduce the issue
Spack version = 0.12.0

Think issue might be similar/realted to #9099 in some regards. Hopefully not a duplicate.

```console
$ spack install emacs+X
==> Error: An unsatisfiable version constraint has been detected for spec:
    python@2.7.15%gcc@7.3.0
while trying to concretize the partial spec:
    meson
meson requires python version 3:, but spec asked for 2.7.15
... # and the relevant part of the error message
```
as far as i can tell the issue appears to be further down the tree, at least atk and gtkplus have the same issue? 

```commandline
Linux build-02-cdc 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Description:	Ubuntu 18.04.1 LTS
``` 

### Additional information

Installing with emacs+X^python3 later failed with problems finding libatspi.so.0 (below)
Re original issue - reporting as I assume default packages + basic variants should just work.
It would also appear gtkplus is missing an at-spi2-core dependency in this case:
  >> 1176    /tmp/username/spack-stage/spack-stage-_9krypmg/gtk+-3.20.10/gtk/tmp-introspectscg70p_2/.libs/Gtk-3.0: error while loading shared libraries: libatspi.so.0: cannot open shared object file: No such file or directory.

```comandline
5 errors found in build log:
     1170      CCLD     libgtk-3.la
     1171      CCLD     gtk-launch
     1172      CCLD     gtk-query-settings
     1173      CCLD     gtk-query-immodules-3.0
     1174      GISCAN   Gtk-3.0.gir
     1175      CCLD     gtk-builder-tool
  >> 1176    /tmp/username/spack-stage/spack-stage-qbkdg18_/gtk+-3.20.10/gtk/tmp-introspectuer6a5ha/.libs/Gtk-3.0: error while loading shared libraries: libatspi.so.0: cannot open shared object file: No such file or directory
     1177    gtkentry.c:2046: Warning: Gtk: multiple comment blocks documenting 'GtkEntry:inner-border:' identifier (already seen at gtkentry.c:876).
     1178    gtkcsssection.h:69: Warning: Gtk: multiple comment blocks documenting 'GtkCssSection:' identifier (already seen at gtkcsssection.c:25).
     1179    Command '['/tmp/username/spack-stage/spack-stage-qbkdg18_/gtk+-3.20.10/gtk/tmp-introspectuer6a5ha/Gtk-3.0', '--introspect-dump=/tmp/username/spack-stage/spack-stage-qbkdg18_/gtk+-3.20.10/gtk/tmp-introspectuer6a5ha/functions.txt,/t
             mp/username/spack-stage/spack-stage-qbkdg18_/gtk+-3.20.10/gtk/tmp-introspectuer6a5ha/dump.xml']' returned non-zero exit status 127.
     1180    /apps_spack/gobject-introspection/1.49.2-gcc-7.3.0-ujuaf57zsyo2dm52h2j2qdveghltjcg7/share/gobject-introspection-1.0/Makefile.introspection:155: recipe for target 'Gtk-3.0.gir' failed
  >> 1181    make[3]: *** [Gtk-3.0.gir] Error 1
     1182    make[3]: Leaving directory '/tmp/username/spack-stage/spack-stage-qbkdg18_/gtk+-3.20.10/gtk'
     1183    Makefile:2421: recipe for target 'all' failed
  >> 1184    make[2]: *** [all] Error 2
     1185    make[2]: Leaving directory '/tmp/username/spack-stage/spack-stage-qbkdg18_/gtk+-3.20.10/gtk'
     1186    Makefile:721: recipe for target 'all-recursive' failed
  >> 1187    make[1]: *** [all-recursive] Error 1
     1188    make[1]: Leaving directory '/tmp/username/spack-stage/spack-stage-qbkdg18_/gtk+-3.20.10'
     1189    Makefile:615: recipe for target 'all' failed
  >> 1190    make: *** [all] Error 2
```
Don't have the knowledge as yet to dig through this one. Left it as one ticket as I feel they're related? Thanks.

**Comment by JSquar** [comment] 2018-12-03 23:07
I could not reproduce your error with libatspi.so.0, running `spack install emacs+X^python@3:` worked fine for me. Maybe try a fresh spack install?

**Comment by citibeth** [comment] 2018-12-13 17:49
Could the techniques in #7926 be used to successfully address your problem?

**Comment by alalazo** [comment] 2020-11-02 15:37
Duplicate of #1781

**Comment by alalazo** [comment] 2020-11-02 15:37
Not an issue anymore, but I suspect this was due to #1781 when Python 2.7.15 was still the default.

**Closed by alalazo** 2020-11-02 15:37 UTC
Labels: build-error, concretization
