### ISSUE TITLE
can't use existing glib due to variant change

### ISSUE THREAD

**Issue by baberlevi** [spack/spack#10576] opened 2019-02-12 20:55 UTC
I have an existing R install that I'd like to continue to use as a dependency for new R packages.

My install of R depends on cairo, which depends on glib.

The version of glib I have was installed pre #9481, and the default tracing variant of '' was used. None is no longer a valid variant choice for tracing, so spack doesn't want to let me re-use the existing dependency.

### Error Message
```
==> Error: invalid values for variant "tracing" in package "glib": ['']
```

I've read through the conversation on #9481, and don't see anything that talks about this as an expected outcome, so I assume it was overlooked.

**Comment by baberlevi** [comment] 2019-02-12 21:06
Tagging @alalazo as author of related PR

**Comment by alalazo** [comment] 2019-02-12 21:18
I suspect this might be a duplicate of #3515 (long standing bug) - will have a closer look tomorrow.

**Comment by alalazo** [comment] 2023-04-05 18:53
Closing this as outdated - using an empty string as a variant has long been forbidden.

**Closed by alalazo** 2023-04-05 18:53 UTC
Labels: bug
