### ISSUE TITLE
Cannot Uninstall Package from Environment

### ISSUE THREAD

**Issue by citibeth** [spack/spack#10331] opened 2019-01-12 22:38 UTC
I've installed `python` inside an environment.  I'm not able to uninstall from within my environment.  And I'm not able to uninstall from "plain vanilla Spack" either.

### Steps to reproduce the issue

```console
$ alias spack
alias spack='spack -e otp-dev-mac'
$ spack find
==> In environment otp-dev-mac
==> Root specs
environment-modules  maven  osmctools  postgresql  py-mysql-connector  py-setuptools  python

==> 16 installed packages
-- darwin-highsierra-x86_64 / clang@9.0.0-apple -----------------
bzip2@1.0.6                 jdk@1.8.0_191  openssl@1.0.1h   py-mysql-connector@8.0.13  readline@7.0   zlib@1.2.11
environment-modules@3.2.10  maven@3.5.0    osmctools@0.9    py-setuptools@40.4.3       sqlite@3.26.0
gdbm@1.18.1                 ncurses@6.1    postgresql@10.3  python@3.6.5               tcl@8.6.8
$ spack uninstall python
==> Will not uninstall python@3.6.5%clang@9.0.0-apple/osojvpu
The following packages depend on it:
    -- darwin-highsierra-x86_64 / clang@9.0.0-apple -----------------
    qkjr5wm py-mysql-connector@8.0.13%clang
    vuarrj6 py-setuptools@40.4.3%clang

==> Error: There are still dependents.
  use `spack uninstall --dependents` to remove dependents too
$ spack uninstall --dependents python
==> The following packages will be uninstalled:

    -- darwin-highsierra-x86_64 / clang@9.0.0-apple -----------------
    qkjr5wm py-mysql-connector@8.0.13%clang
    vuarrj6 py-setuptools@40.4.3%clang
    osojvpu python@3.6.5%clang+dbm~optimizations patches=123082ab3483ded78e86d7c809e98a804b3465b4683c96bd79a2fd799f572244 +pic+pythoncmd~shared~tk~ucs4
==> Do you want to proceed? [y/N] y
==> Error: 'vuarrj6tr5yxov5cercjbre6fsxfauck'
$ \spack uninstall --dependents python
==> Will not uninstall python@3.6.5%clang@9.0.0-apple/osojvpu
The following packages depend on it:
    -- darwin-highsierra-x86_64 / clang@9.0.0-apple -----------------
    qkjr5wm py-mysql-connector@8.0.13%clang
    vuarrj6 py-setuptools@40.4.3%clang
    yufk7lh py-wheel@0.29.0%clang
It is used by the following environments:
    otp-dev-mac

==> Error: There are still dependents.
  use `spack uninstall --dependents` to remove dependents too
  use `spack env remove` to remove from environments
```

### Error Message

See above... Spack gives different excuses at different times for not uninstalling.

**Comment by citibeth** [comment] 2019-01-12 22:40
This seems to be a problem specific to `py-setuptools`, not Spack Environments per se.

```
$ spack uninstall --dependents py-setuptools
==> The following packages will be uninstalled:

    -- darwin-highsierra-x86_64 / clang@9.0.0-apple -----------------
    vuarrj6 py-setuptools@40.4.3%clang
==> Do you want to proceed? [y/N] y
==> Error: 'vuarrj6tr5yxov5cercjbre6fsxfauck'
```

See stacktrace:

```
Traceback (most recent call last):
  File "/Users/citibob/spack/otp/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/Users/citibob/spack/otp/lib/spack/spack/main.py", line 669, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/citibob/spack/otp/lib/spack/spack/main.py", line 440, in _invoke_command
    return_val = command(parser, args)
  File "/Users/citibob/spack/otp/lib/spack/spack/cmd/uninstall.py", line 335, in uninstall
    args, spack.cmd.parse_specs(args.packages) if args.packages else [any])
  File "/Users/citibob/spack/otp/lib/spack/spack/cmd/uninstall.py", line 325, in uninstall_specs
    do_uninstall(env, uninstall_list, args.force)
  File "/Users/citibob/spack/otp/lib/spack/spack/cmd/uninstall.py", line 213, in do_uninstall
    _remove_from_env(item, env)
  File "/Users/citibob/spack/otp/lib/spack/spack/cmd/uninstall.py", line 189, in _remove_from_env
    env.remove(spec, force=True)
  File "/Users/citibob/spack/otp/lib/spack/spack/environment.py", line 554, in remove
    del self.specs_by_hash[dag_hash]
KeyError: 'vuarrj6tr5yxov5cercjbre6fsxfauck'
```

**Comment by citibeth** [comment] 2019-01-12 22:46
I "fixed" this (at least for now), by hacking the lines in `environment.py` adding a try-except around one statement:
```
                try:
                    del self.specs_by_hash[dag_hash]
                except KeyError:
                    pass
```

**Comment by alalazo** [comment] 2022-03-10 10:45
Closing as I can't reproduce the issue anymore (so I assume it was fixed). Feel free to open a new issue if the problem persist.

**Closed by alalazo** 2022-03-10 10:45 UTC
Labels: bug, environments
