### ISSUE TITLE
shiny-server installation: unsatisfiable variant constraint

### ISSUE THREAD

**Issue by Sinan81** [spack/spack#8359] opened 2018-06-03 03:05 UTC
unsatisfiable constraint due to different variants of pcre, which is a dependency of "r" as well as "git"
### Expected Result
Package installs

### Actual Result
```console
user@host /spack (develop) $ git pull
Already up-to-date.
user@host /spack (develop) $ spack install shiny-server
==> Error: An unsatisfiable variant constraint has been detected for spec:

    pcre@8.42%gcc@5.4.0~jit+utf arch=linux-linuxmint18-x86_64 


while trying to concretize the partial spec:

    git@2.17.1%gcc@5.4.0 arch=linux-linuxmint18-x86_64 


git requires pcre variant +jit, but spec asked for ~jit

```

### Steps to reproduce the issue

See above

### Information on your system
Linux, x86_64

**Comment by Sinan81** [comment] 2018-11-13 03:35
A workaround is to use git versions <=2.13 where pcre dependency doesn't require jit variant:
````
spack install shiny-server ^git@2.13.0
````

**Comment by alalazo** [comment] 2019-12-17 13:18
@Sinan81 I think this is yet another symptom of the greedy concretizer. A way to build with recent versions of `git` is to help the solver algorithm:
```console
$ spack spec shiny-server ^pcre+jit
```

**Comment by Sinan81** [comment] 2019-12-17 22:46
That is a better definitely a better solution than downgrading git. Thanks! As far as I am concerned, this issue can be closed as these kind of issues will be resolved with the new concretizer.

**Comment by alalazo** [comment] 2020-11-01 22:10
Duplicate of #5465

**Comment by alalazo** [comment] 2020-11-01 22:10
See https://github.com/spack/spack/issues/5465#issuecomment-720154305

**Closed by alalazo** 2020-11-01 22:10 UTC
Labels: bug, concretization
