### ISSUE TITLE
Adding @when annotation for Cray gives  "Error: spack requires modulecmd.  Make sure it is in your path"

### ISSUE THREAD

**Issue by pramodk** [spack/spack#1990] opened 2016-10-11 07:26 UTC
Hello All,

If I add cray arch specific install method in “any” package, then I get error:

``` bash
./bin/spack spec hdf5 ^mpich
Input spec
------------------------------
  hdf5
      ^mpich

Normalized
------------------------------
==> Error: spack requires modulecmd.  Make sure it is in your path.
```

Simple way to reproduce this is to add dummy method in package, for example:

``` bash
diff --git a/var/spack/repos/builtin/packages/hdf5/package.py b/var/spack/repos/builtin/packages/hdf5/package.py
index c0635cf..6260384 100644
--- a/var/spack/repos/builtin/packages/hdf5/package.py
+++ b/var/spack/repos/builtin/packages/hdf5/package.py
@@ -147,6 +147,10 @@ class Hdf5(Package):
         make("install")
         self.check_install(spec)

+    @when('arch=cray-CNL-sandybridge')
+    def install(self, spec, prefix):
+        print "cray install!"
```

And now you run spack command. I am able to reproduce this on local desktop.

**Comment by becker33** [comment] 2017-06-26 22:36
@pramodk Is this bug still manifesting? I recently changed the logic around modulecmd, hopefully it is fixed now.

**Comment by pramodk** [comment] 2017-07-02 18:40
@becker33 : I am testing with develop and don't see the error. But I am confused with below behaviour : 

I have simple package where I specified install method as:

```
    @when('arch=cray-CNL-mic_knl')
    def install(self, spec, prefix):
        print "Cray install!"

    def install(self, spec, prefix):
        print "Regular Install"
```

I am building on Cray system where I see:
```
$ spack arch
cray-CNL-mic_knl
```
And the package is getting built for this architecture : 

```
$ spack spec mod2c
Input spec
--------------------------------
mod2c

Normalized
--------------------------------
mod2c
    ^cmake@2.8.12:

Concretized
--------------------------------
mod2c@develop%gcc@4.9.3 arch=cray-CNL-mic_knl
    ^cmake@3.5.2%gcc@4.9.3~doc+ncurses+openssl+ownlibs~qt arch=cray-CNL-mic_knl
```

But when I install package then it doesn't call arch specific install method : 

```
spack install -v mod2c
==> cmake@3.5.2 : externally installed in /usr
==> cmake@3.5.2 : already registered in DB
==> Installing mod2c
==> Already fetched /gp........pr/mod2c
==> No checksum needed when fetching with git
==> Already staged mod2c-de......ge/mod2c-develop-vb7wjjqu5w632gvbrsjrkdrugatrzdpr
==> Already patched mod2c
==> Building mod2c [Package]
==> Executing phase : 'install'
Regular Install
```

Anything I am missing obvious here?

**Comment by becker33** [comment] 2017-07-03 20:46
@pramodk What branch are you using? I see mod2c is not in develop, so I can't reproduce the error.

**Comment by pramodk** [comment] 2017-07-03 21:11
Ahh.. mod2c is local package that I have. I believe you could reproduce this issue with any other package (with arch specific install method).

**Comment by alalazo** [comment] 2017-11-22 08:56
@pramodk Is this still an issue?

**Comment by alalazo** [comment] 2018-04-08 08:26
Closing as there's been no reply in a while. Feel free to reopen if still an issue.

**Closed by alalazo** 2018-04-08 08:26 UTC
Labels: cray, modules
