### ISSUE TITLE
FastPackageChecker confused by .DS_Store file in Mac

### ISSUE THREAD

**Issue by naromero77** [spack/spack#5610] opened 2017-10-05 03:27 UTC
This seems to happen often on the Mac environment, in particular when you do a ctrl-break in the middle of the spack install.

Here is the sympton, any spack commands gives this error:
```
Traceback (most recent call last):
  File "/Users/naromero/spack/bin/spack", line 80, in <module>
    import spack.main  # noqa
  File "/Users/naromero/spack/lib/spack/spack/__init__.py", line 104, in <module>
    repo = spack.repository.RepoPath()
  File "/Users/naromero/spack/lib/spack/spack/repository.py", line 370, in __init__
    repo = Repo(root, self.super_namespace)
  File "/Users/naromero/spack/lib/spack/spack/repository.py", line 676, in __init__
    self._fast_package_checker = FastPackageChecker(self.packages_path)
  File "/Users/naromero/spack/lib/spack/spack/repository.py", line 122, in __init__
    self._paths_cache[packages_path] = self._create_new_cache()
  File "/Users/naromero/spack/lib/spack/spack/repository.py", line 146, in _create_new_cache
    tty.warn(msg.format(pkg_dir, pkg_name))
ValueError: unmatched '{' in format

```

This issues is caused by the presence of the .DS_Store file in this directory:
spack/var/spack/repos/builtin/packages/

The work around is trivial, simple remove the aforementioned .DS_Store file resolves the issue. But it quite confusing to run into this error for a user.

**Comment by alalazo** [comment] 2023-04-05 16:45
Duplicate of #12510

**Closed by alalazo** 2023-04-05 16:45 UTC
Labels: bug, macOS
