### ISSUE TITLE
Jupyter notebook fails to install

### ISSUE THREAD

**Issue by certik** [spack/spack#3345] opened 2017-03-03 18:23 UTC
```
[+] /home/certik/repos/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/py-jupyter-console-5.0.0-dm2s57qafex64yne4tbqm4rbsqsza2im
==> Fetching https://github.com/jupyter/notebook/archive/4.2.3.tar.gz
######################################################################## 100.0%
==> Staging archive: /home/certik/repos/spack/var/spack/stage/py-jupyter-notebook-4.2.3-rkbpngcvfiepja6w64zxwovymjw5ms4j/4.2.3.tar.gz
==> Created stage in /home/certik/repos/spack/var/spack/stage/py-jupyter-notebook-4.2.3-rkbpngcvfiepja6w64zxwovymjw5ms4j
==> No patches needed for py-jupyter-notebook
==> Building py-jupyter-notebook [PythonPackage]
==> Executing phase : 'build'
==> Error: ProcessError: Command exited with status 1:
    '/home/certik/repos/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/python-2.7.13-5gx5sb5s5ns2cmne3qwnl632omokfdqu/bin/python' 'setup.py' '--no-user-cfg' 'build'
/home/certik/repos/spack/lib/spack/spack/build_systems/python.py:110, in python:
     109      def python(self, *args):
  >> 110          inspect.getmodule(self).python(*args)

See build log for details:
  /home/certik/tmp/spack-stage/spack-stage-s7SfUD/notebook-4.2.3/spack-build.out

$ cat /home/certik/tmp/spack-stage/spack-stage-s7SfUD/notebook-4.2.3/spack-build.out
==> '/home/certik/repos/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/python-2.7.13-5gx5sb5s5ns2cmne3qwnl632omokfdqu/bin/python' 'setup.py' '--no-user-cfg' 'build'
running build
running build_py
running jsversion
running css
running jsdeps
installing build dependencies with npm
> npm install
/usr/bin/env: ‘node’: No such file or directory
rebuilding js and css failed. The following required files are missing: ['notebook/static/components', 'notebook/static/notebook/js/main.min.js', 'notebook/static/tree/js/main.min.js', 'notebook/static/edit/js/main.min.js', 'notebook/static/terminal/js/main.min.js', 'notebook/static/auth/js/main.min.js', 'notebook/static/style/ipython.min.css', 'notebook/static/style/style.min.css']
Traceback (most recent call last):
  File "setup.py", line 198, in <module>
    main()
  File "setup.py", line 195, in main
    setup(**setup_args)
  File "/home/certik/repos/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/python-2.7.13-5gx5sb5s5ns2cmne3qwnl632omokfdqu/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/certik/repos/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/python-2.7.13-5gx5sb5s5ns2cmne3qwnl632omokfdqu/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/certik/repos/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/python-2.7.13-5gx5sb5s5ns2cmne3qwnl632omokfdqu/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/certik/repos/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/python-2.7.13-5gx5sb5s5ns2cmne3qwnl632omokfdqu/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/home/certik/repos/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/python-2.7.13-5gx5sb5s5ns2cmne3qwnl632omokfdqu/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/certik/repos/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/python-2.7.13-5gx5sb5s5ns2cmne3qwnl632omokfdqu/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/certik/tmp/spack-stage/spack-stage-s7SfUD/notebook-4.2.3/setupbase.py", line 549, in run
    raise e
subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 127
```
I use Ubuntu 16.04 and installed using:
```
spack install -j16 py-jupyter-notebook %gcc@5.4.0
```

**Comment by tgamblin** [comment] 2017-03-03 18:46
@krafczyk

**Comment by krafczyk** [comment] 2017-03-03 18:50
Hmm strange.. Can you do `spack info py-jupyter-notebook` and `spack info npm` for me? node should have been installed as a build dependency.

**Comment by certik** [comment] 2017-03-03 18:53
```
$ spack info py-jupyter-notebook%gcc@5.4.0
PythonPackage:    py-jupyter-notebook
Homepage:         https://github.com/jupyter/notebook

Safe versions:  
    4.2.3    https://github.com/jupyter/notebook/archive/4.2.3.tar.gz
    4.2.2    https://github.com/jupyter/notebook/archive/4.2.2.tar.gz
    4.2.1    https://github.com/jupyter/notebook/archive/4.2.1.tar.gz
    4.2.0    https://github.com/jupyter/notebook/archive/4.2.0.tar.gz
    4.1.0    https://github.com/jupyter/notebook/archive/4.1.0.tar.gz
    4.0.6    https://github.com/jupyter/notebook/archive/4.0.6.tar.gz
    4.0.5    https://github.com/jupyter/notebook/archive/4.0.5.tar.gz
    4.0.4    https://github.com/jupyter/notebook/archive/4.0.4.tar.gz
    4.0.3    https://github.com/jupyter/notebook/archive/4.0.3.tar.gz
    4.0.2    https://github.com/jupyter/notebook/archive/4.0.2.tar.gz

Variants:
    Name        Default   Description

    terminal    off       Enable terminal functionality

Installation Phases:
    build    install

Build Dependencies:
    npm                  py-jinja2           py-nbconvert   py-tornado
    py-ipykernel         py-jupyter-client   py-nbformat    py-traitlets
    py-ipython-genutils  py-jupyter-console  py-setuptools  python
    py-ipywidgets        py-jupyter-core     py-terminado

Link Dependencies:
    python

Run Dependencies:
    py-ipykernel         py-jinja2           py-jupyter-core  py-terminado
    py-ipython-genutils  py-jupyter-client   py-nbconvert     py-tornado
    py-ipywidgets        py-jupyter-console  py-nbformat      py-traitlets

Virtual Packages: 
    None

Description:
    Jupyter Interactive Notebook
```

```
$ spack info npm%gcc@5.4.0                                     
AutotoolsPackage:    npm
Homepage:            https://github.com/npm/npm

Safe versions:  
    3.10.9    https://registry.npmjs.org/npm/-/npm-3.10.9.tgz
    3.10.5    https://registry.npmjs.org/npm/-/npm-3.10.5.tgz

Variants:
    None

Installation Phases:
    autoreconf    configure    build    install

Build Dependencies:
    node-js

Link Dependencies:
    node-js

Run Dependencies:
    None

Virtual Packages: 
    None

Description:
    npm: A package manager for javascript.
```

Node is indeed among modules installed by the above command:
```
node-js-7.1.0-gcc-5.4.0-qiwhfgc
npm-3.10.9-gcc-5.4.0-zl2kybi
```

**Comment by krafczyk** [comment] 2017-03-03 18:59
Okay, I think I know what the problem is,

Apparently `node-js` is not listed as a run dependency of `npm`. This means that it falls back on whatever `node` is installed on the system when it's used as a dependency itself.

patch incoming.

**Comment by certik** [comment] 2017-03-03 19:02
@krafczyk can you please ping me once you submit a patch? I'll try it out.

Thanks for figuring it out.

**Comment by JavierCVilla** [comment] 2017-04-24 11:52
What is the correct way to work around this bug while the patch is pending?

**Comment by krafczyk** [comment] 2017-04-24 15:59
You can try installing 'nodejs' in your system environment. This is how I didn't notice this bug in the first place. I had nodejs installed on my system, so it simply fell back to the system nodejs when it couldn't find the spack installed one. This would be a kludge quick fix for you.

**Comment by mikkokotila** [comment] 2017-04-28 07:01
I have this same issue when I'm trying to install from master (to overcome the --allow-root bug). I have installed npm and nodejs seems to be already installed, but I'm still getting the error. 

I have nodejs and npm installed and also separately installed bower through npm install.

I've reported this in #2375 which I just realized is closed. The error I get is this: 

`    │ │ └── uuid@3.0.1
    │ └── source-map@0.5.6
    └── requirejs@2.3.3
    
    > bower install --allow-root --config.interactive=false
    /usr/bin/env: ‘node’: No such file or directory
    rebuilding js and css failed. The following required files are missing: ['notebook/static/components', 'notebook/static/notebook/js/main.min.js', 'notebook/static/tree/js/main.min.js', 'notebook/static/edit/js/main.min.js', 'notebook/static/terminal/js/main.min.js', 'notebook/static/auth/js/main.min.js', 'notebook/static/style/ipython.min.css', 'notebook/static/style/style.min.css']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-tFpkxw-build/setup.py", line 199, in <module>
        main()
      File "/tmp/pip-tFpkxw-build/setup.py", line 196, in main
        setup(**setup_args)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "setupbase.py", line 577, in run
        raise e
    subprocess.CalledProcessError: Command '['bower', 'install', '--allow-root', '--config.interactive=false']' returned non-zero exit status 127
    
    ----------------------------------------
  Rolling back uninstall of notebook
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-tFpkxw-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-imy2QR-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-tFpkxw-build/`

**Comment by krafczyk** [comment] 2017-05-01 18:05
@mikkokotila Can you try to install `py-jupyter-notebook` with a clean spack from the current develop again and let me know if it succeeds this time?

I'm revisiting this issue, and I'm no longer able to reproduce the problem.

**Comment by davydden** [comment] 2018-06-25 17:07
@krafczyk @certik 

> I'm revisiting this issue, and I'm no longer able to reproduce the problem.

`py-jupyter-notebook` also builds for me on macOS with clang 9.1, although `spack activate py-jupyter-notebook` fails 😞

**Comment by hartzell** [comment] 2018-06-25 20:41
I've built it recently on CentOS 7 and Mac OS X (10.13.[45]).

If/when you get it built and working, I'd be curious if `jupyter-nbconvert` works.  I had trouble with it related to how `configparser` handles the `backports` namespace.  [Details here](https://gist.github.com/hartzell/0046187ead604e7ea31378a35375c61e).

**Comment by qhan1028** [comment] 2018-08-13 08:31
just install `git` before installing notebook.
`apt-get install -y git`

**Comment by alalazo** [comment] 2020-04-09 11:37
Closing since this doesn't seem an issue as of:
* **Spack:** 0.14.1-562-62cc815
* **Python:** 2.7.5
* **Platform:** linux-rhel7-skylake_avx512

```console
$ spack install py-notebook
[...]
  Fetch: 0.18s.  Build: 4.74s.  Total: 4.92s.
[+] /home/culpo/github/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/py-notebook-6.0.1-euningzsq3igqjaxkmdhy3id7eh5o7sy
```

**Closed by alalazo** 2020-04-09 11:37 UTC
Labels: build-error, new-package
