### ISSUE TITLE
Things not picked up from packages.yaml

### ISSUE THREAD

**Issue by citibeth** [spack/spack#660] opened 2016-03-27 16:09 UTC
## Problem 1

In packages.yaml, i have:

```
    python:
        version: [3.5.1]
```

And yet, the following does not pick it up:

```
$ spack spec py-cython
  py-cython@0.23.4%gcc@4.9.3=linux-x86_64
      ^python@2.7.11%gcc@4.9.3=linux-x86_64
          ^bzip2@1.0.6%gcc@4.9.3=linux-x86_64
          ^ncurses@6.0%gcc@4.9.3=linux-x86_64
          ^openssl@system%gcc@4.9.3=linux-x86_64
          ^readline@6.3%gcc@4.9.3=linux-x86_64
          ^sqlite@3.8.5%gcc@4.9.3=linux-x86_64
          ^zlib@1.2.8%gcc@4.9.3=linux-x86_64
```

Instead, I have to say `spack spec py-cython ^python@3:`.
## Problem 2

I also have in `packages.yaml`:

```
    all:
        providers:
            blas: [atlas]
            lapack: [atlas]
```

However, `spack spec py-numpy ^python@3:` does not pick that up either:

```
  py-numpy@1.10.4%gcc@4.9.3+blas+lapack=linux-x86_64
      ^openblas@0.2.17%gcc@4.9.3=linux-x86_64
      ^py-nose@1.3.6%gcc@4.9.3=linux-x86_64
          ^py-setuptools@19.2%gcc@4.9.3=linux-x86_64
              ^python@3.5.1%gcc@4.9.3=linux-x86_64
                  ^bzip2@1.0.6%gcc@4.9.3=linux-x86_64
                  ^ncurses@6.0%gcc@4.9.3=linux-x86_64
                  ^openssl@system%gcc@4.9.3=linux-x86_64
                  ^readline@6.3%gcc@4.9.3=linux-x86_64
                  ^sqlite@3.8.5%gcc@4.9.3=linux-x86_64
                  ^zlib@1.2.8%gcc@4.9.3=linux-x86_64
```

To get atlas, I have to say `spack spec py-numpy +blas+lapack ^python@3: ^atlas`

**Comment by mathstuf** [comment] 2016-04-27 19:26
See also #303.

**Comment by adamjstewart** [comment] 2016-07-26 18:10
Problem 2 has been solved, Problem 1 is still broken.

**Comment by becker33** [comment] 2017-03-09 00:57
Problem 2 does not appear to be resolved at this time.
```
$ more ~/.spack/packages.yaml
packages:
    all:
       providers:
            mpi: [spectrum-mpi, openmpi]
...

$ spack spec lulesh
...
lulesh@2.0.3%gcc@4.8.5~mpip arch=linux-rhel7-ppc64le 
  ^openmpi@2.0.2%gcc@4.8.5~java~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm+verb +vt arch=linux-rhel7-ppc64le
```

**Comment by alalazo** [comment] 2019-10-29 12:35
Using spack at 3cf21e6edc14e8431a0a65867a45df35aef1911e. Problem 1 seems to be solved:
```yaml
spack:
  specs:
  - py-cython
  packages:
    python:
      version: [3.5.1]
```
With the `spack.yaml` above:
```console
$ spack concretize
==> Concretized py-cython
 -   272wthh  py-cython@0.29.13%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
 -   5idrzfr      ^py-setuptools@41.4.0%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
 -   6ofrzik          ^python@3.5.1%gcc@9.0.1+bz2+ctypes+dbm+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-ubuntu18.04-broadwell
[+]  qdqkcwv              ^bzip2@1.0.8%gcc@9.0.1+shared arch=linux-ubuntu18.04-broadwell
[+]  mrptssh                  ^diffutils@3.7%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  fpz367q                      ^libiconv@1.16%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
 -   7onhxvp              ^expat@2.2.9%gcc@9.0.1+libbsd arch=linux-ubuntu18.04-broadwell
 -   nanvela                  ^libbsd@0.9.1%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  fklde6b              ^gdbm@1.18.1%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  urdw22a                  ^readline@8.0%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  leuzbbh                      ^ncurses@6.1%gcc@9.0.1~symlinks~termlib arch=linux-ubuntu18.04-broadwell
[+]  5vmfbrq                          ^pkgconf@1.6.3%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  4zep4o3              ^gettext@0.20.1%gcc@9.0.1+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu18.04-broadwell
[+]  7n6ho3b                  ^libxml2@2.9.9%gcc@9.0.1~python arch=linux-ubuntu18.04-broadwell
[+]  grthptm                      ^xz@5.2.4%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  os3djb5                      ^zlib@1.2.11%gcc@9.0.1+optimize+pic+shared arch=linux-ubuntu18.04-broadwell
[+]  fc2wypl                  ^tar@1.32%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
 -   n6x4ata              ^libffi@3.2.1%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  pksawhz              ^openssl@1.1.1d%gcc@9.0.1+systemcerts arch=linux-ubuntu18.04-broadwell
[+]  k3s2csy                  ^perl@5.30.0%gcc@9.0.1+cpanm+shared+threads arch=linux-ubuntu18.04-broadwell
 -   eisf7or              ^sqlite@3.30.1%gcc@9.0.1~column_metadata+fts~functions~rtree arch=linux-ubuntu18.04-broadwell
```

**Comment by alalazo** [comment] 2019-10-29 12:38
Problem 2 seems to be solved too:
```yaml
spack:
  specs:
  - py-numpy
  packages:
    all:
      providers:
        blas: [atlas]
        lapack: [atlas]
```
Concretizing the environment above I get:
```console
$ spack concretize
==> Concretized py-numpy
 -   juqqpa7  py-numpy@1.17.3%gcc@9.0.1+blas+lapack arch=linux-ubuntu18.04-broadwell
 -   dnlxbbw      ^atlas@3.10.3%gcc@9.0.1+shared threads=none tune_cpu=-1 arch=linux-ubuntu18.04-broadwell
 -   m3midf4      ^py-setuptools@41.4.0%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
 -   4zkul3b          ^python@3.7.4%gcc@9.0.1+bz2+ctypes+dbm+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-ubuntu18.04-broadwell
[+]  qdqkcwv              ^bzip2@1.0.8%gcc@9.0.1+shared arch=linux-ubuntu18.04-broadwell
[+]  mrptssh                  ^diffutils@3.7%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  fpz367q                      ^libiconv@1.16%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
 -   7onhxvp              ^expat@2.2.9%gcc@9.0.1+libbsd arch=linux-ubuntu18.04-broadwell
 -   nanvela                  ^libbsd@0.9.1%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  fklde6b              ^gdbm@1.18.1%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  urdw22a                  ^readline@8.0%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  leuzbbh                      ^ncurses@6.1%gcc@9.0.1~symlinks~termlib arch=linux-ubuntu18.04-broadwell
[+]  5vmfbrq                          ^pkgconf@1.6.3%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  4zep4o3              ^gettext@0.20.1%gcc@9.0.1+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu18.04-broadwell
[+]  7n6ho3b                  ^libxml2@2.9.9%gcc@9.0.1~python arch=linux-ubuntu18.04-broadwell
[+]  grthptm                      ^xz@5.2.4%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  os3djb5                      ^zlib@1.2.11%gcc@9.0.1+optimize+pic+shared arch=linux-ubuntu18.04-broadwell
[+]  fc2wypl                  ^tar@1.32%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
 -   n6x4ata              ^libffi@3.2.1%gcc@9.0.1 arch=linux-ubuntu18.04-broadwell
[+]  pksawhz              ^openssl@1.1.1d%gcc@9.0.1+systemcerts arch=linux-ubuntu18.04-broadwell
[+]  k3s2csy                  ^perl@5.30.0%gcc@9.0.1+cpanm+shared+threads arch=linux-ubuntu18.04-broadwell
 -   eisf7or              ^sqlite@3.30.1%gcc@9.0.1~column_metadata+fts~functions~rtree arch=linux-ubuntu18.04-broadwell
```

**Comment by alalazo** [comment] 2019-10-29 12:43
Closing as both problems seem to be solved based on the testing above. Also, it seems that since this issue was opened we added a few regression tests for preferences expressed in `packages.yaml` in `concretize_preferences.py`.

Anybody: feel free to reopen if there's something still to be addressed here.

**Closed by alalazo** 2019-10-29 12:43 UTC
Labels: bug, configuration
