### ISSUE TITLE
AutotoolsPackage Openmpi with clang on os x 

### ISSUE THREAD

**Issue by bvanessen** [spack/spack#6139] opened 2017-11-03 22:19 UTC
I was trying to build OpenMPI with clang-5.0.0 (installed from homebrew) on OS X and spack complained that it could not find m4, autoconf, automake, or libtool.  I solved this locally, by adding

  depends_on('m4')
    depends_on('autoconf')
    depends_on('automake')
    depends_on('libtool')

but I don't think that I should have.  It seems like the spack environment should have implicitly added these dependencies for AutotoolsPackages.

**Comment by scheibelp** [comment] 2017-11-03 23:02
Generally these are not required for all packages so `AutotoolsPackage` doesn't include them by default. There is some discussion at https://github.com/LLNL/spack/pull/2859 on this. Reading through it I don't see anything conclusively against adding them as default dependencies.

Is the failure occurring with `openmpi` specifically? Could you include the full spec? It will only complain about missing `m4` etc. if the configure script is missing and it tries to run `autoreconf`. When I pull version `3.0.0` it has a configure script. At least, I'm assuming your error message looked like:

`Cannot generate configure: missing dependencies`...

**Comment by bvanessen** [comment] 2017-11-03 23:05
I will try to reproduce the full spec when I have a chance.  I only encountered this with OpenMPI, when I was trying to build LBANN on OS X. I didn’t look to see if there were problems with other packages.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by adamjstewart** [comment] 2018-01-04 20:27
I just successfully built OpenMPI with Clang on macOS and didn't see this error. As @scheibelp mentioned, the error message you saw can only occur when you are trying to build a package that does not come with a `configure` script. Since the latest release of OpenMPI does have this script, I'm not sure how you could have seen this error. Either you modified the package to add a `develop` version, or it was actually another package that crashed. I'll close this issue for now, but if you figure out how to reproduce the problem, feel free to reopen.

**Closed by adamjstewart** 2018-01-04 20:27 UTC
Labels: build-error, macOS
