### ISSUE TITLE
Python extensions not using Spack-built dependences

### ISSUE THREAD

**Issue by lee218llnl** [spack/spack#2313] opened 2016-11-11 21:45 UTC
We have found that some Python extensions do not load their Spack-built extensions at load/runtime, which can lead to some version mismatch errors. Notably, this happened for rpy2 and for PyQt. In Rpy2, we saw the following:

[lee218@rzgenie2:~]$ python -m rpy2.tests                                       
During startup - Warning messages:                                              
1: package "methods" in options("defaultPackages") was not found                
2: package 'datasets' in options("defaultPackages") was not found               
3: package 'utils' in options("defaultPackages") was not found                  
4: package 'grDevices' in options("defaultPackages") was not found              
5: package 'graphics' in options("defaultPackages") was not found               
6: package 'stats' in options("defaultPackages") was not found                  
7: package 'methods' in options("defaultPackages") was not found                
rpy2 version: 2.5.6                                                             
- built against R version: 3-2.3--69752                                         
- running linked to R version: R version 3.2.3 (2015-12-10)                     
E                                                                               
======================================================================          
ERROR: __main__ (unittest.loader.LoadTestsFailure)                              
----------------------------------------------------------------------          
LookupError: 'show' not found                                                   

----------------------------------------------------------------------
Ran 1 test in 0.000s                                                  

FAILED (errors=1)

In PyQt, we saw this:

[lee218@rzgenie2:Incident1157989]$ python main-radiobuttons.py                                        
Cannot mix incompatible Qt library (version 0x40805) with this library (version 0x40806)                                                                        
Aborted (core dumped)             

In the case of R, the tests invoke R from one's PATH, so we were picking up /usr/bin/R. One could add the Spack-built R bin directory to $PATH to get around this issue. This could also be done by modifying os.environ["PATH"] from within rpy2's __init__.py script.

For the PyQt issue, it was loading /usr/lib64 Qt libraries, and one could add the Spack-built Qt lib directory to $LD_LIBRARY_PATH to get around this. However this would have to be set before invoking python and could not be done by modifying os.environ["LD_LIBRARY_PATH"] after python invocation. As a hack, I added the following to pyqt's __init__.py:

    import ctypes
    ctypes.cdll.LoadLibrary("/collab/usr/gapps/python/build/spack-toss3/opt/spack/toss_3_x86_64_ib/gcc-4.8.5/qt-4.8.6-3iv3jpmfiryyper2cf7nsctwqvba4zu3/lib/libQtNetwork.so.4")
    ctypes.cdll.LoadLibrary("/collab/usr/gapps/python/build/spack-toss3/opt/spack/toss_3_x86_64_ib/gcc-4.8.5/qt-4.8.6-3iv3jpmfiryyper2cf7nsctwqvba4zu3/lib/libQtXml.so.4")
    ctypes.cdll.LoadLibrary("/collab/usr/gapps/python/build/spack-toss3/opt/spack/toss_3_x86_64_ib/gcc-4.8.5/qt-4.8.6-3iv3jpmfiryyper2cf7nsctwqvba4zu3/lib/libQtDBus.so.4")
    ctypes.cdll.LoadLibrary("/collab/usr/gapps/python/build/spack-toss3/opt/spack/toss_3_x86_64_ib/gcc-4.8.5/qt-4.8.6-3iv3jpmfiryyper2cf7nsctwqvba4zu3/lib/libQtSvg.so.4")

I guess there is a wide range of ways this can be addressed in Spack, via modules, scripts, etc. I'm guessing that this problem may be more general and so I'd like to solicit other people's ideas on how we should handle this in Spack. Thoughts?

**Comment by adamjstewart** [comment] 2016-11-11 22:17
@citibeth has had several interesting suggestions as to how to RPATH Python modules.

**Comment by citibeth** [comment] 2016-11-12 02:40
Yes, RPATH is not compiled into Python modules; see #1927 for an outline of how this could (should) be done in the future (when someone gets a round toit).

As a workaround, you can use `spack module loads -r` to generate the load commands for all the dependencies you need.  For example, `spack module loads -r py-basemap`.

**Comment by lee218llnl** [comment] 2016-11-21 18:09
FYI, this also affect mpi4py when there is a conflicting MPI, which can be worked around with the ctypes.cdll.LoadLibrary trick.

**Comment by becker33** [comment] 2022-08-18 23:44
Closing as duplicate of #1927

**Closed by becker33** 2022-08-18 23:44 UTC
Labels: bug, rpath
