### ISSUE TITLE
Discussion on Changing Hashes

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2247] opened 2016-11-04 19:08 UTC
@tgamblin  I'm pulling this out of #2238 because that is a PR and is now closed.  But it seems to have ignited a decent discussion.

@adamjstewart  At one point, #1338 I proposed how we could gracefully handle changing Spack hashes, which you brought up in #1335.  Not many people seem to have noticed #1338.  Do you think these ideas might be the right direction for us?

>  Also, I am planning on adding checksumming of the package.py file itself to Spack, but am holding off so that @adamjstewart does not murder me due to #1325-related concerns.

Yes, this worries me too.  If we can solve #1325 then it might not be so bad.  But in general, I don't want checksums to change just because I fixed a flake8 in the package.  I wonder if there's any way to checksum the bytecode of the package instead of the package itself?

Or... add an option to `config.yaml` to turn off package source hashing.  I really think it would cause me more pain than it would help.  Allowing users to turn off controversial features is often a way to move forward in peace.

> For example, once the hash changes, it is no longer possible to say "build with this thing I already have installed". 

So it looks like this will not really be a problem.  Spack will find a suitable version and decide it doesn't have to rebuild???

> I would like Spack to use things that are already installed, unless I am explicitly installing them, in which case they should update to the latest version. @citibeth has concerns about reproducibility, so this should be configurable.

The "reuse vs rebuild" debate is over, in my mind, for the following two reasons:

  1. Allowing Spack's concretization algo to see packages already installed will make `spack find`, `spack load`, etc. a WHOLE LOT more useful (once they are switched to use concretization).

 2. Concretizing based on what's already installed can always be reproduced by generating a file of what's already installed, and then concretizing based on that ---- possibly after the user has edited it.  That option should be an integral part of this upcoming feature.

**Comment by alalazo** [comment] 2016-11-04 19:12
>  I wonder if there's any way to checksum the bytecode of the package instead of the package itself?

I think this potentially makes hashing a function of the interpreter that is used.

**Comment by adamjstewart** [comment] 2016-11-04 19:15
> > Also, I am planning on adding checksumming of the package.py file itself to Spack, but am holding off so that @adamjstewart does not murder me due to #1325-related concerns.

> Yes, this worries me too. If we can solve #1325 then it might not be so bad. But in general, I don't want checksums to change just because I fixed a flake8 in the package. I wonder if there's any way to checksum the bytecode of the package instead of the package itself?

Agreed. Changes to a `package.py` can be important, but if you installed something and it's working fine, then they probably aren't important to you. If it isn't working, you can uninstall it and reinstall it with the new `package.py`.

> The "reuse vs rebuild" debate is over, in my mind

🎉 

Let me take another look at #1338

**Comment by citibeth** [comment] 2016-11-04 19:17
> Agreed. Changes to a package.py can be important, but if you installed
> something and it's working fine, then they probably aren't important to you.
>

Yes, exactly.  Someone adds a newline to `zlib/package.py`, and now Spack
wants to rebuild everything.

**Comment by tgamblin** [comment] 2016-11-04 19:50
I don't really want to get into a huge discussion about this right now because I was thinking I would get release things done today.  But let me see if I can clear this up.  This is also relevant for #1325.

> Yes, this worries me too. If we can solve #1325 then it might not be so bad. But in general, I don't want checksums to change just because I fixed a flake8 in the package. I wonder if there's any way to checksum the bytecode of the package instead of the package itself?

FYI: @scheibelp took a prototype I wrote up a long time ago and has a `package.py` hasher that he uses to generate new release numbers for RPMs. This is sketch of how it works.

`package.py` files contain two things: constraints that are inputs to the concretizer (`version`, `depends_on`, `extends`, etc.) and install code.  The former are all captured by the current hash -- in the sense that they contribute to what the final spec's metadata looks like.  The install code is not currently captured.

The package hasher we wrote up strips comments, blank lines, directives, and `@when`-decorated functions that wouldn't be executed for the particular concrete spec to be hashed.  You could go deeper (e.g. hash a canonically pretty-printed source version), but this handles most of the issues with source changes, and it handles the fact that adding a new version to the _metadata_ for a package shouldn't affect the hash of a concrete spec _instance_. So I don't really expect this to be an issue.  Python has nice features for grabbing the source of a file right out of the `Package` class object.  This may require a slight rework now that @alalazo has added `CMakePackage` and friends but I think it can be handled.

Note that this kind of hashing is something that has been done before in projects like `nix`, `guis`, and `hashdist`. The distinction here is that Spack has both a hash and a DAG model -- we can potentially take two build DAGs and figure out if one could substitute for the other.  I think there is a lot of power there, and we could use that to do things that other tools can't do at all.  e.g., Spack could eventually take a tree of packages and "minimize" it: based on the constraints we encode and some binary compatibility rules, we could re-RPATH things so that only a minimal set of packages remain, and older versions would be removed if a new versions could be used instead.  _That_ is a long way off, but it's a thing I'd like to do once Spack is stable and has a slightly more robust dependency model.

> Or... add an option to config.yaml to turn off package source hashing. I really think it would cause me more pain than it would help. Allowing users to turn off controversial features is often a way to move forward in peace.

It's also a way to bloat the scope of this project, end up maintaining more things than I can handle, and make hashes meaningless as a measure of reproducibility, if they could be generated different ways based on different user preferences.  I think we should discuss it and try to come up with something sustainable.  Peace is great but collaboration and leverage shouldn't be underrated.  If everyone doing their own thing were the answer, you wouldn't be using Spack 😄.  

Anyway, I don't think this is as big an issue as you think, because...

> So it looks like this will not really be a problem. Spack will find a suitable version and decide it doesn't have to rebuild???

I said in the other thread that this is why I was holding off.  We don't have this balance between rebuilding and reusing in the concretizer right now -- reuse is only possible if the hash matches what the deterministic concretizer would come up with.  We can integrate package hashing once the concretizer can make smarter choices.

It is important here not to conflate the *policy* we use to select what to build with the *granularity* of the provenance stored.  I would ideally like Spack to store as much build provenance as possible for reproducibility. `package.py` hashing would allow that and would allow us to trace bugs and such to issues with `package.py` versions (something not in the provenance now). I think this will be particularly important when we integrate #445 -- Spack should able to concretize not only on what is available *locally* but also on what is available in a remote binary cache.  In that instance, you likely really do want to be able to distinguish archives by `package.py` hash, to rule out builds that were broken.

So, I'm reasonably sure we can do this and allow *both* reuse and better reproducibility with finer-grained hashing.  But I don't plan to do package hashing until we have a concretizer that can handle it, and I think we can work out the usability bugs that @adamjstewart and @citibeth have mentioned here.

Also, I totally agree with @citibeth's last 2 points.  I think we're on the same page there.  Now back to implementing all this stuff!

**Comment by TomasPuverle** [comment] 2016-12-04 23:04
Hi,

I've been reading through all the issues mentioned above by @citibeth, which obviously led me down a rabbit hole of feature discussions, bug reports and related issues.

I have to admit I'm having a bit of trouble piecing together what is under consideration, what is under construction, what has been rejected etc.

Is there any documentation (before I dive into the source to try and figure it out) about the algorithm and the package selection process, but perhaps more importantly, a summary of the current thinking and future directions?  I don't want to be looking at or suggesting things which have been already considered and rejected.  If not, I'm happy to dig into it more but I thought I'd at least ask. 

Thank you,

Tom

**Comment by adamjstewart** [comment] 2016-12-05 16:38
> On this issue, why not apply spack to itself? In some way, every package would implicitly depend on the version of spack it was built with (or at least the version of the algorithm used for hashing).

I'm basically doing this right now (I have 3 different Spack installations) and the problem is that hash-changing PRs are being merged in the middle of a development cycle. I'm already on `spack-0.10` even though 0.10 hasn't been released yet, and if the hash changes again, I guess I'll have to go to `spack-0.10.1` or something. I've been trying to push @tgamblin to only merge hash-changing PRs at the boundary of releases, but it's difficult because you want a lot of users to test out such important changes before a new release. The best way to do it in my mind is to make a completely separate release branch. Then, hash-changing PRs are only allowed to be merged to release branches and backported to develop once the release is released. So using the version of the hashing algorithm would be better than using the version of Spack, although less intuitive.

> I have to admit I don't fully understand (yet) why the hashes are included in the directory names (I believe this was also mentioned in the discussion of #1325, but I haven't seen an answer); I think it would be just as good to use arbitrary file naming (mktemp, incremental, or any other unique policy) and then keep the mappings in the spack database. Nothing is lost on the RPATH etc front, as the names continue to be unique.

This was my line of thinking. It would also have the benefit of a shorter installation path name. @tgamblin explained the reason to me once, but I didn't quite understand why it was the only possible solution. I think it was because we don't want to loop through every installed package to see if a dependency is already installed. I think we are calculating the hash of what we need and seeing if that directory exists; if not, build it. Although, there is already talk of relying on already installed packages more often, so that would mean we would have to loop through all already installed packages anyway.

**Comment by marcmengel** [comment] 2021-07-16 22:00
Okay, so I've been reading through this discussion from #1325, and I have two concrete suggestion that I think might actually help:  

When one adds a new variant to a package, one should specify in the variant what value packages built before the variant was added should be considered: i.e. 
   variant('furble', default=True, description="Turn on furbling", old_missing=False)
would say that we have a variant furble, which now defaults to True, but old packages that don't list the variant either way should be treated as if it were False.   This would let us compute a new hash for the old packages which don't list the variant on a reindex(), and make the package usable by new builds. You could even have a variation of the when= syntax on old_missing so you could specify that it was True back in "@:2.99" and False in "@3.0:" or something. 

Second, we could record the old hashes a package used to have in, say, .spack/old_hashes.yaml, and list all of them in the database.  Then if you used either hash when specifying the package you could find it.  This would let users who have been doing "spack load fred /xyzzy"  to get that package to still find it, but also let it be found by things looking for that package and  (new) variants via the new hash.

I suspect I've overlooked something here someone else would find obvious; but it seems to me these two changes could make our old-packages-under-new-spack issues tractable.

**Comment by tgamblin** [comment] 2021-07-16 23:55
In 0.17 we'll be making the new concretizer default, and it will *prefer* to use installed versions of packages, and will *optionally* use the traditional installation mode that doesn't consider them.  What that means is that if you install one thing, say an MPI implementation, and the installed thing *can* be used by a new thing you install, we'll prefer to do that.  That should change the perception of "hashes changing" every time you pull from spack while also retaining reproducibility, and you'll be able to build the "pristine" version with new dependency versions as well.

We shouldn't need to put any additional burdens on maintainers to do this, so I think it's in general better than a solution that requires folks to document old hashes, or interpolate old variant versions.

**Comment by becker33** [comment] 2022-08-18 23:43
Closing as completed by the new concretizer and spec reuse.

**Closed by becker33** 2022-08-18 23:43 UTC
Labels: concretization, hashes, discussion
